### ISSUE TITLE
razerkbd keeps sending messages to kernel log

### ISSUE THREAD

**Issue by wthielen** [openrazer/openrazer#1007]
Every second there are 2-4 messges from razerkbd, saying that the "Response doesn't match request".

This does not seem good, as it fills up disk space in the end, and adds noise to the log. Is there any way to debug why it is doing this?

This is a Razer Blade 15 Advanced laptop, 2019 model.

**Comment by z3ntu** [comment]
> as it fills up disk space in the end

The kernel itself doesn't write the kernel log to disk, and I'm not aware that systemd is doing that

> and adds noise to the log

true

Are you running any operations (settings effects, etc?) while this is happening? Can you try stopping the daemon (`systemctl --user stop openrazer-daemon.service`) and see if anything changes?
