### ISSUE TITLE
Razor blackwidow elite not working

### ISSUE THREAD

**Issue by nag92** [openrazer/openrazer#1008]
I am getting this error when I try to use Razor genie 

● openrazer-daemon.service - Daemon to manage razer devices in userspace
   Loaded: loaded (/usr/lib/systemd/user/openrazer-daemon.service; disabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Fri 2020-01-24 08:55:06 EST; 1min 59s ago
     Docs: man:openrazer-daemon(8)
  Process: 424 ExecStart=/usr/bin/openrazer-daemon -Fv (code=exited, status=1/FAILURE)
 Main PID: 424 (code=exited, status=1/FAILURE)

Jan 24 08:55:06 pop-os systemd[2150]: Starting Daemon to manage razer devices in userspace...
Jan 24 08:55:06 pop-os openrazer-daemon[424]: Starting daemon.
Jan 24 08:55:06 pop-os openrazer-daemon[424]: 2020-01-24 08:55:06 | razer                          | CRITICAL | User is not a member of the plugdev group
Jan 24 08:55:06 pop-os openrazer-daemon[424]: Stopping daemon.
Jan 24 08:55:06 pop-os systemd[2150]: openrazer-daemon.service: Main process exited, code=exited, status=1/FAILURE
Jan 24 08:55:06 pop-os systemd[2150]: openrazer-daemon.service: Failed with result 'exit-code'.
Jan 24 08:55:06 pop-os systemd[2150]: Failed to start Daemon to manage razer devices in userspace.

**Comment by TermoZour** [comment]
You have to add your user to plugdev group
`sudo usermod -aG plugdev $LOGNAME`
