### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by ale1zin** [openrazer/openrazer#1011]
● openrazer-daemon.service - Daemon to manage razer devices in userspace
   Loaded: loaded (/usr/lib/systemd/user/openrazer-daemon.service; disabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Mon 2020-01-27 01:14:08 -03; 24s ago
     Docs: man:openrazer-daemon(8)
  Process: 3720 ExecStart=/usr/bin/openrazer-daemon -Fv (code=exited, status=1/FAILURE)
 Main PID: 3720 (code=exited, status=1/FAILURE)
      CPU: 231ms

jan 27 01:14:08 localhost.localdomain systemd[1154]: Starting Daemon to manage razer devices in userspace...
jan 27 01:14:08 localhost.localdomain openrazer-daemon[3720]: Starting daemon.
jan 27 01:14:08 localhost.localdomain openrazer-daemon[3720]: 2020-01-27 01:14:08 | razer                          | CRITICAL | User is not a member of the plugdev group
jan 27 01:14:08 localhost.localdomain openrazer-daemon[3720]: Stopping daemon.
jan 27 01:14:08 localhost.localdomain systemd[1154]: openrazer-daemon.service: Main process exited, code=exited, status=1/FAILURE
jan 27 01:14:08 localhost.localdomain systemd[1154]: openrazer-daemon.service: Failed with result 'exit-code'.
jan 27 01:14:08 localhost.localdomain systemd[1154]: Failed to start Daemon to manage razer devices in userspace.

**Comment by ale1zin** [comment]
![image](https://user-images.githubusercontent.com/45977655/73150119-66658e80-40a3-11ea-8579-67382571434b.png)

**Comment by ale1zin** [comment]
![image](https://user-images.githubusercontent.com/45977655/73150852-328c6800-40a7-11ea-8fe0-fd60ffbcb3b4.png)

**Comment by lah7** [comment]
> CRITICAL | User is not a member of the plugdev group

Please run this command, log out and log back in to the computer:

    sudo gpasswd -a $USER plugdev

**Comment by ale1zin** [comment]
Before you send it I found this command in another forum and it worked, thanks anyway! But now I have another problem, I change the dpi but I don't feel the effects, it seems that it just doesn't change. :(

**Comment by ale1zin** [comment]
![image](https://user-images.githubusercontent.com/45977655/73193678-ba0ac300-4109-11ea-9b5e-0eddc20386af.png)

**Comment by z3ntu** [comment]
So you mean when you untick the "Set Logo Active" checkbox, then the light on the logo LED stay on?

**Comment by ale1zin** [comment]
No, all functions work except for dpi.

**Comment by ale1zin** [comment]
I tried to reinstall using the flatpack and this error appeared.

**Comment by ale1zin** [comment]
![image](https://user-images.githubusercontent.com/45977655/73231429-19df8900-415f-11ea-934b-21e9975f4d35.png)
