### ISSUE TITLE
[Orbwearer chroma] only color settings available

### ISSUE THREAD

**Issue by shassino** [openrazer/openrazer#1021]
Hewo folks. I tried ur project yesterday on my manjaro setup. I installed 2.7.0 package from aur along with razercommander.

Once I open razercommander I get the following log:

> Skipping macro logic for device Razer Orbweaver Chroma
>   Exception: org.freedesktop.DBus.Python.AttributeError: Traceback (most recent call last):
>   File "/usr/lib/python3.8/site-packages/dbus/service.py", line 711, in _message_cb
>     retval = candidate_method(self, *args, **keywords)
>   File "/usr/lib/python3.8/site-packages/openrazer_daemon/dbus_services/dbus_methods/macro.py", line 30, in delete_macro
>     self.key_manager.dbus_delete_macro(macro_key)
> AttributeError: 'RazerOrbweaverChroma' object has no attribute 'key_manager'

Is this expected?

Linux shm-pc 5.3.18-1-MANJARO #1 SMP PREEMPT Wed Dec 18 18:34:35 UTC 2019 x86_64 GNU/Linux

Logs attached
[razer.log](https://github.com/openrazer/openrazer/files/4149289/razer.log)
[journal.log](https://github.com/openrazer/openrazer/files/4149295/journal.log)
[dmesg.log](https://github.com/openrazer/openrazer/files/4149302/dmesg.log)

**Comment by chabad360** [comment]
Ah, yes... Currently the macro feature support for the Orbweaver Chroma is missing (primarily because it doesn't have macro keys), but I'm working to entirely replace it with #1124.
