### ISSUE TITLE
Macro keys not working for BlackWidow Ultimate 2013

### ISSUE THREAD

**Issue by RiverMatt** [openrazer/openrazer#1031]
### Distribution
Linux Mint 19.3

### Support

- [Y] Have you tried rebooting?
- [Y] Have you looked at the [Troubleshooting](https://github.com/openrazer/openrazer/wiki/Troubleshooting) page?

The macro keys are not working on my BlackWidow Ultimate 2013. I've installed the driver, confirmed that it works, and /sys/bus/hid/drivers/razerkbd/0003:1532:011A.000F/device_mode shows 3:0 (which should be driver mode, right?). I've tried RazerGenie and Polychromatic, which let me adjust the lighting (this does work), but I cannot record macros with those programs as far as I can tell.

I am trying to record macros with the on-the-fly method. Pressing Fn+F9 causes the flashing M to appear, I press a macro key (M1-M5), the light goes solid, then I type a macro, finishing by pressing Fn+F9. Macro light goes away. However, when I press the M-button I recorded it on, nothing happens.

Getting these macro keys to work could be quite handy for vim...

Hopefully I'm not missing something silly, but this appears to be a problem. Thank you.

**Comment by OfficialStamper** [comment]
Bump

openrazer-daemon 2.8.0

Linux Mint 20

Razer Blackwidow Ultimate 2012

I never get the Flashing (M) with either FN+(M) nor FN+F9

Unable to record/use macros at all 

As I am using a different device, happy to create a new issue if that is whats required?  Please advise.

**Comment by sarka9000** [comment]
Same issue here with Razer Blackwidow Ultimate Classic (Polychromatic reports it as 2012). I can change game mode and brightness in Polychromatic, but cannot record macros with the keyboard buttons.
openrazer-daemon 3.11.0
polychromatic 0.9.6
Ubuntu 24.04

**Comment by z3ntu** [comment]
Please don't necro-bump issues. And macros are essentially unsupported and will be removed soon, see #2337. Use https://github.com/sezanzeb/input-remapper
