### ISSUE TITLE
Fix Razer Blade Mid 2019 Advanced Mercury Effects

### ISSUE THREAD

**Issue by cesarvargas00** [openrazer/openrazer#1042]
Hello,

I couldn't get my wave effect to work properly. It doesn't have that fade-in/fade-out effect. Also, I couldn't get my keyboard work with different colors for each key. It seems that all keys are stuck with the same color. No independent color changing.

Thank you!

**Comment by z3ntu** [comment]
Hi, you're talking about the device 1532:0245, right?
