### ISSUE TITLE
Error starting openrazer on Fedora

### ISSUE THREAD

**Issue by cl0h** [openrazer/openrazer#1051]
$ uname -a
Linux host 5.5.9-200.fc31.x86_64 #1 SMP Thu Mar 12 13:55:19 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

● openrazer-daemon.service - Daemon to manage razer devices in userspace
   Loaded: loaded (/usr/lib/systemd/user/openrazer-daemon.service; disabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Fri 2020-03-20 15:00:54 GMT; 24s ago
     Docs: man:openrazer-daemon(8)
  Process: 4025 ExecStart=/usr/bin/openrazer-daemon -Fv (code=exited, status=1/FAILURE)
 Main PID: 4025 (code=exited, status=1/FAILURE)
      CPU: 100ms

Mar 20 15:00:54 fedora22 systemd[2216]: Starting Daemon to manage razer devices in userspace...
Mar 20 15:00:54 fedora22 openrazer-daemon[4025]: Starting daemon.
Mar 20 15:00:54 fedora22 openrazer-daemon[4025]: 2020-03-20 15:00:54 | razer                          | CRITICAL | User is not a member of the plugdev group
Mar 20 15:00:54 fedora22 openrazer-daemon[4025]: Stopping daemon.
Mar 20 15:00:54 fedora22 systemd[2216]: openrazer-daemon.service: Main process exited, code=exited, status=1/FAILURE
Mar 20 15:00:54 fedora22 systemd[2216]: openrazer-daemon.service: Failed with result 'exit-code'.
Mar 20 15:00:54 fedora22 systemd[2216]: Failed to start Daemon to manage razer devices in userspace.

**Comment by lah7** [comment]
> CRITICAL | User is not a member of the plugdev group

[Please run this command](https://github.com/openrazer/openrazer/wiki/Troubleshooting#daemon), and re-log in - this should do the trick:

    sudo gpasswd -a $USER plugdev
