### ISSUE TITLE
Turkish Q Layout Support

### ISSUE THREAD

**Issue by xlith** [openrazer/openrazer#1052]
Could you please add layout support for Turkish Q keyboard (tr_TR.UTF-8) .

Outputs
```
cat /sys/bus/hid/drivers/razerkbd/0*/kbd_layout
0a
```
![photo_2020-03-21_15-18-32](https://user-images.githubusercontent.com/510560/77226302-5391a680-6b88-11ea-9069-a55934aaad4f.jpg)

**Comment by z3ntu** [comment]
Cheers!
