### ISSUE TITLE
Configuring top buttons on the Deathadder Elite

### ISSUE THREAD

**Issue by KeirSimmons** [openrazer/openrazer#1054]
### Distribution

Ubuntu 18.04 (Pop!OS)
Deathadder Elite

### Support

- [x] Have you tried rebooting?
- [x] Have you looked at the [Troubleshooting](https://github.com/openrazer/openrazer/wiki/Troubleshooting) page?

So I have the polychromatic tools working fine (the GUI apps), and this allows me to change the lighting effects with no problem. But I want to remap some of the buttons on the mouse, but not sure where to start. I took a look at the documentation, and the first thing I see is `cat device_type` for the mouse driver, but I have no idea where I'm supposed to run this? Simply running it in a terminal obviously does not work, but I can't find any introductory documentation on where to get started. Any help will be appreciated!

**Comment by z3ntu** [comment]
We do not support configuring the buttons of the devices at the moment.
