### ISSUE TITLE
Deamon cannot be relaunched (Pyolochromatic Issue) Manjaro Linux

### ISSUE THREAD

**Issue by Mathew1602** [openrazer/openrazer#1056]
I am very new to Linux and I just tried to install the Pyolochromatic and i cant seem to get it to work. I have already installed open-razer then Pyolochromatic and then I restarted my computer after the install. I have reinstalled the application multiple times but i cant seem to get it to work. Thank you in advanced.

Here is my error from the  terminal :

![Screenshot_2020-03-22_22-43-07](https://user-images.githubusercontent.com/62529482/77275427-a6ee1c80-6c8e-11ea-9a49-f242899df61f.png)

**Comment by z3ntu** [comment]
Hi, could you please give me the output of the command `lsusb | grep 1532` and of the command `sudo modprobe razerkbd`? Thanks.

**Comment by lah7** [comment]
There is a typo in the command - should be a lowercase `v`, like so:

    openrazer-daemon -Fv

**Comment by Mathew1602** [comment]
> Hi, could you please give me the output of the command `lsusb | grep 1532` and of the command `sudo modprobe razerkbd`? Thanks.

Here are the commands you asked me to run, and thank you for helping me so far :)

![Screenshot_2020-03-22_22-39-02](https://user-images.githubusercontent.com/62529482/77328687-447b3780-6cf3-11ea-93b2-5bd9748d76b2.png)

**Comment by z3ntu** [comment]
It looks like you forgot to install the kernel headers for your kernel. You can install them with `sudo pacman -S linux55-headers` and then reboot.

**Comment by Mathew1602** [comment]
> It looks like you forgot to install the kernel headers for your kernel. You can install them with `sudo pacman -S linux55-headers` and then reboot.

Hello so i installed the headers and then rebooted but now i get this error instead. 

![Screenshot_2020-03-22_22-39-02](https://user-images.githubusercontent.com/62529482/77331105-a8ebc600-6cf6-11ea-9507-1c3bf8d4b07d.png)

**Comment by Mathew1602** [comment]
> It looks like you forgot to install the kernel headers for your kernel. You can install them with `sudo pacman -S linux55-headers` and then reboot.

When i try to add the user then log out and log back in I still get the same error as before 

![Screenshot_2020-03-22_22-39-02](https://user-images.githubusercontent.com/62529482/77331256-dcc6eb80-6cf6-11ea-8464-750b25c86749.png)

**Comment by lah7** [comment]
Try this instead - and re-log in:

    sudo gpasswd -a $USER plugdev

**Comment by Mathew1602** [comment]
> Try this instead - and re-log in:
> 
> 
> 
>     sudo gpasswd -a $USER plugdev

Thank you that worked :), I really appreciate the help. I tried to get this to work for days. Thank you again
