### ISSUE TITLE
How to install on Deepin

### ISSUE THREAD

**Issue by woann** [openrazer/openrazer#1071]
How to install on Deepin

**Comment by z3ntu** [comment]
Deepin seems to use dpkg and apt, so you can run `./scripts/build_debs.sh` from the repository to build some deb files which you can install. In case you get an error, check the file linked in the script output, it'll likely be some missing dependencies. Also it might not build at all on Deepin in case the dependencies are named differently.

**Comment by woann** [comment]
@z3ntu ok thinks

**Comment by z3ntu** [comment]
According to #645 you might be able to use the Debian Sid repository (linked on our website openrazer.github.io)

**Comment by woann** [comment]
I already tried,But&nbsp;Debian Sid repository&nbsp; is not found.Maby It could be remove or discard.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Luca Weiss"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月30日(星期一) 下午3:55
收件人:&nbsp;"openrazer/openrazer"<openrazer@noreply.github.com&gt;;
抄送:&nbsp;"woann"<304550409@qq.com&gt;;"State change"<state_change@noreply.github.com&gt;;
主题:&nbsp;Re: [openrazer/openrazer] How to install on Deepin (#1071)





 
According to #645 you might be able to use the Debian Sid repository (linked on our website openrazer.github.io)

**Comment by woann** [comment]
@z3ntu I already tried,But Debian Sid repository is not found.Maby It could be remove or discard.
