### ISSUE TITLE
Save idle time & low battery threshold in daemon

### ISSUE THREAD

**Issue by z3ntu** [openrazer/openrazer#1085]
+ save values like done in #888 (once it's merged :slightly_smiling_face: )
+ add `getIdleTime` and `getLowBatteryThreshold` functions to dbus interface
+ add wrappers for those in pylib

**Comment by bno1** [comment]
I added `getIdleTime` and `getLowBatteryThreshold` to my PR: https://github.com/openrazer/openrazer/pull/1129. I could pull them out and put them in a separate PR if you want.

**Comment by z3ntu** [comment]
Yes please put them into a separate PR. Combining unrelated changes in a PR is never nice from the maintainer side :)

**Comment by z3ntu** [comment]
This was solved nicely in #1137 - closing.
