### ISSUE TITLE
Profile LEDs not correct for Orbweaver Chroma

### ISSUE THREAD

**Issue by chabad360** [openrazer/openrazer#1089]
The profile LEDs for the Orbweaver Chroma should be remapped as they all hit the wrong stuff:

Currently:

```
profile_led_green -> blue led
profile_led_red   -> green led
profile_led_blue  -> yellow led
```

Should be:

```
profile_led_green -> greed led
profile_led_red   -> yellow led
profile_led_blue  -> blue led
```

I've identified the culprit: 

https://github.com/openrazer/openrazer/blob/3592f8197dc2bd143f02a5f996ba8f6feb9b7f80/driver/razercommon.h#L52-L54

As these are hardcoded (and because this was originally written for the Tatarus), there's doesn't seem to be a super easy way out.

**Comment by lah7** [comment]
I can also confirm this is the case with **Tartarus Chroma**.

Looking at `git blame`, it [appears it was the Nostromo](https://github.com/openrazer/openrazer/blame/3592f8197dc2bd143f02a5f996ba8f6feb9b7f80/driver/razercommon.h#L52-L54) that has them in a different order.

https://github.com/openrazer/openrazer/commit/86af64a8f3d11a13dd09be37a26069b1998855b4#diff-6f38cc63b8755079814e6aa5d740b081L47-L49

**Comment by chabad360** [comment]
@lah7 I could give this a shot, but the question is whether to just change it (along with the name, because there is no red LED) to fit the Tartarus and Orbweaver (as Razer has since discontinued the Nostromo), or to add another set of `#define`s (which in it of it self brings a naming challenge) and the requisite functions to make this work.

**Comment by z3ntu** [comment]
From the information I have, the defines are correct from name to number. I'd say "fixing" this in the driver is the best solution, so adding an if or a switch to the respective functions which changes the id for those devices.

**Comment by chabad360** [comment]
@z3ntu I'll give it a shot (I am super unfamiliar with C/C++, so here goes!).

**Comment by chabad360** [comment]
@z3ntu I'd give it a shot, but I'm extremely unfamiliar with C/C++, and a quick look at that code doesn't give a boost of confidence. So... maybe you or @lah7 could do it?

**Comment by lah7** [comment]
I'm not confident with C either, but I'll have a look. :eyes:
