### ISSUE TITLE
Debian package

### ISSUE THREAD

**Issue by stephanlachnit** [openrazer/openrazer#1095]
I'm interested in packing this officially for Debian, however openrazer is already debianized - sort of.
The Debian Policy (which btw also applies for Ubuntu) recommends not having a `debian` folder in upstream if possible, as it complicates everything a bit.
Are you interested in moving the current `debian` folder to a different branch? It's not the end of the world if it doesn't happen, it is possible to overwrite these files, but I rather avoid it if I can.

**Comment by z3ntu** [comment]
The package is already in Debian..?

**Comment by stephanlachnit** [comment]
Oh god sorry nvm.

**Comment by z3ntu** [comment]
No problem :smile:
