### ISSUE TITLE
Crashes on Opening on Pop_OS 19.10

### ISSUE THREAD

**Issue by ghost** [openrazer/openrazer#1098]
I don't know why, but when I open RazerGenie (I made sure that it was the latest version and OpenRazer was installed) with Pop_OS version 19.10, it crashes with these logs:

● openrazer-daemon.service - Daemon to manage razer devices in userspace
   Loaded: loaded (/usr/lib/systemd/user/openrazer-daemon.service; disabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Wed 2020-04-15 03:43:58 EDT; 25s ago
     Docs: man:openrazer-daemon(8)
  Process: 4353 ExecStart=/usr/bin/openrazer-daemon -Fv (code=exited, status=1/FAILURE)
 Main PID: 4353 (code=exited, status=1/FAILURE)

Apr 15 03:43:58 pop-os systemd[1677]: Starting Daemon to manage razer devices in userspace...
Apr 15 03:43:58 pop-os openrazer-daemon[4353]: Starting daemon.
Apr 15 03:43:58 pop-os openrazer-daemon[4353]: 2020-04-15 03:43:58 | razer                          | CRITICAL | User is not a member of the plugdev group
Apr 15 03:43:58 pop-os openrazer-daemon[4353]: Stopping daemon.
Apr 15 03:43:58 pop-os systemd[1677]: openrazer-daemon.service: Main process exited, code=exited, status=1/FAILURE
Apr 15 03:43:58 pop-os systemd[1677]: openrazer-daemon.service: Failed with result 'exit-code'.
Apr 15 03:43:58 pop-os systemd[1677]: Failed to start Daemon to manage razer devices in userspace.

Does anyone know what's happening and how I can fix this?

**Comment by clintar** [comment]
Looks like you need to add yourself to the plugdev group. You will need to log out and back in after that probably.
