### ISSUE TITLE
Support for Lian Li pc-o11 Dynamic Razer Edition

### ISSUE THREAD

**Issue by galenoshea** [openrazer/openrazer#1119]
### Device Info

* Name: Lian Li pc-o11 Dynamic Razer Edition
* Product Number: N82E16811112590
* Model Number: PC-O11D Razer

### Device Information
```
Please post the output of
    lsusb -d 1532: -v
```

```
Please post the output of
    ls -lah /dev/input/by-id/
```

### Packet Captures

<Please see here as we probably need packet captures>
<https://github.com/openrazer/openrazer/wiki/Reverse-Engineering-USB-Protocol>

### Synapse Screenshots
<Screenshots of all available options as seen on Razer Synapse>

**Comment by z3ntu** [comment]
Duplicate of #903
