### ISSUE TITLE
Missing Magic Sys does not work for left ALT key in kernel module razerkbd

### ISSUE THREAD

**Issue by Tikeri** [openrazer/openrazer#1125]
Hello,

The module is catching keyboard input events but does not handles the Magic Sys Request key combos which is pretty critical in some situations.

Running kernel version 4.4.164 and openrazer 2.7.0 (from git, merged in January).

Found that documentation but I am not sure how to implement this at all :
https://www.kernel.org/doc/html/latest/admin-guide/sysrq.html#i-want-to-add-sysrq-key-events-to-a-module-how-does-it-work

**Comment by lah7** [comment]
From my understanding, the magic SysRq key always speaks directly to the kernel, so this isn't affected when `razerkbd` is loaded. I have it enabled on Manjaro and works as expected - e.g. flush cache to disk (Alt+SysRq+S)

The documentation you've found sounds useful if `razerkbd` wishes to add an input to Magic SysRq to handle a request, but I don't believe there is a use case for it right now. Good to know though!

**Comment by Tikeri** [comment]
Thanks for the quick reply, well this is curious that it works on your system configuration.
I've done the following tests before opening this issue :
  1. razerkbd loaded : tried multiple SysRq and nothing happened + nothing from dmesg
  2. blacklisted razerkbd module + removed udev rule file from openrazer : after reboot I've tried the same and SysRq are working

I'm runnning Gentoo Linux and custom kernel but :
~ ;-) zgrep SYSR /proc/config.gz 
CONFIG_MAGIC_SYSRQ=y
CONFIG_MAGIC_SYSRQ_DEFAULT_ENABLE=0x1

**Comment by lah7** [comment]
Whoops, I should have said it works for me with <kbd>Alt Gr</kbd> (right Alt) + <kbd>SysRq</kbd> + <kbd>S</kbd> but not with left <kbd>Alt</kbd>. I have a GB layout. :gb:

Now you mention it, I tried unloading the daemon and `razerkbd`, and calling Magic SysRq with the left <kbd>Alt</kbd> works, so I guess that's the bug.

Does it work with your keyboard's right Alt key? (Easiest check is watching the kernel log and trying an emergency sync)

**Comment by Tikeri** [comment]
I can confirm this behaviour, it works fine with Alt Gr here too (FR layout) :
[ 6768.484726] Emergency Sync complete

This means there is only a minor modification to do in the module source ? :)

**Comment by Tikeri** [comment]
I am not sure to understand very well from razerkbd_driver.c file : 
>static int razer_event(struct hid_device *hdev, struct hid_field *field, struct hid_usage *usage, __s32 value)
>...
>    // Store Alt state
>    if(usage->code == KEY_LEFTALT) {
>        asc->left_alt_on = value;
>    }
>    // Block Alt-Tab
>    if(asc->block_keys[1] && asc->left_alt_on && usage->code == KEY_TAB) {
>        return 1;
>    }
>    // Block Alt-F4
>    if(asc->block_keys[2] && asc->left_alt_on && usage->code == KEY_F4) {
>        return 1;
>    }

When only LEFTALT is enabled it goes to he end of the function and return 0 while it should return 1 ?

**Comment by lah7** [comment]
Not proficient in C myself :exploding_head: but that area of code looks like it's for game mode, which would disable those keys. 

----

Is your driver _purely_ stable (v2.7.0) or a git commit since its release?

I've just got to the bottom of what was causing my ALT key to behave like CTRL when the daemon isn't running, bd864c87c64908611cc989109c4970c14cf314fb might be related to this problem too. 

https://github.com/openrazer/openrazer/pull/1049#issuecomment-621868240

If you revert that commit, rebuild and reboot, does the SysRq combination work again for left Alt?

**Comment by Tikeri** [comment]
> Is your driver purely stable (v2.7.0) or a git commit since its release?

It was from git and merged the 7 January this year (2019-01-07T22:56:28 >>> app-misc/openrazer-9999: 1 minute, 26 seconds)

I actually tried again right now with latest revision and it also doesn't works.

Btw I'm not able to find the revision or build date somewhere, maybe should it be added somewhere and be printed by openrazer-daemon --version ?

**Comment by lah7** [comment]
The latest release (2.8.0) has fixed the issue. Left ALT + SysRq works again. :+1:
