### ISSUE TITLE
Alt left registered as Control left

### ISSUE THREAD

**Issue by DasHammett** [openrazer/openrazer#1132]
### Distribution

Gentoo - Kernel 5.6.5

### Support

- [x] Have you tried rebooting?
Yes
- [x] Have you looked at the [Troubleshooting](https://github.com/openrazer/openrazer/wiki/Troubleshooting) page?
Yes

Hi, 

I have a BlackWidow Ultimate 2016 and the ALT left is not registered as such, but as Control left. Keyboard layout is Spanish (code 10) and is correctly identified by razerkbd.

I have used `xev` to capture the keystroke when pressing left ALT key to confirm what was being sent to the system.

```
KeyPress event, serial 70, synthetic NO, window 0x2400001,
    root 0x1e6, subw 0x0, time 1224348, (1078,5), root:(1085,981),
    state 0x10, keycode 37 (keysym 0xffe3, Control_L), same_screen YES,
    XLookupString gives 0 bytes: 
    XmbLookupString gives 0 bytes: 
    XFilterEvent returns: False
```
Could you perhaps review?
Thank you

Kind regards,

**Comment by lah7** [comment]
It's a regression: https://github.com/openrazer/openrazer/commit/bd864c87c64908611cc989109c4970c14cf314fb - seems to only happen if the driver is loaded but the daemon is not running.

It might also be responsible for breaking SysRq with the left Alt key too (https://github.com/openrazer/openrazer/issues/1125)

Good job it's not a stable release yet, cos' this bug was winding me up thinking a KDE update had broken Alt+Tab. :sweat_smile:

**Comment by DasHammett** [comment]
Glad to see it is already a known issue. 

Too bad in Gentoo systems there are no releases, it always pulls the repo. I use i3 and my mod key is left ALT, so basically I could not do anything at all! :rofl: 

Hope this can get resolved soon

Thanks

**Comment by z3ntu** [comment]
Same issue as #1077 

I've reverted the patch on master for now, of course #872 isn't solved anymore now. I hope we find a good solution for that..

**Comment by lah7** [comment]
I can confirm the latest release / master has fixed the Alt/Ctrl issue. (Or for users coming from a non-git 2.7 release, nothing broke at all :smile:) Please update your copy of OpenRazer - the version should read `2.8`.

**Comment by Tikeri** [comment]
Thanks a lot ! :)
I've upgraded to 2.8.0 already and got back the magic :)
