### ISSUE TITLE
Support for Razer Basilisk Essential 

### ISSUE THREAD

**Issue by tomoki1337** [openrazer/openrazer#1134]
saw support added for the Razer Basilisk in #804fa58 yet still no support for the Essential model 
### Device Info

* Name: Razer Basilisk Essential 
* Product Number: RZ01-02650100
* Model Number: RZ01-0265

### Device Information

output of lsusb -d 1532:0065 -v

```
Bus 002 Device 004: ID 1532:0065 Razer USA, Ltd 
Device Descriptor:
  bLength                18
  bDescriptorType         1
  bcdUSB               2.00
  bDeviceClass            0 
  bDeviceSubClass         0 
  bDeviceProtocol         0 
  bMaxPacketSize0        64
  idVendor           0x1532 Razer USA, Ltd
  idProduct          0x0065 
  bcdDevice            2.00
  iManufacturer           1 Razer
  iProduct                2 Razer Basilisk Essential
  iSerial                 0 
  bNumConfigurations      1
  Configuration Descriptor:
    bLength                 9
    bDescriptorType         2
    wTotalLength       0x0054
    bNumInterfaces          3
    bConfigurationValue     1
    iConfiguration          0 
    bmAttributes         0xa0
      (Bus Powered)
      Remote Wakeup
    MaxPower              500mA
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        0
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      1 Boot Interface Subclass
      bInterfaceProtocol      2 Mouse
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength      94
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x81  EP 1 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0008  1x 8 bytes
        bInterval               1
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        1
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      0 
      bInterfaceProtocol      1 Keyboard
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength     159
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x82  EP 2 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0010  1x 16 bytes
        bInterval               1
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        2
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      0 
      bInterfaceProtocol      1 Keyboard
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength      61
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x83  EP 3 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0008  1x 8 bytes
        bInterval               1
can't get device qualifier: Resource temporarily unavailable
can't get debug descriptor: Resource temporarily unavailable
Device Status:     0x0000
  (Bus Powered)

```

```
lrwxrwxrwx 1 root root  10 May  2 22:20 usb-Razer_Razer_Basilisk_Essential-event-if01 -> ../event12
lrwxrwxrwx 1 root root   9 May  2 22:20 usb-Razer_Razer_Basilisk_Essential-event-mouse -> ../event8
lrwxrwxrwx 1 root root   9 May  2 22:20 usb-Razer_Razer_Basilisk_Essential-if01-event-kbd -> ../event9
lrwxrwxrwx 1 root root  10 May  2 22:20 usb-Razer_Razer_Basilisk_Essential-if02-event-kbd -> ../event13
lrwxrwxrwx 1 root root   9 May  2 22:20 usb-Razer_Razer_Basilisk_Essential-mouse -> ../mouse0

```

### Packet Captures
currently not possible 
### Synapse Screenshots
![image](https://user-images.githubusercontent.com/22425997/81009982-df6c4300-8e55-11ea-9425-f9553fcb87c6.png)
![image](https://user-images.githubusercontent.com/22425997/81010029-f4e16d00-8e55-11ea-939a-c98a15d1f564.png)
![image](https://user-images.githubusercontent.com/22425997/81010068-00cd2f00-8e56-11ea-96bc-913f02183d89.png)
![image](https://user-images.githubusercontent.com/22425997/81010223-35d98180-8e56-11ea-924c-95dd642694dc.png)
![image](https://user-images.githubusercontent.com/22425997/81010171-1f332a80-8e56-11ea-9bb8-bb1e81d69a04.png)

**Comment by tomoki1337** [comment]
added synapse screenshots

**Comment by aabedraba** [comment]
Bumping this up, having the same problem.

**Comment by druffinelli** [comment]
I would also like support for the Razer Basilisk Essential. Even the back/forward buttons do not work well for me.

**Comment by simonyee** [comment]
Hi,
When is the development for the Razer Basilisk mouse for ubuntu 20.04 going to move forward?

**Comment by Klaas-Lindi** [comment]
I would also like to have support for my essential! "Surprisingly" the devices supported are the more expensive ones...  What works for me is to install synapse on a windows device (might also work with OS.X), apply my settings and then connect the mouse to my linux-computer. I haven't tried a virtual windows computer or anything like that yet. Though the device still cannot be found by polychromatic afterwards, all the settings I have made are saved on the mouse, so it is fully functional. Even the DPI button still has the values I programmed.

**Comment by LinusPNutz** [comment]
I recently bought the mouse and would like to have it supported on Linux too.
The pulsing light kinda bugs me :) and i don't know how to change it on linux. It worked well with the keyboard.

**Comment by Gimzie** [comment]
Just bought this same exact mouse as well, would be great to have support for it on Linux! +1

**Comment by rcotrina94** [comment]
Just bought the Basilisk Essential as well. Let me know if I can help with the support for it in OpenRazer.

**Comment by Copiercowboy** [comment]
I see that at pcap has been requested, has this been provided yet? And if not, can you point where to provide this info?

**Comment by z3ntu** [comment]
@callihamm https://github.com/openrazer/openrazer/wiki/Reverse-Engineering-USB-Protocol

**Comment by kiaraly** [comment]
pcaps can be found on this openrgb [issue](https://gitlab.com/CalcProgrammer1/OpenRGB/-/issues/654)

**Comment by z3ntu** [comment]
The pcaps contain info that `razer_chroma_extended_matrix_effect_custom_frame` is used with transaction id 0x1f, MATRIX_DIMS [1, 1], `razer_chroma_extended_matrix_brightness` with led id 0 (and of course also transaction id 0x1f).

If somebody wants to look into development for this device, you can probably start with a copy of the Mamba Elite and continue from there.

**Comment by XECortex** [comment]
I've also got this mouse delivered today, and I thought it would work with the default Basilisk version driver, but then I saw this :(

How long will it take to add support for the Basilisk Essential mouse? I could also help reverse engineering if needed!

**Comment by slugcat-dev** [comment]
Any updates?
