### ISSUE TITLE
Does not work with my Razer Naga Epic

### ISSUE THREAD

**Issue by ronaldoverardo** [openrazer/openrazer#1140]
I have a Razer Naga Epic with USB VID: PID 1532: 001F where the Razer Configurator app works perfectly, but with RazerGenie it only says "No Device was detected". So, I would like to inform you that you have a bug, if you need to do any test, I will be available my email is ronaldoverardo@gmail.com.
Hugs and I wait.

**Comment by z3ntu** [comment]
Your device is not supported yet, it's tracked at #197 .
