### ISSUE TITLE
Razer Balistic wireless mouse

### ISSUE THREAD

**Issue by KeeKira** [openrazer/openrazer#1146]
On Manjaro 5.4  open-razer supports the Ballistic mouse but not the ballistic wireless mouse.
Looking for workaround or support.
Sincerely
Sherry Caraway

**Comment by Arilas** [comment]
Support for this is done in #1152

**Comment by z3ntu** [comment]
This seems to be about the Basilisk mouse which is handled in other issue, please use the search function to find them.
