### ISSUE TITLE
Cynosa Chroma undetected by the driver

### ISSUE THREAD

**Issue by Mayravixx** [openrazer/openrazer#1147]
I'm at a bit of a loss here, I installed openrazer-meta from the AUR on my Arch installation today, and for whatever reason, Polychromatic claims that my supported razer keyboard isn't recognized. Anyone know how I could fix this? Is it also possible that it's doing this because I also have a HyperX mouse plugged in?
![razeroof](https://user-images.githubusercontent.com/50846413/81631684-0387d100-93ce-11ea-9add-50edf6b979ad.png)

**Comment by z3ntu** [comment]
Can you make sure your kernel headers are installed (e.g. `linux-headers`) and run 
`sudo dkms install openrazer-driver/2.8.0` ?

**Comment by Mayravixx** [comment]
That was my issue, I didn't have the linux-headers package, and upon installing that, it ran sudo dkms install openrazer-driver/2.8.0 automatically. Closing this issue as it's now resolved, thanks.
