### ISSUE TITLE
Driver sometimes loads incorrect on boot

### ISSUE THREAD

**Issue by leofah** [openrazer/openrazer#1153]
### Distribution

Arch Linux x86_64
Kernel: linux 5.6.13.arch1-1

### Support

- [x] Have you tried rebooting?
- [x] Have you looked at the [Troubleshooting](https://github.com/openrazer/openrazer/wiki/Troubleshooting) page?

Sometimes after boot the driver is not loaded correctly (I guess). If i want to press a Key, this key will be pressed multiple times (like 15 times). It look likes the key is released to late. However after re-plugging the keyboard it works fine with no problems.

I think this happened after each reboot if a new kernel was installed and the dkms had run. But on the last time this happened the last kernel update was a while ago.

Here is my dmesg and journalctl log, if it helps.
[razer.log](https://github.com/openrazer/openrazer/files/4661323/razer.log)

EDIT: I tried rebooting over SSH and the same incident occured.

**Comment by z3ntu** [comment]
Does this issue also happen with openrazer *not* installed?

**Comment by leofah** [comment]
After uninstalling the driver this issue happened directly on the next boot, but since then, it has not happened the past few days.

**Comment by chabad360** [comment]
Is it possible that a driver issue can include the brightness being set to zero?
