### ISSUE TITLE
Blackwidow Classic Mac support

### ISSUE THREAD

**Issue by fifthrider** [openrazer/openrazer#116]
Turns out the Mac layout of the Blackwidow Classic has a different VID:PID from the other models: 1532:010e. Implementation likely tracks the existing Blackwidow Classic support otherwise.

Could use daemon support, as well.

Thanks!

**Comment by terricain** [comment]
:) will have a look in janurary. Remind me :wink:

**Comment by simcop2387** [comment]
Didn't realize I had the mac layout.  Just got mine back after a few years of it being in storage at my parents place.  I'll see if I can enable it to work in just a little bit.

**Comment by terricain** [comment]
PR in progress here https://github.com/terrycain/razer-drivers/pull/123
