### ISSUE TITLE
deafault.target in openrazer-daemon.service

### ISSUE THREAD

**Issue by yaiqsa** [openrazer/openrazer#1176]
While working on an openrazer-based daemon, I was looking at the openrazer systemd service file. (to determine dependencies for my own daemon). [here](https://github.com/openrazer/openrazer/blob/master/daemon/resources/openrazer-daemon.systemd.service.in) I found the last line; `WantedBy=default.target`. I guess this was put there to make sure the openrazer daemon is ran before any openrazer-based applications are started.
However, why make the daemon a dependency to a variable target? As mentioned on [the Arch forum](https://wiki.archlinux.org/index.php/Systemd#Default_target_order) 'default.target' can reference to multiple different targets. Would it be more stable to reference a specific target here?

I hope this isn't a 'stupid' suggestion, I don't claim to know a lot about systemd, but this seemed a bit strange to me.

For good measures, my setup:
Kernel version: Debian 4.19.118-2+deb10u1
openrazer-[daemon,driver-dkms,meta] version: 2.8.0+dfsg-1

**Comment by z3ntu** [comment]
I guess https://unix.stackexchange.com/a/506374 should answer your question? The service file was added with https://github.com/openrazer/openrazer/commit/3299d608e8810f218cbdf12298cf3fa417889698 so this line has been present since then.
