### ISSUE TITLE
Cannot control sides on Razer Mamba Elite

### ISSUE THREAD

**Issue by LogischesWindows** [openrazer/openrazer#1178]
The Razer Mamba Elite has 22 LEDs on the sides of it it seems, but I cannot control them using OpenRazer. They just breath every color because that is the default mode.

**Comment by z3ntu** [comment]
We do have support for that in OpenRazer but both polychromatic and RazerGenie don't support the sides on the stable version, but they do on git master. So your best bet is to build one of those (or both) UIs from git and that should get it working. Note that with polychromatic from git you also need PR #1149
