### ISSUE TITLE
Razer blade stealth late 2017 keyboard doesnt work

### ISSUE THREAD

**Issue by Lillievela** [openrazer/openrazer#1182]
### Distribution
 Manjaro latest testing, Kernel 5.7.6-1

### Support

- [x ] Have you tried rebooting?
- [x ] Have you looked at the [Troubleshooting](https://github.com/openrazer/openrazer/wiki/Troubleshooting) page?

Whenever I install and setup openrazer and reboot my keyboard seems to outright quit taking inputs outside of the brightness controls for the backlight, it only seems to occur after i reboot and if its installed, and there does seem to be a slight lag issue system-wide when its installed

**Comment by z3ntu** [comment]
Hi @Lillievela , I'm not aware of the driver doing any input "manipulation", especially on the laptops. From what I can read you have already tried to uninstall OpenRazer and then it works again?

**Comment by Lillievela** [comment]
Yes, i am able to change the colours and settings, and using my phone with kde connect i can remove openrazer and keep the changes. but its just that i cannot keep it installed as it somehow is preventing my from using the keyboard

**Comment by z3ntu** [comment]
Can you try installing an older version (e.g. v2.5.0) and see if that works? You could go as far back as v2.1 which is where support for that device was introduced (see #420, #422)

**Comment by Lillievela** [comment]
I managed to get 2.6.0 installed via AUR but it still has the same issue

**Comment by z3ntu** [comment]
Then I don't really know what's causing the issues, sorry.
