### ISSUE TITLE
per key effect or layers

### ISSUE THREAD

**Issue by Darkmadda** [openrazer/openrazer#119]
Synapse, the windows/mac software from razer, allows layers where sets of keys can have an effect, so like my numberkeys i've set to wave, and my qwerty keys have a reactive effect and my number pad has a ripple. Synapse even has preset key layers, like you can set wsda keys to an other effect. It would be nice to have different effects for dynamic key groups. If this is already possible please let me know. I've tried searching the issues and google without any success. If this is something that requires kernel changes it's out of my league but python or gtk i could help.

**Comment by terricain** [comment]
Its planned dont you worry, its also something I want but theres a fair bit of work to be done before then.
