### ISSUE TITLE
Razer DeathAdder 2013 not changing colors

### ISSUE THREAD

**Issue by henryruhs** [openrazer/openrazer#1196]
I have no adequate explanation what is going on but my old "Razer DeathAdder 2013" does not change colors for some reason. 

Tried via Polychromatic and Chroma-Feedback. Turning on/off works so the driver is partial okay.

OS: Ubuntu 18.04 LTS
Python: 3.6.9
openrazer-daemon: 2.8.0

**Comment by z3ntu** [comment]
Can you try with an older release of openrazer, to see if it's a regression?

**Comment by henryruhs** [comment]
Sure, how to switch between the versions on Ubuntu? That one is not working:

```
sudo apt-get install openrazer-meta=2.7.0
```

**Comment by blshkv** [comment]
DeathAdder 2013 is a single color,  green, device. What are you talking about?..

**Comment by henryruhs** [comment]
You are right... I mixed it up with another device
