### ISSUE TITLE
Support for Elementary OS

### ISSUE THREAD

**Issue by ghost** [openrazer/openrazer#1197]
I have recently switched to Elementary OS and was disappointed to find no support for it. Is it possible to add this, or tell me an alternative/workaround? Thanks!

**Comment by z3ntu** [comment]
elementary OS 5.1 is based on Ubuntu 18.04 so you can just use the repos for Ubuntu 18.04.

**Comment by z3ntu** [comment]
@Iridium-glitch The website has been updated: https://openrazer.github.io/#download
