### ISSUE TITLE
razor tartarus v2 no keypad key button support 

### ISSUE THREAD

**Issue by beartravels** [openrazer/openrazer#1198]
ive installed everything under thee sun to get this tto work but to no avial it all does not want to be remaped geni or poymorphus thingy lights fworks ggreat thats not what i bouhgt it for lol
i want to rmap its keys any program in the world for that?
tartus v2
18.04

**Comment by chabad360** [comment]
Unfortunately, Openrazer doesn't yet support remapping keys, but it is in the works (#1124). There are tools like keyboarding master or input-modifier that can remap your keys until then.

**Comment by beartravels** [comment]
ahh ok ya keyboard master does not work unless youve logged in a super hard wya unles you have a simple trick to log in as root kwyboard maseter is out

**Comment by beartravels** [comment]
and su in terminal does not count

**Comment by chabad360** [comment]
Keyboard master only needs sudo to install, afterwards you don't need sudo

**Comment by nova8080** [comment]
Hey!  I just came across your post while searching around for my own problem.  If you still need to keybind your tartarus v2, it takes a little time, but it is doable. I'll post what worked for me once I finally fix (or give up) my naga trinity mousebutton 4&5 from changing the DPI.

**Comment by flyer48** [comment]
Hi nova8080,

yes please tell me how to keybind my tartarus v2, that would be great!

**Comment by AnTeBiOss** [comment]
Hi there, i'm Really interested by keybinding on tartarus v2.
How do i help ?
