### ISSUE TITLE
Basilisk X HyperSpeed Not Found

### ISSUE THREAD

**Issue by ghost** [openrazer/openrazer#1199]
Hello, I can't map the mouse in the application. Seems to be out of the driver list for the software. I've connected the device by bluetooth.

**Comment by Icy-Thought** [comment]
The support for Basilisk Hyperspeed X has not been merged into the main branch yet. I also have been looking forward to this PR to land in the main branch, hopefully we get to see this done in the near future!

More info:
https://github.com/openrazer/openrazer/pull/1129

**Comment by z3ntu** [comment]
Closing this issue then.
