### ISSUE TITLE
Support for Razer Raptor 27 (Monitor)

### ISSUE THREAD

**Issue by Aerodin** [openrazer/openrazer#1217]
### Razor Raptor 27

Connects via HDMI/DisplayPort/USB C

Controlled via Razer Synapse via USB C.

Initially I tried setting the RGB values and profile via a friend's borrowed Windows 10 laptop, however, the effects only remain as long as the computer is plugged in via USB C.  Otherwise it switches back to the default of cycling through all colors.

* Name: Razor Raptor 27
* Product Number: <See under device>
* Model Number: RZ39-0276

### Device Information
```
Please post the output of
    lsusb -d 1532: -v

No output information could be seen related to the Raptor 27.
```

```
Please post the output of
    ls -lah /dev/input/by-id/

No output information could be seen related to the Raptor 27.
```

### Packet Captures

<Please see here as we probably need packet captures>
<https://github.com/openrazer/openrazer/wiki/Reverse-Engineering-USB-Protocol>

### Synapse Screenshots
<Screenshots of all available options as seen on Razer Synapse>

**Comment by LandingGitHub** [comment]
Is there any update about the compatibility for the Razer Raptor 27 monitor? I'll would gladly help testing :)

**Comment by spynin** [comment]
I also have the same display. Is it more difficult to port due to the usb-c connection utilized for synapse?

**Comment by hendy643** [comment]
[Raptor27usbcap.zip](https://github.com/openrazer/openrazer/files/6680608/Raptor27usbcap.zip)
![RGBModes](https://user-images.githubusercontent.com/62912828/122641363-b449bf00-d0fc-11eb-913e-96a06b1ff034.jpg)

I've attached a wireshark capture from windows.

I noted the following packets might possibly be related.
The capture seemed to include some kind of device handshake at the start.

59 - 62 toggle underglow on/off
99 - 100 colour to 0%
119 - 120 colour to 10%
135 - 136 colour to 100%
Higher than this: changed colour mode from static to Breathing.


To note:
It appears as 2 USB devices in device manager.

**Comment by z3ntu** [comment]
@hendy643 Thanks for the pcap. Basically it looks like any other Razer device, a few things that I see in there:

* Use `razer_chroma_extended_matrix_brightness` with ZERO_LED for brightness
* Use `razer_chroma_extended_matrix_set_custom_frame` for custom frame
* And use `MATRIX_DIMS = [1, 12]` in the daemon

The rest you'll have to guess and try it out whether it works.

Also I haven't seen the USB product id for this device yet, either lsusb on Linux or I guess in the device manager in Windows this should be visible.

**Comment by LandingGitHub** [comment]
Nice! some progress :)
Thanks guys for looking at it

**Comment by jedimasterjonny** [comment]
> Also I haven't seen the USB product id for this device yet, either lsusb on Linux or I guess in the device manager in Windows this should be visible.

USB PID: `0F12`

**Comment by jedimasterjonny** [comment]
To prevent duplication of effort if anyone else comes here - I've picked this up in: https://github.com/openrazer/openrazer/pull/1541
