### ISSUE TITLE
Error binding OpenSuse Leap 

### ISSUE THREAD

**Issue by navtek** [openrazer/openrazer#122]
Hi, I'm having issues trying to use the drivers in OpenSuse, I've been following the guide but I can't bind the keyboard.

I have a BlackWidow X Chroma Keyboard and whenever I try to bind I get the following error:

`bash: bind: Permission denied`

Already installed twice, it appears to be making and installing correctly (no error messages), so I don't know where the problem might be.

Thanks in advance

**Comment by z3ntu** [comment]
So you tried the rpms that are available [here](https://github.com/terrycain/razer-drivers/releases/tag/v1.1.3)? If yes, these rpms were only tested on Fedora 25.
But ultimately you have to bind using a root shell (sudo doesn't work as you would expect it to)
**EDIT:** Or you can use something like that: `echo "123123123" | sudo tee -a bind`

**Comment by navtek** [comment]
I installed the rpms, but still no luck, I also tried to bind using a root shell and it now says the following:

`bash: echo: write error: No such device`

When I run `ls -l /sys/bus/hid/devices/` I get the following:

`lrwxrwxrwx 1 root root 0 Dec 21 08:10 0003:03F0:134A.0001 -> ../../../devices/pci0000:00/0000:00:14.0/usb3/3-11/3-11:1.0/0003:03F0:134A.0001

lrwxrwxrwx 1 root root 0 Dec 21 08:10 0003:1532:0216.0002 -> ../../../devices/pci0000:00/0000:00:14.0/usb3/3-12/3-12:1.0/0003:1532:0216.0002

lrwxrwxrwx 1 root root 0 Dec 21 08:10 0003:1532:0216.0003 -> ../../../devices/pci0000:00/0000:00:14.0/usb3/3-12/3-12:1.1/0003:1532:0216.0003

lrwxrwxrwx 1 root root 0 Dec 21 08:10 0003:1532:0216.0004 -> ../../../devices/pci0000:00/0000:00:14.0/usb3/3-12/3-12:1.2/0003:1532:0216.0004`

0003:1532:0216.0004 is the interface I should be binding to.

**Comment by terricain** [comment]
What commands did you run to bind

**Comment by navtek** [comment]
I ran `echo -n "0003:1532:0216.0004" > bind` inside `/sys/bus/hid/drivers/razerkbd`

**Comment by z3ntu** [comment]
Did you unbind the device first?

**Comment by navtek** [comment]
I couldn't unbind, the device doesn't show up when I run the following:

`cd /sys/bus/hid/drivers/hid-generic`
`ls -l`

This is the result:

`lrwxrwxrwx 1 root root    0 Dec 21 08:14 0003:03F0:134A.0001 -> ../../../../devices/pci0000:00/0000:00:14.0/usb3/3-11/3-11:1.0/0003:03F0:134A.0001

--w------- 1 root root 4096 Dec 21 08:14 bind

lrwxrwxrwx 1 root root    0 Dec 21 08:14 module -> ../../../../module/hid_generic

--w------- 1 root root 4096 Dec 21 08:14 new_id

--w------- 1 root root 4096 Dec 21 08:14 uevent

--w------- 1 root root 4096 Dec 21 16:20 unbind`

**Comment by terricain** [comment]
anything in dmesg? and are you sure its using the right driver version?

**Comment by navtek** [comment]
I get the following, running `dmesg | grep -i usb`

[dmesg.txt](https://github.com/terrycain/razer-drivers/files/669651/dmesg.txt)

**Comment by z3ntu** [comment]
So you are using openSUSE Leap 42.2, right?

**Comment by navtek** [comment]
Yes, that's right

**Comment by terricain** [comment]
Least theres no errors in dmesg, thats a start ;)

**Comment by navtek** [comment]
How can I make sure it's using the right driver version?

**Comment by terricain** [comment]
latest checkout of this repo right?

**Comment by navtek** [comment]
Yes, I checked out 2 days ago, we're there any essential changes since?

**Comment by z3ntu** [comment]
> I installed the rpms

Yesterday I installed OpenSUSE Leap in a virtual machine just for testing and I managed to install the rpms which are available in the release section of this repo more or less fine (`dkms` package was not resolvable -> install from some 3rd party source & `python3-dbus` was not available -> `sudo pip install pydbus` & opensuse has python3.4 -> `sudo mv /usr/lib/python3.5/site-packages/razer* /usr/lib/python3.4/site-packages/`) and then the driver just worked(tm). So I can say that it isn't a general OpenSUSE problem.

**Comment by navtek** [comment]
So I realized I only installed the kernel modules (my bad), I tried to install all other dependencies for the other rpms and I got stuck with `python3-dbus`, used `sudo pip install pydbus` but still not taking it.

**Comment by z3ntu** [comment]
Binding should still work without the other packages though. You can ignore the `python3-dbus` dependency if you use `sudo pip install pydbus` to install it. Try recompiling the kernel module with `sudo dkms remove razer_chroma_driver/1.0.0 && sudo dkms install razer_chroma_driver/1.0.0` and reboot afterwards.

**Comment by z3ntu** [comment]
@navtek Could you please try the packages from [the obs repo](https://software.opensuse.org/download.html?project=home%3Az3ntu&package=razer-drivers)?

**Comment by navtek** [comment]
@z3ntu Will try right now

**Comment by navtek** [comment]
@z3ntu Got the driver working, when I go to `sys/bus/hid/drivers/razerkbd/0003\:1532\:0216.0005` and trigger `cat device_type` I get `Razer BlackWidow X Chroma` but when I try to run any command I get an error, i.e. if I try to run `echo -n "1" > mode_pulsate` I get `bash: mode_pulsate: Permission denied`, already tried with sudo and root shell

**Comment by navtek** [comment]
Got the driver working and now I can interact with the matrix functions, got some problems with the daemon, will check out in a bit...

**Comment by z3ntu** [comment]
Please do `sudo zypper refresh && sudo zypper update` because there was a dependency missing (but it's fixed now). Hopefully everything works then :) If you have any other problems it's easier if you contact me (@z3ntu) or @terrycain on Telegram because it's much easier to communicate with people over a realtime chat.

**Comment by terricain** [comment]
Pretty sure theres packages for this now

**Comment by terricain** [comment]
Technically binding is working now, Try rpms listed under the opensuse section here - https://terrycain.github.io/razer-drivers/
