### ISSUE TITLE
Naga Trinity Unable to configure key macros

### ISSUE THREAD

**Issue by drewaydelott** [openrazer/openrazer#1220]
Mouse: Razer Naga Trinity (1532:0067)
Openrazer Daemon: 2.8.0
OS: Ubuntu 20.04.1 LTS Focal
Kernel: 5.4.0-42-Generic
Software Frontend:  RazerCommander, Polychromatic, and RazerGenie (All stable channels)

Issue: No software is showing any configuration options for key macros for the buttons on any of the side panels. The buttons all work with the default behavior of inserting, with the thumb keys inserting the number of whichever side button is pressed (Key 1 inserts "1", Key 2 inserts "2", etc...)

Color changes work flawlessly, and i am able to set color profiles up with no issues. 

There dont seem to be any errors in the logs, the device is detected, and the Daemon runs and DBus is being served normally. (Log Attached)
[razer.log](https://github.com/openrazer/openrazer/files/5032097/razer.log)

**Comment by z3ntu** [comment]
Should be implemented with #1124 on the openrazer side.

**Comment by sezanzeb** [comment]
https://github.com/sezanzeb/key-mapper can do it
