### ISSUE TITLE
Daemon Issue?

### ISSUE THREAD

**Issue by LuxLucian** [openrazer/openrazer#1223]
I am running Solus 4.1 and have bumped into this issue. RazerGenie gives me an error message (Polychromatic does the same) and I am unsure what's wrong. I have a Razer Cynosa Chroma and a Mamba Wireless.
![Screenshot from 2020-08-07 16-24-33](https://user-images.githubusercontent.com/63475999/89693126-c9de3d80-d8ca-11ea-89a6-d8be6b37af4c.png)
![Screenshot from 2020-08-07 16-24-50](https://user-images.githubusercontent.com/63475999/89693128-cb0f6a80-d8ca-11ea-9e95-aaf002d80058.png)

**Comment by LuxLucian** [comment]
https://pastebin.com/RUUxHTv1
https://pastebin.com/GWn82443
![Screenshot from 2020-08-10 16-29-12](https://user-images.githubusercontent.com/63475999/89837794-ec6c9280-db26-11ea-878a-8a0b66c39972.png)




![Screenshot from 2020-08-10 16-29-55](https://user-images.githubusercontent.com/63475999/89837799-eeceec80-db26-11ea-998b-7c023db09a0e.png)

**Comment by chabad360** [comment]
It appears that Solus doesn't support DKMS, so your installation process will be a bit more manual. This may be of use to you: https://discuss.getsol.us/d/1222-how-to-install-github-sources-requiring-dkms-for-missing-devices-drivers/8

**Comment by LuxLucian** [comment]
Just to clarify, would I DL the source code for openrazer extract it to a temp directory, and compile the items? This would install it properly, assuming the compile succeeds? Sorry, bit new to compile from source, would rather not break something.

**Comment by chabad360** [comment]
Yup!

**Comment by LuxLucian** [comment]
So, I successfully compiled the source code, but when I try to install razergenie I'm still prompted to install openrazer. Should I do that or am I missing an important step?

**Comment by z3ntu** [comment]
I'd suggest you contact the maintainers of the package at Solus - it should "just work" when installed as that's how they provide the package.
