### ISSUE TITLE
Mouse locked with green on sides and scrollwheel

### ISSUE THREAD

**Issue by Owen000** [openrazer/openrazer#1226]
### Distribution
Arch Linux

Arch 5.7.12
### Support

- [ ] Have you tried rebooting? yes
- [ ] Have you looked at the [Troubleshooting](https://github.com/openrazer/openrazer/wiki/Troubleshooting) page? yes

On my razer lancehead TE it will not change the side and scroll wheel rgb, I can get the razer logo to change though. I am using arch linux and have tried openRGB, polychromatic. My mouse has onboard profiles and I saved one but it will not load and goes to this green color. I had this issue quite a while ago on ubuntu also but the colors were black. I have recently changed the color scheme to green on windows and now it seems to be locked in the memory of the mouse. The keyboard and mouse-pad change colors fine while the mouse refuses to and is locked with green. I have all of the drivers installed and am running it as root.

**Comment by z3ntu** [comment]
Hi, currently both polychromatic and RazerGenie don't support the lighting on the side. You can change them manually via the Python API (see examples/ directory in the repository for examples) or via D-Bus for now.
