### ISSUE TITLE
Device support for Kiyo

### ISSUE THREAD

**Issue by JCTekDev** [openrazer/openrazer#1229]
Hi,

I'm interewted in buying Kayo webcam but Synapse doesn't seem available for Linux (my OS) based on link below.

https://www.wikiversus.com/gaming/webcams/razer-kiyo/

Please help!

**Comment by z3ntu** [comment]
> The Razer Kiyo runs out of the box.

> [...] the camera is working out of the box for me. I'm running Ubuntu 19.10

https://askubuntu.com/questions/993115/does-the-razer-kiyo-work-under-linux#comment1858964_1120666
