### ISSUE TITLE
Add OpenRazer to systemd startup

### ISSUE THREAD

**Issue by Lockna** [openrazer/openrazer#1231]
### Distribution
Arch Linux 
Kernel Version: 5.8.1
### Support

- [ x] Have you tried rebooting?
- [ x] Have you looked at the [Troubleshooting](https://github.com/openrazer/openrazer/wiki/Troubleshooting) page?

I was wondering how I can add the openrazer-daemon to the systemd startup.
I have to start it manually or it starts when I open the polychromatic frontend.
When I type in 
`sudo systemctl enable openrazer-daemon`
it gives me this output
`Failed to enable unit: Unit file openrazer-daemon.service does not exist.`
Am I missing something?

**Comment by z3ntu** [comment]
`systemctl --user enable openrazer-daemon.service` should work for that.

**Comment by Lockna** [comment]
Works, thanks
