### ISSUE TITLE
The daemon didn't detect a device that is connected.

### ISSUE THREAD

**Issue by GRX78FL** [openrazer/openrazer#1233]
### Distribution

Fedora 32 (Workstation Edition)
### Support

- [ ] Have you tried rebooting?
Yes.
- [ ] Have you looked at the [Troubleshooting](https://github.com/openrazer/openrazer/wiki/Troubleshooting) page?
Yes.

## Info

Razer Genie version: 0.8.1
OpenRazer Daemon version: 2.8.0
Linux version:  5.7.15-200.fc32.x86_64

## Issue:
![genie](https://user-images.githubusercontent.com/20095224/90963081-fd03fd80-e482-11ea-82d2-e8b20528d258.png)

## razer_mount log

**[root@xxxxx ~]# journalctl -b | grep -i razer_mount**
`Aug 21 22:34:11 xxxxx razer_mount[1581]: Driver razerkbd`
`Aug 21 22:34:11 xxxxx razer_mount[1580]: Driver razerkbd`
`Aug 21 22:34:11 xxxxx razer_mount[1582]: Driver razerkbd`
`Aug 21 22:34:11 xxxxx razer_mount[1584]: Device_ID 0003:1532:0233.0008`
`Aug 21 22:34:11 xxxxx razer_mount[1585]: Device_ID 0003:1532:0233.0007`
`Aug 21 22:34:11 xxxxx razer_mount[1586]: Device_ID 0003:1532:0233.0006`
`Aug 21 22:34:11 xxxxx razer_mount[1587]: Modprobing razerkbd`
`Aug 21 22:34:11 xxxxx razer_mount[1589]: Modprobing razerkbd`
`Aug 21 22:34:11 xxxxx razer_mount[1588]: Modprobing razerkbd`
`Aug 21 22:34:11 xxxxx systemd-udevd[1255]: 0003:1532:0233.0008: Process 'razer_mount razerkbd 0003:1532:0233.0008' failed with exit code 1.`
`Aug 21 22:34:11 xxxxx systemd-udevd[1259]: 0003:1532:0233.0006: Process 'razer_mount razerkbd 0003:1532:0233.0006' failed with exit code 1.`
`Aug 21 22:34:11 xxxxx systemd-udevd[1283]: 0003:1532:0233.0007: Process 'razer_mount razerkbd 0003:1532:0233.0007' failed with exit code 1.`

## razer daemon log

**[root@xxxxx ~]# cat /home/XXXXX/.local/share/openrazer/logs/razer.log | grep CRITICAL**
`2020-08-22 02:31:12 | razer                          | CRITICAL | Could not access /sys/devices/pci0000:00/0000:00:14.0/usb1/1-8/1-8:1.2/0003:1532:0233.0008/device_type, file is not owned by plugdev`

**Comment by z3ntu** [comment]
Can you please post the output of the command `sudo modprobe razerkbd` ?

**Comment by GRX78FL** [comment]
**[root@xxxxx ~]# modprobe razerkbd**
`modprobe: FATAL: Module razerkbd not found in directory /lib/modules/5.7.16-200.fc32.x86_64`

Something is broken because modprobing the driver was working fine on Linux 5.7.15-200.fc32.x86_64.

**Comment by z3ntu** [comment]
Can you try running `sudo dkms install openrazer-driver/2.8.0` and reboot?

**Comment by GRX78FL** [comment]
That fixed it!
I still don't know what exactly went wrong, but I'm assuming installation of the module failed in between kernel updates.
Thank you!

Please sign up to uphold and verify your github profile as a creator so that I can send you some BAT (it's a cryptocurrency). :)

**Comment by z3ntu** [comment]
Not sure either what broke but quite a few distros seem to have regular problems with dkms. I can just say that on Arch Linux dkms is rock-solid :wink:
