### ISSUE TITLE
Razer Huntsman TE Fn Key is not working

### ISSUE THREAD

**Issue by PCC17** [openrazer/openrazer#1235]
Currently I am using the Razer Huntsman Te which theoretically should be supported in OpenRazer.
I installed PolyChromatic and I am able to control the light effects on the keyboard - so at least some functions do work.

The real problem is that the Fn Key is not working.
So what do I mean with that?
I am using Ubuntu 20.04 and open razer daily build (stable version doesn't work either).
When I am trying to assign the media keys in system preferences pressing the Fn Key doesn't make any difference at all.

**Comment by z3ntu** [comment]
See also #872
We had a fix in #1049 but unfortunately it introduced a regression so we had to revert the fix: [#1049 (comment)](https://github.com/openrazer/openrazer/pull/1049#issuecomment-621868240)

Closing as duplicate of #1174
