### ISSUE TITLE
Support for DeathAdder V2 Mini (1532:008C)

### ISSUE THREAD

**Issue by setlord** [openrazer/openrazer#1256]
Please support DeathAdder V2 Mini (1532:008C)

Thank you!

**Comment by lah7** [comment]
Hi, in order to add support for a new device, it is helpful to know what protocol it may be using as we don't have the hardware. Please follow the **[Device Support](https://github.com/openrazer/openrazer/issues/new?template=new-device-support.md)** template, providing you have the mouse.

**Comment by lah7** [comment]
Thanks, closing this issue in favour of #1258.
