### ISSUE TITLE
Razer blade 15 (2020 base) can't rebind keyboard to razerkbd.

### ISSUE THREAD

**Issue by aneeshdurg** [openrazer/openrazer#1271]
### Distribution

Ubuntu 20.04

### Support

- [x] Have you tried rebooting?
- [x] Have you looked at the [Troubleshooting](https://github.com/openrazer/openrazer/wiki/Troubleshooting) page?

I can unbind the keyboard from hid_generic but can't rebind to razerkbd, and I get the error `no such device`. Running `journalctl -b | grep razer` yielded nothing.

**Comment by z3ntu** [comment]
Are you sure you're using a version of the driver where the device is supported? I've only merged support for that device yesterday.

**Comment by aneeshdurg** [comment]
Yup that was it! Switching to the daily ppa solved it.
