### ISSUE TITLE
Direct does nothing on deathadder elite V1

### ISSUE THREAD

**Issue by CoffeeIsLife87** [openrazer/openrazer#1272]
### Distribution

Windows through openRGB

### Support

- [x ] Have you tried rebooting?
- [x ] Have you looked at the [Troubleshooting](https://github.com/openrazer/openrazer/wiki/Troubleshooting) page?

Direct mode just sets the mouse to off regardless of the color sent

Static mode sets just fine though

**Comment by z3ntu** [comment]
I'm not sure what you're talking about, but OpenRazer doesn't have a "direct mode" and you're mentioning Windows - a platform not supported by openrazer - and openrgb - a different project than this. So I'm closing the issue.
