### ISSUE TITLE
Alt key doing weird things

### ISSUE THREAD

**Issue by NBBZ** [openrazer/openrazer#1275]
### Distribution
Arch 5.8.12-arch1-1

### Support

- [y ] Have you tried rebooting?
- [y ] Have you looked at the [Troubleshooting](https://github.com/openrazer/openrazer/wiki/Troubleshooting) page?

the alt key is doing weird lighting for example in wave it only alternates between green red and a brief yellow, or in spectrum doing an entirely different color and in costume lighting not working at all its the left one to be clear
and im using the blackwidow elite

**Comment by lah7** [comment]
It sounds like a hardware fault - that key's LED might be missing the "blue" out of RGB if it can only produce red, green and yellow (which is mixing R and G)

You can probably confirm this by setting all the keys to a static **white**, **red**, **green** then **blue**.

For the wave/spectrum/static effects, OpenRazer is instructing the hardware to the firmware to apply them, so no software is involved with the actual processing of those effects which could cause the ALT key to be different to the rest.
