### ISSUE TITLE
Razer Naga Trinity Not supported

### ISSUE THREAD

**Issue by RPavlik1** [openrazer/openrazer#1276]
### Distribution

Razer Naga Trinity
Linux 
Bus 003 Device 002: ID 1532:0067 Razer USA, Ltd Razer Naga Trinity

NAME="Linux Mint"
VERSION="20 (Ulyana)"
ID=linuxmint
ID_LIKE=ubuntu

### Support

- [ X ] Have you tried rebooting?
- [x] Have you looked at the [Troubleshooting](https://github.com/openrazer/openrazer/wiki/Troubleshooting) page?

Cannot use the custom editor and clicking in on the mouse wheel does not let me scroll. 
I can use the mousewheel to scroll up and down though. That works just fine.

![Screenshot from 2020-10-01 22-13-57](https://user-images.githubusercontent.com/69617740/94881464-8f5cd100-0433-11eb-8fc3-87ad1e4d76e6.png)

**Comment by z3ntu** [comment]
Hi, the "custom editor" in RazerGenie for mice is tracked in https://github.com/z3ntu/RazerGenie/issues/10 but it's not needed for anything except for configuring very custom lighting patterns.

> and clicking in on the mouse wheel does not let me scroll.

That's a general Linux-thing, middle click is pasting the secondary clipboard iirc. It seems that with GNOME you can disable that feature; or e.g. in web browsers you can install extensions to enable the middle click scrolling.

**Comment by RPavlik1** [comment]
Thanks for letting me know, still real new to linux in general. =)
