### ISSUE TITLE
openrazer-daemon.service error

### ISSUE THREAD

**Issue by qubka** [openrazer/openrazer#1277]
● openrazer-daemon.service - Daemon to manage razer devices in userspace
     Loaded: loaded (/usr/lib/systemd/user/openrazer-daemon.service; disabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Fri 2020-10-02 16:49:00 IST; 24s ago
       Docs: man:openrazer-daemon(8)
    Process: 26107 ExecStart=/usr/bin/openrazer-daemon -F (code=exited, status=1/FAILURE)
   Main PID: 26107 (code=exited, status=1/FAILURE)

Oct 02 16:49:00 root systemd[933]: Starting Daemon to manage razer devices in userspace...
Oct 02 16:49:00 root openrazer-daemon[26107]: Starting daemon.
Oct 02 16:49:00 root openrazer-daemon[26107]: 2020-10-02 16:49:00 | razer                          | CRITICAL | User is not a member of the plugdev group
Oct 02 16:49:00 root openrazer-daemon[26107]: 2020-10-02 16:49:00 | razer                          | CRITICAL | Please run the command 'sudo gpasswd -a $USER plugdev' and then reboot!
Oct 02 16:49:00 root openrazer-daemon[26107]: Stopping daemon.
Oct 02 16:49:00 root systemd[933]: openrazer-daemon.service: Main process exited, code=exited, status=1/FAILURE
Oct 02 16:49:00 root systemd[933]: openrazer-daemon.service: Failed with result 'exit-code'.
Oct 02 16:49:00 root systemd[933]: Failed to start Daemon to manage razer devices in userspace.

**Comment by z3ntu** [comment]
> Please run the command 'sudo gpasswd -a $USER plugdev' and then reboot!
