### ISSUE TITLE
Support for Razer Blackwidow Lite (2020)

### ISSUE THREAD

**Issue by sgourdas** [openrazer/openrazer#1281]
### Device Info

* Name: Razer Blackwidow Lite 
* Product Number: RZ03-02640700-R3M1
* Model Number: RZ03-0264

**Comment by z3ntu** [comment]
The BlackWidow Lite (`1532:0235`) is already supported since version 2.6.0 (released mid 2019)

**Comment by sgourdas** [comment]
I generated an OpenRazer64.dll with openrazer win32, but OpenRGB will not find my Blackwidow Lite. Can anyone help with that?

**Comment by z3ntu** [comment]
We don't support Windows so you're on your own here
