### ISSUE TITLE
Starlight effect on not-per-key-lit laptops like razer-laptop-control

### ISSUE THREAD

**Issue by mtib** [openrazer/openrazer#1282]
### Distribution

Manjaro 5.8.11, openrazer-git

### Support / Feature request

I have a Razer Blade 15" (Early 2020) version, I used to use [razer-laptop-control](https://github.com/mtib/razer-laptop-control) which was able to convincingly fake a [starlight effect](https://github.com/mtib/razer-laptop-control/blob/master/rgb_test_service/src/effects.cpp) on the Base model which has not individually lit keys, but still multiple keyboard lighting zones.

I don't know if this support / feature request issue is an application or driver one, the reason I *think* it should be here is that in:

```
ls /sys/devices/pci0000:00/0000:00:14.0/usb1/1-8/1-8:1.2/0003:1532:0255.0004/                 [2]
country        firmware_version   matrix_effect_breath	  modalias	     uevent
device_mode    hidraw		  matrix_effect_none	  power		     version
device_serial  input		  matrix_effect_reactive  report_descriptor
device_type    kbd_layout	  matrix_effect_spectrum  subsystem
driver	       matrix_brightness  matrix_effect_static	  test
```

I see no way to address the light zones independently, in which case it would be easy to port the starlight effect over. I am confused as the applications using openrazer still report the ability to enable starlight or wave, but then fail as the file in /sys/.../ is missing, but I' guess that's just the apps not reading the laptops ability properly.

**Comment by z3ntu** [comment]
If the device (I'm guessing you're talking about `1532:0255`?) supports multiple lighting zones then this device likely needs these lines in the driver:
```
CREATE_DEVICE_FILE(&hdev->dev, &dev_attr_matrix_effect_custom);
CREATE_DEVICE_FILE(&hdev->dev, &dev_attr_matrix_custom_frame);
```
and also some additional configuration in the daemon
