### ISSUE TITLE
udev premissions issue

### ISSUE THREAD

**Issue by krutoileshii** [openrazer/openrazer#129]
UDEV permissions missing MODE without which the daemon won't run on fedora.

currently reads: # Set permissions if this is an input node
SUBSYSTEM=="input|hid", GROUP:="plugdev"

Should Read

# Set permissions if this is an input node
SUBSYSTEM=="input|hid", GROUP:="plugdev", MODE="660"

**Comment by z3ntu** [comment]
What Fedora version are you using? And how did you install the driver? (eg rpms or manual)

**Comment by krutoileshii** [comment]
installed from the RPMs provided on the site, running fedora 25. kept giving me errors when running under the logged in user even after granting permissions to the group. but once I added the mode, it was running fine. Basically what i ran into is that permission wouldn't let you read it unless you are root which is inconvenient so both the daemon would not work properly. Daemon starts, but is unable to actually do anything with the keyboard.

**Comment by terricain** [comment]
@z3ntu mind testing the mode on the other os's you have vm's of. I see no reason why it would affect anything adversely.

**Comment by krutoileshii** [comment]
I can spin one up if nessessary. Just need a few days as new year is coming up.  I'll give it a shot and will let your know.

**Comment by krutoileshii** [comment]
I can probably even do a live cd boot just to eliminate the VM from the equation.

**Comment by terricain** [comment]
Sure

**Comment by krutoileshii** [comment]
Ok gave it a shot on both fedora mode doesn't cause any issues. however, it is not necessary on both suse and ubuntu. i wonder if there was a package on my system that caused it not to work unless root. i'll spin up a fedora vm later on and give it a shot. but adding MODE shouldn't cause any issues at all

**Comment by terricain** [comment]
Yeah I was thinking "it cant hurt" though having evidence doesn't hurt either

**Comment by krutoileshii** [comment]
Any reason to use plugdev instead of some other group that already belongs to a user?

**Comment by terricain** [comment]
Because on a fresh Ubuntu installation you literally only are in the suoders group and thats about it, plugdev made the most sense. The bigger question is wether or not to add the user to the group during package installation

**Comment by krutoileshii** [comment]
that would likely solve a lot of questions and issues , the only time we might have an issue is when there are more than one user.

**Comment by terricain** [comment]
There are bigger issues when there's more than 1 user. Havnt tested or built the daemon for that scenario but 2 of them will probs try and compete against each other a bit

**Comment by krutoileshii** [comment]
why would they compete? can't we just have the daemon started with the session at the same time instead?

**Comment by terricain** [comment]
The daemon autostart when you log in. So if you log out it'll still be running. If you then log in as another user it'll start again. If any of them are doing things like ripple effect both of them will try and interact with the driver simultaneously

**Comment by krutoileshii** [comment]
couldn't we simply have it shut down on log off?

**Comment by terricain** [comment]
It could happen, though if you log off it might possibly kill it anyway.

**Comment by krutoileshii** [comment]
or even simpler, before starting, kill all other versions

**Comment by terricain** [comment]
If its one running by another user then the current daemon wouldn't have permission to kill it. Its not something I had in mind when I first created the daemon but I'll look into it more if its really an issue people are facing

**Comment by krutoileshii** [comment]
I have multiple users on my server currently most won't even know how to start it as they are technologically impaired l. But was just wondering.

**Comment by terricain** [comment]
@krutoileshii what device/s do you have?

**Comment by krutoileshii** [comment]
I have the 2016 blackwidow

**Comment by terricain** [comment]
Technically as long as ripple effect isnt active, there wont be an issue

**Comment by krutoileshii** [comment]
Would it make sense to run it under its own username and group?

**Comment by terricain** [comment]
not really, well the idea was if it ran as the user it can do things like set the brightness of devices to 0 when screensaver is off
