### ISSUE TITLE
Adding Pop! Os as a download distro / Help with Viper Ultimate and charging dock

### ISSUE THREAD

**Issue by Daggerpov** [openrazer/openrazer#1291]

**Comment by z3ntu** [comment]
Hi, as far as I know Pop!_OS is based on Ubuntu so you should be able to use the normal Ubuntu instructions there. Does that work for you?

If that works, we can of course add Pop!_OS to the installation instructions as is done already with Linux Mint & elementary OS

**Comment by Daggerpov** [comment]
well, I did install it but I can't actually open the application. I search for it and there's an icon that shows up for both it and Polychromatic but they won't create a new window and open for whatever reason.

**Comment by z3ntu** [comment]
Can you please run `polychromatic-controller` in a terminal and check the output?

**Comment by Daggerpov** [comment]
![image](https://user-images.githubusercontent.com/53918934/95990044-06617480-0df9-11eb-8616-b7d4a2eaa421.png)

**Comment by z3ntu** [comment]
As you workaround you can do `sudo apt install python3-distro` , then it should launch fine. Does that make it work?

I've filed https://github.com/polychromatic/polychromatic/issues/289 so this can get fixed for everyone.

**Comment by Daggerpov** [comment]
![image](https://user-images.githubusercontent.com/53918934/95995831-fbf6a900-0dff-11eb-9351-105dfd773d12.png)

**Comment by z3ntu** [comment]
`head -n1 /usr/bin/polychromatic-controller` and `which python3` please

**Comment by Daggerpov** [comment]
![image](https://user-images.githubusercontent.com/53918934/95999151-9efcf200-0e03-11eb-887f-4f82eccce2d8.png)

**Comment by lah7** [comment]
Try changing the shebang to `#!/usr/bin/python3` (you'll need to edit the file `/usr/bin/polychromatic-controller` and `/usr/bin/polychromatic-tray-applet` as root). It seems there's a local installation of Python and so it's failing to load the system-installed modules.

This won't be necessary in future versions of Polychromatic, since it's been changed to `#!/usr/bin/python3`.

Similar issue to https://github.com/polychromatic/polychromatic/issues/265#issuecomment-659548947

**Comment by Daggerpov** [comment]
![image](https://user-images.githubusercontent.com/53918934/96003471-3f551580-0e08-11eb-849b-3a103314c2cb.png)

**Comment by lah7** [comment]
Modifying files in `/usr/bin` requires superuser (root) privileges, you can do that with either:

    sudo nano /usr/bin/polychromatic-controller

And make the changes in the Terminal, then press <kbd>CTRL</kbd>+<kbd>X</kbd> then <kbd>Y</kbd> to save.

Or graphically - I believe since Pop_OS! is GNOME, the text editor would be **gedit**:

    sudo gedit /usr/bin/polychromatic-controller

**Comment by Daggerpov** [comment]
Alright, the application works now and launches, but I'm unable to change the lighting effects for my Razer Viper Ultimate mouse or see the charging dock device for it. As for the first issue, this is the error raised in the terminal:
![image](https://user-images.githubusercontent.com/53918934/96010627-04ef7680-0e10-11eb-8cac-6e8d4825b331.png)
also, the python directories are different...

**Comment by Daggerpov** [comment]
Wait nevermind, I needed to restart the daemon to resolve that first issue. So, I'm still wondering why the two python paths are different and why the charging dock won't show up as a device.

**Comment by lah7** [comment]
The Python paths in that screenshot look correct for an Ubuntu-based distro (`/usr/lib/python3/dist-packages/`). Most other distros (and custom installs) normally use `site-packages`.

~~The charging dock doesn't appear as a separate device~~, but OpenRazer does support changing its effect/colour, there are some scripts in this repo that may work:

    scripts/razer_mouse/driver/set_charging_colour.py
    scripts/razer_mouse/driver/set_charging_effect.py

~~Unfortunately, Polychromatic doesn't support charging docks _yet_.~~

**Comment by Daggerpov** [comment]
how do I navigate to these scripts in the repo?

**Comment by lah7** [comment]
Scratch that part about the charging docks, I'm unfamiliar with them. It should appear as a separate device (like `Razer Lancehead Wireless (Receiver)`) and therefore should work in Polychromatic (no need for those scripts)

If you haven't already since installing OpenRazer, you should restart the computer so the device is properly bound to the driver.

**Comment by Daggerpov** [comment]
Well, even when I restart my computer it doesn't show up in the overview on devices, but it lights up.

**Comment by nightsky30** [comment]
@Daggerpov Fairly certain the Viper Ultimate and Basilisk Ultimate mice come with the same dock (or at least it seems [issues](https://github.com/openrazer/openrazer/issues/1018)/[PRs](https://github.com/openrazer/openrazer/pull/1034) tracking the device support for those mice referenced the same dock PID). If it's the Razer charging dock with PID 007e, then it looks like support is being added in PR #1152 along with the Basilisk Ultimate.

**Comment by Daggerpov** [comment]
Yes, they both come with the same charging dock. So you're basically just telling me to wait until it's fixed in a later version of this software?

**Comment by nightsky30** [comment]
> Yes, they both come with the same charging dock. So you're basically just telling me to wait until it's fixed in a later version of this software?

I'm simply saying device support appears to be in the works (to answer as to why it isn't working for you now). I don't know if/when that PR will be merged. Does not seem the author is finishing it any time soon.

Waiting is one option, yes. Building that [branch](https://github.com/openrazer/openrazer/wiki/Building-a-package#ubuntu--linux-mint) for your own personal use is another (though his branch is now behind). And I'm sure testing and feedback for device support would be appreciated. It seems getting the brightness value for the charger isn't working (makes me wonder if that is another wait time issue).

**Comment by Daggerpov** [comment]
alright, I was just clarifying. I wasn't trying to bash the author or talk badly about the software so don't take it as that.
