### ISSUE TITLE
Cannot accept & close Configuring Secure Boot message 

### ISSUE THREAD

**Issue by LornaJ51** [openrazer/openrazer#1294]
Distribution Ubuntu 20.04 LTS

I have followed the instructions for installing via Terminal but the install pops us a message "Your system has UEFI Secure Boot enabled" and I must choose a password. But there is nio indication as to where I have to enter the password, and the <OK> at the foot of the message doesn't seem to be enabled as an 'accept' button, so I cannot get past this screen.  I have tried rebooting and starting the install again and it just sticks at the same place.

**Comment by z3ntu** [comment]
It's probably easiest to just disable Secure Boot. I don't think I've heard many success stories of dkms modules working with Secure Boot properly. This prompt you're seeing isn't from openrazer but from something else - maybe dkms or some ubuntu scripts for dkms.
