### ISSUE TITLE
Deathadder Essential not working 

### ISSUE THREAD

**Issue by charles285** [openrazer/openrazer#1301]
### Distribution

Linux pop-os 5.4.0-7642-generic #46~1598628707~20.04~040157c-Ubuntu SMP Fri Aug 28 18:02:16 UTC  x86_64 x86_64 x86_64 GNU/Linux
### Support

- [x] Have you tried rebooting?
- [x] Have you looked at the [Troubleshooting](https://github.com/openrazer/openrazer/wiki/Troubleshooting) page?

razer_mount log: 
```
Oct 19 10:48:46 pop-os razer_mount[849]: Driver razerkbd
Oct 19 10:48:46 pop-os razer_mount[848]: Driver razerkbd
Oct 19 10:48:46 pop-os razer_mount[851]: Driver razerkbd
**Oct 19 10:48:46 pop-os razer_mount[854]: Device_ID 0003:1532:011A.0002
Oct 19 10:48:46 pop-os razer_mount[852]: Device_ID 0003:1532:011A.0004
Oct 19 10:48:46 pop-os razer_mount[853]: Device_ID 0003:1532:011A.0003**
Oct 19 10:48:46 pop-os razer_mount[858]: Changing group /sys/bus/hid/drivers/razerkbd/0003:1532:011A.0004/
Oct 19 10:48:46 pop-os razer_mount[857]: Changing group /sys/bus/hid/drivers/razerkbd/0003:1532:011A.0002/
Oct 19 10:48:46 pop-os razer_mount[862]: Changing group /sys/bus/hid/drivers/razerkbd/0003:1532:011A.0003/
Oct 19 10:48:46 pop-os razer_mount[865]: Changed group /sys/bus/hid/drivers/razerkbd/0003:1532:011A.0002/
Oct 19 10:48:46 pop-os razer_mount[866]: Changed group /sys/bus/hid/drivers/razerkbd/0003:1532:011A.0004/
Oct 19 10:48:46 pop-os razer_mount[869]: Changed group /sys/bus/hid/drivers/razerkbd/0003:1532:011A.0003/
```
Daemon log also suggest that the mouse is connected:
```
2020-10-19 09:56:28 | razer                          | INFO     | Initialising Daemon (v2.8.0). Pid: 3531
2020-10-19 09:56:28 | razer.screensaver              | INFO     | Initialising DBus Screensaver Monitor
2020-10-19 09:56:28 | razer                          | INFO     | **Found device.0: 0003:1532:011A.0004**
2020-10-19 09:56:28 | razer.device0                  | INFO     | Initialising device.0 RazerBlackWidowUltimate2013
2020-10-19 09:56:29 | razer.device0                  | INFO     | Putting device into driver mode. Daemon will handle special functionality
2020-10-19 09:56:29 | razer                          | INFO     | Serving DBus
```
lsmod | grep razermouse:
```
razermouse             86016  0
hid                   131072  6 i2c_hid,usbhid,hid_multitouch,razerkbd,hid_generic,razermouse
```
checking the `/sys/bus/hid/drivers` folder gives me this
ls -l /sys/bus/hid/drivers:
```
total 0
drwxr-xr-x 2 root root 0 Oct 19 10:48 hid-generic
drwxr-xr-x 2 root root 0 Oct 19 10:48 hid-multitouch
drwxr-xr-x 2 root root 0 Oct 19 10:48 razerkbd
drwxr-xr-x 2 root root 0 Oct 19 11:07 razermouse
```

However lsusb give me this:
```
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 006: ID 0cf3:e006 Qualcomm Atheros Communications Dell Wireless 1802 Bluetooth 4.0 LE
Bus 001 Device 005: ID 0bda:0129 Realtek Semiconductor Corp. RTS5129 Card Reader Controller
Bus 001 Device 004: ID 0c45:6710 Microdia Integrated Webcam
Bus 001 Device 003: ID 0951:16a4 Kingston Technology HyperX Virtual Surround Sound
Bus 001 Device 002: ID 1532:011a Razer USA, Ltd BlackWidow Ultimate 2013
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
```
The mouse doesn't even light up. I followed the troubleshooting guide and my user is in the plugdev group.
Let me know if you need any other info.
Thanks in advance.

**Comment by z3ntu** [comment]
It looks like the kernel doesn't see your mouse at all (it's not showing up in the `lsusb` output). Can you try the mouse on another computer to see if it works there? Also note that openrazer just controls the lights, dpi and things on the mouse but the normal mouse functionality is provided by in-kernel modules so if the mouse doesn't work at all then it's very likely that it's not openrazer's fault.

**Comment by charles285** [comment]
> It looks like the kernel doesn't see your mouse at all (it's not showing up in the `lsusb` output). Can you try the mouse on another computer to see if it works there? Also note that openrazer just controls the lights, dpi and things on the mouse but the normal mouse functionality is provided by in-kernel modules so if the mouse doesn't work at all then it's very likely that it's not openrazer's fault.

Makes sense, thanks for your time!
