### ISSUE TITLE
Feature request: OpenLogitech?

### ISSUE THREAD

**Issue by sanawu** [openrazer/openrazer#1309]
Would be nice to have something like this for Logitech too, OpenLogitech?

**Comment by z3ntu** [comment]
[libratbag](https://github.com/libratbag/libratbag) supports a bunch of Logitech devices so you should look there.

**Comment by sanawu** [comment]
It's for a Keyboard not a mouse, currently the only solution for me is to use Windows in VirtualBox and the Windows Logitech software to configure it then back to Linux but I have to do that every session as it's not retained in non-volatile memory
