### ISSUE TITLE
Support for the Razer Huntsman Mini

### ISSUE THREAD

**Issue by Tochey** [openrazer/openrazer#1310]
Can you add support for the Razer Huntsman Mini. I love what you guys are doing

**Comment by z3ntu** [comment]
Can you please check whether your device has the usb id `1532:0257`? `lsusb | grep 1532` should tell you

**Comment by Tochey** [comment]
Where can I find the usb id? I looked on the back and nothing there

**Comment by z3ntu** [comment]
You can run `lsusb | grep 1532` in a terminal.

**Comment by Tochey** [comment]
tried running it on a Mac terminal but the command was not found 
<img width="366" alt="git" src="https://user-images.githubusercontent.com/54341970/97166112-15321a80-175b-11eb-8679-c45de85bc114.png">
Does this image help?

**Comment by z3ntu** [comment]
Yes, this is a duplicate of #1230 then, but I'm not sure why you're asking for support in a Linux driver when you're using macOS?
