### ISSUE TITLE
Support for [Macs]

### ISSUE THREAD

**Issue by dodgerblue1** [openrazer/openrazer#1315]
### Device Info

* Name: <Macs>
Are you adding support for macs soon? I really need synapse 3 for mac or something like it. 
If not, thank you anyways.

**Comment by z3ntu** [comment]
Please read any of the issues found when searching for `macOS` in the issue search... https://github.com/openrazer/openrazer/issues?q=macos

**Comment by lah7** [comment]
> Simply put, it's not possible for OpenRazer in its current form to run on Windows/Mac because it depends on a Linux-only driver. There's @z3ntu's razer_test which handles everything in user space, eliminating the need for a driver. It's a work-in-progress, and is already making progress to run on Windows/Mac.
>
> Eventually that project will supersede OpenRazer 2.x, so hopefully some day.

From here: https://github.com/openrazer/openrazer/issues/1038#issuecomment-598193639.
