### ISSUE TITLE
Razer Basilisk is not recognized

### ISSUE THREAD

**Issue by KaratekHD** [openrazer/openrazer#1317]
### Distribution

openSUSE Tumbleweed

### Support

- [X] Have you tried rebooting?
- [X] Have you looked at the [Troubleshooting](https://github.com/openrazer/openrazer/wiki/Troubleshooting) page?

I just received my Razer Basilisk, as it is listed as supported with Openrazer. However, it is not recognized by the daemon. 
I did a bit of research, and figured out it has a slightly different PID:
 ```
Bus 001 Device 002: ID 1532:0065 Razer USA, Ltd RZ01-0265, Gaming Mouse [Basilisk Essential]
```
Is this a huge problem or could I just somewhere change the ID the daemon expects?

Thank you

~Jens

**Comment by z3ntu** [comment]
Your device is tracked in #1134

**Comment by KaratekHD** [comment]
Thank you, wasn't aware this is a different model.
