### ISSUE TITLE
Razer Blade 15 (Early 2020) Keyboard effects not working

### ISSUE THREAD

**Issue by maxkofler** [openrazer/openrazer#1327]
Some effects on the Razer Blade 15 (Early 2020) do not work (Polychromatic says "Error in setting effect "..." on Razer Blade 15 (Early 2020)) also other Frontends don't are capable of setting these effects

lsusb | grep 1532 is giving me:
"Bus 001 Device 003: ID 1532:0255 Razer USA, Ltd Razer Blade"

And the error from polychromatic is a permission error:

```
Failed to set effect 'starlight' for Razer Blade 15 Base (Early 2020).
Exception: org.freedesktop.DBus.Python.PermissionError: Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/dbus/service.py", line 711, in _message_cb
    retval = candidate_method(self, *args, **keywords)
  File "/usr/lib/python3/dist-packages/openrazer_daemon/dbus_services/dbus_methods/chroma_keyboard.py", line 540, in set_starlight_random_effect
    with open(driver_path, 'wb') as driver_file:
PermissionError: [Errno 13] Permission denied: '/sys/devices/pci0000:00/0000:00:14.0/usb1/1-8/1-8:1.2/0003:1532:0255.0004/matrix_effect_starlight'
```

Effects that cause the upper error:

- Starlight
- Wave

Effects that can be set, but don't work (they don't throw an error, but result in the effect Breath or Spectrum):

- Reactive
- Ripple

**Comment by z3ntu** [comment]
Hi, please provide the output of `lsusb | grep 1532` .
Additionally please start polychromatic-controller from the command line and check if you see an exception there when you get the "Error in setting effect" message in the UI.

**Comment by maxkofler** [comment]
> Hi, please provide the output of `lsusb | grep 1532` .
> Additionally please start polychromatic-controller from the command line and check if you see an exception there when you get the "Error in setting effect" message in the UI.

Ok, thankyou, I update the issue

**Comment by z3ntu** [comment]
Does this happen on every boot or just sometimes? Maybe try rebooting a couple of times and checking if it doesn't work each time.

**Comment by maxkofler** [comment]
> Does this happen on every boot or just sometimes? Maybe try rebooting a couple of times and checking if it doesn't work each time.

Nope, doesn't make a difference, also updated openrazer, it does not work... updated the original  comment with more infos
