### ISSUE TITLE
how to configure keys on razerorbweaver

### ISSUE THREAD

**Issue by user-only** [openrazer/openrazer#1329]
### Distribution
Linux Mint 20

### Support

- [ ] Have you tried rebooting?
- [x] Have you looked at the [Troubleshooting](https://github.com/openrazer/openrazer/wiki/Troubleshooting) page?

How can I configure keys? 
I've installed:
- openrazer, the keypad wasn't found
- opengenie, the keypad is found
I don't need the lighting feature but the binding of keys. Which programms needed to do this?
(English is not my favorite language and difficult to me.)

**Comment by chabad360** [comment]
Currently openrazer doesn't support keybinding, but it is in the works (#1124). If you don't want to wait (or don't wanna try it out), you can use things like keyboard-master or input-modifier to remap your keys.
