### ISSUE TITLE
Razer Viper

### ISSUE THREAD

**Issue by ghost** [openrazer/openrazer#1341]
### Distribution
Fedora 33

### Support
After updating firmware on the Razer Viper to the latest, the daemon no longer detects it.

**Comment by diffficult** [comment]
dammit, I knew that one reboot into windows did something. Having the same issue. I might add, that somehow my Orbweaver `1532:0113 Razer USA, Ltd RZ07-0074 Gaming Keypad [Orbweaver]` was affected as well.

**Comment by z3ntu** [comment]
Anything in `dmesg` regarding e.g. `razer`?

**Comment by diffficult** [comment]
> Anything in `dmesg` regarding e.g. `razer`?

not on my end. I will test on a different computer later on and report back. 

edit:

my bad, kernel headers weren't installed when I migrate all my stuff, found out when I used the mouse in my old rig. 
At least for me, no problems with the mouse.
