### ISSUE TITLE
Razerkbd nowhere to be found in manjaro

### ISSUE THREAD

**Issue by TcdUqkZZZ** [openrazer/openrazer#1344]
### Distribution
fully updated manjaro installation
### Support

after installing,  there is no razerkbd  under /sys/bus/hid/drivers/, nor does `lsmod | grep razerkbd` return anything.

daemon runs, but obviously cannot bind the device, so client software doesn't recognize it. `razer_mount log: sudo journalctl -b | grep -i razer_mount` similarly returns nothing, despite razer_mount script actually being where it should be.

as far as the deamon goes, it starts correctly and then remains at SERVING DBUS.

note that `dkms status` returns 
```
openrazer-driver, 2.9.0, 4.9.243-1-MANJARO, x86_64: installed
openrazer-driver, 2.9.0, 5.9.8-2-MANJARO, x86_64: installed

```

issue is present both in the regular and git packages.
as it should.
Thanks for the help.

**Comment by TcdUqkZZZ** [comment]
Uodate: after solving this issue, I still find the drivers not working: even tryingto bind the device as root results in failure with error no such device, while binding and unbinding in hid-generic works perfectly.

**Comment by z3ntu** [comment]
Can you please post the output of the command `lsusb | grep 1532` ?

**Comment by googleboy360** [comment]
any update on this just got my keyboard today! trying to figure out a way now

**Comment by yumyumfarted** [comment]
Hello, 
I'm having a similar issue. I'll attach the files and output that I'm having:

(I'm using Poly-chromatic, so I'll attach a screenshot of the troubleshooter [here](https://imgur.com/a/KaI6nLv))

After running "sudo modprobe razerkbd" manually, I got this output:

```
modprobe: FATAL: Module razerkbd not found in directory /lib/modules/5.9.16-1-MANJARO

```
I checked and all of my packages are built to py 3.9 as well. I couldn't tell if I had to rebuild everything to 3.8, or rebuild to 3.9. If it's the 3.9, I won't have to do anything. 


I also confirmed that my keyboard is supported, I'm using the Black-widow essential.

**Comment by z3ntu** [comment]
@yumyumfarted Try `sudo dkms install openrazer-driver/3.0.0`. You're likely missing the kernel headers for your kernel (`linux59-headers`)

**Comment by yumyumfarted** [comment]
Yeah, it looks like I don't have the headers. The headers are 5.10, and the version is 5.9. Looks like I need to update the kernel.

**Comment by yumyumfarted** [comment]
Okay, the dkms module is loaded now. If you look at the picture, there are only two errors now. "DKMS module is currently loaded" and "Check for supported hardware". Which I have checked and it is supported.

**Comment by yumyumfarted** [comment]
Had to do a reboot, everything works now.
