### ISSUE TITLE
Razer Ornata V2 not supported

### ISSUE THREAD

**Issue by FIvanO** [openrazer/openrazer#1359]
Razer Ornata V2 not supported. Tried on Linux 20.04

**Comment by FIvanO** [comment]
openrazer-daemon can't recognize "Razer Ornata V2" keyboard. Does someone have any tips on how to recognize it?
(Screen from razer-genie app)
![image](https://user-images.githubusercontent.com/23000810/100739994-aa6ea180-33e0-11eb-9337-a316530aa82f.png)

Thanks

**Comment by nightsky30** [comment]
Support for this device is tracked in #1187

**Comment by FIvanO** [comment]
Did not found there at least something useful for resolving the issue.

**Comment by nightsky30** [comment]
The linked issue is to track adding support for the Ornata V2. It is not supported by the daemon at this time. There is nothing that can be done regarding your issue other than actually adding and testing the code to support the device.

**Comment by z3ntu** [comment]
Closing as duplicate of #1187 , thanks @nightsky30
