### ISSUE TITLE
AsyncIO

### ISSUE THREAD

**Issue by terricain** [openrazer/openrazer#136]
Have opened an issue for the PR https://github.com/terrycain/razer-drivers/pull/115

Merged PR into - https://github.com/terrycain/razer-drivers/tree/cyanogen-async

Have made debian/ubunut packages for gbulb and python3-evdev 0.6.4

**Comment by z3ntu** [comment]
* Fedora & openSUSE packages exist for python3-gbulb and python3-evdev.
~~* rpm packages don't build for openSUSE (all versions) (yet)~~
* The AUR has both.

**Comment by terricain** [comment]
Hmm might just be easier to bodge the opensuse ones if we need to

**Comment by z3ntu** [comment]
Got [gbulb](https://build.opensuse.org/package/show/home:z3ntu/python3-gbulb) and [evdev](https://build.opensuse.org/package/show/home:z3ntu/python-evdev) building for Fedora & openSUSE :)

**Comment by terricain** [comment]
Nice

**Comment by hyperb1iss** [comment]
Have the 3.4 stuff working, check my master branch. Queue is getting kinda deep :) I'll open a ticket in the next day or two to explain the new stuff!

**Comment by terricain** [comment]
Will have a look, all ive noticed from my own dabbling in asyncio is that it all works great apart from the ripple effect which just lags

**Comment by hyperb1iss** [comment]
Rebased my branch onto master and squashed down a lot of the changes.

**Comment by terricain** [comment]
Am busy but will try and get a look at it this weekend
