### ISSUE TITLE
Error after update to python-3.9.0-1

### ISSUE THREAD

**Issue by ghost** [openrazer/openrazer#1362]
### Distribution

Arch Linux 5.9.11-arch2-1

### Support

- [x] Have you tried rebooting?
- [x] Have you looked at the [Troubleshooting](https://github.com/openrazer/openrazer/wiki/Troubleshooting) page?

/usr/bin/polychromatic-controller throws exception at line 52 and 58. I rolled back afterwards so I don't remember the exact message I got, but it was something like: "couldn't find pylib" (same for "polychromatic"). I didn't get the expected print messages (see line 63-65). There is basically a problem with the "pylib" and "polychromatic" module when using python-3.9.0-1, they are not recognized.

**Comment by z3ntu** [comment]
You need to rebuild all AUR packages that contain Python with such upgrades in Arch. 
You can list the affected packages with the command `pacman -Qo /usr/lib/python3.8/`

**Comment by ghost** [comment]
Will try soon, I am currently in class :). I will let you know after rebuilding, thanks for replying so fast btw.

**Comment by ghost** [comment]
@z3ntu rebuilding worked, thanks for the tip! I will close the issue.

**Comment by Trollwut** [comment]
Sorry to do the grave-digging, but just for the sake of completeness, you can update all affected packaghe with this command (using the `paru` AUR helper in this example:

    pacman -Qoq /usr/lib/python3.8/ | paru -S --rebuild -

This command could be modified for future updated, if necessary.

**Comment by leofleeo** [comment]
Lots of apps coded in python really hate me

**Comment by leofleeo** [comment]
Whenever I try the solution I get this error:
No package owns /usr/lib/python3.8

**Comment by lah7** [comment]
@CloudyWhale Try again but reinstall packages that were installed for `3.9`. Python 3.10 is the latest now (`pacman -Q python`). In Arch, whenever there's a major version of Python, all Python packages that came from the AUR need to be rebuilt.

    pacman -Qoq /usr/lib/python3.9/ | paru -S --rebuild -

**Comment by leofleeo** [comment]
I did earlier and it worked.
