### ISSUE TITLE
Fetching not working on Gentoo linux

### ISSUE THREAD

**Issue by pogwizd** [openrazer/openrazer#1366]
### Distribution: Gentoo Linux

profile: 17.1 - desktop/plasma/systemd
kernel: 5.9.1-gentoo

### Support

While truying to install openrazer, the emerge command quit returning the following error message:

> * Fetching https://github.com/openrazer/openrazer.git ...
> git fetch https://github.com/openrazer/openrazer.git +HEAD:refs/git-r3/HEAD
> fatal: unable to access 'https://github.com/openrazer/openrazer.git/': Problem with the SSL CA cert (path? access rights?)
>  * ERROR: app-misc/openrazer-9999::vifino-overlay failed (unpack phase):
>  *   Unable to fetch from any of EGIT_REPO_URI

Now the question is why is it impossible to download the given file while trying to emerge it...

Thank for any help,

**Comment by z3ntu** [comment]
Please check your SSL certificates. I can neither fix your machine, github or the gentoo ebuild.
