### ISSUE TITLE
Diamonback Chroma && Deathstalker Chroma branch

### ISSUE THREAD

**Issue by terricain** [openrazer/openrazer#137]
Merged [PR](https://github.com/terrycain/razer-drivers/pull/121) into branch [CalcProgrammer1-diamondback_deathstalker_test](https://github.com/terrycain/razer-drivers/tree/CalcProgrammer1-diamondback_deathstalker_test)
@CalcProgrammer1 - have merged PR into branch, 

Copied this here for reference
>I have tested the Diamondback and the DeathStalker Chroma.
>
>The Diamondback works just like the Mamba TE except with a 21 LED matrix rather than a 16 LED matrix. The LED array column 0 is the top right LED and continues down and around and up the left side to LED array column 18. Column 19 is the logo LED and column 20 is the scroll wheel LED.
>
>The DeathStalker does not have per-key backlighting and functions more like the mice and Firefly than the other keyboards. I discovered that despite only having 6 zones exposed in the official Chroma SDK, it really has 12 controllable LEDs with every two LEDs blended together to light one zone. If you set them to two very different colors, you will get a mess. It can be used to make smoother gradients though. Treat it like a Firefly with 12 columns when using custom effects, otherwise it works like the other keyboards.
>
>IMPLEMENTED: Addition of these two devices to driver, changes to get custom effects working with these devices
>
>TESTED: All lighting modes except Reactive including custom effects, serial number, device type, firmware version requests, actual usage as keyboard/mouse, game mode LED, macro mode LED and macro mode LED effect
>
>NOT TESTED: Macros, key remaps, game mode, reactive effects, DPI changes, any other special non-lighting related stuff
>
>NOT IMPLEMENTED: Daemon/application layer stuff

**Comment by terricain** [comment]
I have merged the driver and resolved the conflicts. Would you mind checking out `CalcProgrammer1-diamondback_deathstalker_test` and testing that, once thats done we can go onto testing the parts you havent tested yet.

**Comment by CalcProgrammer1** [comment]
I'm out of town for the week and didn't bring my DeathStalker with me.  I do have my Diamondback.  I can test next weekend for sure with both devices.

**Comment by terricain** [comment]
Awesome :smile:

**Comment by usineur** [comment]
Hi. This branch seems deleted now. Is there any reason for that ?

**Comment by terricain** [comment]
ooh crap I think I might have deleted it by accident. lemme go and find it again

**Comment by terricain** [comment]
Its back again

**Comment by terricain** [comment]
Have pushed daemon support to said branch, can someone test so i can merge it.

**Comment by usineur** [comment]
Yes, I will give it a try

So I just tried with "Polychromatic Controller", my DeathStalker answers well to each effects expect "Reactive" but it seems normal because this effect is not supported for this keyboard.

**Comment by terricain** [comment]
PPA updated.
