### ISSUE TITLE
Support for both Razer Basilisk Ultimate and Nari Ultimate

### ISSUE THREAD

**Issue by Fluffy4Star** [openrazer/openrazer#1374]
### Support

- [ ] Have you tried rebooting?
- [ ] Have you looked at the [Troubleshooting](https://github.com/openrazer/openrazer/wiki/Troubleshooting) page?

**Comment by nightsky30** [comment]
Please see #1215 and #974

**Comment by z3ntu** [comment]
As @nightsky30 said (thanks!)
