### ISSUE TITLE
Support for [Razer Blade 15 Advanced (2020)] - Windows Server 2019

### ISSUE THREAD

**Issue by fayv0** [openrazer/openrazer#1393]
### Device Info

* Name: <Razer Blade 15 Advanced (2020)>
* Product Number: <RZ09-03305E43>
* Model Number: <RZ09-0330>

This is a bit of an odd request but I wouldn't think it would be too difficult, I'd like to request Windows Server 2019 drivers as the Windows 10 version do not seem to work.  My USB VID:PID is 1532:0253, the driver in question is the touchpad. I haven't had any luck with the wireless NIC either but I can just find a replacement worst case scenario with compatibility.

Any help or advice is greatly appreciated.
Thanks

**Comment by z3ntu** [comment]
I'm not sure why you think that OpenRazer is available for Windows, I think it is clearly stated everywhere that OpenRazer is Linux-only.
