### ISSUE TITLE
Razer Orochi 2011

### ISSUE THREAD

**Issue by theonedemon** [openrazer/openrazer#141]
Not support old mouse:
`
Bus 002 Device 004: ID 1532:0013 Razer USA, Ltd Orochi mouse
`

**Comment by terricain** [comment]
https://github.com/terrycain/razer-drivers/wiki/Reverse-Engineering-USB-Protocol

**Comment by z3ntu** [comment]
@theonedemon Can you please provide screenshots and wireshark captures of the usb traffic sent by Synapse (see link from Terry)?

**Comment by theonedemon** [comment]
Sorry for the delayed response
I made dump via wireshark: https://www.dropbox.com/sh/915jxsyvfb6wecz/AADoOjFw5ZS8qhDhycUgorV5a?dl=0

**Comment by terricain** [comment]
Also need `ls -lah /dev/input/by-id`

**Comment by terricain** [comment]
Also what distro are you on

**Comment by theonedemon** [comment]
> Also need ls -lah /dev/input/by-id

lrwxrwxrwx 1 root root   9 Июн 23 20:34 usb-046d_081b_F5473740-event-if00 -> ../event7
lrwxrwxrwx 1 root root   9 Июн 23 20:34 usb-Logitech_USB_Receiver-if02-event-kbd -> ../event2
lrwxrwxrwx 1 root root  10 Июн 25 15:31 usb-Razer_Razer_Orochi-event-mouse -> ../event13
lrwxrwxrwx 1 root root  10 Июн 25 15:31 usb-Razer_Razer_Orochi-if01-event-kbd -> ../event14
lrwxrwxrwx 1 root root   9 Июн 25 15:31 usb-Razer_Razer_Orochi-mouse -> ../mouse1

> Also what distro are you on

Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.2 LTS
Release:	16.04
Codename:	xenial
kernel: 4.8.0-54-generic #57~16.04.1-Ubuntu

**Comment by terricain** [comment]
install the debs from here
https://drive.google.com/open?id=0BydYgD2LzDUCZnplQU43Ti1Ibms
```
sudo dpkg -i debname*
sudo apt-get install -f
```

Reboot
then do
```
lsmod | grep razer
ls -lah /sys/bus/hid/drivers
```

**Comment by theonedemon** [comment]
> lsmod | grep razer

```
razermouse             61440  0
hid                   122880  7 razermouse,hid_generic,usbhid,hidp,hid_logitech_dj,hid_logitech_hidpp
```
> ls -lah /sys/bus/hid/drivers

```
drwxr-xr-x 2 root root 0 Jun 25 18:58 hid-generic
drwxr-xr-x 2 root root 0 Jun 25 18:58 logitech-djreceiver
drwxr-xr-x 2 root root 0 Jun 25 18:58 logitech-hidpp-device
drwxr-xr-x 2 root root 0 Jun 25 18:58 razermouse
```

**Comment by terricain** [comment]
ls -lah /sys/bus/hid/drivers/razermouse

**Comment by theonedemon** [comment]
```
total 0
drwxr-xr-x 2 root root    0 Jun 25 18:58 .
drwxr-xr-x 6 root root    0 Jun 25 18:58 ..
lrwxrwxrwx 1 root root    0 Jun 25 19:08 0003:1532:0013.0006 -> ../../../../devices/pci0000:00/0000:00:12.2/usb1/1-5/1-5.2/1-5.2:1.0/0003:1532:0013.0006
lrwxrwxrwx 1 root root    0 Jun 25 19:08 0003:1532:0013.0007 -> ../../../../devices/pci0000:00/0000:00:12.2/usb1/1-5/1-5.2/1-5.2:1.1/0003:1532:0013.0007
--w------- 1 root root 4.0K Jun 25 18:56 bind
lrwxrwxrwx 1 root root    0 Jun 25 19:08 module -> ../../../../module/razermouse
--w------- 1 root root 4.0K Jun 25 19:08 new_id
--w------- 1 root root 4.0K Jun 25 19:08 uevent
--w------- 1 root root 4.0K Jun 25 19:08 unbind
```

**Comment by z3ntu** [comment]
`ls -la /sys/bus/hid/drivers/razermouse/0*/`

**Comment by theonedemon** [comment]
> ls -la /sys/bus/hid/drivers/razermouse/0*/

```
/sys/bus/hid/drivers/razermouse/0003:1532:0013.0006/:
total 0
drwxr-xr-x 5 root plugdev    0 Jun 25 18:56 .
drwxr-xr-x 5 root root       0 Jun 25 19:11 ..
-r--r--r-- 1 root plugdev 4096 Jun 25 18:56 country
-rw-rw---- 1 root plugdev 4096 Jun 25 18:56 device_mode
-r--r----- 1 root plugdev 4096 Jun 25 18:56 device_serial
-r--r----- 1 root plugdev 4096 Jun 25 18:56 device_type
lrwxrwxrwx 1 root plugdev    0 Jun 25 18:56 driver -> ../../../../../../../../bus/hid/drivers/razermouse
-r--r----- 1 root plugdev 4096 Jun 25 18:56 firmware_version
drwxr-xr-x 3 root plugdev    0 Jun 25 18:56 hidraw
drwxr-xr-x 3 root plugdev    0 Jun 25 18:56 input
-rw-rw---- 1 root plugdev 4096 Jun 25 18:56 logo_led_state
-r--r--r-- 1 root plugdev 4096 Jun 25 18:56 modalias
drwxr-xr-x 2 root plugdev    0 Jun 25 18:56 power
-r--r--r-- 1 root plugdev 4096 Jun 25 18:56 report_descriptor
-rw-rw---- 1 root plugdev 4096 Jun 25 18:56 scroll_led_state
lrwxrwxrwx 1 root plugdev    0 Jun 25 18:56 subsystem -> ../../../../../../../../bus/hid
--w--w---- 1 root plugdev 4096 Jun 25 18:56 test
-rw-r--r-- 1 root plugdev 4096 Jun 25 18:56 uevent
-r--r----- 1 root plugdev 4096 Jun 25 18:56 version

/sys/bus/hid/drivers/razermouse/0003:1532:0013.0007/:
total 0
drwxr-xr-x 5 root plugdev    0 Jun 25 18:56 .
drwxr-xr-x 5 root root       0 Jun 25 19:11 ..
-r--r--r-- 1 root plugdev 4096 Jun 25 18:56 country
lrwxrwxrwx 1 root plugdev    0 Jun 25 18:56 driver -> ../../../../../../../../bus/hid/drivers/razermouse
drwxr-xr-x 3 root plugdev    0 Jun 25 18:56 hidraw
drwxr-xr-x 3 root plugdev    0 Jun 25 18:56 input
-r--r--r-- 1 root plugdev 4096 Jun 25 18:56 modalias
drwxr-xr-x 2 root plugdev    0 Jun 25 18:56 power
-r--r--r-- 1 root plugdev 4096 Jun 25 18:56 report_descriptor
lrwxrwxrwx 1 root plugdev    0 Jun 25 18:56 subsystem -> ../../../../../../../../bus/hid
-rw-r--r-- 1 root plugdev 4096 Jun 25 18:56 uevent

```

**Comment by z3ntu** [comment]
`cat /sys/bus/hid/drivers/razermouse/0*/{device_type,device_serial,firmware_version,device_mode,logo_led_state,scroll_led_state}`

**Comment by theonedemon** [comment]
> cat /sys/bus/hid/drivers/razermouse/0*/{device_type,device_serial,firmware_version,device_mode,logo_led_state,scroll_led_state}

```
Razer Orochi 2011
PM000767010762
v9.99
0:0
0
0
```

**Comment by z3ntu** [comment]
```
cd $(dirname /sys/bus/hid/drivers/razermouse/0*/device_serial)
echo -n '1' > logo_led_state
echo -n '1' > scroll_led_state
cat logo_led_state
cat scroll_led_state
sleep 10s # check if the leds are on!! 10 second pause ;)
echo -n '0' > logo_led_state
echo -n '0' > scroll_led_state
cat logo_led_state
cat scroll_led_state
```

**Comment by terricain** [comment]
Run those commands in batches of 2 as they will change leds. If you run them all at once it'll just look like the leds are off.

If it works that is

**Comment by theonedemon** [comment]
Output:
1
1
0
0

logo_led_state - control battery indicator
scroll_led_state - control scroll led

It's works!

**Comment by theonedemon** [comment]
please add support to polychromatic-controller

**Comment by z3ntu** [comment]
Yes, daemon support will come soon 😃

**Comment by terricain** [comment]
Install these debs, reboot https://drive.google.com/open?id=0BydYgD2LzDUCZnplQU43Ti1Ibms

Then see if it appears in polychromatic

**Comment by theonedemon** [comment]
> Then see if it appears in polychromatic
thanks, mouse connected in polychromatic, but toogle indicator block works incorrect:

![](https://dl.dropboxusercontent.com/1/view/g5671ym3liebo52/Apps/Shutter/ae1de_2017-06-25.png)

1. Settings:
![](https://dl.dropboxusercontent.com/1/view/6vslybk9eksf5wt/Apps/Shutter/7a544_2017-06-25.png)
1.1 Scrool whell led - off
1.2 Power indicator - off

2. Settings:
![](https://dl.dropboxusercontent.com/1/view/9bb748qkqea6oxb/Apps/Shutter/1fd1f_2017-06-25.png)
2.1 Scrool whell led - off
2.2 Power indicator - on

3. Settings:
![](https://dl.dropboxusercontent.com/1/view/rj7lyt9mzd4bsks/Apps/Shutter/40dd9_2017-06-25.png)
2.1 Scrool whell led - on
2.2 Power indicator - on

4. Settings:
![](https://dl.dropboxusercontent.com/1/view/p1nq5kylw67mqm4/Apps/Shutter/d4b83_2017-06-25.png)
2.1 Scrool whell led - off
2.2 Power indicator - off

Please tell me what the program can be change bind key in mouse or change sensitivity ( DPI ) ?

**Comment by terricain** [comment]
I dont have pcaps or images for dpi in synapse

**Comment by theonedemon** [comment]
1. I upload pcap change "sensitivity" and "Polling Rate"
https://www.dropbox.com/sh/915jxsyvfb6wecz/AADoOjFw5ZS8qhDhycUgorV5a?dl=0

2. Customize bind dont logging in wireshark

**Comment by terricain** [comment]
Customised binds are done in software

**Comment by terricain** [comment]
Install these debs and reboot
https://drive.google.com/open?id=0BydYgD2LzDUCZnplQU43Ti1Ibms
DPI "might" work

**Comment by theonedemon** [comment]
i installed last debs:
![](https://dl.dropboxusercontent.com/1/view/3a4xvsehjulyegs/Apps/Shutter/83224_2017-06-26.png)

but, change DPI not changed speed mouse cursor =( 

after restart daemon reset settings:
![](https://dl.dropboxusercontent.com/1/view/gtws9gj1jqrthsk/Apps/Shutter/c11ec_2017-06-26.png)

@terrycain you can write to me when you updated remotes/origin/feature_orochi_2011_0x0013
I can compile the drivers myself, this should speed up debugging

**Comment by theonedemon** [comment]
@terrycain please push last commit with dpi

**Comment by theonedemon** [comment]
i tested drivers 2 day, dpi and pooling_rate change incorrect:
`cat dpi` show:
```
76:76
```
change dpi: 
```
echo -n '500' > dpi 
#or
echo -n '500:500' > dpi
```
dont change real dpi in mouse and `echo dpi` always show 76:76

`cat poll_rate` show always =  0

I open my pcap ( 01_polling_rate_125.pcapng , 01_polling_rate_500.pcapng , 01_polling_rate_1000.pcapng ) and found second diffs except:
![](https://dl.dropboxusercontent.com/1/view/xcuk6w1q5f1df6u/Apps/Shutter/a2303_2017-06-28.png)

**Comment by terricain** [comment]
try 
`echo -ne '\x4c' > dpi`
or 
`echo -ne '\x9c' > dpi`

**Comment by terricain** [comment]
poll rate is fine, probs an issue with storing the value. first difference is poll rate, 2nd is a crc. As your mouse doesnt support querying the dpi/poll rate i have to store it (which gets lost on reboot) and there probably a line missing to save it after sending it to the device

**Comment by theonedemon** [comment]
change dpi via console work 
`echo -ne '\x4c' > dpi` output ( cat dpi  ): 76:76
`echo -ne '\x9c' > dpi` output: 156:156
`echo -ne '\x1c' > dpi` output: 28:28

in polychromatic-controller settings not working:
![](https://dl.dropboxusercontent.com/1/view/9rtsbfsnm15b6gr/Apps/Shutter/anim.gif)

**Comment by terricain** [comment]
Does the dpi changes from terminal actually change dpi though?

**Comment by theonedemon** [comment]
yes, in terminal dpi change and no save dpi after reboot

**Comment by terricain** [comment]
Yeah the not saving dpi after reboot is a hardware thing (which synapse hides in software), newer mice do save said dpi.

Ok im not in the mood tonight, but remind me on the weekned and i'll have a look, i have a feeling i know what it is.

**Comment by theonedemon** [comment]
ok, thank you.

**Comment by terricain** [comment]
get latest change from the branch.
Run python3 and then try this
```
from razer.client import DeviceManager
a = DeviceManager()
a.devices

b = a.devices[0]
b.dpi
```
Paste the output.

**Comment by theonedemon** [comment]
```
>>> from razer.client import DeviceManager
>>> a = DeviceManager()
>>> a.devices
[<RazerMouse PM004209829121>]
>>> b = a.devices[0]
>>> b.dpi
(2011, 2011)
>>> 
```

last commit branch feature_orochi_2011_0x0013 = 53e7b053feb1bcfdf6bc22e0b45662af1fc8fb5b

**Comment by terricain** [comment]
ok continuing with that above try
```
b.dpi = 1000, 1000
b.dpi
```
Does that change the dpi?

**Comment by theonedemon** [comment]
```
>>> b.dpi = 1000, 1000
>>> b.dpi
(979, 979)
>>> 
```

dpi has changed

**Comment by terricain** [comment]
ok, therefore, the python library is working, (reason the numbers arnt the same is due to fitting a value > 255 into 1 byte). If applications like polychromatic dont work with dpi, that an application issue. As far as I'm concerned the 2011 is supported :smile:. Will release this weekend and then it should be available in package form

**Comment by terricain** [comment]
Version 1.1.14 is out on launchpad, non Ubuntu packages will be out shortly.
