### ISSUE TITLE
Support for Razer kraken BT

### ISSUE THREAD

**Issue by Anowaa** [openrazer/openrazer#1410]
Hi! thank you for this project! I'm hoping that this could support BT even just to check for the battery percentage, thank you again! I really wish they'd make synapse 3 fo Mac users .___.

**Comment by z3ntu** [comment]
1. This project does not support macOS, only Linux.
2. It sounds like you're looking for https://gitlab.freedesktop.org/pulseaudio/pulseaudio/-/issues/722
