### ISSUE TITLE
Unrecognised Device - Chroma Cynosa 

### ISSUE THREAD

**Issue by geeflaxx** [openrazer/openrazer#1413]
- [ yeah] Have you tried rebooting?
- [yeah ] Have you looked at the [Troubleshooting](https://github.com/openrazer/openrazer/wiki/Troubleshooting) page?

i want to start polychromatic-git, but i get the error that my device is unrecognised.
my chroma cynosa keyboard is in the list of compatibilty.

i use for the install yay -S polychromatic-git

![ERROR KEy](https://user-images.githubusercontent.com/21129138/105841462-eaaf6200-5fd4-11eb-9422-63f98ecd3bf5.jpg)

**Comment by z3ntu** [comment]
Can you check the daemon logs? `journalctl --user-unit openrazer-daemon.service` and `sudo journalctl -b | grep -i razer_mount` ?

**Comment by geeflaxx** [comment]
![Screenshot_20210126_132753](https://user-images.githubusercontent.com/21129138/105844982-5b0cb200-5fda-11eb-9b49-5a61a60ce9d3.png)
![Screenshot_20210126_132653](https://user-images.githubusercontent.com/21129138/105845034-71b30900-5fda-11eb-9cf5-e0f9b29c46b2.png)
bad installed ?

**Comment by z3ntu** [comment]
`openrazer-daemon --version` ?

**Comment by geeflaxx** [comment]
patrick@archlinux ~ $ openrazer-daemon --version
openrazer-daemon 2.9.0

**Comment by z3ntu** [comment]
Also nothing happens when you unplug and replug the device? At least the command `sudo journalctl -b | grep -i razer_mount` from before should show something.

**Comment by geeflaxx** [comment]
![Screenshot_20210126_133820](https://user-images.githubusercontent.com/21129138/105845945-c905a900-5fdb-11eb-8400-ead16b52dadb.png)

**Comment by z3ntu** [comment]
That looks good now. The daemon should now recognize the device - if not please check `openrazer-daemon -Fv`

**Comment by geeflaxx** [comment]
![Screenshot_20210126_134110](https://user-images.githubusercontent.com/21129138/105846236-31548a80-5fdc-11eb-9aa3-2a68f1676bb1.png)

seemed good, i repluged the keyboard and start polychromatic again

**Comment by z3ntu** [comment]
So it works now?

**Comment by geeflaxx** [comment]
after i restart it works :D
i thank you very much !
