### ISSUE TITLE
Missing dependency in Ubuntu package

### ISSUE THREAD

**Issue by christianhujer** [openrazer/openrazer#142]
I have a Razer Blade Stealth (late 2016, Kaby Lake).
I am using Kubuntu 16.10.
I have just installed the razer-drivers by following the instructions given on https://terrycain.github.io/razer-drivers/#download

```
sudo add-apt-repository ppa:terrz/razerutils
sudo apt update
sudo apt install python3-razer razer-kernel-modules-dkms razer-daemon razer-doc
sudo modprobe razerkbd
```

When starting `razer-service`, I get the following error message:

```
christian.hujer@christian-hujer-Blade-Stealth:~$ razer-service 
Traceback (most recent call last):
  File "/usr/bin/razer-service", line 7, in <module>
    from razer_daemon.daemon import daemonize
  File "/usr/lib/python3/dist-packages/razer_daemon/daemon.py", line 20, in <module>
    gi.require_version('Gdk', '3.0')
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 118, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Gdk not available
```

It seems that a dependency is missing.

**Comment by terricain** [comment]
You know what package satisfies that?

**Comment by christianhujer** [comment]
I also tried installing whatever was mentioned in https://terrycain.github.io/razer-drivers/#other that didn't help either. I don't know what package satisfies that, still trying to figure that out.

**Comment by christianhujer** [comment]
I don't know, maybe in case you have a debian / ubuntu system, could you check where the Gdk library for Python is and check which package owns that file?

**Comment by terricain** [comment]
Will have a look when I get home

**Comment by z3ntu** [comment]
Try installing `gtk3` (or whatever it is called)

**Comment by terricain** [comment]
Try installing `gir1.2-gtk-3.0`

**Comment by christianhujer** [comment]
Installing gir1.2-gtk3.0 solved the problem. That's missing dependency. `razer-service` now starts fine.

**Comment by christianhujer** [comment]
```
christian.hujer@christian-hujer-Blade-Stealth:~$ sudo apt-get install razer-daemon
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 razer-daemon : Depends: gir1.2-gtk3.0 but it is not installable
E: Unable to correct problems, you have held broken packages.
```
I think it's the dash missing, the package name is `gir1.2-gtk-3.0`, and I think it's my fault because it's already wrong in the comment above.

Should this issue be reopened or should I file a new issue?

**Comment by z3ntu** [comment]
See #160 (it's being worked on right now)
