### ISSUE TITLE
Support for Razer Blade 15" 2021

### ISSUE THREAD

**Issue by dgmiller81** [openrazer/openrazer#1439]
Razer Blade 15" 2021 - No driver support for the 2021 version of the blade 15.   Would like to see this information.

**Comment by z3ntu** [comment]
Please provide the info from the issue template: https://github.com/openrazer/openrazer/issues/new?assignees=&labels=Device+Support&template=new-device-support.md&title=Support+for+%5Bdevice+name+here%5D

**Comment by dgmiller81** [comment]
Closing - opened a new issue with the necessary information.
