### ISSUE TITLE
My Razer Basilisk Mouse has a Different Device ID

### ISSUE THREAD

**Issue by hanssia** [openrazer/openrazer#1444]
On the supported devices list:, the ID for Razer Basilisk is "1532:0064".  Below is my mouse:

Bus 001 Device 004: ID 1532:0065 Razer USA, Ltd RZ01-0265, Gaming Mouse [Basilisk Essential]

**Comment by z3ntu** [comment]
You have a Basilisk Essential, issue #1134 tracks this device.
