### ISSUE TITLE
Razer Chroma Kitty Edition sidetone?

### ISSUE THREAD

**Issue by HunnyBon** [openrazer/openrazer#1449]
### Distribution
Manjaro Linux Kernel 5.9.16-1

### Support

- [x] Have you tried rebooting?
- [x] Have you looked at the [Troubleshooting](https://github.com/openrazer/openrazer/wiki/Troubleshooting) page?

Hello. I was wondering if the sidetone for the Razer Chroma Kitty Edition headset could be supported. I ask this because it doesn't seem to be strictly software based, as booting into Windows with Synapse 3 loaded up and rebooting into Linux seems to keep the sidetone enabled. It's way different from setting up a pulseaudio sink, because it's instant and possibly through the headset hardware itself. Is there a way to configure it through Linux, and if not, can it be supported?

**Comment by z3ntu** [comment]
If you can provide USB packet captures from Synapse toggling this on and off, it might be possible to reimplement the switch. See https://github.com/openrazer/openrazer/wiki/Reverse-Engineering-USB-Protocol
