### ISSUE TITLE
Kraken Ultimate registers as a monochrome device.

### ISSUE THREAD

**Issue by hendy643** [openrazer/openrazer#1451]
### Distribution

Arch.
Ubuntu 18.04
Ubuntu 20.04

### Support

- [ x] Have you tried rebooting?
- [ x] Have you looked at the [Troubleshooting](https://github.com/openrazer/openrazer/wiki/Troubleshooting) page?

The Kraken Ultimate is a full RGB device, but it registers as a monochrome device.

![screenie](https://user-images.githubusercontent.com/62912828/110351479-c790bd00-802c-11eb-975c-e813cdb25b70.png)

**Comment by lah7** [comment]
"Monochromatic" has nothing to do with OpenRazer. It's Polychromatic's way of _guessing_ (for the most part) whether a device uses the RGB APIs but only physically renders one colour (usually green). For example, the BlackWidow Ultimate 2016.

It's a bug in the application, [please raise the issue there](https://github.com/polychromatic/polychromatic/issues). But, seeing as I'm the author of the app, I've added it to my to-do list. 📝

**Comment by lah7** [comment]
Fixed in https://github.com/polychromatic/polychromatic/commit/9b70e7fe5e4c7c380e091565eb658467c04a8a3b. If you're on the edge PPA or `polychromatic-git` AUR, the fix will be heading your way. 🚚
