### ISSUE TITLE
Suggestion for Windows VM

### ISSUE THREAD

**Issue by rquast** [openrazer/openrazer#146]
Just a suggestion for updating the reverse engineering documentation. I think you can use the free Windows VMs for IE to do this? https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/

This may help anyone who is looking for a Windows VM.

**Comment by terricain** [comment]
As long as you can run it in virtualbox or kvm AND install the Razer synapse software then sure I don't see why not. Try it if it works I'll add it to the wiki

**Comment by rquast** [comment]
Will do. I've downloaded it and will attempt to install the synapse software and run wireshark. Will let you know how it goes.

**Comment by CalcProgrammer1** [comment]
You don't really even need to run Windows in a VM on Linux.  If you install Wireshark on Windows it provides USBPcap as an option and you can log USB transfers from Windows itself.

**Comment by z3ntu** [comment]
You can also download an ISO here: https://www.microsoft.com/software-download/windows10

**Comment by terricain** [comment]
@CalcProgrammer1 theres been cases where usb packets don't get captured. The VM method is more reliable though as long as i get packets im not bothered :wink:

**Comment by rsandoz** [comment]
wireshark in windows has "sometimes works" behavior for me :(

**Comment by terricain** [comment]
Added link
