### ISSUE TITLE
Support for [Razer Firefly v2], seems stable, read down below

### ISSUE THREAD

**Issue by Lanhild** [openrazer/openrazer#1461]
### Device Info
Razer Firefly v2

I made thorough tests for the compatibility layer (if I can call it like that) for the Razer product 'Firefly v2' from the master branch of the repo. All the tests I went through had no problems, everything worked perfectly and flawlessly, so I guess your team could maybe add it's support to the official stable branch.

Thank you, 
Lanhild

**Comment by Lanhild** [comment]
Of course others should make tests to confirm what I'm saying.

**Comment by z3ntu** [comment]
Yes, the device is already supported in git master and will be included in the next release.
