### ISSUE TITLE
Cannot bind device to razerkbd

### ISSUE THREAD

**Issue by ghost** [openrazer/openrazer#1462]
### Distribution 
Arch Linux - latest

### Support

- [x] Have you tried rebooting? yep
- [x] Have you looked at the [Troubleshooting](https://github.com/openrazer/openrazer/wiki/Troubleshooting) page? google too

Having trouble issuing `sudo echo -n "0003:1532:022A.0003" > bind`
`bash: bind: Permission denied`

My keyboard is a Razer Cynosa Chroma. I know its USB VIP:PID is 1532:022A. 1532:022A.0003 is the device listed in lsusb as a "Mouse" so I'm pretty sure I need to bind that one.

`/sys/bus/hid/drivers/hid-generic` didn't have any binds for my keyboard at all, so I guess no need to unbind.

How do I bind `0003:1532:022A.0003` ?

**Comment by z3ntu** [comment]
May I ask why you're trying to do this or what you're trying to achieve? The udev rules do the rebinding automatically, there should be no need for you to do anything.
