### ISSUE TITLE
Fn key doesn't work while the daemon is running

### ISSUE THREAD

**Issue by Broeckelmann** [openrazer/openrazer#1466]
### Distribution
Fedora 33

### Support

- [X ] Have you tried rebooting?
- [X ] Have you looked at the [Troubleshooting](https://github.com/openrazer/openrazer/wiki/Troubleshooting) page?

I just installed the new razer packages and new driver. Now I have Huntsman Mini with lightning support, the lightning now works fine, but the fn-button no longer works, means no F5, etc works anymore. It worked before so it has to be new driver or something in the packages, I don't know which though. Would be nice if it can be fixed, because without the fn support it's kind of a useless keyboard ^-^.

**Comment by z3ntu** [comment]
As a workaround you can stop the daemon (`systemctl --user stop openrazer-daemon.service`)

---

So essentially it seems at least these devices have broken Fn keys currently:
* Huntsman Mini - #1466
* ~~Huntsman TE - https://github.com/openrazer/openrazer/pull/1363#issuecomment-786440971~~
* BlackWidow (2019) - #1459

Please try applying this patch to the driver source, compile and load this driver (`make driver && sudo rmmod razerkbd && sudo insmod ./driver/razerkbd.ko` should work) and give me the output from dmesg from it when using the Fn key?
```diff
diff --git a/driver/razerkbd_driver.c b/driver/razerkbd_driver.c
index fdf4569..c2cd895 100644
--- a/driver/razerkbd_driver.c
+++ b/driver/razerkbd_driver.c
@@ -2185,6 +2185,8 @@ static int razer_raw_event(struct hid_device *hdev, struct hid_report *report, u
         return 0;
     }
 
+    printk(KERN_ERR "razerkbd event: size %d - data\n", size);
+    print_hex_dump(KERN_ALERT, " razerkbd: ", DUMP_PREFIX_NONE, 16, 1, data, size, false);
     // The event were looking for is 16 or 22 bytes long and starts with 0x04.
     // Newer firmware seems to use 22 bytes.
     if(intf->cur_altsetting->desc.bInterfaceProtocol == USB_INTERFACE_PROTOCOL_KEYBOARD &&

```
**Also please only copy out the parts from your dmesg which are not from normal typing (and entering passwords..) because it's essentially a key logger :D**
(adapted from https://github.com/openrazer/openrazer/pull/873#issuecomment-577804267)

**Comment by Broeckelmann** [comment]
Thank you very much for the quick answer, the workaround works (`systemctl --user stop openrazer-daemon.service`).

I'll try applying the patch next.

**Comment by Broeckelmann** [comment]
So I tried around a bit.

Huntsman Mini dmesg:

// This is a normal event
[  312.333553] razerkbd event: size 8 - data
[  312.333557]  razerkbd: 00 00 52 47 46 4b 00 00

// These are fn events
[  313.030879] razerkbd event: size 22 - data
[  313.030890]  razerkbd: 02 e2 00 00 00 00 00 00 00 00 00 00 00 00 00 00
[  313.030892]  razerkbd: 00 00 00 00 00 00
[  313.121555] razerkbd event: size 22 - data
[  313.121560]  razerkbd: 02 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
[  313.121562]  razerkbd: 00 00 00 00 00 00
[  313.314549] razerkbd event: size 22 - data
[  313.314553]  razerkbd: 02 ea 00 00 00 00 00 00 00 00 00 00 00 00 00 00
[  313.314556]  razerkbd: 00 00 00 00 00 00
[  313.432547] razerkbd event: size 22 - data
[  313.432550]  razerkbd: 02 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
[  313.432552]  razerkbd: 00 00 00 00 00 00
[  313.600552] razerkbd event: size 22 - data
[  313.600556]  razerkbd: 02 e9 00 00 00 00 00 00 00 00 00 00 00 00 00 00
[  313.600558]  razerkbd: 00 00 00 00 00 00
[  313.714686] razerkbd event: size 22 - data
[  313.714691]  razerkbd: 02 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
[  313.714693]  razerkbd: 00 00 00 00 00 00
[  313.869676] razerkbd event: size 22 - data
[  313.869680]  razerkbd: 02 b6 00 00 00 00 00 00 00 00 00 00 00 00 00 00
[  313.869682]  razerkbd: 00 00 00 00 00 00
[  313.984687] razerkbd event: size 22 - data
[  313.984690]  razerkbd: 02 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
[  313.984692]  razerkbd: 00 00 00 00 00 00
[  314.174669] razerkbd event: size 22 - data
[  314.174673]  razerkbd: 02 cd 00 00 00 00 00 00 00 00 00 00 00 00 00 00
[  314.174675]  razerkbd: 00 00 00 00 00 00
[  314.312669] razerkbd event: size 22 - data
[  314.312672]  razerkbd: 02 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
[  314.312674]  razerkbd: 00 00 00 00 00 00
[  314.499668] razerkbd event: size 22 - data
[  314.499671]  razerkbd: 02 b5 00 00 00 00 00 00 00 00 00 00 00 00 00 00
[  314.499672]  razerkbd: 00 00 00 00 00 00
[  314.604668] razerkbd event: size 22 - data
[  314.604671]  razerkbd: 02 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
[  314.604673]  razerkbd: 00 00 00 00 00 00
[  315.342669] razerkbd event: size 22 - data
[  315.342672]  razerkbd: 01 00 00 00 00 00 00 00 00 00 00 00 04 00 00 00
[  315.342674]  razerkbd: 00 00 00 00 00 00
[  315.487668] razerkbd event: size 22 - data
[  315.487671]  razerkbd: 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
[  315.487672]  razerkbd: 00 00 00 00 00 00
[  316.244670] razerkbd event: size 22 - data
[  316.244674]  razerkbd: 01 00 00 00 00 00 00 00 00 00 00 00 04 00 00 00
[  316.244676]  razerkbd: 00 00 00 00 00 00
[  316.356669] razerkbd event: size 22 - data
[  316.356674]  razerkbd: 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
[  316.356675]  razerkbd: 00 00 00 00 00 00`Huntsman Mini dmesg:
[  316.516668] razerkbd event: size 22 - data
[  316.516669]  razerkbd: 01 00 00 00 00 00 00 00 00 00 80 00 00 00 00 00
[  316.516670]  razerkbd: 00 00 00 00 00 00
[  316.629668] razerkbd event: size 22 - data
[  316.629670]  razerkbd: 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
[  316.629672]  razerkbd: 00 00 00 00 00 00
[  316.806667] razerkbd event: size 22 - data
[  316.806670]  razerkbd: 01 00 00 00 00 00 00 00 00 00 40 00 00 00 00 00
[  316.806671]  razerkbd: 00 00 00 00 00 00
[  316.934669] razerkbd event: size 22 - data
[  316.934673]  razerkbd: 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
[  316.934675]  razerkbd: 00 00 00 00 00 00
[  317.084685] razerkbd event: size 22 - data
[  317.084687]  razerkbd: 01 00 00 00 00 00 00 00 00 00 00 08 00 00 00 00
[  317.084689]  razerkbd: 00 00 00 00 00 00
[  317.210669] razerkbd event: size 22 - data
[  317.210674]  razerkbd: 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
[  317.210675]  razerkbd: 00 00 00 00 00 00
[  317.350670] razerkbd event: size 22 - data
[  317.350674]  razerkbd: 01 00 00 00 00 00 00 00 00 00 00 04 00 00 00 00
[  317.350676]  razerkbd: 00 00 00 00 00 00
[  317.470669] razerkbd event: size 22 - data
[  317.470672]  razerkbd: 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
[  317.470673]  razerkbd: 00 00 00 00 00 00
[  317.793669] razerkbd event: size 22 - data
[  317.793672]  razerkbd: 04 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
[  317.793674]  razerkbd: 00 00 00 00 00 00
[  319.469557] razerkbd event: size 22 - data
[  319.469563]  razerkbd: 04 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00
[  319.469565]  razerkbd: 00 00 00 00 00 00
[  319.798554] razerkbd event: size 22 - data
[  319.798558]  razerkbd: 01 00 00 00 00 00 00 00 00 00 00 00 04 00 00 00
[  319.798559]  razerkbd: 00 00 00 00 00 00
[  319.920554] razerkbd event: size 22 - data
[  319.920558]  razerkbd: 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
[  319.920560]  razerkbd: 00 00 00 00 00 00
[  320.588557] razerkbd event: size 22 - data
[  320.588563]  razerkbd: 04 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
[  320.588565]  razerkbd: 00 00 00 00 00 00
[  320.815553] razerkbd event: size 22 - data
[  320.815557]  razerkbd: 01 00 00 00 00 00 00 01 00 00 00 00 00 00 00 00
[  320.815558]  razerkbd: 00 00 00 00 00 00

**Comment by Broeckelmann** [comment]
Tell me when you need more for testing. ^-^

**Comment by z3ntu** [comment]
Weird, with v3.0.0 this should work now on your device.. And even with this and the daemon started, the fn key doesn't work?

**Comment by Broeckelmann** [comment]
Nop, I can try to reinstall and then see.

**Comment by Broeckelmann** [comment]
Still doesn't works, hmm.

**Comment by sebw** [comment]
Just upgraded and Fn key does not work on my Huntsman mini either. Fn key works again after stopping the service.

Patched the drivers with the diff above and this is the output:

Fn key pressed:

```
[ 2843.154503] razerkbd event: size 22 - data
[ 2843.154534]  razerkbd: 04 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00
[ 2843.154603]  razerkbd: 00 00 00 00 00 00
```

Fn key released:

```
[ 2844.007550] razerkbd event: size 22 - data
[ 2844.007557]  razerkbd: 04 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
[ 2844.007564]  razerkbd: 00 00 00 00 00 00
```

**Comment by z3ntu** [comment]
Please try #1468 if that works for you.

**Comment by z3ntu** [comment]
@fjpanag Can you please try the v3.0.0 release on your BlackWidow (2019) and check again if it works or doesn't work for you?

**Comment by sebw** [comment]
#1468 works for me on Huntsman mini!

**Comment by fjpanag** [comment]
@z3ntu I just tried v3.0.0, but still nothing...

**Comment by z3ntu** [comment]
@sebw Thanks for confirming!

@fjpanag Can you please also patch the driver as written in https://github.com/openrazer/openrazer/issues/1466#issuecomment-804066364 and send the dmesg parts?

**Comment by unphased** [comment]
I'm on a huntsman mini and stopping the service didn't fix my fn key...

**Comment by ne04** [comment]
Also with Razer Huntsman mini, fn key isn't working. This means no access to F1, F2, etc, as well as arrow keys and volume control, among other things.

**Comment by unphased** [comment]
I'm definitely returning my huntsman mini if this doesnt work soon. because the default position of the fn key and arrow keys is unacceptable, however the key switches are SO GOOD. Very torn I am. Will Openrazer have the capability of changing which key is Fn key? Will openrazer be able to write to the keyboard to make that capability possible to use under windows? I'd like to make it so that right Alt is fn key, and just use shift, ctrl, menu, and fn keys as arrow keys. That's the first step. Then the next step is to enable sane access to page up/down. 

I think it's a very fat chance. I will return the keyboard 😢

**Comment by fjpanag** [comment]
I'm really sorry for the late reply.

It seems that on latest on master (47b79ff1c86666496ead7c36e3791c39a9c0407c), everything works correctly!  
Thank you!

**Comment by kpuljek** [comment]
I just got the update to 3.0.1 and the Fn key still doesn't work. Do I have to do anything else?

**Comment by z3ntu** [comment]
Have you rebooted after updating? Also to confirm, you're using the Huntsman Mini, right?

**Comment by kpuljek** [comment]
Yeah, Huntsman Mini, and have just removed everything and reinstalled it again, then rebooted.
openrazer-daemon --version
openrazer-daemon 3.0.1

Still nothing. :/

**Comment by alimagik1** [comment]
Distribution
Arch Linux

Support
[X ] Have you tried rebooting?
[X ] Have you looked at the [Troubleshooting](https://github.com/openrazer/openrazer/wiki/Troubleshooting) page?

Kernel ver 6.0.5 and 5.15.75-1

BlackWidow V3 Mini HyperSpeed also found a bug in the Fn key in the Japanese version

In the Japanese version, pressing the Fn key to switch between English and Japanese works as an ECS key, but if openrazer-daemon.service is running, it does not work as an ECS key. Works as a key to switch between Japanese and English. (For the English version, the ECS key and the ~ key)

Only one key has a problem. Keys that combine with other Fn keys work.

If you do one of the following as a temporary measure, it will work normally.
1.Stop openrazer-daemon.service
2.Uninstall kernel-header
3.Connect the keyboard with Bluetooth

hope it improves

**Comment by z3ntu** [comment]
@alimagik1 I don't quite understand what you mean.

From what I can see from pictures of the keyboard (and openrazer code), at least the US version has ` and ~ characters on the Esc key. So normally you get Esc key, and when you press Fn+Esc then you get one of these characters.

How it this different from your variant, the Japanese version? Might be useful to include a picture of your keyboard so I understand the problem better. I also have no clue about input with Japanese so "key to switch between Japanese and English" doesn't say anything to me.

**Comment by alimagik1** [comment]
> @alimagik1 I don't quite understand what you mean.
> 
> From what I can see from pictures of the keyboard (and openrazer code), at least the US version has ` and ~ characters on the Esc key. So normally you get Esc key, and when you press Fn+Esc then you get one of these characters.
> 
> How it this different from your variant, the Japanese version? Might be useful to include a picture of your keyboard so I understand the problem better. I also have no clue about input with Japanese so "key to switch between Japanese and English" doesn't say anything to me.

thanks for reply

Paste the image of the Japanese keyboard layout

![71WoUtulyuS _AC_SL1500_](https://user-images.githubusercontent.com/13101956/198883006-0f2fc743-e8ad-46d3-ab88-f9162443db9b.jpg)

In the Japanese version, a key to switch between English and Japanese is assigned to the position of the ECS key in the English version.

If I press the English/Japanese switch key at the same time as the Fn key, I want it to work as an ESC key, but the English/Japanese switch key doesn't change.

When you stop the operation of OpenRazer, pressing the Fn key and the Japanese/English switching key will work as the ESC key.

Other keys work fine when pressed simultaneously with the Fn key.
Pressing the Fn key + 1 key works as F1.

Thank you

**Comment by z3ntu** [comment]
Can you run `sudo libinput debug-events --show-keycodes` (you might need to install some extra packages so this command works) and press this button (when it does work for switching) and send the output here?

**Comment by alimagik1** [comment]
When running openrazer-daemon.service results in not recognizing the Fn key

```
sudo libinput debug-events --show-keycodes
-event2   DEVICE_ADDED            Power Button                      seat0 default group1  cap:k
-event8   DEVICE_ADDED            Video Bus                         seat0 default group2  cap:k
-event1   DEVICE_ADDED            Lid Switch                        seat0 default group3  cap:S
-event0   DEVICE_ADDED            Sleep Button                      seat0 default group4  cap:k
-event6   DEVICE_ADDED            Integrated Camera: Integrated C   seat0 default group5  cap:k
-event7   DEVICE_ADDED            Integrated Camera: Integrated I   seat0 default group5  cap:k
-event27  DEVICE_ADDED            Razer Razer BlackWidow V3 Mini    seat0 default group6  cap:k
-event28  DEVICE_ADDED            Razer Razer BlackWidow V3 Mini    seat0 default group6  cap:kp scroll-nat
-event29  DEVICE_ADDED            Razer Razer BlackWidow V3 Mini    seat0 default group6  cap:p left scroll-nat scroll-button
-event30  DEVICE_ADDED            Razer Razer BlackWidow V3 Mini    seat0 default group6  cap:k
-event25  DEVICE_ADDED            ELAN0670:00 04F3:3150 Mouse       seat0 default group7  cap:p left scroll-nat scroll-button
-event26  DEVICE_ADDED            ELAN0670:00 04F3:3150 Touchpad    seat0 default group7  cap:pg  size 99x54mm tap(dl off) left scroll-nat scroll-2fg-edge click-buttonareas-clickfinger dwt-on dwtp-on
-event12  DEVICE_ADDED            HDA Intel PCH Headphone           seat0 default group8  cap:k
-event4   DEVICE_ADDED            Intel HID events                  seat0 default group9  cap:k
-event3   DEVICE_ADDED            AT Translated Set 2 keyboard      seat0 default group10 cap:k
-event10  DEVICE_ADDED            TPPS/2 JYT_Synaptics TrackPoint   seat0 default group11 cap:p left scroll-nat scroll-button
-event5   DEVICE_ADDED            ThinkPad Extra Buttons            seat0 default group12 cap:k
-event31  DEVICE_ADDED            DA V2 Pro Mouse                   seat0 default group13 cap:p left scroll-nat scroll-button
-event256  DEVICE_ADDED            DA V2 Pro Consumer Control        seat0 default group13 cap:kp scroll-nat
-event257  DEVICE_ADDED            DA V2 Pro System Control          seat0 default group13 cap:k
-event259  DEVICE_ADDED            DA V2 Pro Keyboard                seat0 default group13 cap:k
-event28  KEYBOARD_KEY            +0.000s	KEY_GRAVE (41) pressed
 event28  KEYBOARD_KEY            +0.093s	KEY_GRAVE (41) released
 event28  KEYBOARD_KEY            +3.659s	KEY_GRAVE (41) pressed
 event28  KEYBOARD_KEY            +3.785s	KEY_GRAVE (41) released

```

Fn key works if openrazer-daemon.service is stopped

```
sudo libinput debug-events --show-keycodes
-event2   DEVICE_ADDED            Power Button                      seat0 default group1  cap:k
-event8   DEVICE_ADDED            Video Bus                         seat0 default group2  cap:k
-event1   DEVICE_ADDED            Lid Switch                        seat0 default group3  cap:S
-event0   DEVICE_ADDED            Sleep Button                      seat0 default group4  cap:k
-event6   DEVICE_ADDED            Integrated Camera: Integrated C   seat0 default group5  cap:k
-event7   DEVICE_ADDED            Integrated Camera: Integrated I   seat0 default group5  cap:k
-event27  DEVICE_ADDED            Razer Razer BlackWidow V3 Mini    seat0 default group6  cap:k
-event28  DEVICE_ADDED            Razer Razer BlackWidow V3 Mini    seat0 default group6  cap:kp scroll-nat
-event29  DEVICE_ADDED            Razer Razer BlackWidow V3 Mini    seat0 default group6  cap:p left scroll-nat scroll-button
-event30  DEVICE_ADDED            Razer Razer BlackWidow V3 Mini    seat0 default group6  cap:k
-event25  DEVICE_ADDED            ELAN0670:00 04F3:3150 Mouse       seat0 default group7  cap:p left scroll-nat scroll-button
-event26  DEVICE_ADDED            ELAN0670:00 04F3:3150 Touchpad    seat0 default group7  cap:pg  size 99x54mm tap(dl off) left scroll-nat scroll-2fg-edge click-buttonareas-clickfinger dwt-on dwtp-on
-event12  DEVICE_ADDED            HDA Intel PCH Headphone           seat0 default group8  cap:k
-event4   DEVICE_ADDED            Intel HID events                  seat0 default group9  cap:k
-event3   DEVICE_ADDED            AT Translated Set 2 keyboard      seat0 default group10 cap:k
-event10  DEVICE_ADDED            TPPS/2 JYT_Synaptics TrackPoint   seat0 default group11 cap:p left scroll-nat scroll-button
-event5   DEVICE_ADDED            ThinkPad Extra Buttons            seat0 default group12 cap:k
-event31  DEVICE_ADDED            DA V2 Pro Mouse                   seat0 default group13 cap:p left scroll-nat scroll-button
-event256  DEVICE_ADDED            DA V2 Pro Consumer Control        seat0 default group13 cap:kp scroll-nat
-event257  DEVICE_ADDED            DA V2 Pro System Control          seat0 default group13 cap:k
-event259  DEVICE_ADDED            DA V2 Pro Keyboard                seat0 default group13 cap:k
-event27  KEYBOARD_KEY            +0.000s	KEY_ESC (1) pressed
^[ event27  KEYBOARD_KEY            +0.125s	KEY_ESC (1) released
 event27  KEYBOARD_KEY            +2.637s	KEY_GRAVE (41) pressed
 event27  KEYBOARD_KEY            +2.755s	KEY_GRAVE (41) released
 event27  KEYBOARD_KEY            +3.788s	KEY_ESC (1) pressed
^[ event27  KEYBOARD_KEY            +3.929s	KEY_ESC (1) released
 event27  KEYBOARD_KEY            +5.162s	KEY_GRAVE (41) pressed
 event27  KEYBOARD_KEY            +5.292s	KEY_GRAVE (41) released
```

Searching for other similar cases, I found the following resolved issue:
#1705 

The Device IDs of Huntsman Mini and Huntsman Mini (JP) seem to be different, so I checked that the Japanese version of BlackWidow V3 Mini Hyperspeed may have a different Device ID as well, but it seems to be the same as the English version's Device ID.

```
lsusb -d 1532: -v

Bus 003 Device 006: ID 1532:0258 Razer USA, Ltd Razer BlackWidow V3 Mini
Device Descriptor:
  bLength                18
  bDescriptorType         1
  bcdUSB               2.00
  bDeviceClass            0 
  bDeviceSubClass         0 
  bDeviceProtocol         0 
  bMaxPacketSize0        64
  idVendor           0x1532 Razer USA, Ltd
  idProduct          0x0258 
  bcdDevice            2.00
  iManufacturer           1 Razer
  iProduct                2 Razer BlackWidow V3 Mini
  iSerial                 0 
  bNumConfigurations      1
  Configuration Descriptor:
    bLength                 9
    bDescriptorType         2
    wTotalLength       0x0086
    bNumInterfaces          5
    bConfigurationValue     1
    iConfiguration          0 
    bmAttributes         0xa0
      (Bus Powered)
      Remote Wakeup
    MaxPower              500mA
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        0
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      1 Boot Interface Subclass
      bInterfaceProtocol      1 Keyboard
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength      61
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x81  EP 1 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0040  1x 64 bytes
        bInterval               1
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        1
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      0 
      bInterfaceProtocol      1 Keyboard
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength     177
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x82  EP 2 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0040  1x 64 bytes
        bInterval               1
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        2
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      0 
      bInterfaceProtocol      2 Mouse
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength      75
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x83  EP 3 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0040  1x 64 bytes
        bInterval               1
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        3
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      0 
      bInterfaceProtocol      0 
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength      22
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x84  EP 4 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0040  1x 64 bytes
        bInterval               1
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        4
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      0 
      bInterfaceProtocol      1 Keyboard
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength     348
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x85  EP 5 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0040  1x 64 bytes
        bInterval               1
Device Status:     0x0000
  (Bus Powered)

```

Is there anything else I can do?

**Comment by alimagik1** [comment]
When I updated the system with the yay command on November 6, 2022 Japan time, I confirmed that the Japanese version of BlackWidow V3 Mini HyperSpeed can switch between the Japanese-English switch key and the ESC key correctly.

kernel version that worked
linux kernel ver 6.07 and 5.15.77

Thank you very much for your help.

**Comment by bathwaterpizza** [comment]
Running openrazer v3.7 with polychromatic on Manjaro, Fn keys are not working and there is no option to remap the keys in multiple frontends I've tried.
