### ISSUE TITLE
How to open on Debian 10

### ISSUE THREAD

**Issue by klib654** [openrazer/openrazer#1469]
### Distribution

Nick, Debian 10
### Support

- [x] Have you tried rebooting? yes
- [x] Have you looked at the [Troubleshooting](https://github.com/openrazer/openrazer/wiki/Troubleshooting) page? yes

idk how to open it on debian 10, or is it an app, or is it commands? idk man

**Comment by klib654** [comment]
@ryanw

**Comment by lah7** [comment]
OpenRazer is just a driver and daemon. You should install one of the frontends to interact with it:

https://github.com/openrazer/openrazer#applications

Alternately, there is the Python API, D-Bus and sysfs interfaces to interact with it directly.
