### ISSUE TITLE
OpenRazer randomly crashes

### ISSUE THREAD

**Issue by Mythbusters123** [openrazer/openrazer#1472]
### Distribution
Arch Linux

### Support

- [ ] Have you tried rebooting? Yes
- [ ] Have you looked at the [Troubleshooting](https://github.com/openrazer/openrazer/wiki/Troubleshooting) page? yes

Ever since 3.0.0 came out, I am not able to change any keys on my blackwidow elite. I have looked at the logs and all it says is that its resuming the keyboard. This happens randomly for me, and sometimes when I open discord it just randomly stops. I have tried using polychromatic and razerCommander. I have also trioed switching kernles from Zen to Lts, to no avail. Later today I will try razerGenie/Snake, and possibly reinstall the drivers again. Yes, my user is in the plugdev group and yes my keyboard is connected :joy:

**Comment by z3ntu** [comment]
> I am not able to change any keys on my blackwidow elite

You mean you aren't able to change the lighting colors of your keys?

**Comment by Mythbusters123** [comment]
Yea, sorry for poor wording

**Comment by z3ntu** [comment]
The device is shown in the the various frontends, yes?
Can you try downgrading to v2.9.0 to see if that changes anything?

**Comment by Mythbusters123** [comment]
How would I go about downgrading? I am running arch Linux if that is helpful.

**Comment by z3ntu** [comment]
If you still have the old .pkg.tar.zst lying around (e.g. in /var/cache/pacman/pkg/), you can just do `sudo pacman -U $thatfile` . Alternatively you can check out the commit in the AUR repo that points to v2.9.0 and run makepkg there.

**Comment by Mythbusters123** [comment]
I just rolled back to 2.9, and nothing fixed it.

**Comment by Mythbusters123** [comment]
Reinstalled arch completely. Still didnt help.

**Comment by Mythbusters123** [comment]
Alright, so digging into they tty said that the report length was invalid and gave the number -100

**Comment by z3ntu** [comment]
Not sure what's happening there...

**Comment by Mythbusters123** [comment]
for a better understanding, i took this with my phone while i was shutting down. However I did observe it happening in TTY too. https://imgur.com/a/FNz2Key

**Comment by Mythbusters123** [comment]
Bump

**Comment by z3ntu** [comment]
Sounds like an issue either with your computer or your keyboard. Can you test the keyboard on a different PC whether it works correctly there?

**Comment by Mythbusters123** [comment]
I dual boot windows and linux, and razer synapse works perfectly fine on windows, also I think 3.0.1 fixed this but let me do more testing on this
