### ISSUE TITLE
Ubuntu 20.04 PPA key expired

### ISSUE THREAD

**Issue by sebastijan2112** [openrazer/openrazer#1477]
### Distribution

Ubuntu 20.04 LTS
### Support

- [ x] Have you tried rebooting?
- [ x] Have you looked at the [Troubleshooting](https://github.com/openrazer/openrazer/wiki/Troubleshooting) page?

Hi,

It appears the key has expired for the Ubuntu 20.04 repo:

# curl -s http://download.opensuse.org/repositories/hardware:/razer/xUbuntu_20.04/Release.key  | gpg --with-fingerprint
gpg: WARNING: no command supplied.  Trying to guess what you mean ...
pub   rsa2048 2014-09-16 [SC] [expired: 2021-03-28]
uid           hardware OBS Project <hardware@build.opensuse.org>

**Comment by z3ntu** [comment]
Thanks, should be fixed now.

---

For reference for future me: `osc signkey --extend hardware:razer` (fails with an error but still does the job) and rebuild at least one package per version to publish the new key.
