### ISSUE TITLE
Support for Razer Kraken X headphones

### ISSUE THREAD

**Issue by Kostas-Mavrogalos** [openrazer/openrazer#1483]
### Distribution

Distributor:	Ubuntu, and more specifically, xUbuntu
Release:	20.04

Hey, I came here through a small quest with Razer. Is it possible to make Razer Kraken X headphones have support with this awesome app? I would love to have it and it's not yet supported

**Comment by z3ntu** [comment]
I think these headphones are covered by this comment https://github.com/openrazer/openrazer/issues/1396#issuecomment-753455216

**Comment by Kostas-Mavrogalos** [comment]
It would, but mine don't have a jack, but a USB. Also, OpenRazer says it knows that a Razer product is connected to the PC, but the daemon doesn't detect it, so idk :/

**Comment by z3ntu** [comment]
Ok, can you send the output of `lsusb | grep 1532` please?

**Comment by Kostas-Mavrogalos** [comment]
Bus 001 Device 006: ID 1532:0526 Razer USA, Ltd Razer Kraken X USB

**Comment by z3ntu** [comment]
The device is tracked in #1326
