### ISSUE TITLE
scriptable functions to disable / enable lighting

### ISSUE THREAD

**Issue by Deathtech-00** [openrazer/openrazer#1487]
### Distribution
Xubuntu 20.04

### Support

- [ ] Have you tried rebooting?
- [ ] Have you looked at the [Troubleshooting](https://github.com/openrazer/openrazer/wiki/Troubleshooting) page?

I can't seem to locate any documentation on passable commands that would allow us to script out on/off sequences. Is this already a function that exists and I am just not able to find the info?

**Comment by chabad360** [comment]
Have a look at the examples folder.

**Comment by Deathtech-00** [comment]
Ah, sorry about that. Thank you for the response, and the awesome software.

**Comment by z3ntu** [comment]
Looks solved. Closing.
