### ISSUE TITLE
Razer Mamba Elite, Side lighting not change able

### ISSUE THREAD

**Issue by Skullaxel** [openrazer/openrazer#1494]
### Distribution

Openrazor

### Support

- [yes ] Have you tried rebooting?
- [yes ] Have you looked at the [Troubleshooting](https://github.com/openrazer/openrazer/wiki/Troubleshooting) page?

In the software it self i can only change the logo and mouse wheel colors but not the sides. the code in the folder has the *main* code but it wont change anything, it will change it to lets say wave, but it wont update it to the mouse. so it stays the same

**Comment by lah7** [comment]
Sounds like a duplicate of https://github.com/openrazer/openrazer/issues/1489.

Are you using a frontend application? If so, which one/version? (e.g. Polychromatic, RazerGenie)

**Comment by gabrielmajosi** [comment]
Same thing happens with me. Polychromatic doesnt work, I will try RazerGenie in a moment.

**Comment by gabrielmajosi** [comment]
Update: RazerGenie works fine. I doubt this is a problem with openrazer, so consider making a issue in polychromatic repository

**Comment by z3ntu** [comment]
Closing with this reasoning.
