### ISSUE TITLE
Rare errors with sudo gpasswd -a $USER plugdev

### ISSUE THREAD

**Issue by AlexD2548** [openrazer/openrazer#1498]
sudo gpasswd -a ***** plugdev
Adding user ***** to group plugdev
(2021-04-19 18:24:00:639210): [sss_cache] [confdb_get_enabled_domain_list] (0x0040): Failed to get [domains] from [sssd], error [2] (No such file or directory)
(2021-04-19 18:24:00:639244): [sss_cache] [init_domains] (0x0020): Could not initialize domains
(2021-04-19 18:24:00:644725): [sss_cache] [confdb_get_enabled_domain_list] (0x0040): Failed to get [domains] from [sssd], error [2] (No such file or directory)
(2021-04-19 18:24:00:644764): [sss_cache] [init_domains] (0x0020): Could not initialize domains

I did search online for these issues but could not find anything. Any idea?

Another error when I run: $ sudo modprobe razerkbd
modprobe: FATAL: Module razerkbd not found in directory /lib/modules/5.9.16-1-MANJARO

**Comment by lah7** [comment]
Running `echo $?` immediately afterwards should output `0` if the `gpasswd` command was successful.

Not heard of `sss_cache`, but it sounds like your system is configured as part of a domain / LDAP setup:

* https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/6/html/deployment_guide/sssd-cache

----

> Another error when I run: $ sudo modprobe razerkbd
> modprobe: FATAL: Module razerkbd not found in directory /lib/modules/5.9.16-1-MANJARO

Make sure you have the Linux headers installed for Manjaro:

    sudo pacman -S linux-headers

Then try installing the driver again via DKMS:

    sudo dkms install openrazer-driver/3.0.1

(Or just reinstall the `openrazer-driver-dkms` package)
