### ISSUE TITLE
macOS support

### ISSUE THREAD

**Issue by LuxuryWasTaken** [openrazer/openrazer#1502]
I know a lot of people asked this, so before spamming no, just read.

I know the dev told current OpenRazer build won't support windows or macOS because of it's driver written for linux.

But there is a lot of forks for macOS using OpenRazer driver.

https://github.com/dylanparker/osx-razer-led
https://github.com/1kc/razer-macos
https://github.com/dylanparker/osx-razer-led

We really need a Razer tool that works in macOS. Because the 2 links I sent above is only supporting 1 device that devs are using.

**Comment by z3ntu** [comment]
The projects are open source. Feel free to make it work, but I 1. don't have a macOS computer and 2. am not interested in it personally.

If someone is maintaining all the macOS support including handling the issues, then I'm not opposed to having some support code present in the openrazer repo, but again, someone has to be responsible for that and maintain that.
