### ISSUE TITLE
Kubuntu/hirsute not compatible (no template found)

### ISSUE THREAD

**Issue by afrothundaaaa** [openrazer/openrazer#1505]
### Distribution

Kubuntu 21.04 (Hirsute)

### Support

- [x] Have you tried rebooting?
- [x] Have you looked at the [Troubleshooting](https://github.com/openrazer/openrazer/wiki/Troubleshooting) page?

I am unable to install OpenRazer on Kubuntu 21.04 following the Ubuntu install guide.  

```
$ sudo add-apt-repository ppa:openrazer/stable
Traceback (most recent call last):
  File "/usr/bin/add-apt-repository", line 363, in <module>
    addaptrepo = AddAptRepository()
  File "/usr/bin/add-apt-repository", line 41, in __init__
    self.distro.get_sources(self.sourceslist)
  File "/usr/lib/python3/dist-packages/aptsources/distro.py", line 91, in get_sources
    raise NoDistroTemplateException(
aptsources.distro.NoDistroTemplateException: Error: could not find a distribution template for Kubuntu/hirsute
```

Not sure what I can do to provide assistance/testing but please let me know.

**Comment by lah7** [comment]
If you recently upgraded Kubuntu, it might not have been fully completed. Make sure all your packages are up-to-date.

To fix, you'll need to edit the "distribution template" in `/etc/lsb-release` to read:
```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=21.04
DISTRIB_CODENAME=hirsute
DISTRIB_DESCRIPTION="Ubuntu 21.04"
```

Or try:

    sudo apt install --reinstall base-files

Then try running the `add-apt-repository` command again.
