### ISSUE TITLE
Support for Razer Thunderbolt 4 Dock Chroma

### ISSUE THREAD

**Issue by SylvainRamousse** [openrazer/openrazer#1506]
### Device Info

* Name: Thunderbolt 4 Dock Chroma
* Product Number: RC21-0169
* Model Number: RC21-01690100

### Device Information
From a macbook pro (beware, we're talking about a thunderbolt device): 
```
RAZER THUNDERBOLT 4 DOCK CHROMA:

                  Product ID: 0x0f21
                  Vendor ID: 0x1532
                  Version: 2.00
                  Speed: Up to 12 Mb/s
                  Manufacturer: RAZER
                  Location ID: 0x00146000 / 14
                  Current Available (mA): 500
                  Current Required (mA): 500
                  Extra Operating Current (mA): 0

Thunderbolt 4 Dock:
                  Product ID: 0x122e
                  Vendor ID: 0x1532
                  Version: 17.46
                  Serial Number: ***
                  Speed: Up to 12 Mb/s
                  Manufacturer: Razer
                  Location ID: 0x00148000 / 7
                  Current Available (mA): 500
                  Current Required (mA): 0
                  Extra Operating Current (mA): 0
```

**Comment by j-maynard** [comment]
I can shed more light on this on the Linux side.  The Thunderbolt docks entry under lspci is:

```
07:00.0 PCI bridge: Intel Corporation Thunderbolt 4 Bridge [Goshen Ridge 2020] (rev 02)
08:00.0 PCI bridge: Intel Corporation Thunderbolt 4 Bridge [Goshen Ridge 2020] (rev 02)
08:01.0 PCI bridge: Intel Corporation Thunderbolt 4 Bridge [Goshen Ridge 2020] (rev 02)
08:02.0 PCI bridge: Intel Corporation Thunderbolt 4 Bridge [Goshen Ridge 2020] (rev 02)
08:03.0 PCI bridge: Intel Corporation Thunderbolt 4 Bridge [Goshen Ridge 2020] (rev 02)
08:04.0 PCI bridge: Intel Corporation Thunderbolt 4 Bridge [Goshen Ridge 2020] (rev 02)
09:00.0 USB controller: Intel Corporation Thunderbolt 4 USB Controller [Goshen Ridge 2020] (rev 02)
```

The lsusb is as follows:
```
Bus 005 Device 013: ID 1532:122e Razer USA, Ltd Thunderbolt 4 Dock
Bus 005 Device 010: ID 1532:0f21 Razer USA, Ltd RAZER THUNDERBOLT 4 DOCK CHROMA
```

Mah thinking is the Chroma control will sit on the USB so its just like any other Razer USB device.  This still needs a pcap which I could do with some simple instructions on how to get for you.

**Comment by z3ntu** [comment]
@j-maynard Getting pcaps is documented at https://github.com/openrazer/openrazer/wiki/Reverse-Engineering-USB-Protocol

In general I don't imagine there to be much useful information in the pcaps, as is with all newish devices - it's probably going to be a case of trial-and-error on the person who implements support. But given that the device also exposes a USB interface I don't expect there to be major differences to the other devices that are supported.

**Comment by j-maynard** [comment]
Synapse Pictures:
![image](https://user-images.githubusercontent.com/29251905/124638411-d4120e80-de82-11eb-918a-c7e820495aa4.png)
![image](https://user-images.githubusercontent.com/29251905/124638452-e12efd80-de82-11eb-9bb0-1758319d9f55.png)

**Comment by j-maynard** [comment]
Sorry I skipped the most important screen shot (The one which shows how many LEDs there are to control in Chroma Studio).  

Now I've done the PR for the Blade Advanced (https://github.com/openrazer/openrazer/pull/1561) I think I might try looking at this to see if I can make it work.  If anyone with experience of the code base has ideas I am happy to hear them.

![image](https://user-images.githubusercontent.com/29251905/126046553-70287434-2884-46a2-b4ce-425078ddf8c3.png)
