### ISSUE TITLE
Support for Macos

### ISSUE THREAD

**Issue by pascal-adk** [openrazer/openrazer#1510]
### Device Info

* Name: MacBook Pro 2020
* Product Number: <See under device>
* Model Number: <See under device>

### Packet Captures

Default Razer Synapse don't Work

### Synapse Screenshots
Default Razer Synapse don't Work

**Comment by z3ntu** [comment]
Please use the issue search before filing new issues: https://github.com/openrazer/openrazer/issues?q=macOS
