### ISSUE TITLE
file is not owned by plugdev

### ISSUE THREAD

**Issue by gprime31** [openrazer/openrazer#1513]
dist: Arch 64

2021-05-14 08:44:10 | razer                          | CRITICAL | Could not access /sys/devices/pci0000:00/0000:00:14.0/usb1/1-7/1-7:1.2/0003:1532:011A.0007/device_type, file is not owned by plugdev
2021-05-14 08:44:10 | razer                          | INFO     | Serving DBus

from :  
~/.local/share/openrazer/logs/razer.log

**Comment by gprime31** [comment]
![2021-05-14_09-05](https://user-images.githubusercontent.com/44535257/118274845-a4064a80-b493-11eb-8012-7e90a000a20d.png)

**Comment by gprime31** [comment]
if i change the owner to root:plugdev it fixes the permission problem
but then i get:
permissionError: [Errno 13] Permission denied: '/dev/input/by-id/usb-Razer_Razer_BlackWidow_Ultimate-if01-event-kbd'
when running openrazer-daemon -Fv

**Comment by gprime31** [comment]
ok then do:
sudo chown $user:plugdev /dev/input/by-id/usb-Razer_Razer_BlackWidow_Ultimate-event-kbd
and
sudo chown $user:plugdev /dev/input/by-id/usb-Razer_Razer_BlackWidow_Ultimate-if01-event-kbd
and everything passes checks.
![2021-05-14_09-25](https://user-images.githubusercontent.com/44535257/118277130-7242b300-b496-11eb-98f4-7046076bb6aa.png)
![2021-05-14_09-27](https://user-images.githubusercontent.com/44535257/118277314-ac13b980-b496-11eb-9313-7ca080e0277a.png)

**Comment by gprime31** [comment]
and works
But, i have to do this every boot.
any suggestions??

**Comment by lah7** [comment]
It sounds like [udev rules](https://wiki.archlinux.org/title/Udev) are not working on your Arch install. I'm not sure exactly how to fix this, but installing `openrazer-driver-dkms` from AUR should have installed the file `/usr/lib/udev/rules.d/99-razer.rules` required to automatically set the permissions.

**Comment by gprime31** [comment]
yes, it missing.
find: ‘99-razer.rules’: No such file or directory
where can i find it? there is only one choice in the AUR

**Comment by gprime31** [comment]
seems like openrazer/install_files/udev/99-razer.rules is missing from the AUR . i found in on an older build:
https://github.com/openrazer/openrazer/blob/master/install_files/udev/99-razer.rules
will try this.

**Comment by gprime31** [comment]
that fixed it ^^^^ works on boot now, thanks.
I just copied the rules from the old build. and made the file.

**Comment by lah7** [comment]
The file is provided in `openrazer-driver-dkms` (AUR) [corrected above, `openrazer-meta` was wrong, my bad]. 

Glad you found a solution! For some reason, your system had misplaced the files. Hopefully this won't happen again when you next update the packages.

**Comment by gprime31** [comment]
![2021-05-16_07-46](https://user-images.githubusercontent.com/44535257/118395920-fb82f280-b61a-11eb-989a-8a86c561026e.png)

**Comment by gprime31** [comment]
So it's the wrong package listed on the website? ^^^^

**Comment by lah7** [comment]
`openrazer-meta` is correct, it's [a meta package](https://wiki.archlinux.org/title/Meta_package_and_package_group) that depends on `openrazer-daemon`, `openrazer-driver-dkms` and `python-openrazer`. Installing that depends on these 3 packages so you can easily install using an AUR helper like `yay`:

    yay -S openrazer-meta

My clarification above was that the udev rule file you were missing is provided in `openrazer-driver-dkms`, so that would have been the package to reinstall, as reinstalling `openrazer-meta` would not have worked.

**Comment by gprime31** [comment]
Ok, I see, thanks.

**Comment by xamindar** [comment]
This is still an issue with the latest arch packages. I have tried both the standard package and the aur ones and none of them install the udev rule for permissions.

**Comment by z3ntu** [comment]
@xamindar See https://archlinux.org/packages/extra/any/openrazer-driver-dkms/, click "View the file list for openrazer-driver-dkms" and you will see `usr/lib/udev/rules.d/99-razer.rules`

And please don't necro-bump some issues, create a new one if you need support.
