### ISSUE TITLE
Manjaro not working with openrazer

### ISSUE THREAD

**Issue by AbleTheAbove** [openrazer/openrazer#1531]
### Distribution

Manjaro 

### Support

- [X] Have you tried rebooting?
- [X] Have you looked at the [Troubleshooting](https://github.com/openrazer/openrazer/wiki/Troubleshooting) page?

I tried getting open razer and polychromatic to work and I couldn't

**Comment by lah7** [comment]
Need more details... is there an error? What happens? Common missed installation steps are:

* Have you added your user to the `plugdev` group and restarted? (Run `openrazer-daemon -Fv`)

* Have you installed the correct kernel header package? Usually that's `linux-headers`, but if you use the LTS kernel then `linux-lts-headers`. If they were missing, then you'll need to rebuild the driver with `sudo dkms install openrazer-driver/3.0.1`

**Comment by AbleTheAbove** [comment]
I've added my user to the group 

I've also installed the headers 
There is a error saying device not valid

**Comment by lah7** [comment]
Please could you paste the log / output or a screenshot?

Also, what Razer hardware do you have?

    lsusb | grep 1532

**Comment by AbleTheAbove** [comment]
![image](https://user-images.githubusercontent.com/75036841/122626580-02b17c00-d071-11eb-90c6-ae212ebef538.png)

![image](https://user-images.githubusercontent.com/75036841/122626610-22e13b00-d071-11eb-9744-6e91950b0a60.png)
Sorry about the delay

**Comment by lah7** [comment]
That version of Polychromatic doesn't look like it was compiled correctly - the custom style is incorrect - not sure how that happened. (It has an option to enable native Qt themes in **Edit → Preferences** if desired)

Try clicking **Troubleshoot**, this should identify the problem. I'm guessing DKMS or plugdev permission error, since your device is supported.

**Comment by AbleTheAbove** [comment]
![image](https://user-images.githubusercontent.com/75036841/122693287-d6c40100-d1fe-11eb-965c-c787750e2dce.png)

**Comment by z3ntu** [comment]
Can you please follow the text and run the first command?

**Comment by AbleTheAbove** [comment]
![image](https://user-images.githubusercontent.com/75036841/123212503-806af280-d48a-11eb-9bd9-a1e0f33bdbc4.png)

**Comment by lah7** [comment]
The kernel headers are missing - install the package `linux510-headers`, run the `dkms install` command again and then reboot.

Your system might be out of date, the latest 5.10 version is `5.10.42` but the output above suggests you're running `5.10.36`. The driver won't install if the kernel and headers have mismatching versions.

So, to get everything back on track:

    sudo pacman -Syu linux510-headers

**Comment by AbleTheAbove** [comment]
Thanks that fixed the issue
