### ISSUE TITLE
Device Settings Reset When Switching Between Windows and Linux on a Dual Boot System

### ISSUE THREAD

**Issue by K4LCIFER** [openrazer/openrazer#1532]
### Distribution

Arch Linux

### Support

- [X] Have you tried rebooting?
- [] Have you looked at the [Troubleshooting](https://github.com/openrazer/openrazer/wiki/Troubleshooting) page?

I use Polychromatic to specify effects for the device (I have also submitted a bug report to Polychromatic's github page as I don't know if it is better suited to be there or here), and when I manually set an effect on linux and reboot back into linux, the effect persists; however, if I boot into windows which is running synapse, and then reboot back into linux, the settings for the razer device are reset. Its not until I go back into polychromatic and manually disable and reenable the settings do they begin working again. So somehow windows is messing with the settings for the device.

**Comment by lah7** [comment]
OpenRazer 3.0.0 introduced a persistence feature, which should be re-applying your settings when booting into Linux.

Check this option is enabled in `~/.config/openrazer/razer.conf`:

    restore_persistence = True

If necessary, stop the daemon and delete `~/.config/openrazer/persistence.conf` to start fresh.
