### ISSUE TITLE
DPI clutch not working 

### ISSUE THREAD

**Issue by aiintdeadyet** [openrazer/openrazer#1567]
### Linux mint 20.1

 james and 3.0.1~ubuntu20.04.1

### Support

- [x] Have you tried rebooting?
- [x] Have you looked at the [Troubleshooting](https://github.com/openrazer/openrazer/wiki/Troubleshooting) page?

My DPI clutch/sniper button is not working on my basilisk V2. I also have not been able to switch DPI using the two buttons below the scroll wheel. I don't know if this is a bug or if the feature is just not supported but either way it is something that I want to work so I am looking for a fix. Any Ideas?

**Comment by z3ntu** [comment]
I don't think this is supported yet.
