### ISSUE TITLE
Cannot import saved keyboard themes.

### ISSUE THREAD

**Issue by nuncio-bitis** [openrazer/openrazer#1578]
Cannot import existing *.razorchroma themes saved with OpenRazer. In fact, OpenRazor has no way of opening or importing anything that it can save to disk.

**Comment by z3ntu** [comment]
See https://github.com/openrazer/openrazer/issues/362#issuecomment-323611191 . Does that answer your question?

**Comment by nuncio-bitis** [comment]
Nope.

**Comment by z3ntu** [comment]
Can you please expand on your question then?
