### ISSUE TITLE
Change colors of the wave effect?

### ISSUE THREAD

**Issue by nullptr448** [openrazer/openrazer#1582]
### Distribution
Arch Linux

Manjaro , Linux 5.10.56-1

### Question

I'd like to change the colors of the effect, is there a way?
My keyboard is the Razer Ornata Chroma

**Comment by z3ntu** [comment]
The wave effect that we're using is provided by the firmware, so we cannot change anything there other than the direction of the effect.
If you really want to change the colors, then you'll have to write your own custom effect, similar to this starlight effect https://github.com/openrazer/openrazer/blob/master/examples/custom_starlight.py

**Comment by nullptr448** [comment]
> The wave effect that we're using is provided by the firmware, so we cannot change anything there other than the direction of the effect.
> If you really want to change the colors, then you'll have to write your own custom effect, similar to this starlight effect https://github.com/openrazer/openrazer/blob/master/examples/custom_starlight.py

Okay, Thanks.
