### ISSUE TITLE
Import Error und Debian 8.7

### ISSUE THREAD

**Issue by artificial-immersion** [openrazer/openrazer#159]
File "/usr/bin/polychromatic-controller", line 29, in <module>
    import razer.daemon_dbus
ImportError: No module named 'razer'

I installed the driver from the repository via manual compiliation and polychromatic afterwards.
I also tried to manually install the python lib but couldn't verify if it worked.

**Comment by z3ntu** [comment]
You should use the debs provided. And what commands did you use to install?

**Comment by z3ntu** [comment]
@artificial-immersion Please answer, otherwise this issue will be closed due to inactivity.

**Comment by z3ntu** [comment]
@terrycain Please close
