### ISSUE TITLE
opensuse tumbleweed result after install

### ISSUE THREAD

**Issue by marabubrest** [openrazer/openrazer#1590]
× openrazer-daemon.service - Daemon to manage razer devices in userspace
     Loaded: loaded (/usr/lib/systemd/user/openrazer-daemon.service; disabled; vendor preset: disabled)
     Active: failed (Result: exit-code) since Tue 2021-08-24 22:28:40 CEST; 24s ago
       Docs: man:openrazer-daemon(8)
    Process: 6142 ExecStart=/usr/bin/openrazer-daemon -F (code=exited, status=1/FAILURE)
   Main PID: 6142 (code=exited, status=1/FAILURE)
        CPU: 58ms

**Comment by z3ntu** [comment]
Please try running `openrazer-daemon -Fv` manually from the terminal and post the output here.

**Comment by marabubrest** [comment]
```
:~> openrazer-daemon -Fv
Traceback (most recent call last):
  File "/usr/bin/openrazer-daemon", line 11, in <module>
    from openrazer_daemon.daemon import RazerDaemon, __version__
ModuleNotFoundError: No module named 'openrazer_daemon'
:~> zypper se openrazer-daemon
Repository 'openSUSE:Tumbleweed' is out-of-date. You can run 'zypper refresh' as root to update it.
Repository 'home:buschmann23' is out-of-date. You can run 'zypper refresh' as root to update it.
Repository 'packman' is out-of-date. You can run 'zypper refresh' as root to update it.
Repository 'snappy' is out-of-date. You can run 'zypper refresh' as root to update it.
Loading repository data...
Reading installed packages...

S | Name             | Summary                   | Type
--+------------------+---------------------------+--------
i | openrazer-daemon | OpenRazer Service package | package_
```
it said not found but i had installed it ( so at least it is there somewhere )

**Comment by marabubrest** [comment]
i deserve gulag , i made one enormous mistake : i added the leaf repo instead of tumbleweed .
then i failed to realise that because i use a rolling distro , i had to build the kernel module .

everything is working fine
