### ISSUE TITLE
Razer blade 15 late 2019 linux support please

### ISSUE THREAD

**Issue by napsterred** [openrazer/openrazer#1632]
hey my razer id is 24B for myb razer blade 15 advanceced late 2019, can i please get any possible driver support for linux for it , please, thanks

**Comment by z3ntu** [comment]
Duplicate of #1041

**Comment by napsterred** [comment]
Hey i couldn't figure out whether to reverse engineer the usb or edit the device id in open razer . Could anyone please post instructions that work for the RB15 ADVANCED late 2019 optical switch model. I tried all these steps didn't know which to focus on to successfully make the keyboard recognizable. Thanks for support for all the models guys, If ya could help me with this one it would be a charm , :24B , thanks guys.
