### ISSUE TITLE
Support for RazerBlade15 Advanced late 2019 optical switches

### ISSUE THREAD

**Issue by napsterred** [openrazer/openrazer#1636]
### Device Info

* Name: <RazerBlade15>
* Product Number: RZ09-03137E02
* Model Number: Advanced optical switches late 2019
### Device Information
```
Please post the output of
    lsusb -d 1532: -v
```
Bus 001 Device 005: ID 1532:024b Razer USA, Ltd Gaming Laptop [Blade 15 Advanced (Late 2019)]
Couldn't open device, some information will be missing
Device Descriptor:
  bLength                18
  bDescriptorType         1
  bcdUSB               2.00
  bDeviceClass            0 
  bDeviceSubClass         0 
  bDeviceProtocol         0 
  bMaxPacketSize0        64
  idVendor           0x1532 Razer USA, Ltd
  idProduct          0x024b Gaming Laptop [Blade 15 Advanced (Late 2019)]
  bcdDevice            2.00
  iManufacturer           1 Razer
  iProduct                2 Razer Blade
  iSerial                 0 
  bNumConfigurations      1
  Configuration Descriptor:
    bLength                 9
    bDescriptorType         2
    wTotalLength       0x0054
    bNumInterfaces          3
    bConfigurationValue     1
    iConfiguration          0 
    bmAttributes         0xa0
      (Bus Powered)
      Remote Wakeup
    MaxPower              500mA
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        0
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      1 Boot Interface Subclass
      bInterfaceProtocol      1 Keyboard
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength      61
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x81  EP 1 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0008  1x 8 bytes
        bInterval               1
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        1
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      0 
      bInterfaceProtocol      1 Keyboard
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength     159
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x82  EP 2 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0010  1x 16 bytes
        bInterval               1
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        2
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      0 
      bInterfaceProtocol      2 Mouse
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength      94
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x83  EP 3 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0008  1x 8 bytes
        bInterval 

```
Please post the output of
    ls -lah /dev/input/by-id/
```
ls -lah /dev/input/by-id/
total 0
drwxr-xr-x 2 root root 220 Oct  9 17:48 .
drwxr-xr-x 4 root root 780 Oct  9 17:48 ..
lrwxrwxrwx 1 root root   9 Oct  9 17:48 usb-Azurewave_Integrated_Camera_200901010001-event-if00 -> ../event5
lrwxrwxrwx 1 root root  10 Oct  9 17:48 usb-Azurewave_Integrated_Camera_200901010001-event-if02 -> ../event11
lrwxrwxrwx 1 root root   9 Oct  9 17:48 usb-Logitech_USB_Receiver-if02-event-mouse -> ../event9
lrwxrwxrwx 1 root root   9 Oct  9 17:48 usb-Logitech_USB_Receiver-if02-mouse -> ../mouse2
lrwxrwxrwx 1 root root  10 Oct  9 17:48 usb-Razer_Razer_Blade-event-if01 -> ../event16
lrwxrwxrwx 1 root root  10 Oct  9 17:48 usb-Razer_Razer_Blade-event-kbd -> ../event13
lrwxrwxrwx 1 root root  10 Oct  9 17:48 usb-Razer_Razer_Blade-if01-event-kbd -> ../event14
lrwxrwxrwx 1 root root  10 Oct  9 17:48 usb-Razer_Razer_Blade-if02-event-mouse -> ../event25
lrwxrwxrwx 1 root root   9 Oct  9 17:48 usb-Razer_Razer_Blade-if02-mouse -> ../mouse3

### Packet Captures

<Please see here as we probably need packet captures>
<https://github.com/openrazer/openrazer/wiki/Reverse-Engineering-USB-Protocol>

us 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 005: ID 1532:024b Razer USA, Ltd Gaming Laptop [Blade 15 Advanced (Late 2019)]
Bus 001 Device 004: ID 13d3:56d5 IMC Networks Integrated Camera
Bus 001 Device 003: ID 8087:0029 Intel Corp. AX200 Bluetooth
Bus 001 Device 002: ID 046d:c53f Logitech, Inc. USB Receiver
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 004 Dev

### Synapse Screenshots

synapse shows no device recognized

<Screenshots of all available options as seen on Razer Synapse>

**Comment by napsterred** [comment]
i am willing to pay a bill or some money to any driver coder that can make the effects work for this model on my computer. Please, i can hire as an individual contract or even update the entire app , but i am willing to pay to please make it work.

**Comment by z3ntu** [comment]
Duplicate of #1041
