### ISSUE TITLE
Fedora 35 Support

### ISSUE THREAD

**Issue by dbarbi1** [openrazer/openrazer#1641]
Trying to install on a fresh Fedora 35 beta using the instructions [here](https://software.opensuse.org/download.html?project=hardware%3Arazer&package=openrazer-meta) with the Fedora 34 repo and it results in:
`Error: 
 Problem: package openrazer-meta-3.1.0-1.1.noarch requires python3-openrazer, but none of the providers can be installed
  - conflicting requests
  - nothing provides python(abi) = 3.9 needed by python3-openrazer-3.1.0-1.1.noarch
(try to add '--skip-broken' to skip uninstallable packages)
`
Looks like Fedora 35 ships with python 3.10. I installed the Fedora python3.9 package, but that didn't help.

**Comment by z3ntu** [comment]
Hi, Fedora 35 isn't yet available on our package builder (openSUSE build service). I think the easiest solution is building the package from source for now, see https://github.com/openrazer/openrazer/wiki/Building-a-package#fedora

You might also be able to get away with using the Fedora Rawhide repository for now, but you should definitely remember to switch to the Fedora 35 repository once it's available.

**Comment by dbarbi1** [comment]
Thanks @z3ntu. Using the Rawhide repo worked, thanks! I was unaware that it existed. I'll keep checking back to see when the official Fedora 35 repo is up and change over to it once available.

Thanks for all the hard work.

**Comment by tscherf** [comment]
Opening this up again because Fedora 35 has been GA'ed yesterday. Can you guys please add a new repo for ['Fedora 35'](https://download.opensuse.org/repositories/hardware:/razer/).

**Comment by koyuawsmbrtn** [comment]
Building manually helped, thanks!

**Comment by lah7** [comment]
Looks like we had duplicate issues: https://github.com/openrazer/openrazer/issues/1656#issuecomment-960650350. Fedora 35's repository is now enabled, which will keep the package up-to-date.
