### ISSUE TITLE
Support for Razer Kraken X USB

### ISSUE THREAD

**Issue by farouqBenarous** [openrazer/openrazer#1648]
### Distribution

Razer Kraken X USB

### Support

- [yes ] Have you tried rebooting?
- [ yes] Have you looked at the [Troubleshooting](https://github.com/openrazer/openrazer/wiki/Troubleshooting) page?

The Razer Kraken X USB is not supported yet by openrazer

**Comment by z3ntu** [comment]
Please provide the output of `lsusb | grep 1532`

**Comment by farouqBenarous** [comment]
here we go 

```

Bus 002 Device 014: ID 1532:0526 Razer USA, Ltd 
Bus 002 Device 013: ID 1532:0083 Razer USA, Ltd 
Bus 002 Device 011: ID 1532:025e Razer USA, Ltd USB2.0 Hub
```

**Comment by farouqBenarous** [comment]
![Screenshot from 2021-10-23 17-10-39](https://user-images.githubusercontent.com/28826938/138563697-4696c0bb-f242-45b0-8efa-59d5223d6057.png)


here's what i see when in openrazer

**Comment by z3ntu** [comment]
Duplicate of #1490 then
