### ISSUE TITLE
Device Support: Razer Core

### ISSUE THREAD

**Issue by CalcProgrammer1** [openrazer/openrazer#169]
If you have a Razer Core, it is now possible to use it on your Blade/Blade Stealth in Linux via a BIOS
mod described here to disable the unsupported Thunderbolt security:

https://www.reddit.com/r/linux_gaming/comments/5q2q80/razer_core_working_on_ubuntu_1610_razer_blade/

I modded my early 2016 RBS BIOS and got the Core working.  It presents a USB device for the lighting controller.  I will try to capture some packets this weekend and will try to work on a driver based on the Firefly/Chroma Mug code.  I expect it to be similar to the Firefly with 9 LEDs (inside LED strip is all one zone, then 8 individually controlled ones on the front).  It definitely supports custom effects through the official SDK.  I am not aware of any other funtionality provided by the Core's USB device, as the USB hub is just a hub, the Ethernet port is a separate USB 3.0 ASIX gigabit controller, and the GPU is presented on the PCIe bus.

**Comment by terricain** [comment]
Awesome dude. :smile: Be sure to drop some pcaps here ;-) would be the first core i've seen

**Comment by CalcProgrammer1** [comment]
Added the Core's USB ID to the firefly driver and all the basic effects work, but custom effect fails.  Going to capture some packets.

Just a suggestion - It would be nice if you consolidated the various "light only" devices into one driver, maybe call it razerchroma or something, to contain Firefly, Core, Mug, and any new devices that don't provide anything other than lighting (the mug has a switch I guess, but that could just be one device-specific case).  It seems like it would make adding new devices easier than copy-pasting the entire Firefly driver and renaming razerfirefly, updating the Makefile, etc.

**Comment by CalcProgrammer1** [comment]
<img width="515" alt="razercorecustomred" src="https://cloud.githubusercontent.com/assets/1051772/22355797/920006d0-e3f2-11e6-89a0-9ca04f8239c5.PNG">
<img width="513" alt="razercorecustomwhite" src="https://cloud.githubusercontent.com/assets/1051772/22355798/921a1d04-e3f2-11e6-986d-f999694b282e.PNG">

First capture I sent all white (FF FF FF) to the Core, second capture I sent all red (FF 00 00) except for the side LED zone which was all white (FF FF FF).

So yeah, it looks like 9 LEDs.  I'll have to make sure the driver is sending the right values for the other parts of the protocol though.

**Comment by CalcProgrammer1** [comment]
Ok, so it requires the razer_chroma_standard_matrix_set_custom_frame function rather than the razer_chroma_misc_one_row_set_custom_frame one, and does take a row ID in addition to a column start and stop ID.  I can drive it with the standard matrix function.  I'll go ahead and write a new module for it.

**Comment by z3ntu** [comment]
![](http://developer.razerzone.com/wp-content/uploads/core-template-grid-1.png)

> **Razer Core**
> * 1 zone for the internal lighting
> * 8 zones for the underglow

**Comment by terricain** [comment]
> Ok, so it requires the razer_chroma_standard_matrix_set_custom_frame function rather than the razer_chroma_misc_one_row_set_custom_frame one, and does take a row ID in addition to a column start and stop ID. I can drive it with the standard matrix function. I'll go ahead and write a new module for it.

Nice.



> Just a suggestion - It would be nice if you consolidated the various "light only" devices into one driver, maybe call it razerchroma or something, to contain Firefly, Core, Mug, and any new devices that don't provide anything other than lighting (the mug has a switch I guess, but that could just be one device-specific case). It seems like it would make adding new devices easier than copy-pasting the entire Firefly driver and renaming razerfirefly, updating the Makefile, etc.

And yeah it would be great but in the end it'll be far more hassle to move to that, and then comes the fact that I have maybe 5/30odd supported devices and would rather not break everything. I get enough issues raised as it is :wink:
