### ISSUE TITLE
Version 1.1.8

### ISSUE THREAD

**Issue by jpfoote** [openrazer/openrazer#171]
As of Version 1.1.8 the razor-drivers are working flawlessly on Ubuntu 16.04 with a BlackWidow Chroma.

Thank you!

polychromatic 0.3.6.1
Configuration 4

Daemon Version         1.1.8
Razor Python Library  1.1.8

Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.1 LTS
Release:	16.04

**Comment by terricain** [comment]
Np
