### ISSUE TITLE
Kraken Chroma 7.1 v2 Custom Effect

### ISSUE THREAD

**Issue by CalcProgrammer1** [openrazer/openrazer#172]
One of the big differences between v1 and v2 is that v2 supports custom effects in the official SDK.  If you send two static effects in a row, the firmware fades between the current color and the new color.  Applying a custom effect changes the color instantly, which is better when you're driving the effect from an application such as my visualizer.  I will try and capture some packets while sending custom effects using my visualizer in Windows and see what needs changed to support custom effects on the v2.  The ManOWar may also support custom effects, see https://github.com/CalcProgrammer1/KeyboardVisualizer/issues/62.  The v1 does not according to Razer.

**Comment by CalcProgrammer1** [comment]
Ok, it seems to be alternating between these two commands rapidly when I run keyboard visualizer commanding white (and using custom effects).

![krakenv2white](https://cloud.githubusercontent.com/assets/1051772/22394782/331d6dda-e4ef-11e6-9687-abd0c02a617f.PNG)
![krakenv2other](https://cloud.githubusercontent.com/assets/1051772/22394787/58a1a81e-e4ef-11e6-84a5-784d989395d1.PNG)

**Comment by CalcProgrammer1** [comment]
I got it working.  It looks like you already had the custom address discovered in your header file, but no implementation to write to it.  I went ahead and added the ability to send RGB+Intensity because I screwed up and set intensity to zero and needed a way to undo that.  I will submit a PR soon, going to test with the v1 and see if it is possible to use custom effects on it, but it probably isn't.

EDIT:  Holy WTF RAZER YOU FREAKING LIARS!!!

The Kraken 7.1 Chroma V1 does support custom effects.  It works just freaking fine.  If I send custom effects it sets the color instantly with no fade.  WHY IS THIS NOT A THING IN THE OFFICIAL SDK??????  This issue has driven me insane with a stupid workaround for over a year.  Come on Razer!

**Comment by terricain** [comment]
Yeah i have a list of the addresses, I just was too lazy at the time to implement it :wink:

**Comment by z3ntu** [comment]
Uhm this is merged, right? https://github.com/terrycain/razer-drivers/pull/173

**Comment by terricain** [comment]
Yeah
