### ISSUE TITLE
delete

### ISSUE THREAD

**Issue by Graphite86** [openrazer/openrazer#1787]
### Distribution

  Razer Huntsman V2 Analog

### Support

- [YES ] Have you tried rebooting? 
- [YES ] Have you looked at the [Troubleshooting](https://github.com/openrazer/openrazer/wiki/Troubleshooting) page?

delete

**Comment by z3ntu** [comment]
I'm not sure what Synapse has to do with OpenRazer. Synapse is a Windows program and openrazer is only available on Linux.
