### ISSUE TITLE
Segmentation fault under Debian

### ISSUE THREAD

**Issue by artificial-immersion** [openrazer/openrazer#181]
Getting a segmentation fault under Debian 8 and Stretch when enterting the command:
razer_bcd_controller -3
I am using a Blackwidow Chroma btw.
I tried it as normal user and as root.

**Comment by z3ntu** [comment]
Are you sure you are using terrycain's version of the driver? The command razer_bcd_controller doesn't exist anymore. Installation instructions are located at https://terrycain.github.io/razer-drivers/

**Comment by z3ntu** [comment]
@artificial-immersion Can this be closed?
