### ISSUE TITLE
Razer Blackwidow Chroma V2 (released Jan 24, 2017) Support

### ISSUE THREAD

**Issue by V13Axel** [openrazer/openrazer#184]
This device was released quite recently, and I wound up getting one. Decided it'd be helpful to myself and others to try and contribute to this project.

USB ID is `1532:0221`

Output of `sudo lsusb -d 1532:0221 -v`:

```Bus 003 Device 012: ID 1532:0221 Razer USA, Ltd 
Device Descriptor:
  bLength                18
  bDescriptorType         1
  bcdUSB               2.00
  bDeviceClass            0 (Defined at Interface level)
  bDeviceSubClass         0 
  bDeviceProtocol         0 
  bMaxPacketSize0        64
  idVendor           0x1532 Razer USA, Ltd
  idProduct          0x0221 
  bcdDevice            2.00
  iManufacturer           1 Razer
  iProduct                2 Razer BlackWidow Chroma V2
  iSerial                 0 
  bNumConfigurations      1
  Configuration Descriptor:
    bLength                 9
    bDescriptorType         2
    wTotalLength           84
    bNumInterfaces          3
    bConfigurationValue     1
    iConfiguration          0 
    bmAttributes         0xa0
      (Bus Powered)
      Remote Wakeup
    MaxPower              500mA
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        0
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      1 Boot Interface Subclass
      bInterfaceProtocol      1 Keyboard
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength      61
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x81  EP 1 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0008  1x 8 bytes
        bInterval               1
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        1
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      0 No Subclass
      bInterfaceProtocol      1 Keyboard
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength     159
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x82  EP 2 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0010  1x 16 bytes
        bInterval               1
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        2
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      0 No Subclass
      bInterfaceProtocol      2 Mouse
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength      94
          Report Descriptor: (length is 94)
            Item(Global): Usage Page, data= [ 0x01 ] 1
                            Generic Desktop Controls
            Item(Local ): Usage, data= [ 0x02 ] 2
                            Mouse
            Item(Main  ): Collection, data= [ 0x01 ] 1
                            Application
            Item(Local ): Usage, data= [ 0x01 ] 1
                            Pointer
            Item(Main  ): Collection, data= [ 0x00 ] 0
                            Physical
            Item(Global): Usage Page, data= [ 0x09 ] 9
                            Buttons
            Item(Local ): Usage Minimum, data= [ 0x01 ] 1
                            Button 1 (Primary)
            Item(Local ): Usage Maximum, data= [ 0x05 ] 5
                            Button 5
            Item(Global): Logical Minimum, data= [ 0x00 ] 0
            Item(Global): Logical Maximum, data= [ 0x01 ] 1
            Item(Global): Report Size, data= [ 0x01 ] 1
            Item(Global): Report Count, data= [ 0x05 ] 5
            Item(Main  ): Input, data= [ 0x02 ] 2
                            Data Variable Absolute No_Wrap Linear
                            Preferred_State No_Null_Position Non_Volatile Bitfield
            Item(Global): Report Size, data= [ 0x01 ] 1
            Item(Global): Report Count, data= [ 0x03 ] 3
            Item(Main  ): Input, data= [ 0x03 ] 3
                            Constant Variable Absolute No_Wrap Linear
                            Preferred_State No_Null_Position Non_Volatile Bitfield
            Item(Global): Usage Page, data= [ 0x00 0xff ] 65280
                            (null)
            Item(Local ): Usage, data= [ 0x40 ] 64
                            (null)
            Item(Global): Report Size, data= [ 0x08 ] 8
            Item(Global): Report Count, data= [ 0x02 ] 2
            Item(Global): Logical Minimum, data= [ 0x81 ] 129
            Item(Global): Logical Maximum, data= [ 0x7f ] 127
            Item(Main  ): Input, data= [ 0x02 ] 2
                            Data Variable Absolute No_Wrap Linear
                            Preferred_State No_Null_Position Non_Volatile Bitfield
            Item(Global): Usage Page, data= [ 0x01 ] 1
                            Generic Desktop Controls
            Item(Local ): Usage, data= [ 0x38 ] 56
                            Wheel
            Item(Global): Logical Minimum, data= [ 0x81 ] 129
            Item(Global): Logical Maximum, data= [ 0x7f ] 127
            Item(Global): Report Size, data= [ 0x08 ] 8
            Item(Global): Report Count, data= [ 0x01 ] 1
            Item(Main  ): Input, data= [ 0x06 ] 6
                            Data Variable Relative No_Wrap Linear
                            Preferred_State No_Null_Position Non_Volatile Bitfield
            Item(Local ): Usage, data= [ 0x30 ] 48
                            Direction-X
            Item(Local ): Usage, data= [ 0x31 ] 49
                            Direction-Y
            Item(Global): Logical Minimum, data= [ 0x00 0x80 ] 32768
            Item(Global): Logical Maximum, data= [ 0xff 0x7f ] 32767
            Item(Global): Report Size, data= [ 0x10 ] 16
            Item(Global): Report Count, data= [ 0x02 ] 2
            Item(Main  ): Input, data= [ 0x06 ] 6
                            Data Variable Relative No_Wrap Linear
                            Preferred_State No_Null_Position Non_Volatile Bitfield
            Item(Main  ): End Collection, data=none
            Item(Global): Usage Page, data= [ 0x00 0xff ] 65280
                            (null)
            Item(Local ): Usage, data= [ 0x02 ] 2
                            (null)
            Item(Global): Logical Minimum, data= [ 0x00 ] 0
            Item(Global): Logical Maximum, data= [ 0x01 ] 1
            Item(Global): Report Size, data= [ 0x08 ] 8
            Item(Global): Report Count, data= [ 0x5a ] 90
            Item(Main  ): Feature, data= [ 0x01 ] 1
                            Constant Array Absolute No_Wrap Linear
                            Preferred_State No_Null_Position Non_Volatile Bitfield
            Item(Main  ): End Collection, data=none
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x83  EP 3 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0008  1x 8 bytes
        bInterval               1
Device Status:     0x0000
  (Bus Powered)
```

`ls -lah /dev/input/by-id/`:

```
lrwxrwxrwx 1 root root  10 Feb  1 22:48 usb-Razer_Razer_BlackWidow_Chroma_V2-event-kbd -> ../event18
lrwxrwxrwx 1 root root  10 Feb  1 22:48 usb-Razer_Razer_BlackWidow_Chroma_V2-if01-event-kbd -> ../event19
```

Not in a position currently where I can do the pcap(s) and take Synapse screenshots, just thought I'd go ahead and open an issue for this device to get the ball rolling.

**Comment by z3ntu** [comment]
Could you tell me the product/model number of the ~~mouse~~ keyboard just for documentation reasons? :) 

Screenshots from Synapse would be pretty cool to see if there are new hardware/firmware effects.

**Comment by V13Axel** [comment]
@z3ntu not sure what you mean... It's a keyboard.

It's the BlackWidow Chroma V2, as mentioned in the issue title: http://www.razerzone.com/gaming-keyboards-keypads/razer-blackwidow-chroma-v2

Model RZ03-0203
Product number RZ03-02030200-R3U1

As for the synapse screenshots, I'm not currently in a position to provide them. I'll do so later this evening, around 6 or 7PM EST.

**Comment by z3ntu** [comment]
Yeah sorry, in the first second I somehow read DeathAdder Chroma V2 and apparently I wrote that down. But yes, I meant exactly these numbers :)

**Comment by terricain** [comment]
@V13Axel Will also need a few packet captures, how-to [here](https://github.com/terrycain/razer-drivers/wiki/Reverse-Engineering-USB-Protocol), I am assuming its functionally equivelent to the V1 but i have a strong suspicion that it uses the non-simple effects commands, hence I want captures just to make sure.

**Comment by V13Axel** [comment]
@terrycain Yep, planning to do that as soon as I can. For now, here are the Chroma options:

http://imgur.com/a/zC3MO

**Comment by z3ntu** [comment]
The dropdown menu ("Effect") in the second image would be nice :)

**Comment by wtjerry** [comment]
I also got one of these keyboards.
lsusb gave the same result as V13Axel already posted. My product number however is a bit different: RZ03-02031200-R3Q1 (it is a swiss keyboard)

Here an print screen of the effect dropdown: https://imgur.com/a/snZl7

**Comment by terricain** [comment]
Can you get some packet captures? Pretty sure I already know what's going to be there but I like evidence

**Comment by cptdaaaaave** [comment]
my Blackwidow Chroma v2 is on the way and I'm keen to help out if there is anything I can do :)

**Comment by terricain** [comment]
Packet captures :smile:

**Comment by vbujanca** [comment]
@terrycain do you mean sniff packets with wireshark?

**Comment by terricain** [comment]
USB packets yes - https://github.com/terrycain/razer-drivers/wiki/Reverse-Engineering-USB-Protocol

**Comment by terricain** [comment]
^^ Basically you need a windows vm with synapse installed. If anyone is capable then I'll list what I need.

**Comment by vbujanca** [comment]
@terrycain I have most of the setup installed, I will be neding wireshark as well, on the guest machine I guess. I'll be doing this now

**Comment by cptdaaaaave** [comment]
So you're running wireshark on your *nix host and relying on the virtual box USB pass through from the windows VM?

**Comment by terricain** [comment]
@cptdaaaaave yeah, @vbujanca you need wireshark on the linux, to _watch_ the traffic going to the windows.

**Comment by cptdaaaaave** [comment]
@terrycain cool, have all that except my keyboard. So I'll get on it once it arrives next week 👍🏼

**Comment by vbujanca** [comment]
I see, in this case I will be needing an extra keyboard as the vm needs to steal it in order to run synapse. I will probably just have to filter the razer keyboard. If you don't mind then I'll be doing this tomorrow morning. Cheers!

**Comment by terricain** [comment]
No probs, and as long as wireshark sees packets and synapse sees keyboard thats all that matters.

I need
* a capture from before the vm is started going all the way until synapse is open and on screen
* one capture per effect (excluding ripple, fire) and just click some options of each effcet, like for breathing, clikc single breathing, dual breathing colours and random.
* game mode on and off a few times

* fire effect, it will spam a shit load of packets, capture like a few seconds.

**Comment by vbujanca** [comment]
I think I have captured all that you asked, please let me know if you need anything else. Good luck!

btw, all of the effects, I have started from none and then played with all options (changed at least one color/random where available, wave direction, brightness and duration)

[capture.zip](https://github.com/terrycain/razer-drivers/files/780359/capture.zip)

**Comment by terricain** [comment]
Will have a look at the weekend

**Comment by terricain** [comment]
@vbujanca what os you on?

**Comment by terricain** [comment]
@vbujanca also what physical key layout does your keyboard have?

**Comment by vbujanca** [comment]
@terrycain 

host os linux mint 17.3, guest vm (in virtualbox) is windows 10 the demo image from ms

the layout is plain english us

**Comment by terricain** [comment]
1. Disable secure boot if its on
1. Grab [these](https://drive.google.com/drive/folders/0BydYgD2LzDUCMUliMndjTzFZUmc?usp=sharing) debs, install them (`dpkg -i debname.deb`, will probably then need to also run `apt-get install -f` to fix dependencies)
1. Reboot, literally this step is crucial

Now 
```
ls -l /sys/bus/hid/drivers/
ls -l /sys/bus/hid/drivers/razerkbd
ls -l /sys/bus/hid/drivers/razerkbd/0*/
```

**Comment by vbujanca** [comment]
```
ls -l /sys/bus/hid/drivers/
total 0
drwxr-xr-x 2 root root 0 Feb 17 14:56 hid-generic
drwxr-xr-x 2 root root 0 Feb 17 14:56 razerkbd


ls -l /sys/bus/hid/drivers/razerkbd
total 0
lrwxrwxrwx 1 root root    0 Feb 17 14:59 0003:1532:0221.0001 -> ../../../../devices/pci0000:00/0000:00:14.0/usb1/1-4/1-4:1.0/0003:1532:0221.0001
lrwxrwxrwx 1 root root    0 Feb 17 14:59 0003:1532:0221.0002 -> ../../../../devices/pci0000:00/0000:00:14.0/usb1/1-4/1-4:1.1/0003:1532:0221.0002
lrwxrwxrwx 1 root root    0 Feb 17 14:59 0003:1532:0221.0003 -> ../../../../devices/pci0000:00/0000:00:14.0/usb1/1-4/1-4:1.2/0003:1532:0221.0003
--w------- 1 root root 4096 Feb 17 14:56 bind
lrwxrwxrwx 1 root root    0 Feb 17 14:59 module -> ../../../../module/razerkbd
--w------- 1 root root 4096 Feb 17 14:59 new_id
--w------- 1 root root 4096 Feb 17 14:59 uevent



ls -l /sys/bus/hid/drivers/razerkbd/0*/
/sys/bus/hid/drivers/razerkbd/0003:1532:0221.0001/:
total 0
lrwxrwxrwx 1 root plugdev    0 Feb 17 14:56 driver -> ../../../../../../../bus/hid/drivers/razerkbd
drwxr-xr-x 3 root plugdev    0 Feb 17 14:56 hidraw
drwxr-xr-x 3 root plugdev    0 Feb 17 14:56 input
-rw-rw---- 1 root plugdev 4096 Feb 17 14:56 key_alt_f4
-rw-rw---- 1 root plugdev 4096 Feb 17 14:56 key_alt_tab
-rw-rw---- 1 root plugdev 4096 Feb 17 14:56 key_super
-r--r--r-- 1 root plugdev 4096 Feb 17 14:56 modalias
drwxr-xr-x 2 root plugdev    0 Feb 17 14:56 power
-r--r--r-- 1 root plugdev 4096 Feb 17 14:56 report_descriptor
lrwxrwxrwx 1 root plugdev    0 Feb 17 14:56 subsystem -> ../../../../../../../bus/hid
-rw-r--r-- 1 root plugdev 4096 Feb 17 14:56 uevent

/sys/bus/hid/drivers/razerkbd/0003:1532:0221.0002/:
total 0
lrwxrwxrwx 1 root plugdev    0 Feb 17 14:56 driver -> ../../../../../../../bus/hid/drivers/razerkbd
drwxr-xr-x 3 root plugdev    0 Feb 17 14:56 hidraw
drwxr-xr-x 3 root plugdev    0 Feb 17 14:56 input
-rw-rw---- 1 root plugdev 4096 Feb 17 14:56 key_alt_f4
-rw-rw---- 1 root plugdev 4096 Feb 17 14:56 key_alt_tab
-rw-rw---- 1 root plugdev 4096 Feb 17 14:56 key_super
-r--r--r-- 1 root plugdev 4096 Feb 17 14:56 modalias
drwxr-xr-x 2 root plugdev    0 Feb 17 14:56 power
-r--r--r-- 1 root plugdev 4096 Feb 17 14:56 report_descriptor
lrwxrwxrwx 1 root plugdev    0 Feb 17 14:56 subsystem -> ../../../../../../../bus/hid
-rw-r--r-- 1 root plugdev 4096 Feb 17 14:56 uevent

/sys/bus/hid/drivers/razerkbd/0003:1532:0221.0003/:
total 0
-rw-rw---- 1 root plugdev 4096 Feb 17 14:56 device_mode
-r--r----- 1 root plugdev 4096 Feb 17 14:56 device_serial
-r--r----- 1 root plugdev 4096 Feb 17 14:56 device_type
lrwxrwxrwx 1 root plugdev    0 Feb 17 14:56 driver -> ../../../../../../../bus/hid/drivers/razerkbd
-r--r----- 1 root plugdev 4096 Feb 17 14:56 firmware_version
-rw-rw---- 1 root plugdev 4096 Feb 17 14:56 game_led_state
drwxr-xr-x 3 root plugdev    0 Feb 17 14:56 hidraw
drwxr-xr-x 3 root plugdev    0 Feb 17 14:56 input
-rw-rw---- 1 root plugdev 4096 Feb 17 14:56 macro_led_effect
-rw-rw---- 1 root plugdev 4096 Feb 17 14:56 macro_led_state
-rw-rw---- 1 root plugdev 4096 Feb 17 14:56 matrix_brightness
--w--w---- 1 root plugdev 4096 Feb 17 14:56 matrix_custom_frame
--w--w---- 1 root plugdev 4096 Feb 17 14:56 matrix_effect_breath
--w--w---- 1 root plugdev 4096 Feb 17 14:56 matrix_effect_custom
--w--w---- 1 root plugdev 4096 Feb 17 14:56 matrix_effect_none
--w--w---- 1 root plugdev 4096 Feb 17 14:56 matrix_effect_reactive
--w--w---- 1 root plugdev 4096 Feb 17 14:56 matrix_effect_spectrum
--w--w---- 1 root plugdev 4096 Feb 17 14:56 matrix_effect_static
--w--w---- 1 root plugdev 4096 Feb 17 14:56 matrix_effect_wave
-r--r--r-- 1 root plugdev 4096 Feb 17 14:56 modalias
drwxr-xr-x 2 root plugdev    0 Feb 17 14:56 power
-r--r--r-- 1 root plugdev 4096 Feb 17 14:56 report_descriptor
lrwxrwxrwx 1 root plugdev    0 Feb 17 14:56 subsystem -> ../../../../../../../bus/hid
-rw-rw---- 1 root plugdev 4096 Feb 17 14:56 test
-rw-r--r-- 1 root plugdev 4096 Feb 17 14:56 uevent
-r--r----- 1 root plugdev 4096 Feb 17 14:56 version

```

**Comment by terricain** [comment]
ok to start with, sudo to root, cd to `/sys/bus/hid/drivers/razerkbd/0003:1532:0221.0003/`
```
cat device_mode
cat device_serial
cat device_type
cat firmware_version
cat test
cat version
```

**Comment by vbujanca** [comment]
```
cat device_mode
0:0

cat device_serial
IO1704F15600402

cat device_type
Razer BlackWidow Chroma V2

cat firmware_version
v1.0

cat test
018100

cat version
1.1.8
```

**Comment by terricain** [comment]
What physical key layout do you have on the keyboard? Pic would be nice, but thats looking good gimme a bit and ill post some more :)

**Comment by vbujanca** [comment]
@terrycain sent you pic from phone, lemme know if you got it

**Comment by terricain** [comment]
Nope no pic

**Comment by vbujanca** [comment]
![img_20170217_153152_01](https://cloud.githubusercontent.com/assets/6816108/23082639/31917134-f528-11e6-8171-b8cc1da89699.jpg)

**Comment by terricain** [comment]
Here is more, paste things line by line, dont paste multiple lines. I have doubts about these ones, they "should" work
```
# Dont try other things with device mode, trust me, though i think ive hardcoded safe options
echo -ne '\x03\x00' > device_mode
cat device_mode
# Should output something like 3:0, if it doesnt then :-(

# Should toggle game mode led (wont actually do game mode things)
cat game_led_state
echo '1' > game_led_state
cat game_led_state
echo '0' > game_led_state

# Macro led
echo '1' > macro_led_state
cat macro_led_state
echo '1' > macro_led_effect
cat macro_led_effect
# Wait as it should blink

# No blink
echo '0' > macro_led_effect
# macro led off
echo '0' > macro_led_state



# Try brightness
echo -n '255' > matrix_brightness
cat matrix_brightness
echo -n '128' > matrix_brightness
cat matrix_brightness
echo -n '64' > matrix_brightness
cat matrix_brightness
echo -n '255' > matrix_brightness
cat matrix_brightness
```

**Comment by vbujanca** [comment]
@terrycain I can only continue testing this on Monday, sorry. Have nice weekend there!

**Comment by terricain** [comment]
@vbujanca np

**Comment by vbujanca** [comment]
```
echo -ne '\x03\x00' > device_mode

cat device_mode
3:0

```

Al lthe other features seem to work, from root

**Comment by terricain** [comment]
you tested all the ones above? what about the ones not mentioned?

**Comment by vbujanca** [comment]
the brightness, macro led state/effect and game led state react to echo commands

**Comment by terricain** [comment]
Awesome, take it the ones that output strings like serials work too. What f/w version is it on by the way. And i'll paste some more to do later. About 1/4 the way through all testing i think.

**Comment by vbujanca** [comment]
isn't it the firmware_version I have sent you earlier (1.0) ? if not, can I find it in synapse?

**Comment by terricain** [comment]
My bad was being lazy and didnt look up, yep thats kl

**Comment by terricain** [comment]
```
# Static
echo -ne '\xFF\x00\x00' > matrix_effect_static
echo -ne '\x00\xFF\x00' > matrix_effect_static

# Specturm
echo -n '1' > matrix_effect_spectrum

# Wave
echo -n '1' > matrix_effect_wave
echo -n '2' > matrix_effect_wave

# No effect
echo -n '1' > matrix_effect_none

# Reactive
echo -ne '\x03\xFF\x00\x00' > matrix_effect_reactive

# Breathing
echo -ne '\xFF\x00\x00' > matrix_effect_breath
echo -ne '\xFF\x00\xFF\xFF\xFF\x00' > matrix_effect_breath
echo -ne '\x01' > matrix_effect_breath

# Starlight
echo -ne '\x02\xFF\x00\x00' > matrix_effect_starlight
echo -ne '\x02\xFF\x00\xFF\xFF\xFF\x00' > matrix_effect_starlight
echo -ne '\x02' > matrix_effect_starlight

```

**Comment by vbujanca** [comment]
Spectrum works fine. So does wave effect (both directions) and none. Reactive mode works too.

Not sure what static effect does, but I assume it is also working as it reacts by illuminating all keys.

However, the line `echo -ne '\xFF\x00\x00' > matrix_effect_breathing` generates a 'Permission denied'

I am running all these commands as root

**Comment by terricain** [comment]
Reread the comment, added startlight to it after accidentally commenting, also corrected typo breathing should be breath.

Static should just change colour, thats it, a solid colour.

**Comment by vbujanca** [comment]
ok, Breathing effect works now, after 2nd breathing command it also alternates between two or more colors?

`echo -ne '\x02\xFF\x00\x00' > matrix_effect_starlight` ends up in permission denied

**Comment by terricain** [comment]
> ok, Breathing effect works now, after 2nd breathing command it also alternates between two or more colors?
Yeah,

And crap yeah forgot a section, copy-paste mistake. Install [these](https://drive.google.com/open?id=0BydYgD2LzDUCMUliMndjTzFZUmc) debs, reboot (reboot crucial) then try starlight bit

**Comment by vbujanca** [comment]
starlight effect works fine now, the second command makes it alternate colors, not sure about third starlight command as doesn't seem to change anything

**Comment by terricain** [comment]
np

**Comment by terricain** [comment]
Will add daemon support, and drum up some more tests tomorrow, but near enough there now :)

**Comment by terricain** [comment]
Try [these](https://drive.google.com/open?id=0BydYgD2LzDUCMUliMndjTzFZUmc) debs, reboot. Then go grab `d-feet` application (for troubleshooting) and grab either polychromatic or razer-commander (links in readme) and see if they work

**Comment by vbujanca** [comment]
I'm afraid I can't help further, due to my linux distribution, both polychromatic and razer commander require gtk 3.14+, whereas I run linux mint 17.

I might be able to upgrade soon, will let you know when I can test again.

**Comment by terricain** [comment]
@vbujanca  can you run `d-feet`?

**Comment by vbujanca** [comment]
I can. I am also upgrading mint so I can hopefully test the whole stack soon

**Comment by terricain** [comment]
Well if you open d-feet, click on the session tab, find an entry named razer.org (or something like that), on the right expand all the subtree options then send or link to a screenshot

**Comment by z3ntu** [comment]
*`org.razer`

**Comment by vbujanca** [comment]
![dfeet_razer](https://cloud.githubusercontent.com/assets/6816108/23213507/2f1025c2-f8d9-11e6-8824-ee6f5513c109.png)

**Comment by z3ntu** [comment]
@vbujanca You sure that the device is connected? If `ls -al /sys/bus/hid/drivers/razerkbd/0*/` returns no error, please do a `pkill -e razer && razer-service --verbose -F` and look again into d-feet. If there's still no entry `/org/razer/device/<serialno>` please send the output from the razer-service command above.
EDIT:
Forget it, the Blackwidow v2 doesn't have daemon support yet... @terrycain please fix 👍 
EDIT 2: At least the blackwidow_chroma_v2_0x0221 branch doesn't have daemon support yet, maybe the debs Terry posted have daemon support... So please try the stuff that are before the first edit :)

**Comment by vbujanca** [comment]
the razerkbd folder is missing! apparently the mint upgrade removed it? I will have to reinstall the earlier deb packages

**Comment by z3ntu** [comment]
nah, it's missing because the keyboard isn't bound to the driver. Try replugging it...

**Comment by vbujanca** [comment]
replugging it didn't work, are you sure I don't have to reinstall those packages?

**Comment by terricain** [comment]
@vbujanca Try reinstall

**Comment by vbujanca** [comment]
![dfeet_razer_01](https://cloud.githubusercontent.com/assets/6816108/23223478/2e1af79e-f8f9-11e6-8b64-263067e40bc3.png)

![dfeet_razer_02](https://cloud.githubusercontent.com/assets/6816108/23223483/31dfe6b4-f8f9-11e6-8e8e-a9476e3ad927.png)

**Comment by terricain** [comment]
Nice. Will write up some tests when I get home

**Comment by vbujanca** [comment]
I had some issues with building the kernel dependencies (the kernel headers were missing after mint upgrade) but everything should be working now. The polychromatic app still doesn't work on mint 18.1 

Razer commander works though. It is missing some effects, such as starlight. Or is there another branch that I could try, currently on master

**Comment by terricain** [comment]
@vbujanca Ahh does using Razer-commander work with the keyboard?

**Comment by vbujanca** [comment]
Indeed it does now (using master)

**Comment by terricain** [comment]
@vbujanca Awesome, I'm going to class this as working. @gabmus, @lah7 apps need updating
