### ISSUE TITLE
Razer Blade Stealth (Original) - toggling logo_led_state seems to have no effect

### ISSUE THREAD

**Issue by somayweall** [openrazer/openrazer#186]
Steps to reproduce:
(starting with lid logo off)
- navigate to /sys/bus/hid/devices/[device id]
type command: `echo -n "1" > logo_led_state` into Terminal

Expected behavior
- Logo light comes on

Actual behavior
- Logo light remains off.
- Other commands worked and had immediate effect, such as `echo -n "1" > fn_toggle`

**Comment by terricain** [comment]
Can you get me some packet captures of razer synapse doing the same - https://github.com/terrycain/razer-drivers/wiki/Reverse-Engineering-USB-Protocol

**Comment by somayweall** [comment]
Will do.  Was unable to connect to the device from within VirtualBox.  Will reinstall Windows again on the metal and attempt packet capture.

**Comment by z3ntu** [comment]
@thesurfaceofthevoid Any update?

**Comment by z3ntu** [comment]
Closing as there was no response.
