### ISSUE TITLE
Razer BlackWidow Chroma 1532:0203	ripple effect lag

### ISSUE THREAD

**Issue by TrueNix** [openrazer/openrazer#190]
Hi, is there any way to make ripple effect faster, it feels slow compare to windows.

Thanks.

**Comment by terricain** [comment]
Seems fine on my machine. What app are you using to set ripple?

**Comment by TrueNix** [comment]
Thanks for replying, 
I'm using Polychromatic. 
It is not lag so much but it's much slower then on windows, maybe I should request speed tweaking for ripple effect?

**Comment by terricain** [comment]
Polychromatic could set the refresh rate to lower value than is default. Other than that, there's not much else can be done.

**Comment by lah7** [comment]
I'm the author of Polychromatic - I'll set the refresh rate to `0.01` (the default is `0.05`) for the next release - that's assuming devices other than the BlackWidow Chroma will be OK at this value.

**Comment by TrueNix** [comment]
Thank you so much!

**Comment by terricain** [comment]
Should be fine

**Comment by tildearrow** [comment]
I tried to use `0.01` as refresh rate (via D-Bus) and it still is very slow.
Maybe a parameter for speed would be good?

**Comment by TrueNix** [comment]
yeah a variable parameter would be ideal.

**Comment by terricain** [comment]
would require some tweaking, am too busy to do it now but next time im around that bit of code ill look into it
