### ISSUE TITLE
Razer DeathAdder 2013 support

### ISSUE THREAD

**Issue by rodjun** [openrazer/openrazer#195]
Hey, i noticed that my ~~good~~ ol' DeathAdder 2013 is not supported, let's change that!

Some preliminary info:

MODEL NO.      : RZ01-0084, Gaming Mouse
PRODUCT NO. : RZ01-00840100-R3U1

Output of "lsusb -d 1532:0037 -v": https://gist.github.com/rodjun/0a512d4682c61dfb026e0f0e485f6de1

Output of "ls -lah /dev/input/by-id/": https://gist.github.com/rodjun/87322b6aee7318131acfeaa3b7557513

Currently installing VirtualBox, i'll take some pictures of Razer Synapse when i'm done setting up the VM!

**Comment by z3ntu** [comment]
You copy-pasted the `0015` from the Naga Classic ;) `0037` is correct (the output you actually posted is correct) 👍

**Comment by rodjun** [comment]
Yeah i was using other issues as a start point for mine, totally missed that hahaha, it's fixed now.

After some google searches i found out that razercfg supports the DA 2013, can any info be infered from their [code](https://github.com/mbuesch/razer/blob/master/librazer/hw_deathadder2013.c)?

**Comment by z3ntu** [comment]
No idea, ask @terrycain ;) But apparently Terry has all (at least older) devices in his heart so he can add support very easily 😆

**Comment by RedactedProfile** [comment]
I was shocked actually to find that the 2013 model isn't supported. Its a pretty basic mouse, can the elite driver not be copied and basically stripped of the special features the Elite offers uniquely?

**Comment by terricain** [comment]
Just to confirm is this a 0037 or a 0015

**Comment by QuakeDasKueken** [comment]
0037

**Comment by z3ntu** [comment]
@QuakeDasKueken @RedactedProfile Could one of you please make screenshots from the available options on the mouse in Synapse (on Windows)?

**Comment by rodjun** [comment]
@z3ntu 
http://i.imgur.com/QX6ZIwB.png
http://i.imgur.com/Dwtyow1.png
http://i.imgur.com/9bgd8j3.png
http://i.imgur.com/NjeYunz.png
http://i.imgur.com/LoPisMx.png

**Comment by binarykitchen** [comment]
Yeah me too, I wish Razer DeathAdder 2013 support for Ubuntu 17.04 too - if there is anything I can help with, lemme know.

**Comment by terricain** [comment]
Ok ideally packet captures of 
* sliding dpi from min to max
* changing poll rate
* toggling scroll and logo leds

I could probably grab the needed info from razercfg but thats more hassle from my point of view as the packet captures near enough directly translate to what is in the driver

**Comment by najashark** [comment]
hi, here is my capture for button click, polling rate and lighting
this is list how i do the capture for easy guide

button
left click
right click
forward button
back button
scroll up
scroll down

polling rate
125
500
1000

lighting
scroll ON/OFF
logo ON/OFF


[deathadder2013.zip](https://github.com/terrycain/razer-drivers/files/1239355/deathadder2013.zip)

**Comment by najashark** [comment]
just to add, how to capture DPI and Acceleration?
because if I just slide the setting in synapse, nothing is captured in wireshark

**Comment by terricain** [comment]
accleration is a windows thing, dpi should work, if it doesnt then your filters probably wrong

**Comment by najashark** [comment]
this is new capture for button(I missed the scroll click) and profile button below the mouse.
below is the image i use to do the click in ascending order. Later I will provide DPI capture

![button](https://user-images.githubusercontent.com/1461279/29528905-4c69a7bc-86d0-11e7-9bff-82d9a00a98c9.png)


[deathadder.zip](https://github.com/terrycain/razer-drivers/files/1239497/deathadder.zip)

**Comment by najashark** [comment]
still never get the DPI captured from synapse but i captured DPI change from another driver from [here](https://github.com/mbuesch/razer)
the step are 450, 900, 1800, 3500

[deathadder-DPIsteps.pcapng.zip](https://github.com/terrycain/razer-drivers/files/1239902/deathadder-DPIsteps.pcapng.zip)

**Comment by ghost** [comment]
Any idea on when support will be available for the DeathAdder 2013?

Currently using `da2013ctl` but id love to use this software instead

**Comment by terricain** [comment]
Am without internet for a while as just moved house, remind me again in like 2 weeks :wink:

**Comment by najashark** [comment]
its not 2 weeks, but just a reminder 😉

**Comment by terricain** [comment]
Snooze for 1 week. I have internet now, but am now catching up with all the backlog :wink:

**Comment by ZakharH** [comment]
Any progress yet?

**Comment by ZakharH** [comment]
its a week and a half, but just wondering if there's something in the works ;)

**Comment by ghost** [comment]
Checking in, just wondering if there is anything in the works

**Comment by binarykitchen** [comment]
yo, any news on this one?

**Comment by furai** [comment]
Isn't it exactly like the other DA? Just different usb id and that's all? It goes up to 6400DPI.

I'd love for it to see it supported. Then I'd probably switch from https://github.com/mbuesch/razer to these drivers.

**Comment by terricain** [comment]
@furai You mean 6400DPI right?

**Comment by furai** [comment]
Uh, yeah, 6400 DPI. Pressed 0 one time too much. Edited.

**Comment by danshou** [comment]
Is there any way to help with this ? At least with the testing maybe.

**Comment by manu212** [comment]
is it possible to get this mouse supported?

**Comment by ghost** [comment]
If you're looking for something to use right now, look into `da2013ctl`. I'm using it currently, but I really am looking forward to when this is done

**Comment by hamjo** [comment]
Any update on this? It's been in progress for 7 months now.

**Comment by ghost** [comment]
I think this can be closed now @z3ntu

**Comment by z3ntu** [comment]
Fixed by 791a4ad3050be477d741b921d1b522494327bced
