### ISSUE TITLE
Deleted User account originally installed on linux mint

### ISSUE THREAD

**Issue by magnum93** [openrazer/openrazer#198]
Hi Deleted the original user account to create a new linux user account, now when I log in the daemon cannot connect, how do I change the password for the daemon or allow the new user access?
This is a kinda bug as the software fails to work after creating a ne wuser daemon does not seamlessly log in to connect , any help appreciated please.

**Comment by magnum93** [comment]
I fixed it myself the new user has to be added to the plug-dev group

**Comment by z3ntu** [comment]
Yes, the user has to be in the group `pludev`. If the issue is solved, please close the issue.

**Comment by magnum93** [comment]
Many thanks for your assistance can we donate towards development

**Comment by terricain** [comment]
> Many thanks for your assistance can we donate towards development

No probs, and sure if you want

**Comment by magnum93** [comment]
Where can we send paypal donation? thanks

On 02/11/2017 06:48 PM, Terry Cain wrote:

Many thanks for your assistance can we donate towards development

No probs, and sure if you want

**Comment by terricain** [comment]
You can send it to `terry@terrys-home.co.uk` :smile:
