### ISSUE TITLE
How do i use the driver?

### ISSUE THREAD

**Issue by ghost** [openrazer/openrazer#203]
Hi, i have the razer Abyssus 2014 mice and after downloading the packages for my OS which is Ubuntu 16.10 i couldn't figure out how to use them, i tried looking for the set_mouse_dpi file but it seems it's missing.

**Comment by terricain** [comment]
@gedreher It's just called dpi now

**Comment by terricain** [comment]
Also you shouldnt use the driver directly, the daemon provides a dbus api and theres a python library that interracts with that.

**Comment by ghost** [comment]
oh ok, didn't know that, in which directory i can find that python library?

**Comment by terricain** [comment]
did you install all the debs?

**Comment by z3ntu** [comment]
```
from razer.client import DeviceManager
a = DeviceManager()
a.devices
```
gives you an array from razer devices if you mean that

**Comment by ghost** [comment]
yes, i added the repository manually and in the terminal i pasted this "sudo apt install python3-razer razer-kernel-modules-dkms razer-daemon razer-doc"

**Comment by terricain** [comment]
```
$ python3
>>> from razer.client import DeviceManger
>>>
```
Should work

**Comment by ghost** [comment]
that worked, thank both of you!

**Comment by nonetrix** [comment]
> ```
> $ python3
> >>> from razer.client import DeviceManger
> >>>
> ```
> 
> Should work

ModuleNotFoundError: No module named 'razer'

**Comment by z3ntu** [comment]
@nonetrix Change the `razer.client` to `openrazer.client`, the project has had a rename since the comment was written
