### ISSUE TITLE
Razer Tartarus macro keys

### ISSUE THREAD

**Issue by isoraqathedh** [openrazer/openrazer#206]
The Tartarus seems to be only lights-controllable. After installing the driver from the PPA and manually rebinding the device to the driver as instructed in the wiki, I get this as the interface:

```
root@tosemcler /sys/bus/hid/drivers/razerkbd/0003:1532:0208.0006 # ls
country        firmware_version      matrix_effect_none      profile_led_blue   test
device_mode    hidraw                matrix_effect_spectrum  profile_led_green  uevent
device_serial  input                 matrix_effect_static    profile_led_red    version
device_type    matrix_brightness     modalias                report_descriptor
driver         matrix_effect_breath  power                   subsystem
```

So there's no `macro_keys` file that can be written to to enable them.

This is done on Linux Mint 18, if this is relevant.

**Comment by terricain** [comment]
no need for tartarus, it emits keycodes normally

**Comment by isoraqathedh** [comment]
Are the keycodes configurable, or at least use the "upper-half" keycodes starting from 191?

**Comment by terricain** [comment]
Not exactly, the daemon "should" take an exclusive read on tartarus's input files, and essentially you can get it to run macros which would simulate pressing other keys

**Comment by isoraqathedh** [comment]
How would I be able to confirm this? Right now the macro keys are not generating messages that, e.g. `xev` can detect. If that is the expected behaviour, how can I instruct the daemon to change the behaviour to, e.g. make key 07 send keycode 197?

**Comment by terricain** [comment]
In theory that means the daemon is working and actually doing its job :smile:. Am actually in the middle of revamping all of the macro code. Its not possible at current to emit raw keycodes as it currently either runs commands or sends a string of keys to `xte` to run. By keys I mean actual letters (or whatever names xte accepts)

Any specific reason you need to send a keycode?

**Comment by isoraqathedh** [comment]
Sending keycodes (or better yet, keysyms) would allow better compatibility with xkb, and would mean that, e.g. Emacs can bind to those keys using the normal methods. Furthermore it would mean that shift, alt, &c. would behave normally with the keys on the Tartarus as well, and finally it means I can also attach commands in the same place as the rest of the keys (via xbindkeys or similar).

**Comment by terricain** [comment]
The issue im facing at the moment is that reading from the event file gives out say code 21 signifying a y, and matches the output of dumpkeys, but according to XKB y is 29. On a different razer keyboard code 21 = z and 29 still means y. xev on the other hand gives me keycode 29 when i press Y so somewhere unknown to me 21 is getting mapped to Y (or z on other kb's), am thinking udev but cant find anything solid to verify this.

I could listen to XKB for key events but it wont notify me for when keys are held down via autorepeat events (which I am using for some things). Reading from the event file gives the problem of not being able to convert the codes to the local keymap.

Any ideas

**Comment by isoraqathedh** [comment]
If it's just Y and Z, I think it might be that you're using French/German keyboards, because those are AZERTY/QWERTZ. That might be implemented on the hardware level but others might be on a software level, so it's a bit of a mess in that respect.

I'm not the best at this hardware thing, so I'm sorry that I can't be much help with the actual implementation or ways forward. I've definitely seen another program do it though – you might want to look at [Keyboarding Master](https://bitbucket.org/conzar/keyboarding-master)'s code to see how they did it.

**Comment by terricain** [comment]
Yeah its definitly possible as some crappy piece in X does it somewhere. Am soon going to rage quit and just support raw keycodes and a dictionary of scan/keycodes to keysym mappings and provide a few known ones and let users generate their own if need be

**Comment by tildearrow** [comment]
I think I can give an idea, but I'm just going to say it in one word: uinput.

**Comment by z3ntu** [comment]
He already knows about uinput ;)
![image](https://cloud.githubusercontent.com/assets/3768500/23155139/957de902-f811-11e6-8842-6513e5d487fa.png)
(that was yesterday)

**Comment by terricain** [comment]
Ha, I was talking to the lads on the razer chat lady night about exactly that. I'd need to get udev to deal with permissions of uinput but other than that should be good. And even better python-evdev has some bindings for it so I can use evdev for all the key event stuffs :-) 

Still doesn't solve converting the event codes to characters/keysyms based on layout but think I'm just going to bite the bullet on that one and make some dictionaries of known conversions

**Comment by terricain** [comment]
Have a plan... am working on it ;-), wanna get my macro implementation much better so I don't need to revisit it in a while
