### ISSUE TITLE
Daemon.py - minor cosmetic bug and question

### ISSUE THREAD

**Issue by memoryleakno1** [openrazer/openrazer#209]
In deamon.py why do you fork twice on startup? I am trying to understand how it works.

On second fork in catch block there is print message:
```python
        except OSError as err:
            print("Failed first fork. Error: {0}".format(err))
```
You obviously ment to say
```python
            print("Failed second fork. Error: {0}".format(err))
```

**Comment by terricain** [comment]
Linux double fork, Google.
And yeah copy paste error

**Comment by memoryleakno1** [comment]
Ok. thanks i will.
