### ISSUE TITLE
Razer Blade Late 2016 0x0224

### ISSUE THREAD

**Issue by snatella** [openrazer/openrazer#214]
Bus 001 Device 004: ID 1532:0224 Razer USA, Ltd

[chroma-lsusb.txt](https://github.com/terrycain/razer-drivers/files/801305/chroma-lsusb.txt)

Happy to provide more info if needed.

**Comment by z3ntu** [comment]
Please record packet captures of the keyboard effects from Synapse. See https://github.com/terrycain/razer-drivers/wiki/Reverse-Engineering-USB-Protocol

**Comment by ryanisnan** [comment]
I'm a new owner of a razer blade 2017 and the apps don't seem to have driver support yet, would be interested in helping out with this project. Would love to chat with someone about getting started.

**Comment by z3ntu** [comment]
Please post the output of `lsusb` 
And you can join our chat at Telegram (dunno how right now but will tell you later)

**Comment by z3ntu** [comment]
Do you have a username set on Telegram? If yes please post it and I will add you. I don't know if it's possible without a username right now as we don't have a 'join' link afaik

**Comment by ryanisnan** [comment]
I'll try to sign up - we'll see what happens. If not, my email is simply my
username at gmail.

**Comment by z3ntu** [comment]
Username isn't the email (you don't even need an email address for Telegram)

**Comment by lezed1** [comment]
I have the same issue on my Razer Blade Stealth Late 2016. I can post a packet capture of ripple with a few different parameters if that helps.

**Comment by z3ntu** [comment]
@lezed1 the usb id of yours is `1532:0224`? And yes, packet captures are needed.

**Comment by lezed1** [comment]
@z3ntu No, it's a Razer Blade Stealth (Late 2016) with id `1532:0220`. However, it's the same issue on a different but also recent model. I'm currently typing out another issue, so I'll make a capture in a few minutes.

**Comment by lezed1** [comment]
Here is a capture of a few different ripples. It starts with red (`0xFF0000`), green (`0x00FF00`) and blue (`0x0000FF`). It ends with a ripple of (`0xDDDDDD`).

From looking at the packets, this seems to just be using the individual key settings, so this may be solved by getting individual lighting working (#223).

**Comment by z3ntu** [comment]
Please note, that this issue is about 1532:0224 and not 1532:0220 :)

**Comment by lezed1** [comment]
Yes, but it appears to affect both. Would you like me to make a new issue?

**Comment by z3ntu** [comment]
But it's still not for this issue. #166 is probably what you are looking for.

**Comment by lezed1** [comment]
Oh, that's definitely better. I missed it by only searching for "stealth", my mistake.

**Comment by z3ntu** [comment]
*I deleted some comments here to keep it tidy and the messages were completely unrelated*

**Comment by z3ntu** [comment]
@ryanisnan btw your "Blade 2017" is actually "Late 2016" 😉 so you are in the correct issue

**Comment by ryanisnan** [comment]
Thanks @z3ntu - I wish Razer named these things slightly less confusing ;)

**Comment by snatella** [comment]
Sorry, this is still on my radar to do at some point - just will take a bit of time and I'm fresh out of it! Happy to try some lighter weight tasks like dev packages if someone wants to throw them my way/direct me to wherever chat that is discussed.

**Comment by z3ntu** [comment]
We have a Telegram chat where afaik most communication happen. Hit me up @z3ntu and I can add you to the group.

**Comment by juliancoleman** [comment]
Has anyone made an attempt to reverse engineer this device?

**Comment by z3ntu** [comment]
Hopefully we have something to test in the next couple of days.

**Comment by terricain** [comment]
Still need screenshots and packet captures

**Comment by Retic1337** [comment]
[Razer-0224.tar.gz](https://github.com/terrycain/razer-drivers/files/907230/Razer-0224.tar.gz)
Attempted to create packet captures

**Comment by terricain** [comment]
:+1: will look at it this weekend, am on mobile, does tar include screenshots?

**Comment by lezed1** [comment]
No, it's split into folders that have what effect each capture is though.

**Comment by terricain** [comment]
@lezed1 Ahh cool

**Comment by terricain** [comment]
Had brief look at them, looks good from here, hopefully will get some time this week to work on it, should be a copy/paste job

**Comment by terricain** [comment]
Who actaully has this that can test, and then what distro you on

**Comment by terricain** [comment]
And can this laptop also toggle the logo led on the laptop lid?

**Comment by fgblomqvist** [comment]
I have it (or rather I have the 2017 Blade but it has the same keyboard signature). I'm running Ubuntu 17.04 with GNOME. Would love to test it. Have had the laptop for a month now and as far as I know, you cannot toggle the lid led (I have not read anything about it). But I might be wrong.

**Comment by terricain** [comment]
Ahh can i get the product and model number of your laptop for @z3ntu's records, theres a spreadsheet somewhere.

Do you have telegram/can you get it? Me and a fair few other razer people hang out there now, would be easier for me to spam you with instructions there, if not the issue will do :wink:

**Comment by juliancoleman** [comment]
I have a late 2016 Razer Blade with a 7th gen Intel core i7-7700HQ (same as @fgblomqvist). I'm currently on Ubuntu 16.04, using the Nvidia driver 381 (non-LTS). I can confirm that not even Synapse on Windows allows you to toggle the LED on the lid, so I'm unsure if this is possible, or if there's some workaround.

**Comment by terricain** [comment]
Nope thats cool, I just know some laptops do some dont.

**Comment by terricain** [comment]
Ok grab debs from [here](https://drive.google.com/drive/folders/0BydYgD2LzDUCSi1BdExpSlRlNm8?usp=sharing)
install with `sudo dpkg -i debname`, install deps with `sudo apt-get install -f` then reboot

then hopefully post output of `lsmod | grep razer`

**Comment by juliancoleman** [comment]
`lsmod | grep razer` outputs an empty response for me. However, the install process seemed to have gone through just fine, so that's good.

**Comment by terricain** [comment]
`sudo modprobe razerkbd`
`lsmod | grep razer`

**Comment by juliancoleman** [comment]
*derp*... forgot to `modprobe`..

```
razerkbd               53248  0
hid                   122880  5 i2c_hid,hid_generic,usbhid,hid_rmi,razerkbd
```

**Comment by terricain** [comment]
ok in theory udev should do that for us but we can deal with udev another time.

`ls /sys/bus/hid/drivers/hid-generic`
`ls /sys/bus/hid/drivers/razerkbd`

**Comment by juliancoleman** [comment]
`ls /sys/bus/hid/drivers/hid-generic`

```
0003:046D:C537.0001  0003:046D:C537.0002  0003:1532:0224.0003  0003:1532:0224.0004  0003:1532:0224.0005  bind  module  new_id  uevent  unbind
```

`ls /sys/bus/hid/drivers/razerkbd`

```
bind  module  new_id  uevent  unbind
```

**Comment by terricain** [comment]
ok are you in the plugdev group? if not add yourself, log out and log back in.

Then sudo to root
```
/lib/udev/razer_mount razerkbd 0003:1532:0224.0003
/lib/udev/razer_mount razerkbd 0003:1532:0224.0004
/lib/udev/razer_mount razerkbd 0003:1532:0224.0005
```

**Comment by terricain** [comment]
Then `ls /sys/bus/hid/drivers/razerkbd`

**Comment by juliancoleman** [comment]
when I ran the command, it said I was added to that group. Secure Boot has been disabled this entire time, so I can't imagine something happened with that. Let me keep going with these and I'll get back to you in a second.

**Comment by juliancoleman** [comment]
```
sudo /lib/udev/razer_mount razerkbd 0003:1532:0224.0003
[sudo] password for julian:
Driver razerkbd
Device_ID 0003:1532:0224.0003
Unbinding 0003:1532:0224.0003 from hid-generic
Binding 0003:1532:0224.0003 to razerkbd
sh: printf: I/O error
```

**Comment by terricain** [comment]
ooh thats an odd one

**Comment by juliancoleman** [comment]
Alright, so running any of those commands disabled my keyboard until a reboot

**Comment by terricain** [comment]
Yeah it would do, it managed to unbind from the general usb keyboard driver, but failed to bind it to the razer one

**Comment by juliancoleman** [comment]
The backlights still work, so there's that :smile:

**Comment by terricain** [comment]
Ha

**Comment by juliancoleman** [comment]
Haha okay, where do we go from here? Do you still want me to `ls /sys/bus/hid/drivers/razerkbd`? Or will that not have changed?

**Comment by terricain** [comment]
Ok install the razer-kernel-moduels deb from here - https://drive.google.com/open?id=0BydYgD2LzDUCSi1BdExpSlRlNm8

then reboot
```
ls /sys/bus/hid/drivers/hid-generic
```

**Comment by juliancoleman** [comment]
add user to plugdev group again?

**Comment by terricain** [comment]
only have to do that once

**Comment by juliancoleman** [comment]
`ls /sys/bus/hid/drivers/hid-generic`

```
0003:046D:C537.0001  0003:046D:C537.0002  bind  module  new_id  uevent  unbind
```

**Comment by terricain** [comment]
ooh
that looks more promising

**Comment by terricain** [comment]
ls /sys/bus/hid/drivers/razerkbd

**Comment by juliancoleman** [comment]
Yesssss. Let's do this.

`ls /sys/bus/hid/drivers/razerkbd`

```
0003:1532:0224.0003  0003:1532:0224.0004  0003:1532:0224.0005  bind  module  new_id  uevent  unbind
```

**Comment by terricain** [comment]
ls /sys/bus/hid/drivers/razerkbd/0003:1532:0224.0005/

make sure the / is on the end

**Comment by juliancoleman** [comment]
`ls /sys/bus/hid/drivers/razerkbd/0003:1532:0224.0005`

```
country        firmware_version   matrix_custom_frame     matrix_effect_spectrum   power              version
device_mode    fn_toggle          matrix_effect_breath    matrix_effect_starlight  report_descriptor
device_serial  hidraw             matrix_effect_custom    matrix_effect_static     subsystem
device_type    input              matrix_effect_none      matrix_effect_wave       test
driver         matrix_brightness  matrix_effect_reactive  modalias                 uevent
```

**Comment by terricain** [comment]
```
sudo -i
cd /sys/bus/hid/drivers/razerkbd/0003:1532:0224.0005/
cat version
cat device_mode
cat device_serial
cat device_type
cat firmware_version
car matrix_brightness
```

**Comment by juliancoleman** [comment]
`cat version`

```
1.1.9
```

`cat device_mode`

```
0:0
```

`cat device_serial`

```
BY1711A34901954
```

`cat device_type`

```
Razer Blade (Late 2016)
```

`cat firmware_version`

```
v1.0#
```

`cat matrix_brightness`

```
255
```

**Comment by z3ntu** [comment]
Sure, that there is a hash after the firmware_version?

**Comment by juliancoleman** [comment]
here is a direct copy/paste from my terminal

```
julian# cat firmware_version 
v1.0#
```

here is the context

```
sudo -i
[sudo] password for julian:
julian# cd /sys/bus/hid/drivers/razerkbd/0003:1532:0224.0005
julian# cat version
1.1.9
julian# cat device_mode
0:0
julian# cat device_serial 
BY1711A34901954
julian# cat device_type
Razer Blade (Late 2016)
julian# cat firmware_version 
v1.0#
julian# cat matrix_brightness 
255
julian# 
```

**Comment by terricain** [comment]
you running somthing other than bash?

**Comment by juliancoleman** [comment]
`zsh`

**Comment by terricain** [comment]
Thats probably zsh objecting that it hasnt output'd a line feed '\n', mine noramlly spams '%' though

**Comment by juliancoleman** [comment]
huh... I can `vim` it out if that helps, or I can switch to `bash` and try it again

**Comment by terricain** [comment]
nah its fine, technically that value is for show, its never used anywhere :wink: at least the serial doesnt say 'Default String' lol like some halfbaked blades

**Comment by terricain** [comment]
ok back on topic, run as your user in a different terminal,

```
razer-service -s
razer-service -F
```
It should spam some stuff, paste it all in pastebin

**Comment by juliancoleman** [comment]
Sounds good!

https://pastebin.com/AF2gJJYK

**Comment by juliancoleman** [comment]
`razer-service -F` process never completed. I'm assuming it was just a debug watcher?

**Comment by terricain** [comment]
yeah it'll stay open for now

**Comment by juliancoleman** [comment]
Perfect. Great to know!

**Comment by terricain** [comment]
hmm, it seems possibly the first set of debs i gave you were bad, can you Ctrl+C the terminal window to stop the service, install razer-daemon from the last link i gave you, then run the -F command again, then pastebin

**Comment by juliancoleman** [comment]
logout or reboot required?

**Comment by juliancoleman** [comment]
never mind. Looks like it changed

**Comment by terricain** [comment]
nope not for that oen

**Comment by juliancoleman** [comment]
https://pastebin.com/WyUjrWRK

**Comment by juliancoleman** [comment]
Don't mind the `7.6.0` on the first line. That's my Node version

**Comment by terricain** [comment]
much better, (not for the nodejs though, javascript is the devil :wink:)

**Comment by terricain** [comment]
ok err I guess the easiest way to test the bulk quickly would be to grab polychromatic and try each effect (except ripple for now)

**Comment by terricain** [comment]
https://github.com/lah7/polychromatic#driver-installation

**Comment by juliancoleman** [comment]
I have polychromatic and razerCommander. I'll try them now!

**Comment by juliancoleman** [comment]
Dude, ripple totally works

wait...

Sorry, no it doesn't :(

**Comment by juliancoleman** [comment]
I'll pastebin the log

**Comment by juliancoleman** [comment]
https://pastebin.com/5gRYYYHE

I have the `ripple` in there anyhow.

**Comment by terricain** [comment]
any of it not work?

**Comment by juliancoleman** [comment]
Only ripple. It seemed to have given me the FPS profile where the number row was lit, WASD was lit, and the arrow keys were also lit. Individual key lighting doesn't work, but I think this is a known issue on razerCommander.

**Comment by juliancoleman** [comment]
Overall, this is friggin' lit

**Comment by terricain** [comment]
but ripple works?

**Comment by terricain** [comment]
ahh, one sec

**Comment by juliancoleman** [comment]
Ripple does not have the expected behavior. But activating it does light the number row, WASD keys, and the arrow keys

**Comment by terricain** [comment]
lol do they light up sort of like if ripple was working but not covering the whole keyboard?

**Comment by juliancoleman** [comment]
`onKeyDown` does nothing. Some keys have a static color. If you click those keys, the color does not change. If you click a key that doesn't have a static color, the key does not light.

**Comment by terricain** [comment]
ok set a static colour or wave/spectrum (anything but ripple)

run `python3` and enter this
```
from razer.client import DeviceManager
a = DeviceManager()
a.devices
# SHOULD PRINT OUT YOU HAVE 1 DEVICE
b = a.devices[0]
b.fx.advanced.matrix[0,1] = (255, 0, 0)
b.fx.advanced.matrix[1,1] = (0, 255, 0)
b.fx.advanced.matrix[2,1] = (0, 0, 255)
b.fx.advanced.matrix[3,1] = (255, 0, 255)
b.fx.advanced.matrix[4,1] = (255, 255, 0)
b.fx.advanced.matrix[5,1] = (0, 255, 255)
b.fx.advanced.draw()
```
make sense?

**Comment by juliancoleman** [comment]
Also, changing the color while Ripple is active effect, the results do not change. Currently, my function row is blue, the number row is this purplish-pink, the WASD is red, and the arrow keys are green. That's what Ripple is currently setting my layout to

**Comment by terricain** [comment]
change effect again, does it change thne?

**Comment by juliancoleman** [comment]
Yep! Makes sense. I know Python, too

**Comment by juliancoleman** [comment]
So, running the following in `python3` colored the `esc` key `red`, the `tilde/backtick` key `green`, the `tab` key looks like `blue` (I'm colorblind to blue, so it actually looks more purple than anything), the `caps` key is like a `pink`, the `shift` key is `yellow`, and the `ctrl` key is `cyan`. No other keys are lit, neither `onKeyDown` or `onKeyUp`

**Comment by terricain** [comment]
thats cool. Ok it means 2 things, 1 ripple is still buggy (im aware of that and theres a replacement for it lurking in a branch that needs a fair bit of work), and 2 custom colours work for the kb via the daemon service thing.

Ok last thing. Reboot, then open polychromatic / razer commander and see if they just work

**Comment by juliancoleman** [comment]
Sweet! If custom colors work, then that means it shan't be that hard for razerCommander to update with matrix support :smiley: lemme reboot. I'll be right back

**Comment by juliancoleman** [comment]
Okay, so I can confirm that the daemon started on boot and my device was found immediately. Polychromatic Controller finds my device successfully, and razerCommander also finds my device successfully.

**Comment by terricain** [comment]
I declare this device supported!, Will merge to master and roll out a proper release on the weekend

**Comment by Retic1337** [comment]
On Arch, Kernel 4.10.8-1
Installed using the following method
git clone --depth=1 https://github.com/terrycain/razer-drivers.git
cd razer-drivers
sudo make -s all install
Spectrum - Works
Wave - Works
Reactive - Works
Breath - Works
Ripple - Lights up WASD, number keys, and function keys. Edit: also arrow keys
Static - Turns keyboard solid green, no option to change color in Polychromatic Edit: after changing the color in ripple i now have the option to change tho color in static

**Comment by terricain** [comment]
Yeh ripple is buggy, I think its because the laptops without numpad dont like receiving the same RGB as keyboards that have numpad

**Comment by juliancoleman** [comment]
I dunno what happened, but I shut my lid, drove home from work, and rebooted when I got home. No devices found. I'll do some digging around. My preferences were saved, however, and my keyboard is lit up with the last one I was using.

**Comment by terricain** [comment]
hmm, reboot, and then see if you can replicate it.

**Comment by terricain** [comment]
Packages are building in launchpad, will be available soon

**Comment by juliancoleman** [comment]
Sounds good! Reboot did not solve the problem, but I'll get an eye on any apt updates! Thank you so much for all your hard work, man!

**Comment by juliancoleman** [comment]
updated and rebooted. Working again. Rebooted again for good measure. Still seems to be good! It may have been that I only updated the daemon, but I hadn't updated the other dependencies that you had posted from Google Drive. At any rate, all works! (aside from ripple, of course)

**Comment by terricain** [comment]
@juliancoleman 👍
