### ISSUE TITLE
Late 2016 individual key RGB not working

### ISSUE THREAD

**Issue by lezed1** [openrazer/openrazer#223]
It appears that individual keys cannot be set on the Razer Blade Stealth (Late 2016) - id `1532:0220`. If I set the custom colors in Windows and then attempt to set any individual color in Linux, the last custom Windows colors appear (it seems to go to the correct mode) but no key can be updated. Additionally, enabling Ripple mode has the same effect - the keyboard reverts to the last custom state from Windows (This was mentioned in [#214](https://github.com/terrycain/razer-drivers/issues/214#issuecomment-284703711)).

I have a packet capture from a Windows 10 VM. I've selected ~10 seconds of it so it's of manageable size. The colors are static (but through the Chroma Configurator so they are constantly sent). The top (fn, row id `0x0`) row is all color `0x333333`, row `0x1` set to `0x444444`, down to `0x888888`.
[row-by-row-packets-filtered.pcapng.zip](https://github.com/terrycain/razer-drivers/files/824315/row-by-row-packets-filtered.pcapng.zip)

Let me know if you want any more information or different captures. Also, I am running Arch Linux.

**Comment by terricain** [comment]
@lezed1 "Should" be fine

**Comment by lezed1** [comment]
@terrycain What do you mean?

**Comment by terricain** [comment]
I meant what you've done should be ok, haven't had a chance to look at it yet but seeing as you can see some rgb in the capture I reckon it'll be fine.

**Comment by terricain** [comment]
what distro you on?

**Comment by lezed1** [comment]
Arch

**Comment by terricain** [comment]
@z3ntu instructions on how to get branch `bug_lighting_0x0220` plz.

**Comment by lezed1** [comment]
I can build off that branch, sure

**Comment by terricain** [comment]
build, make sure that specific version of the driver is running and that the devices are bound to it.

normally just
```
make
sudo rmmod razerkbd
sudo rmmod razerkbd
sudo insmod ./driver/razerkbd.ko
```
(by this point the daemon will be unhappy as all the files in /sys/bus/hid/drivers/razerkbd/*/ are owned by root)
```
sudo chgrp plugdev /sys/bus/hid/drivers/razerkbd/0*/*
```

**Comment by z3ntu** [comment]
You probably will get some dependency issues because some packages needed are only available in the AUR -> install them first (AUR helper or whatever you like)
**Run the following commands:**
```
git clone https://aur.archlinux.org/razer-drivers-git.git
cd razer-drivers-git
curl https://gist.githubusercontent.com/z3ntu/28cb958ce9a778de0975e54c54b77318/raw/3149acc7d7e046adf33846f65d514d74d516b651/PKGBUILD.bug0220 -o PKGBUILD
makepkg -sr
sudo pacman -U python-razer-git-*.tar* razer-daemon-git-*.tar* razer-driver-dkms-git-*.tar*
```
If you need additional help, you can reach me on Telegram @z3ntu.

**Comment by lezed1** [comment]
This worked correctly on a0caf3993d37c4996a78a0d35cf6784811909a73.

**Comment by lezed1** [comment]
This actually works properly on master! This script (https://gist.github.com/terrycain/c51cb364529d9586514f8201d4ea9dd9) fixed the problem, not the changes on the bugfix branch.

**Comment by terricain** [comment]
@lezed1 :-)

**Comment by terricain** [comment]
Will get the changes into the daemon soonish then :smile:
