### ISSUE TITLE
Inconsistency in get_firmware_version

### ISSUE THREAD

**Issue by tildearrow** [openrazer/openrazer#228]
The razerkbd and razerfirefly drivers do not add a newline after the firmware version.
However, the other drivers do. Should all the drivers add a newline, or not?

**Comment by terricain** [comment]
Err I don't think it matters either way but let's go with newlines

**Comment by terricain** [comment]
New release is out, is in launchpad, will be out soon. Non Ubuntu packages will be out soon after.
