### ISSUE TITLE
Razer Deathadder 3500 (1532:0016) Support

### ISSUE THREAD

**Issue by theov3rc0mer** [openrazer/openrazer#231]
**Razer Deathadder 3500**

- ID `1532:0016`
- Model No. `RZ01-0015`
- Product No. `RZ01-00151400`

**lsusb -d 1532:0016 -v**

```
Bus 001 Device 002: ID 1532:0016 Razer USA, Ltd DeathAdder Mouse
Couldn't open device, some information will be missing
Device Descriptor:
  bLength                18
  bDescriptorType         1
  bcdUSB               2.00
  bDeviceClass            0 (Defined at Interface level)
  bDeviceSubClass         0 
  bDeviceProtocol         0 
  bMaxPacketSize0         8
  idVendor           0x1532 Razer USA, Ltd
  idProduct          0x0016 DeathAdder Mouse
  bcdDevice            1.00
  iManufacturer           1 
  iProduct                2 
  iSerial                 0 
  bNumConfigurations      1
  Configuration Descriptor:
    bLength                 9
    bDescriptorType         2
    wTotalLength           34
    bNumInterfaces          1
    bConfigurationValue     1
    iConfiguration          0 
    bmAttributes         0xa0
      (Bus Powered)
      Remote Wakeup
    MaxPower              100mA
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        0
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      1 Boot Interface Subclass
      bInterfaceProtocol      2 Mouse
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength      73
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x81  EP 1 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0008  1x 8 bytes
        bInterval               1

```

**ls -lah /dev/input/by-id/**

```
drwxr-xr-x 2 root root 100 Mar 13 23:10 .
drwxr-xr-x 4 root root 420 Mar 13 23:10 ..
lrwxrwxrwx 1 root root  10 Mar 13 23:10 usb-Razer_Razer_DeathAdder-event-mouse -> ../event13
lrwxrwxrwx 1 root root   9 Mar 13 23:10 usb-Razer_Razer_DeathAdder-mouse -> ../mouse1
```

![img1](https://cloud.githubusercontent.com/assets/19979868/23890778/9dc25e08-0893-11e7-9f5e-066f76193553.png)

![img2](https://cloud.githubusercontent.com/assets/19979868/23890781/9f594df8-0893-11e7-9810-8d90f2bc8155.png)

Tried to capture something with WS, it is my first time so tell me if I missed something. I tried to capture packets when changing sensivity (goes from 100 to 3500), but nothing is showed on wireshark.

Other captures are: logo light off and on, wheel light of and on, polling rate change (125-500-1000)
[DEathadder3500_pcaps.tar.gz](https://github.com/terrycain/razer-drivers/files/840588/DEathadder3500_pcaps.tar.gz)

**Comment by z3ntu** [comment]
Thanks for the captures and screenshots etc 👍

**Comment by terricain** [comment]
What distro are you running?

**Comment by terricain** [comment]
Mind trying to get the packet captures again, toggle the buttons a few times as well

**Comment by theov3rc0mer** [comment]
Linux Mint...I'll try tomorrow if I can get the captures

**Comment by theov3rc0mer** [comment]
Ok I did a clean install with a w7 virtualbox, so now I have new captures.
However when I change the sensivity of the mouse no packets are shown, tried for at least one hour without success.

Captures are: 
- scroll light off-on
- logo light off-on
- polling rate cycle
- buttons: right,left,wheel button, two side buttons.

If u can help me getting packets of sensivity change ill be grateful because otherwise I don't know how to do.

[RazerDA_Captures_new.tar.gz](https://github.com/terrycain/razer-drivers/files/852405/RazerDA_Captures_new.tar.gz)

**Comment by z3ntu** [comment]
(most likely) Synapse is basically another front-end for the Windows sensitivity settings so the mouse probably doesn't support changing the sensitivity in firmware.

**Comment by terricain** [comment]
Yeah sensitivity is a windows thing, how old is the deathadder? Either I'm not seeing the normal packets im expecting or they're not using the normal protocol

**Comment by z3ntu** [comment]
DeathAdder 3500 was released in Late 2009.

**Comment by theov3rc0mer** [comment]
Yes deathadder is quite old. I found [these](https://bues.ch/cms/hacking/razercfg) drivers that work well with my mouse, except for macros that are the main problem. 
On the page I linked I had the confirmation that old razer devices like mine use a different protocol.
So if u can add support for my mouse using some code from the other project maybe it will be easier, but if u say that implementation would take too much time and u prefer to work to support newer devices I understand you.

**Comment by terricain** [comment]
Ok good, that explains why I dont see what im after :wink:. Am definitely interested in getting it working though will prioritise more fancy devices :smile:.

**Comment by theov3rc0mer** [comment]
Thank you man! If you need further captures or testing I am here! Keep up the good work

**Comment by escobera** [comment]
I have a DeathAdder 3500 as well, would love to see it supported. Don't know if it helps, but this tool is able to config it:

https://github.com/mbuesch/razer

**Comment by z3ntu** [comment]
Yeah we know that tool but fresh packet captures from synapse would be best. (edit: [we apparently already have some for this mouse](https://github.com/terrycain/razer-drivers/issues/231#issuecomment-287542433) so don't mind this msg)

**Comment by NewtSoup** [comment]
I am running Ubuntu 16.04 and just installed these drivers but I get the message "No Device Found" and I have a Razer Death Adder 3.5G ( left handed edition )

**Comment by z3ntu** [comment]
@NewtSoup that's expected as the mouse isn't supported yet. You will have to wait unfortunately

**Comment by terricain** [comment]
Can one of you join telegram to help test, would be easier than me constantly spamming the issue with tests

**Comment by theov3rc0mer** [comment]
@terrycain i can

**Comment by z3ntu** [comment]
Please get yourself a telegram username and then message me @z3ntu so I can add you.

**EDIT:** We are now communicating with @theov3rc0mer over Telegram and trying to get stuff to work!

**Comment by terricain** [comment]
Have more changes ready whenever someone can test

**Comment by M00NBEAST** [comment]
I'm new to Linux, but I managed to get Polychromatic working. I have the DeathAdder 3500 and was wondering if I could use the drivers while you guys are testing them (and how I would install them).

**Comment by z3ntu** [comment]
Yes **please** test them :) What distro are you on (so I can send you instructions to install)?

**Comment by M00NBEAST** [comment]
Linux Mint 18, I believe (the latest Linux Mint)

**Comment by z3ntu** [comment]
[feature_deathadder3500.zip](https://github.com/terrycain/razer-drivers/files/1083001/feature_deathadder3500.zip)
Please install these debs and reboot. Then check if Polychromatic sees the device.

**Comment by Icylittlething** [comment]
I too am on Linux Mint 18.1. I installed all the debs with GDebi, and Polychromatic still doesn't recognize the deathadder 3500. If you want more info, just ask and I'll send you all I can

**Comment by z3ntu** [comment]
* Please post the output of `sudo dkms status razer_chroma_driver/1.0.0`
* And of `python3 -c "from razer.client import DeviceManager; a = DeviceManager(); print(a.devices)"`
* And did you reboot after installing?

**Comment by Icylittlething** [comment]
Yep, I did reboot a few times, but I still get "Device Not Recognized".
The output of `sudo dkms status razer_chroma_driver/1.0.0` was `razer_chroma_driver, 1.0.0, 4.4.0-53-generic, x86_64: installed`
As for the other one, I get:
`~ $ python3 -c "from razer.client import DeviceManager; a = DeviceManager();
\> print(a.devices)"
[]`
Hope I didn't mess it up and this helps

**Comment by z3ntu** [comment]
```
lsmod | grep razer
sudo modprobe razermouse
lsmod | grep razer
```
please

**Comment by Icylittlething** [comment]
http://imgur.com/4Ik7qEM

**Comment by z3ntu** [comment]
`ls -al /sys/bus/hid/drivers/razermouse/0*/`

**Comment by Icylittlething** [comment]
`ls: cannot access '/sys/bus/hid/drivers/razermouse/0*/': No such file or directory`

**Comment by z3ntu** [comment]
I'll send you new debs in a few minutes

**Comment by z3ntu** [comment]
[feature_deathadder3500_v2.zip](https://github.com/terrycain/razer-drivers/files/1083265/feature_deathadder3500_v2.zip)
Please install these and reboot.

**Comment by Icylittlething** [comment]
Ok, it's recognized now \o/
I can disable the lights so it seems it works. I'll test all the features I can, to see if something doesn't work but it seems fine

**Comment by Icylittlething** [comment]
It seems I can't change the DPI of the mouse, even though I can on the Razer Synapse, but the polling rate option and the lights options are there and it seems they work which is already really cool. Thanks for your work!

**Comment by terricain** [comment]
@Icylittlething Yeah its a work in progress

**Comment by Icylittlething** [comment]
Ok, but just getting rid of the lights is really really cool, so thanks for that ^^
If there's anything I can do to help, like testing stuff, I'm subscribed to this conversation so just ask

**Comment by z3ntu** [comment]
Thanks :)

**Comment by z3ntu** [comment]
If you want, you can join us in our Telegram chat. Message me @z3ntu if you are interested.

**Comment by DanielVoogsgerd** [comment]
Hello, I'm using this exact model as we're speaking. If you still need anybody to test some stuff, I'd like to help out.

**Comment by labuzm** [comment]
:+1:

**Comment by d0tfile** [comment]
@labuzm use [reactions](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments) next time, please.

**Comment by subterfugium** [comment]
This has needs testing. I'm running fedora and willing to help to get this integrated.

**Comment by subterfugium** [comment]
I ran:
```
sudo dnf install rpm-build rpmdevtools
rpmdev-setuptree
cd ~/rpmbuild/SPECS
curl https://pastebin.com/raw/hJmt1z54 -o openrazer.spec
spectool -g -R openrazer.spec
sudo dnf -y builddep openrazer.spec
rpmbuild -bb openrazer.spec
sudo dnf install ../RPMS/noarch/*.rpm
```
And I was able to use razerCommander to set polling rate to 1000Hz
```
otto@pc:~$ cat /sys/bus/hid/drivers/razermouse/0003\:1532\:0016.0002/poll_rate 
1000
```
Gonna try different apps when I can find some time.

**Comment by z3ntu** [comment]
also random bits in the branch that should be fixed (but I don't have the time right now)

https://github.com/openrazer/openrazer/compare/feature_deathadder3500?expand=1#diff-5ed59dfc81d91d7e54d03bde5888dd10R2142 double razer_init

https://github.com/openrazer/openrazer/compare/feature_deathadder3500?expand=1#diff-72915fff8b7f6a43f6fa4934e0b9e302R36 order by pid

python class probably has attributes that have been commonized

**Comment by errantspark** [comment]
16.04 with a 1532:0016 happy to help out with testing, @ me if something needs doing

**Comment by GrantM11235** [comment]
> also random bits in the branch that should be fixed (but I don't have the time right now)
> 
> https://github.com/openrazer/openrazer/compare/feature_deathadder3500?expand=1#diff-5ed59dfc81d91d7e54d03bde5888dd10R2142 double razer_init
> 
> https://github.com/openrazer/openrazer/compare/feature_deathadder3500?expand=1#diff-72915fff8b7f6a43f6fa4934e0b9e302R36 order by pid
> 
> python class probably has attributes that have been commonized

Here is a quick patch

```diff
From 47bb7b2ae0bf54037f407aae0311410836e98af9 Mon Sep 17 00:00:00 2001
From: Grant Miller <GrantM11235@gmail.com>
Date: Fri, 8 Feb 2019 17:14:25 -0600
Subject: [PATCH 1/2] Remove extra razer_mouse_init

---
 driver/razermouse_driver.c | 2 --
 1 file changed, 2 deletions(-)

diff --git a/driver/razermouse_driver.c b/driver/razermouse_driver.c
index ed37512..8d303cd 100644
--- a/driver/razermouse_driver.c
+++ b/driver/razermouse_driver.c
@@ -2136,8 +2136,6 @@ static int razer_mouse_probe(struct hid_device *hdev, const struct hid_device_id
         goto exit;
     }
 
-    razer_mouse_init(dev, intf, hdev);
-
     // Init data
     razer_mouse_init(dev, intf, hdev);
 
-- 
2.19.1


From 97f512a02e2758ce665559b311dbd73b7c234199 Mon Sep 17 00:00:00 2001
From: Grant Miller <GrantM11235@gmail.com>
Date: Fri, 8 Feb 2019 17:16:48 -0600
Subject: [PATCH 2/2] Sort by PID

---
 driver/razermouse_driver.h | 9 ++++-----
 1 file changed, 4 insertions(+), 5 deletions(-)

diff --git a/driver/razermouse_driver.h b/driver/razermouse_driver.h
index 969e80b..0bfd6ce 100644
--- a/driver/razermouse_driver.h
+++ b/driver/razermouse_driver.h
@@ -20,6 +20,10 @@
 #define USB_DEVICE_ID_RAZER_OROCHI_2011 0x0013
 #endif
 
+#ifndef USB_DEVICE_ID_RAZER_DEATHADDER_3500
+#define USB_DEVICE_ID_RAZER_DEATHADDER_3500 0x0016
+#endif
+
 #ifndef USB_DEVICE_ID_RAZER_ABYSSUS_1800
 #define USB_DEVICE_ID_RAZER_ABYSSUS_1800 0x0020
 #endif
@@ -32,11 +36,6 @@
 #define USB_DEVICE_ID_RAZER_MAMBA_2012_WIRELESS 0x0025
 #endif
 
-
-#ifndef USB_DEVICE_ID_RAZER_DEATHADDER_3500
-#define USB_DEVICE_ID_RAZER_DEATHADDER_3500 0x0016
-#endif
-
 #ifndef USB_DEVICE_ID_RAZER_IMPERATOR // 2012
 #define USB_DEVICE_ID_RAZER_IMPERATOR 0x002F
 #endif
-- 
2.19.1
```

**Comment by carmelosantana** [comment]
I would also be available for testing.

**Comment by joaolm** [comment]
My device has this ID, model and Product Number... but the name it's not Razer Deathadder 3500.... it's **Razer DeathAdder 3.5G**.

How can I test this?

**Comment by braiam** [comment]
@joaolm Probably the same device, different sensor. Mine is a DeathAdder essential. From the kernel perspective, they are all the same device. The product number of mine is RZ01-00151400, model RZ01-0015.

@z3ntu Is possible to just rebase the branch with the fixes you noted on your previous comment?

**Comment by braiam** [comment]
@z3ntu Is there any issue blocking this?

**Comment by JohnMaddison** [comment]
I'm also having a razer mouse with id 0x0016 would be nice if it could be supported. I tried to compile the feature_deathadder3500 branch but failed as i'm running a kernel 4.4 which is not compatible I think. tried repointing folder in cmakelists.txt but got code errors instead and gave up :(

Any updates on this? @z3ntu

**Comment by axel-dd** [comment]
I would also be available for testing. I have a Razer Deathadder 3.5G mouse with 0x0016.
![FJIMG_20190622_095014](https://user-images.githubusercontent.com/6698567/59961128-641ad080-94d3-11e9-9dba-b1daa03afba0.jpg)

**Comment by z3ntu** [comment]
Hi all, I've pushed some commits to the `feature_deathadder3500` branch which should make DPI work hopefully; but you have to set `450` , `900` or `1800` otherwise the driver will default to 3500 DPI. I'll try to think of some nice way to solve this but it will probably be a "set the actual DPI to whatever is closest to the ones being requested". Also only the DPi for the X axis will be used as that device doesn't have separate X/Y DPI.

**Comment by axel-dd** [comment]
Thx z3ntu, I have tested the changes.

What works:
- Mouse is correctly detected as DeathAdder 3500
- Lightning Features (wheel and logo) with RazerGenie
- Changing Polling Rate with RazerGenie

![DeepinScreenshot_20190715232842](https://user-images.githubusercontent.com/6698567/61251261-3a636b00-a75a-11e9-8ea1-59c9da8f017d.png)


What doesn't work:
- Changing DPI (DPI settings are missing in RazerGenie)

```
set_mouse_dpi.py --dpi_x 450
set_mouse_dpi.py --dpi_x 900
set_mouse_dpi.py --dpi_x 1800
```
commands have no effect...

```
cat /sys/bus/hid/drivers/razermouse/0003\:1532\:0016.0007/dpi 
1:1
```

**Comment by z3ntu** [comment]
Thanks!
DPI isn't yet exposed in the daemon, just in the driver.

I've pushed another commit to that branch which adds print statements to the DPI setting code. Can you run the set_mouse_dpi.py scripts again (with the new commit) and then give me the lines from dmesg (should contain "DA3500 DPI")?

**Comment by axel-dd** [comment]
set DPI does no work.
I have added some debug code to function razer_attr_write_mouse_dpi(...) to check the parameter values. May be this helps.

```
set_mouse_dpi.py --dpi_x=450
Done
set_mouse_dpi.py --dpi_x=900
Done
```

```
[    3.567137] razermouse 0003:1532:0016.0007: input,hidraw6: USB HID v1.11 Mouse [Razer Razer DeathAdder] on usb-0000:1d:00.3-3.3/input0
[  116.587584] razermouse: DPI requires 1 byte or 2 bytes
[  116.587586] count: 4
               buf: \xc2\xc2
[  172.658764] razermouse: DPI requires 1 byte or 2 bytes
[  172.658766] count: 4
               buf: \x84\x84
```

**Comment by z3ntu** [comment]
@axel-dd Thanks for testing. I've pushed another commit to the feature_deathadder3500 branch which should make this function call the other "internal" function at least :)

**Comment by axel-dd** [comment]
I changed the code in function razer_attr_write_mouse_dpi(...)  a little bit. Now all DPI states work.  

```
case USB_DEVICE_ID_RAZER_DEATHADDER_3500_OLD:
        if(count == 2 || count == 4) {
            dpi_x = (buf[0] << 8) | (buf[1] & 0xFF); // TODO make convenience function
            printk(KERN_WARNING "razermouse: DEBUG razer_attr_write_mouse_dpi() count: %zu / dpi_x: %u\n", count, dpi_x);
            deathadder3500_set_dpi(device, dpi_x);
        } else {
            printk(KERN_WARNING "razermouse: DPI requires 2 byte or 4 bytes\n");
        }
        return count;
```

```
[   52.843092] razermouse: DEBUG razer_attr_write_mouse_dpi() count: 4 / dpi_x: 1800
[   52.843093] DA3500 DPI: 708
[   52.843093] DA3500 DPI (internal): 2
[   59.722189] razermouse: DEBUG razer_attr_write_mouse_dpi() count: 4 / dpi_x: 3600
[   59.722191] DA3500 DPI: e10
[   59.722191] DA3500 DPI (internal): 1
[   66.929906] razermouse: DEBUG razer_attr_write_mouse_dpi() count: 4 / dpi_x: 450
[   66.929907] DA3500 DPI: 1c2
[   66.929908] DA3500 DPI (internal): 4
[   71.698053] razermouse: DEBUG razer_attr_write_mouse_dpi() count: 4 / dpi_x: 900
[   71.698055] DA3500 DPI: 384
[   71.698055] DA3500 DPI (internal): 3
[  382.346279] razermouse: DEBUG razer_attr_write_mouse_dpi() count: 2 / dpi_x: 900
[  382.346280] DA3500 DPI: 384
[  382.346281] DA3500 DPI (internal): 3
[  385.338065] razermouse: DEBUG razer_attr_write_mouse_dpi() count: 2 / dpi_x: 450
[  385.338066] DA3500 DPI: 1c2
[  385.338066] DA3500 DPI (internal): 4
[  389.850340] razermouse: DEBUG razer_attr_write_mouse_dpi() count: 2 / dpi_x: 1800
[  389.850341] DA3500 DPI: 708
[  389.850341] DA3500 DPI (internal): 2
[  396.194570] razermouse: DEBUG razer_attr_write_mouse_dpi() count: 2 / dpi_x: 3600
[  396.194572] DA3500 DPI: e10
[  396.194572] DA3500 DPI (internal): 1
```

**Comment by fvguilherme** [comment]
> I changed the code in function razer_attr_write_mouse_dpi(...) a little bit. Now all DPI states work.
> 
> ```
> case USB_DEVICE_ID_RAZER_DEATHADDER_3500_OLD:
>         if(count == 2 || count == 4) {
>             dpi_x = (buf[0] << 8) | (buf[1] & 0xFF); // TODO make convenience function
>             printk(KERN_WARNING "razermouse: DEBUG razer_attr_write_mouse_dpi() count: %zu / dpi_x: %u\n", count, dpi_x);
>             deathadder3500_set_dpi(device, dpi_x);
>         } else {
>             printk(KERN_WARNING "razermouse: DPI requires 2 byte or 4 bytes\n");
>         }
>         return count;
> ```
> 
> ```
> [   52.843092] razermouse: DEBUG razer_attr_write_mouse_dpi() count: 4 / dpi_x: 1800
> [   52.843093] DA3500 DPI: 708
> [   52.843093] DA3500 DPI (internal): 2
> [   59.722189] razermouse: DEBUG razer_attr_write_mouse_dpi() count: 4 / dpi_x: 3600
> [   59.722191] DA3500 DPI: e10
> [   59.722191] DA3500 DPI (internal): 1
> [   66.929906] razermouse: DEBUG razer_attr_write_mouse_dpi() count: 4 / dpi_x: 450
> [   66.929907] DA3500 DPI: 1c2
> [   66.929908] DA3500 DPI (internal): 4
> [   71.698053] razermouse: DEBUG razer_attr_write_mouse_dpi() count: 4 / dpi_x: 900
> [   71.698055] DA3500 DPI: 384
> [   71.698055] DA3500 DPI (internal): 3
> [  382.346279] razermouse: DEBUG razer_attr_write_mouse_dpi() count: 2 / dpi_x: 900
> [  382.346280] DA3500 DPI: 384
> [  382.346281] DA3500 DPI (internal): 3
> [  385.338065] razermouse: DEBUG razer_attr_write_mouse_dpi() count: 2 / dpi_x: 450
> [  385.338066] DA3500 DPI: 1c2
> [  385.338066] DA3500 DPI (internal): 4
> [  389.850340] razermouse: DEBUG razer_attr_write_mouse_dpi() count: 2 / dpi_x: 1800
> [  389.850341] DA3500 DPI: 708
> [  389.850341] DA3500 DPI (internal): 2
> [  396.194570] razermouse: DEBUG razer_attr_write_mouse_dpi() count: 2 / dpi_x: 3600
> [  396.194572] DA3500 DPI: e10
> [  396.194572] DA3500 DPI (internal): 1
> ```

Is possible to change it on the GUI? Do you have tested on which application? RazerGenie? Polychromatic?

**Comment by axel-dd** [comment]
I tested the changes on feature_deathadder3500 commit 0978efc with RazerGenie GUI branch da3.5g. Everything works. I think the other GUI projects need some changes.

**Comment by fvguilherme** [comment]
> I tested the changes on feature_deathadder3500 commit [0978efc](https://github.com/openrazer/openrazer/commit/0978efc01557aea88e852ee72c046b063266925d) with RazerGenie GUI branch da3.5g. Everything works. I think the other GUI projects need some changes.

I can confirm this. I am using Arch and I have done this:

1 - Install `openrazer-meta-git` (`yay -Syu openrazer-meta-git`), remembering to edit PKGBUILD and change **source line** to `source=("git+https://github.com/openrazer/openrazer.git#branch=feature_deathadder3500")` and selecting only `-git` packages when asked (I remember that a time ago regular packages seems doesn't works, I can't confirm);
2 - Run both `sudo gpasswd -a $USER plugdev` and `systemctl --user enable --now openrazer-daemon.service` commands;
3 - Install `razergenie-git`(`yay -Syu razergenie-git`), remembering to edit PKGBUILD and change **source line** to `source=("git+https://github.com/z3ntu/RazerGenie.git#branch=da3.5g")`;
4 - Reboot.

now all options are functional. 

Thanks, @axel-dd  and @z3ntu.

**Comment by z3ntu** [comment]
Awesome! Thanks for testing!

I've cleaned up the commits a bit, and renamed the device to "DeathAdder 3.5G" in the codebase as that seems to be the more official name and to avoid naming conflicts with the "DeathAdder 3500" that's  newer and already supported.

Can you please test one last time, to verify I've not broken anything?

**Comment by fvguilherme** [comment]
Yes, It's working very well! But, two thing: even though the DPI is set to 450, the RazerGenie shows 3500; and the interface still shows "DeathAdder 3500" and "No image". Not a big deal.

I just recompiled the `-git`.

![image](https://user-images.githubusercontent.com/48185753/61742567-caf90700-ad69-11e9-8f02-604cd6dd6303.png)

**Comment by z3ntu** [comment]
Did you reboot (after installing the new package version)?

**Comment by fvguilherme** [comment]
Yes, I did.

edit: It should show "DeathAdder 3.5G" and the image of it?

**Comment by z3ntu** [comment]
Weird. Can you check if (in the pkgver) is 0b0ce04b626f215402c499ebbe224e0575b5635b is used for RazerGenie and commit 22e4b75bf89bc3883c755226469a0a3e284b14e6 for OpenRazer?

It should look like this if you ignore the DeathAdder Chroma:
![image](https://user-images.githubusercontent.com/3768500/61791150-7ad97d80-ae19-11e9-9ee2-89e932a497be.png)

**Comment by axel-dd** [comment]
head on both branches look like this ...
![DeepinScreenshot_20190724205510](https://user-images.githubusercontent.com/6698567/61820634-ae39fd80-ae55-11e9-9d6f-031f81f9c60f.png)

**Comment by fvguilherme** [comment]
ok. It's working now after I remove and reinstall all again. Thanks.
 
![image](https://user-images.githubusercontent.com/48185753/61968707-10f2dc80-afaf-11e9-87f8-afed40119e9c.png)

**Comment by fvguilherme** [comment]
I am getting this after uninstall `-git` packages and install both `openrazer-meta` and `razergenie` from AUR. I get the same error with Flatpak version of RazerGenie.
```
Translation loaded: false
"PM001381463801"
"Razer DeathAdder 3.5G"
DeviceListWidget: Received errored signal!
DeviceListWidget: Reason: "Image download disabled"
DeviceListWidget: Long reason: "Image downloading is disabled. Visit the preferences to enable it."
"mouse"
CURRENT LOCATION:  "1"
CURRENT LOCATION:  "2"
currDPI: (3500)
RazerGenie: Skipping dpi because return value of getDPI() is wrong. Probably the broken fake driver.
maxDPI: 3500
```

**Comment by z3ntu** [comment]
@fvguilherme You have to use the -git version of RazerGenie until a new release is made for that.

**Comment by CarlosUvaSilva** [comment]
how do I install the -git version in Ubuntu? I followed the instruction for the "normal" installation but my razer is detected without picture and I can't change the DPI

**Comment by z3ntu** [comment]
You have to compile that yourself, I don't have daily builds set up for RazerGenie. Instructions are in the RazerGenie readme: https://github.com/z3ntu/RazerGenie#how-to-compile (git clone and cd into the repo first of course)

**Comment by CarlosUvaSilva** [comment]
@z3ntu thank got it working! Is it possible to set a DPI value outside the options available in the dropdown? maybe some magic command or better yet would be to actually turn the dropdown to a slider like the one in razer synapse

**Comment by z3ntu** [comment]
@CarlosUvaSilva I doubt that Synapse can produce more DPI states than the 4 shown in RazerGenie. I would've liked to show the DPI on that device as a slider as well but unfortunately the QSlider widget from Qt doesn't have the functionality needed arbitrary "snap positions" so using a combo box was easier.
