### ISSUE TITLE
Odd behavior on Arch: Deathadder chroma random movement and random stutter

### ISSUE THREAD

**Issue by krutoileshii** [openrazer/openrazer#234]
Swapped my install from fedora to Arch (4.10.3-1-ARCH) got the drivers installed and all. however, lately the mouse was behaving oddly such as:

1 - Random mouse movement (on it's own, hand not even on the mouse)
2 - stutters occasionally

DPI is currently set to 3200@1000 (seems to help a bit)
stutters more when around links or haven't been moved.
likely a libinput issue. not sure where to go to diagnose.

below are the messages from when it happens.

```
[    2.379278] razermouse: loading out-of-tree module taints kernel.
[    2.597206] razermouse 0003:1532:0043.0003: input,hidraw1: USB HID v1.11 Keyboard [Razer Razer DeathAdder Chroma] on usb-0000:00:14.0-13/input1
[    2.597235] razermouse 0003:1532:0043.0002: input,hidraw2: USB HID v1.11 Mouse [Razer Razer DeathAdder Chroma] on usb-0000:00:14.0-13/input0
[    2.657242] razermouse 0003:1532:0043.0004: input,hidraw3: USB HID v1.11 Keyboard [Razer Razer DeathAdder Chroma] on usb-0000:00:14.0-13/input2
[    3.107351] razerkbd 0003:1532:0214.0007: input,hidraw4: USB HID v1.11 Mouse [Razer Razer BlackWidow Ultimate 2016] on usb-0000:00:14.0-14/input2
[    3.163885] razerkbd 0003:1532:0214.0005: input,hidraw5: USB HID v1.11 Keyboard [Razer Razer BlackWidow Ultimate 2016] on usb-0000:00:14.0-14/input0
[    3.267140] razerkbd 0003:1532:0214.0006: input,hidraw6: USB HID v1.11 Keyboard [Razer Razer BlackWidow Ultimate 2016] on usb-0000:00:14.0-14/input1
[  259.731886] razer driver: Device data transfer failed.
[  259.740797] razer driver: Invalid USB repsonse. USB Report length: -32
[  259.740799] razermouse: Invalid Report Length. Start Marker: 00 id: 00 Num Params: 00 Reserved: 00 Command: 00 Params: 00000000000000000000000000000000 .
[  259.742228] razer driver: Device data transfer failed.
[  259.743665] razer driver: Device data transfer failed.
[  259.745085] razer driver: Device data transfer failed.
[  259.746563] razermouse: Response doesnt match request. Start Marker: 02 id: ff Num Params: 03 Reserved: 03 Command: 03 Params: 0104ff00000000000000000000000000 .
[  259.746583] razer driver: Device data transfer failed.
[  259.748011] razermouse: Response doesnt match request. Start Marker: 02 id: ff Num Params: 03 Reserved: 03 Command: 03 Params: 0104ff00000000000000000000000000 .
[  259.748055] razer driver: Device data transfer failed.
[  259.749466] razermouse: Response doesnt match request. Start Marker: 02 id: ff Num Params: 03 Reserved: 03 Command: 03 Params: 0104ff00000000000000000000000000 .
[  259.749531] razer driver: Device data transfer failed.
[  259.750902] razermouse: Response doesnt match request. Start Marker: 02 id: ff Num Params: 03 Reserved: 03 Command: 03 Params: 0104ff00000000000000000000000000 .
```

Below is the only error in syslog:

```
[   228.376] (EE) libinput: Razer Razer DeathAdder Chroma: Failed to create a device for /dev/input/mouse0
[   228.376] (EE) PreInit returned 2 for "Razer Razer DeathAdder Chroma"
[   228.480] (EE) libinput: Razer Razer BlackWidow Ultimate 2016: Failed to create a device for /dev/input/mouse1
[   228.480] (EE) PreInit returned 2 for "Razer Razer BlackWidow Ultimate 2016"


```

here is the something odd when you run: lsusb -vd 1532:0043 |grep bInterval
it outputs a set of 3 values for some reason.
```
Couldn't open device, some information will be missing
        bInterval               1
        bInterval               8
        bInterval               8

```

**Comment by terricain** [comment]
Very weird
To rule out an Arch issue, have you tried it on another linux distro?

**Comment by krutoileshii** [comment]
Not yet. But I will as soon as I get home. Have a laptop with fedora sitting here as well as as raspbian

**Comment by krutoileshii** [comment]
Tried on my fedora laptop, so far no issues. What could be causing it on arch?

**Comment by z3ntu** [comment]
What kernel does your Fedora install have (version)?

**Comment by krutoileshii** [comment]
Fedora is on 4.9.11-200.fc25.x86_64.
also, just updated to 4.10.4-1-ARCH and it still seems to persist but at a lesser extent. going to use it for a bit more to see if it gets worse. Does still occasionally move on it's own. 

One more note: the errors above from arch now don't show up in dmesg output.
but the xorg log contains these:
```
[   349.850] (EE) libinput: Razer Razer DeathAdder Chroma: Failed to create a device for /dev/input/mouse0
[   349.850] (EE) PreInit returned 2 for "Razer Razer DeathAdder Chroma"
.............
[   349.900] (EE) libinput: Razer Razer BlackWidow Ultimate 2016: Failed to create a device for /dev/input/mouse1
[   349.900] (EE) PreInit returned 2 for "Razer Razer BlackWidow Ultimate 2016"

```

journalctrl doesn't show anything outside of polychromatic trying to set resolution past max (errors out and wraps to lower value)

What else would help diagnose this?

**Comment by z3ntu** [comment]
So you were running 4.9.x on Arch and had that issue? I hoped it was the 4.10 kernel upgrade...

**Comment by krutoileshii** [comment]
No 4.9 is good 4.10 is bad. I have 4.9 on fedora install I tested on to see if it's arch specific

**Comment by terricain** [comment]
So its not an issue with the driver :smiley: :+1:

**Comment by krutoileshii** [comment]
Doesn't look like it so far but could be for a newer kernel  Some setting maybe

**Comment by krutoileshii** [comment]
Also I meant 4.10

**Comment by krutoileshii** [comment]
Should I text LTS kernel on arch just to make sure? It's 4.9.17

**Comment by z3ntu** [comment]
Yeah that would be good.

**Comment by krutoileshii** [comment]
LTS kernel wouldn't even boot.... I'll give it another go maybe on Sunday.

**Comment by krutoileshii** [comment]
Still not sure what's causing this at the moment. Seems to be semi-random which makes it a bit hard to catch the issue.

**Comment by krutoileshii** [comment]
Installed latest libinput will report back the results soon

**Comment by krutoileshii** [comment]
Ok, still persists. i have a feeling this has to do with the kernel or libinput as it stutters now as well especially in non-full-screen applications. have a video of it as well.

**Comment by krutoileshii** [comment]
Testing latest kernel. Will report in a bit

**Comment by krutoileshii** [comment]
I think i found a solution to this one... in a form of a $9 mouse pad which is odd as it wasn't doing this before that on fedora. Can you please close this one for now.

**Comment by tildearrow** [comment]
That means your mouse's lens could be getting dirty. Try cleaning the lens up, then try again?

**Comment by krutoileshii** [comment]
Just did. So far so good. Thanks

**Comment by z3ntu** [comment]
😀
