### ISSUE TITLE
Compiling on Windows

### ISSUE THREAD

**Issue by ven3k** [openrazer/openrazer#238]
Is there any way of compiling this project under Windows?
I tried using `make` on CygWin, but it was throwing a lot of errors.

**Comment by z3ntu** [comment]
Take a look at #189 ; and generally Linux and Windows are quite different underneath and that project is for Linux.

**Comment by ven3k** [comment]
I understand differences between Win and Linux, but thought "maybe it's crossplatform"?'
Thanks for referencing it, I hope it'll work

**Comment by terricain** [comment]
is sorta cross platform, @rsandoz has make awesome headway into using it well on windows
