### ISSUE TITLE
razer_mount failed with exit code 1

### ISSUE THREAD

**Issue by domsch1988** [openrazer/openrazer#243]
Having a Problem to get this working under Arch 4.10
I installed razer-driver-meta and all dependencys from AUR. On Reboot i get some systemd-modules failing.

The relevant parts from journalctl:
Mär 30 18:33:40 Arch-Desktop razer_mount[339]: Driver razerkbd
Mär 30 18:33:40 Arch-Desktop razer_mount[341]: Device_ID 0003:1532:0209.0003
Mär 30 18:33:40 Arch-Desktop razer_mount[345]: Modprobing razerkbd
Mär 30 18:33:40 Arch-Desktop razer_mount[340]: Driver razerkbd
Mär 30 18:33:40 Arch-Desktop razer_mount[348]: Driver razerkbd
Mär 30 18:33:40 Arch-Desktop systemd-udevd[206]: Process 'razer_mount razerkbd 0003:1532:0209.0003' failed with exit code 1.
Mär 30 18:33:40 Arch-Desktop razer_mount[352]: Device_ID 0003:1532:0209.0001
Mär 30 18:33:40 Arch-Desktop razer_mount[354]: Device_ID 0003:1532:0209.0002
Mär 30 18:33:40 Arch-Desktop razer_mount[356]: Modprobing razerkbd
Mär 30 18:33:40 Arch-Desktop razer_mount[357]: Modprobing razerkbd
Mär 30 18:33:40 Arch-Desktop systemd-udevd[208]: Process 'razer_mount razerkbd 0003:1532:0209.0001' failed with exit code 1.
Mär 30 18:33:40 Arch-Desktop systemd-udevd[217]: Process 'razer_mount razerkbd 0003:1532:0209.0002' failed with exit code 1.

razercommander says no device connected. Any Idea what went wrong?

**Comment by z3ntu** [comment]
Please post the output of the following commands

```
sudo modprobe razerkbd
lsmod | grep razer
sudo dkms status
```

**Comment by domsch1988** [comment]
This was fast! Thanks!
looks like a problem... modprobe says:

modprobe: FATAL: Module razerkbd not found in directory /lib/modules/4.10.6-1-ARCH

The other two produce no output.

**Comment by z3ntu** [comment]
`pacman -Q razer-driver-dkms`

:)

**Comment by domsch1988** [comment]
Package not found.
Is the driver available through the official repository?

**Comment by z3ntu** [comment]
No it's from the AUR but should be auto-installed when you installed `razer-driver-meta`... Try to reinstall the meta package or just install `razer-driver-dkms`, `razer-daemon` and `python-razer`

**Comment by domsch1988** [comment]
Ok, i installed it manually. Going to reboot and report back.

**Comment by z3ntu** [comment]
👍

**Comment by domsch1988** [comment]
Ok, pacman can now find the driver. Modprobe still can not. Do i have to move it manually to /lib/modules/?

**Comment by z3ntu** [comment]
No don't move anything manually :)

`sudo dkms status` please

**Comment by domsch1988** [comment]
Still nothing

**Comment by z3ntu** [comment]
Do you have your kernel headers installed (eg `linux-headers` for the stock `linux` kernel)?

Try `sudo dkms install razer_chroma_driver/1.0.0`

**Comment by domsch1988** [comment]
Jesus... *HeadmeetsDesk*
linux-headers it was ofc
Easy to miss "small" things on a fresh Arch Installation.

You have been of tremendous help sir! I thank you much!

**Comment by z3ntu** [comment]
No problem. (I actually added a post-install message to remind people but no problem 🙂)
