### ISSUE TITLE
Question: Abyssus V2

### ISSUE THREAD

**Issue by borgdylan** [openrazer/openrazer#245]
I am looking to buy the Blackwidow Chroma V2 from razer and they are giving away a free Abyssus V2 with it. I do know that the keyboard is supported but what about the Abyssus V2? If no what should I do once I get the mouse so as to provide the necessary technical data for it to get supported as well?

**Comment by z3ntu** [comment]
That's my template of what we need basically for new devices:

Please post the output of
`lsusb -d 1532:VID -v`
and
`ls -lah /dev/input/by-id/`
and read [this on how to get packet captures](https://github.com/terrycain/razer-drivers/wiki/Reverse-Engineering-USB-Protocol). Also screenshots of all available options on Razer Synapse are needed.

**Comment by borgdylan** [comment]
I ended up buying the deathadder elite instead as buying directly from razer turned out to be too complicated shipping wise. That means I did not get an Abyssus.

**Comment by z3ntu** [comment]
Yep, that's already supported. :)

**Comment by borgdylan** [comment]
Yes, it's working fine for me.
