### ISSUE TITLE
daemon not responding CENTOS 7

### ISSUE THREAD

**Issue by editRT** [openrazer/openrazer#248]
I'm trying to install the driver on Centos 7, 
my device is Tartarus Chroma, 

I got this error:
```
Importing device logic, waiting for daemon
ERROR: the daemon is not responding!
Try running `killall razer-service && razer-service` or rebooting. If this doesn't work, please fill an issue!
```

if I run razer-service i get this:

```
SyntaxError: Missing parentheses in call to 'print'
[davinci@dhcppc4 razercommander]$  razer-service
Traceback (most recent call last):
  File "/usr/bin/razer-service", line 9, in <module>
    from razer_daemon.daemon import daemonize
  File "/usr/lib/python3.4/site-packages/razer_daemon/daemon.py", line 20, in <module>
    import gi
  File "/usr/lib/python3.4/site-packages/gi/__init__.py", line 39
    print url
            ^
SyntaxError: Missing parentheses in call to 'print'
```

I'm new to linux, 
I've found no solution yet, 
can someone please help, 
thanks, 
Francesco

**Comment by z3ntu** [comment]
This project needs Python 3 which is not available on CentOS 7. If you don't really need CentOS for anything I would suggest you using basically any other distro than CentOS 😉

**Comment by terricain** [comment]
Worst case you can use software collections to get python3 but they are major pita, to the point where I wont "support" the use of them (aka you'll be on your own). I know full well they'll run daemon fine, its just the hassle of running stuff in scl.

**Comment by z3ntu** [comment]
Sorry, but the daemon doesn't support Python 2 and needs Python 3.
