### ISSUE TITLE
set keyboard brightness to 0% when display sleeps; restore brightness to previous level when display wakes

### ISSUE THREAD

**Issue by cphuntington97** [openrazer/openrazer#252]
This functionality exists on Windows and I would like it to exist on Linux. If it is not currently possible, I would like to request it as a feature.

**Comment by lah7** [comment]
This kind of already exists, but is based on the screensaver state (if it supports the Freedesktop spec, like GNOME, MATE and I think LXDE does too). This could just be the lock screen on some desktop environments, depends which one you're using.

So for me, under MATE - if I leave my computer idle long enough so the screensaver activates (and screen goes off), the devices go "off" until the system is unlocked again.

**Comment by terricain** [comment]
It works for all the standard desktop environments

**Comment by z3ntu** [comment]
I can add that it also works with KDE perfectly.

**Comment by cphuntington97** [comment]
Any advice for getting this to work in Enlightenment 21.5?

**Comment by terricain** [comment]
find out what does your screensaver would be a start

**Comment by cphuntington97** [comment]
Can the brightness be controlled from the command line?

**Comment by simotek** [comment]
Enlightenment doesn't use a screensaver, it controls the backlight itself. Do you have a link to the freedesktop spec you are using? we can atleast create a feature request bug for enlightenment to implement the right standard when it puts the display to sleep / wakes up.

**Comment by terricain** [comment]
Does it emit any dbus events when it changes backlight?

**Comment by simotek** [comment]
Not currently, it just writes directly to the back light device. If all the common screensavers and some of the other DE's are using a standard to notify other applications / devices of this then it would be reasonable to get enlightenment to also do this.

**Comment by terricain** [comment]
@simotek org.freedesktop.ScreenSaver
Is the main one that has a getActive method i think

**Comment by z3ntu** [comment]
Closing as it's not our fault. Feel free to file a bug report for Enlightenment or provide us another D-Bus path Enlightenment is using.
