### ISSUE TITLE
Razer Ornata not being recognised on Arch!

### ISSUE THREAD

**Issue by ian-thornsburg** [openrazer/openrazer#254]

**Comment by z3ntu** [comment]
Please run the following commands and send the output here.
```
sudo dkms install razer_chroma_driver/1.0.0
groups
```

And please for the next issues you are reporting somewhere include at least some information without getting asked specifically for it 😉

**Comment by ian-thornsburg** [comment]
This just appeared when I typed in the first one:
```
Your kernel headers for kernel 4.10.8-1-ARCH cannot be found at 
Error! echo
Your kernel headers for kernel 4.10.8-1-ARCH cannot be found at
/usr/lib/modules/4.10.8-1-ARCH/build or /usr/lib/modules/4.10.8-1-ARCH/source.

```

**Comment by z3ntu** [comment]
Yep you have to install the kernel headers for dkms. Probably `linux-headers` for you.

**Comment by ian-thornsburg** [comment]
Thanks! This is my first time using Arch!

**Comment by z3ntu** [comment]
Yes, dkms is a bit confusing as it has no hard dependencies on the kernel headers because you can install multiple kernels which need their own header package. The first line in https://wiki.archlinux.org/index.php/Dynamic_Kernel_Module_Support#Installation tells you *a bit* about it.

**Comment by ian-thornsburg** [comment]
I'm still getting the same error after installing it and restarting my computer! Any idea why?

**Comment by z3ntu** [comment]
`uname -a`
`pacman -Q linux linux-headers`

**Comment by ian-thornsburg** [comment]
Thx

**Comment by z3ntu** [comment]
So it's working now?

**Comment by ian-thornsburg** [comment]
Yeah perfectly I had 4.8 for Linux and 4.10 for headers! lol

**Comment by z3ntu** [comment]
That's kinda what is meant by https://wiki.archlinux.org/index.php/System_maintenance#Partial_upgrades_are_unsupported 😄

**Comment by z3ntu** [comment]
But great to hear that it's working now!

**Comment by ian-thornsburg** [comment]
Yeah thanks A TON!
