### ISSUE TITLE
Macro recording doesn't respect keyboard layout

### ISSUE THREAD

**Issue by simonvpe** [openrazer/openrazer#255]
Hi! I want to start out by saying thank you for this awesome piece of open source software.

I have a problem with macro recording. If i do the following steps:
Press (fn)+(m)
Press (m1)
Type abcdefgh
Press (fn)+(m)
Press (m1) => anihdyuj

I use dvorak keybindings but anihdyuj in qwerty does not map to abcdefgh dvorak so I'm not sure what's at fault here.

**Comment by z3ntu** [comment]
See #200 . And we are working on it.
