### ISSUE TITLE
Razer Naga 2014 lighting not working

### ISSUE THREAD

**Issue by kdb424** [openrazer/openrazer#256]
https://github.com/lah7/polychromatic/issues/77
Continuing the issue raised here upstream to the driver. Lighting unable to change at all even with manual driver access. If you need any other details not listed in that issue, please let me know. I'll also test my mouse in a Windows VM to see if it is possibly my mouse itself.

**Comment by z3ntu** [comment]
Anything in dmesg that comes from `razermouse`? Otherwise probably Synapse packet captures are needed (except it's a really stupid error - @terrycain ? 😉 )

**Comment by kdb424** [comment]
https://pastebin.com/Su5tdwZ9
Logs there from dmesg and all listed commands on troubleshooting page. I'll look into packet captures as needed.

EDIT: Started the wireshark environment to get things set up in case that needed to be done, and turns out that the lighting doesn't work on my mouse at all now even when controlling it through the synapse app. It's stuck completely off, which sounds like a mouse problem, though it didn't used to be like that last I checked. Could have a mouse issue, though regardless would like to get the correct commands that should work for mouse lighting to ensure that polychromatic has that. I'll keep looking into it, and see if there is a way to factory reset the mouse to see if a driver or something I did glitched it out.

**Comment by z3ntu** [comment]
Any update on the issue?

**Comment by kdb424** [comment]
I haven't gotten to get the lights on even in a WIndows machine. It worked before I started playing with this driver, and no longer does. Don't know if it was bad timing, or corrupted something somehow, though I doubt that's easily possible. I guess my mouse won't be of any help unfortunately.

**Comment by z3ntu** [comment]
I'll close this then as right now nothing is confirmed 😉
