### ISSUE TITLE
Nostromo problems on Manjaro

### ISSUE THREAD

**Issue by prispewnic** [openrazer/openrazer#259]
Hello. Not long ago, there was appeared support for the Razer Nostromo. I installed the latest version of the packages : python-razer 1.1.11-1 ; razer-daemon 1.1.11-1 and razer-driver-dkms 1.1.11-1, from AUR. Installation was successful. After that, I installed the razerCommander and Polychromatic, but all I see in the settings is the brightness slider and not one button on the keypad doesn't work, except scroll.

In the xev output, all that I see is a reaction to the scroll wheel. On all other buttons, there are no any reactions.

So, how can I remap nostromo keys and how can I get keystrokes from the xev? Thanks!

My **DKMS status**
razer_chroma_driver, 1.0.0, 4.4.63-1-MANJARO, x86_64: installed
razer_chroma_driver, 1.0.0, 4.9.20-1-rt16-MANJARO, x86_64: installed
razer_chroma_driver, 1.0.0, 4.9.24-1-MANJARO, x86_64: installed

The output of **ls -al /sys/bus/hid/drivers/razer*/0*/**
'/sys/bus/hid/drivers/razerkbd/0003:1532:0111.0005/':
итого 0
drwxr-xr-x 5 root plugdev    0 апр 24 12:25 .
drwxr-xr-x 5 root root       0 апр 24  2017 ..
-r--r--r-- 1 root plugdev 4096 апр 24 12:25 country
lrwxrwxrwx 1 root plugdev    0 апр 24 12:25 driver -> ../../../../../../../../bus/hid/drivers/razerkbd
drwxr-xr-x 3 root plugdev    0 апр 24 12:25 hidraw
drwxr-xr-x 3 root plugdev    0 апр 24 12:25 input
-rw-rw---- 1 root plugdev 4096 апр 24 12:25 key_alt_f4
-rw-rw---- 1 root plugdev 4096 апр 24 12:25 key_alt_tab
-rw-rw---- 1 root plugdev 4096 апр 24 12:25 key_super
-r--r--r-- 1 root plugdev 4096 апр 24 12:25 modalias
drwxr-xr-x 2 root plugdev    0 апр 24 12:25 power
-r--r--r-- 1 root plugdev 4096 апр 24 12:25 report_descriptor
lrwxrwxrwx 1 root plugdev    0 апр 24 12:25 subsystem -> ../../../../../../../../bus/hid
-rw-r--r-- 1 root plugdev 4096 апр 24 12:25 uevent

'/sys/bus/hid/drivers/razerkbd/0003:1532:0111.0007/':
итого 0
drwxr-xr-x 5 root plugdev    0 апр 24 12:25 .
drwxr-xr-x 5 root root       0 апр 24  2017 ..
-r--r--r-- 1 root plugdev 4096 апр 24 12:25 country
-rw-rw---- 1 root plugdev 4096 апр 24 12:25 device_mode
-r--r----- 1 root plugdev 4096 апр 24 12:25 device_serial
-r--r----- 1 root plugdev 4096 апр 24 12:25 device_type
lrwxrwxrwx 1 root plugdev    0 апр 24 12:25 driver -> ../../../../../../../../bus/hid/drivers/razerkbd
-r--r----- 1 root plugdev 4096 апр 24 12:25 firmware_version
drwxr-xr-x 3 root plugdev    0 апр 24 12:25 hidraw
drwxr-xr-x 3 root plugdev    0 апр 24 12:25 input
-rw-rw---- 1 root plugdev 4096 апр 24 12:25 matrix_brightness
-r--r--r-- 1 root plugdev 4096 апр 24 12:25 modalias
drwxr-xr-x 2 root plugdev    0 апр 24 12:25 power
-rw-rw---- 1 root plugdev 4096 апр 24 12:25 profile_led_blue
-rw-rw---- 1 root plugdev 4096 апр 24 12:25 profile_led_green
-rw-rw---- 1 root plugdev 4096 апр 24 12:25 profile_led_red
-r--r--r-- 1 root plugdev 4096 апр 24 12:25 report_descriptor
lrwxrwxrwx 1 root plugdev    0 апр 24 12:25 subsystem -> ../../../../../../../../bus/hid
-rw-rw---- 1 root plugdev 4096 апр 24 12:25 test
-rw-r--r-- 1 root plugdev 4096 апр 24 12:25 uevent
-r--r----- 1 root plugdev 4096 апр 24 12:25 version

**Comment by terricain** [comment]
That means things are actually working. Brightness is all it does. And the daemon is stealing all the keypresses (as they're normally normal keyboard ones like q w e etc...) and will run macro's upon keypress. 

Macros are a bit rubbish atm but I am working on new code that'll make it alot better. I have a nostromo on my desk so can test the macro stuff too.
