### ISSUE TITLE
Razer BlackWidow Chroma V2 M1-M5 macro keys don't produce keycodes

### ISSUE THREAD

**Issue by lmarso** [openrazer/openrazer#262]
in Device Mode (echo -n -e "\x03\x00" > device_mode) testing with actkbd and evtest, i get events + keycodes from all keys but the M1-M5 special left edge vertical row of additional macro keys.  these keys respond to led changes just fine, but the system (debian jessie) can't see the keypress events..

**Comment by z3ntu** [comment]
Do you have Telegram? If yes, it would make testing the driver (=communicating with you) much easier. So if yes, please message me @z3ntu there :)

**Comment by lmarso** [comment]
Also no FN keypress events
