### ISSUE TITLE
razer_bcd not running when trying to use GUIs

### ISSUE THREAD

**Issue by newchild01** [openrazer/openrazer#27]
Somehow I run into the problem, that the service razer_bcd is not running on Arch. Driver is working and all, it is just I can't use any GUI to apply effects.

Is this some known problem/how can I fix this? I am a bit of a linux noob in that regard.

**Comment by GabMus** [comment]
razer_bcd is no more. the new daemon is called razer-service. try running `killall razerdaemon` and then `razer-service` in your terminal

**Comment by GabMus** [comment]
Which driver are you using? How did you install it? What GUI are you using?
Oh and razer_bcd is no more, the new daemon is razer-service

**Comment by terricain** [comment]
You updated to latest? is this issue still relevant?
