### ISSUE TITLE
xdg basedir spec

### ISSUE THREAD

**Issue by WhyNotHugo** [openrazer/openrazer#281]
Currently the daemon looks for the config file in `$HOME`. This is really ugly, and if every app expected this, I'd have my home littered with stuff (there's lot of other reasons why apps don't do this any more, like making backups easier, etc).

The [XDG basedir spec](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) specifies the appropriate places where applications should look for their configurations (and caches, etc).

Ideally, the daemon should look in `$HOME/.config/razer/daemon.conf` (or something like that) for its configuration file.

**Comment by terricain** [comment]
Feel free to make a pull request :wink:

**Comment by terricain** [comment]
Though I dont disagree with you, but for now I have bigger things to work on.

**Comment by z3ntu** [comment]
I'll reopen because I am working on it 😉

**Comment by z3ntu** [comment]
PR in #286

**Comment by terricain** [comment]
Version 1.1.14 is out on launchpad, non Ubuntu packages will be out shortly.
