### ISSUE TITLE
Issues with installation

### ISSUE THREAD

**Issue by pnelego** [openrazer/openrazer#284]
So i have bounced around packages for razer products for a while. such as the "chroma" drivers.
```
Unfortunately I keep encountering this error:
dpkg: error processing archive /var/cache/apt/archives/razer-kernel-modules-dkms_1.1.12-0ubuntu1_amd64.deb (--unpack):
 trying to overwrite '/usr/src/razer_chroma_driver-1.0.0/driver/razerfirefly_driver.h', which is also in package razer-chroma-driver 1.0.0

```

is there a way to fix this?

**Comment by z3ntu** [comment]
Please run `sudo apt purge razer-chroma-driver`

**Comment by pnelego** [comment]
@z3ntu 
returned the following:
`The following packages have unmet dependencies:
 razer-daemon : Depends: razer-kernel-modules-dkms but it is not going to be installed
                Recommends: python3-razer but it is not going to be installed
E: Unmet dependencies. Try 'apt --fix-broken install' with no packages (or specify a solution).
`

EDIT: trying to -f install doesnt fix anything.

**Comment by z3ntu** [comment]
```
sudo apt remove python3-razer razer-kernel-modules-dkms razer-daemon razer-doc
sudo apt --fix-broken install
sudo apt remove razer-chroma-driver
```

**Comment by pnelego** [comment]
That did the trick! Thank you so much.

**Comment by z3ntu** [comment]
np :)
