### ISSUE TITLE
Not working for Debian Jessie 8.8

### ISSUE THREAD

**Issue by Juraci** [openrazer/openrazer#288]
I tried to follow the page installation guide for Debian 8

```@bash
echo 'deb http://download.opensuse.org/repositories/hardware:/razer/Debian_8.0/ /' > /etc/apt/sources.list.d/openrazer-meta.list 
apt-get update
apt-get install openrazer-meta
```

But after the apt get-update I get the following error:

`GPG error: http://download.opensuse.org  Release: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 062F9FD4D6D11CE4`

**Comment by z3ntu** [comment]
You missed these lines:

 ```
wget -nv http://download.opensuse.org/repositories/hardware:razer/Debian_8.0/Release.key -O Release.key
apt-key add - < Release.key
apt-get update
```
