### ISSUE TITLE
Missing Properties Ubuntu 16.04 LTS - Razer Deathadder Chroma v1.4

### ISSUE THREAD

**Issue by asteriskUser** [openrazer/openrazer#290]
Hi All,

I've noticed an issue with the xinput properties. With generic drivers I get to adjust the **Coordinate Transformation Matrix** myself, whilst with the Razer Linux drivers this property seems to be missing.

`xinput --list-props <DevNo>`
`xinput --set-prop <DevNo> <Coordinate Transformation Matrix> X X X X X X X X X`

These are the properties i get with the default Ubuntu driver:

_Device 'Razer Razer DeathAdder Chroma':
	Device Enabled (146):	1
	Coordinate Transformation Matrix (148):	1.000000, 0.000000, 0.000000, 0.000000, 1.000000, 0.000000, 0.000000, 0.000000, 1.000000
	Device Accel Profile (274):	0
	Device Accel Constant Deceleration (275):	1.000000
	Device Accel Adaptive Deceleration (276):	1.000000
	Device Accel Velocity Scaling (277):	10.000000
	Device Product ID (267):	5426, 67
	Device Node (268):	"/dev/input/event2"
	Evdev Axis Inversion (278):	0, 0
	Evdev Axes Swap (280):	0
	Axis Labels (281):	"Rel X" (156), "Rel Y" (157), "Rel Vert Wheel" (273)
	Button Labels (282):	"Button Left" (149), "Button Middle" (150), "Button Right" (151), "Button Wheel Up" (152), "Button Wheel Down" (153), "Button Horiz Wheel Left" (154), "Button Horiz Wheel Right" (155), "Button Side" (271), "Button Extra" (272), "Button Unknown" (270), "Button Unknown" (270), "Button Unknown" (270), "Button Unknown" (270)
	Evdev Scrolling Distance (283):	1, 1, 1
	Evdev Middle Button Emulation (284):	0
	Evdev Middle Button Timeout (285):	50
	Evdev Third Button Emulation (286):	0
	Evdev Third Button Emulation Timeout (287):	1000
	Evdev Third Button Emulation Button (288):	3
	Evdev Third Button Emulation Threshold (289):	20
	Evdev Wheel Emulation (290):	0
	Evdev Wheel Emulation Axes (291):	0, 0, 4, 5
	Evdev Wheel Emulation Inertia (292):	10
	Evdev Wheel Emulation Timeout (293):	200
	Evdev Wheel Emulation Button (294):	4
	Evdev Drag Lock Buttons (295):	0_

Could you please add this property to the driver?
It is especially useful for adjusting the scroll speed.

Thanks,
Viktor

**Comment by terricain** [comment]
Will need to look into it
