### ISSUE TITLE
Razer Mamba Tournament Edition not recognised on Ubuntu 16.04

### ISSUE THREAD

**Issue by ma-sadeghi** [openrazer/openrazer#292]
Hi,

I have a Razer Mamba Tournament Edition, and I use Ubuntu 16.04 LTS. When I open Polychromatic Controller app, it says device not recognized. I'd be thankful if you could help me with the issue.

Cheers,
Amin

PS. Here's the warning I get after running Polychromatic Controller app.

![screenshot from 2017-05-28 19-21-53](https://cloud.githubusercontent.com/assets/14086031/26532865/0072b548-43db-11e7-862f-bf179493c86d.png)

**Comment by z3ntu** [comment]
Please post the output of `sudo dkms status razer_chroma_driver/1.0.0`

**Comment by terricain** [comment]
Also output of `dpkg -l | grep razer`

**Comment by tildearrow** [comment]
Are you in the `plugdev` group?
If not, do `sudo usermod -a -G plugdev $USER`, reboot and try again.

(or does the PPA package set you in the plugdev group by default?)

**Comment by z3ntu** [comment]
The screenshot implies that the daemon is running which is only possible when the user id in the group afaik.

**Comment by ma-sadeghi** [comment]
Thank you all for your help.

@z3ntu
```
razer_chroma_driver, 1.0.0, 4.8.0-52-generic, x86_64: installed
```
@terrycain 
```
ii  python3-razer                               1.1.12-0ubuntu1                               all          Razer Python Library
ii  razer-daemon                                1.1.12-0ubuntu1                               amd64        Razer Device Daemon
ii  razer-doc                                   1.1.12-0ubuntu1                               all          Documentation and examples for the Razer Tools
ii  razer-kernel-modules-dkms                   1.1.12-0ubuntu1                               amd64        Razer Peripheral Drivers
```

**Comment by z3ntu** [comment]
Dumb question: Did you already reboot after installing?

**Comment by ma-sadeghi** [comment]
@z3ntu I think I did, but I just did and it's still not working.

**Comment by z3ntu** [comment]
Can you run `sudo modprobe razermouse; lsmod | grep razer`

**Comment by ma-sadeghi** [comment]
```
modprobe: FATAL: Module razermouse not found in directory /lib/modules/4.8.0-53-generic
```

**Comment by z3ntu** [comment]
`sudo dkms install razer_chroma_driver/1.0.0`

**Comment by ma-sadeghi** [comment]
```
Error! Your kernel headers for kernel 4.8.0-53-generic cannot be found.
Please install the linux-headers-4.8.0-53-generic package,
or use the --kernelsourcedir option to tell DKMS where it's located
```

**Comment by z3ntu** [comment]
Then you gotta install your kernel headers. On Ubuntu it's most likely linux-headers-generic.

**Comment by ma-sadeghi** [comment]
@z3ntu 
```
$ sudo modprobe razermouse; lsmod | grep razer
razermouse             61440  0
hid                   122880  3 razermouse,hid_generic,usbhid
```

**Comment by ma-sadeghi** [comment]
@z3ntu After running `sudo madprobe razermouse`, I rebooted the system and it works now! Thanks a lot for your help/time :)
