### ISSUE TITLE
Wrong dependence requirement for Debian 8

### ISSUE THREAD

**Issue by Mte90** [openrazer/openrazer#295]
I use Debian Sid and I cannot install the package but:
```
python3-evdev : Depends: python3 (< 3.5) but the version 3.5.3-1 was to be installed
```
So for me is not possible to install, it is possible to update the requirement for that dependence?

**Comment by z3ntu** [comment]
You followed the instructions on the website, right?

**Comment by Mte90** [comment]
yes, seems only that for that dependence for me is impossible to install the daemon.
I think that only update the require will unblock my situation.

**Comment by z3ntu** [comment]
Do you use Debian 8 or Sid (=testing)?

**Comment by z3ntu** [comment]
But anyways, if you have `Debian_Stretch` in your `/etc/apt/sources.list.d/openrazer-meta.list` file, please change it to either `Debian_8.0`, `Debian_9.0` or `Debian_Sid` depending on what you are using. Then it should work fine. :) Please report back!

**Comment by Mte90** [comment]
With `Debian_Sid` now is working :-)
Usually the debian repo does not support debian sid so this was an happy resolving :-)
