### ISSUE TITLE
Support for Orweaver Chroma

### ISSUE THREAD

**Issue by DmitryBurstein** [openrazer/openrazer#296]
Please add support for Device ID 1532:0207 (Orbweaver Chroma).
Thanks ahead.

**Comment by z3ntu** [comment]
Please test the pull request #188

**Comment by DmitryBurstein** [comment]
I probably am having trouble installing it: my original installation is Fedora's rpm. I downloaded the #188, made 'all' and 'install' (as root), and rebooted. The log file (~/.razer-service/logs/razer.log) shows the Orbweaver Chroma 'specification' present, the razerkbd is loaded, but /sys/bus/hid/drivers/razerkbd has no devices in it. Moreover, 'echo -n "0003:1532:0207.0005" > bind' (this is the mouse part) gives me '-bash: echo: write error: No such device', while I'm root, and the file is writable. Checking the /sys/bus/hid/drivers/hid-generic reveals no Razer devices in it either. Any further instructions would be welcome.

**Comment by z3ntu** [comment]
I'll write you instructions tomorrow hopefully.

**Comment by z3ntu** [comment]
Sorry for the delay. 

But I got something even better for you: a prebuilt [rpms.zip](https://github.com/terrycain/razer-drivers/files/1064744/rpms.zip) you can install with (download the rpms.zip first and go into the directory you have the zip):

```
mkdir rpms
unzip -d rpms rpms.zip
sudo dnf install rpms/*.rpm
```
Then add your user to the plugdev group if you haven't already (`sudo gpasswd -a $USER plugdev`) and reboot. Then please test everything as we can merge it then after it's tested and working.

**Comment by DmitryBurstein** [comment]
Great, thanks! This one works - kind of. Now I can see the device in Polychromatic, change the lightning effects and brightness, and it works. Unfortunately, everything else has stopped working: no keypress or joystick movement did generate any xev at all.
Another issue: when going back from energy-saving mode (screen off) the chroma lighting is not always coming back - sometimes the device remains blacked-out.

**Comment by terricain** [comment]
ok keypresses missing is the daemon grabbing them all, so that means its working. Macro stuff is rubbish atm but am working on a better implementation

lighting sounds like its setting brightness to 0 and then setting it back to the original value, normally its a bug in the code that handles screensavers

**Comment by DmitryBurstein** [comment]
Thanks. Mostly, the lighting is restored to its initial value and effect (spectrum in my case), but from time to time it just remains solid zero.
As to the key/joystick presses - wouldn't it be better to implement a default scheme working - with no need to reassign everything manually? Just a suggestion.
Is anything else in particular you'd like me to test?

**Comment by DmitryBurstein** [comment]
Would you like me to test something else - in order to release it?

**Comment by z3ntu** [comment]
The PR is already merged so it should be included in the next release. So if you say, everything works, then it's great 😉

**Comment by sKreevA4** [comment]
Hi, I'm new to all of this. (Both having razer peripherals, and this is actually my first comment on github). May I ask if/when this will come to "released"? Also, without having the particular distros with dnf, is there another way to install said driver? Thanks in advance

**Comment by terricain** [comment]
Version 1.1.14 is out on launchpad, non Ubuntu packages will be out shortly.
