### ISSUE TITLE
Dontaion ways

### ISSUE THREAD

**Issue by nick4fake** [openrazer/openrazer#298]
Hi guys,

You did really good job, thank you a lot. While I can not help you in further development, I'd like to do small donation. The problem is simple - I haven't found any ways to do that on your site.

What do you think about providing a way to donate?

- Bohdan

**Comment by terricain** [comment]
My PayPal is terry@terrys-home.co.uk

I should really get one of those button thingys

**Comment by z3ntu** [comment]
My PayPal is https://www.paypal.me/z3ntu but Terry deserves it more 😉
