### ISSUE TITLE
issue with installing via PPA

### ISSUE THREAD

**Issue by rivetrik** [openrazer/openrazer#30]
the deamon still installs except the driver which pulls this error:
rik@rik-Blade-Stealth ~> sudo apt install razer-chroma-driver
[sudo] password for rik: 
Reading package lists... Done
Building dependency tree  
Reading state information... Done
Package razer-chroma-driver is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
E: Package 'razer-chroma-driver' has no installation candidate

yet it will show in synaptic package manager.

and when ever i try to call razer commander from the terminal i get this output:

rik@rik-Blade-Stealth ~> sudo razercommander 
no devices

**Comment by lah7** [comment]
`razer-chroma-driver` is the old package name, the new packages are:
- `python3-razer`
- `razer-kernel-modules-dkms`
- `razer-daemon`
- `razer-doc`

**Comment by GabMus** [comment]
@rivetrik this sounds more like a problem with the daemon or the udev rules, not the driver itself. Looks like the python lib was imported correctly otherwise razerCommander would have complained differently in the terminal. Try rebooting your computer, if that doesn't work, run `killall razerdaemon && razer-service` and try again

**Comment by rivetrik** [comment]
yep, did all that and installed correctly. still no device found, any ideas as to why i get that error?

**Comment by GabMus** [comment]
We can figure it out. If you want we can chat here, but it'd be faster if you contact me on telegram @gabmus.

**Comment by rivetrik** [comment]
cool, ill go ahead and do that real quick if your up for it now
