### ISSUE TITLE
Orochi: button remapping / bluetooth

### ISSUE THREAD

**Issue by daritter** [openrazer/openrazer#300]
Hi,

thanks for the great work.

I was wondering if there's any plan to support remapping of mouse buttons. Specifically I would like (as a lefty) to get rid of the "change DPI" side buttons on my Orochi (1532:0048) and replace them with standard button 4/5 presses (disabling would be fine as well). And preferably over bluetooth :D 

I was hoping Synapse would write the button mapping into the mouse but no such luck, apparently only colors are important :/

**Comment by terricain** [comment]
@daritter I've been real busy as of late but it is being worked on

**Comment by daritter** [comment]
Great, thanks for the info.

If there's anything you need (traffic capture, testing) just let me know.

Cheers, 

Martin

**Comment by z3ntu** [comment]
@daritter Can you give me the product and model number and the full name of the Orochi (should be on a sticker on the bottom of the mouse)?

**Comment by daritter** [comment]
It's inside the battery case: 

RAZER Orochi 8200
Model No: RZ01-0155
Product No: RZ01-01550100

**Comment by z3ntu** [comment]
Thanks.
