### ISSUE TITLE
Razer BlackWidow Chroma V2

### ISSUE THREAD

**Issue by TheAifam5** [openrazer/openrazer#305]
Hey,

I am actually owner of Razer BlackWidow Chroma V2.
I seen a small bug with the backlight only. Everything other works fine.
After set 50%, 75%, always sets to 1% less.
Works with 0%, 25% and 100%.
Also sometimes the backlight makes off and then blink.. I think that happen after when I locking my PC.

If needs more info, please provide instructions and what you need exactly.
Im using ArchLinux with Budgie Desktop.

PS. I am gonna test driver on Android platform with Razer USB headphones. I will write about it later.
Regards,
TheAifam5

**Comment by terricain** [comment]
> After set 50%, 75%, always sets to 1% less.

Yeah nothing we can do, basically the percentage is converted into 1bytes worth of data and there exists some rounding errors.



> Also sometimes the backlight makes off and then blink.. I think that happen after when I locking my PC.

Normally something to do with the screensaver events on DBus



> PS. I am gonna test driver on Android platform with Razer USB headphones. I will write about it later.

Awesome sounds cool
