### ISSUE TITLE
Razer Blade Stealth (Late 2016) Python Issue

### ISSUE THREAD

**Issue by kprinssu** [openrazer/openrazer#309]
I am trying to run the razer-daemon using `razer-daemon -F`, but it always provides the following error:

See the following gist: https://gist.github.com/kprinssu/cf176e688fa529df4cdd2445d575cfaa

**Comment by z3ntu** [comment]
Please post the output of `cat /sys/bus/hid/drivers/razerkbd/0*/device_serial`

**Comment by kprinssu** [comment]
It's empty, as in:

`
$ cat /sys/bus/hid/drivers/razerkbd/0*/device_serial
 
`

**Comment by z3ntu** [comment]
Could you run `sudo dmidecode -t 1` and post the output here? Either Razer f**** something up as in #192 (where they didn't change the serial so it's "Default string"...) or the driver is doing something wrong.

**Comment by kprinssu** [comment]
It's still blank under the serial number.


`# dmidecode 3.0
Getting SMBIOS data from sysfs.
SMBIOS 3.0.0 present.

Handle 0x0001, DMI type 1, 27 bytes
System Information
	Manufacturer: Razer
	Product Name: Blade Stealth
	Version: 2.04
	Serial Number:  
	UUID: Not Settable
	Wake-up Type: Power Switch
	SKU Number:  
	Family: 1A586752

`

**Comment by z3ntu** [comment]
Thanks... @terrycain should be able to write a workaround for
* empty serial
* "Default string" serial

**Comment by kprinssu** [comment]
Fun times when Razer messes up. Thanks for the help.

**Comment by terricain** [comment]
Possibly fixed in 8b8999a, have a look after the next release (v1.1.14)

**Comment by kprinssu** [comment]
I manually installed the latest changes, but it seems that my keyboard is not recognised on Polychromatic.

**Comment by terricain** [comment]
did you reboot?

**Comment by terricain** [comment]
and does `razer-daemon -F` still give errors?

**Comment by z3ntu** [comment]
Actually running `cat /sys/bus/hid/drivers/razerkbd/0*/device_serial` should show it 😃

**Comment by terricain** [comment]
^^ @z3ntu nah, patched it in daemon for now

**Comment by z3ntu** [comment]
Ah okay - good enough

**Comment by kprinssu** [comment]
I did reboot and running `razer-daemon -F` doesn't an error. In fact, the serial issue seems to be fixed, but Polychroamtic says that it doesn't recognise the keyboard. I should also mention that I am on Ubuntu Gnome 17.04.

**Comment by terricain** [comment]
Ahh, I think thats now more an issue with polychromatic than it is with the daemon. @lah7 ^^

**Comment by terricain** [comment]
Should now try raising an issue on the polychromatic repo

**Comment by z3ntu** [comment]
What does `python3 -c "from razer.client import DeviceManager; a = DeviceManager(); print(a.devices)"` give?

**Comment by kprinssu** [comment]
That command outputs an error: https://gist.github.com/kprinssu/718621c63e442cd9528ae1ec4c2fa417

I think it's an underlying issue with the razer-drivers. If you think it's an issue with Polychromatic, I'll go bug the devs over there :).

**Comment by terricain** [comment]
Is the daemon running?

**Comment by kprinssu** [comment]
Not when I ran that command, I'll post an updated log.

**Comment by terricain** [comment]
yeah that command tries to talk to the daemon

**Comment by kprinssu** [comment]
The command that z3ntu posted just returns an empty array: `[]`

**Comment by terricain** [comment]
Hmm, whats the output of lsusb?

**Comment by kprinssu** [comment]
Here is the output of lsusb:

```
Bus 004 Device 004: ID 05e3:0617 Genesys Logic, Inc. 
Bus 004 Device 003: ID 0b95:1790 ASIX Electronics Corp. AX88179 Gigabit Ethernet
Bus 004 Device 002: ID 05e3:0617 Genesys Logic, Inc. 
Bus 004 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 003 Device 005: ID 05e3:0610 Genesys Logic, Inc. 4-port hub
Bus 003 Device 004: ID 1532:0215 Razer USA, Ltd 
Bus 003 Device 002: ID 05e3:0610 Genesys Logic, Inc. 4-port hub
Bus 003 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 005: ID 04f3:223c Elan Microelectronics Corp. 
Bus 001 Device 004: ID 1532:0220 Razer USA, Ltd 
Bus 001 Device 003: ID 0bda:579f Realtek Semiconductor Corp. 
Bus 001 Device 002: ID 8087:0a2b Intel Corp. 
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
```

**Comment by terricain** [comment]
and whats the output from the daemon?

**Comment by kprinssu** [comment]
This is what I get from doing `razer-daemon -F`:

https://gist.github.com/kprinssu/a29a7959a9ba6eb6e12758777ad296a7

**Comment by kprinssu** [comment]
Here is the output from the latest changes:

https://gist.github.com/kprinssu/c83ecfba63a4571caf8a162703c98a19

**Comment by terricain** [comment]
contents of /lib/udev/rules.d/99-razer.rules

**Comment by kprinssu** [comment]
The file doesn't exist.

**Comment by terricain** [comment]
ok that doesnt help. Does  `sudo modprobe razerkbd` work?

**Comment by kprinssu** [comment]
Nope..

**Comment by terricain** [comment]
Wait, have you installed the project using the proper packages?

**Comment by kprinssu** [comment]
I installed it via the instructions here:
https://terrycain.github.io/razer-drivers/#other

**Comment by terricain** [comment]
What distro are you running?

**Comment by kprinssu** [comment]
Ubuntu Gnome 17.04

**Comment by terricain** [comment]
https://terrycain.github.io/razer-drivers/#ubuntu

**Comment by kprinssu** [comment]
I installed the package via apt-get but running `sudo modprobe razerkbd` returns nothing. 
Running `razer-daemon -F` shows that it detects my keyboard, but fails with the first error since I am not running the latest changes.

**Comment by terricain** [comment]
yeah so now patch, and reboot (modprobe only outputs on error btw)

**Comment by kprinssu** [comment]
Can you clarify on what you mean by patching?

**Comment by terricain** [comment]
Take https://github.com/terrycain/razer-drivers/blob/master/daemon/razer_daemon/hardware/device_base.py
and replace the one in /usr/lib/python... somewhere

**Comment by kprinssu** [comment]
Replacing the file gives the following error from Python (when running the daemon):
https://gist.github.com/kprinssu/cd08b057a2cda71cce113b02dda4d498

**Comment by terricain** [comment]
You replaced /usr/lib/python3/dist-packages/razer_daemon/hardware/device_base.py
right?

**Comment by kprinssu** [comment]
I did replace that specific file, not sure what I am doing incorrectly.

**Comment by terricain** [comment]
hmm, ok, remove the razer-daemon package, and i'll release a proper package again soon

**Comment by terricain** [comment]
Version 1.1.14 is out on launchpad, non Ubuntu packages will be out shortly.
