### ISSUE TITLE
Using the driver broke my network card driver

### ISSUE THREAD

**Issue by ChristopherBare** [openrazer/openrazer#315]
As the title suggests, I installed the Razer drivers and rebooted. My network was Ethernet only and the WiFi was unavailable. I uninstalled the Razer drivers and it worked again.

**Comment by z3ntu** [comment]
Uhm can you please post `sudo journalctl | grep -i razer_mount`

**Comment by ChristopherBare** [comment]
It doesn't return anything when I run that.

**Comment by z3ntu** [comment]
Then there is afaik no possibility of our driver interfering. Can you try just installing the kernel driver (package name depends on your distro but it's probably razer-kernel-modules-dkms or razer-driver-dkms) and try that?

**Comment by ChristopherBare** [comment]
This was what I ran to install it from the PPA: `sudo apt install python3-razer razer-kernel-modules-dkms razer-daemon razer-doc`. I'm running Ubuntu 16.04 - Cinnamon if that helps.

**Comment by z3ntu** [comment]
Yes, please run `sudo apt install razer-kernel-modules-dkms` and then reboot.

**Comment by ChristopherBare** [comment]
Okay, I did that. The WiFi appears to be behaving normally again. Thank you!

**Comment by z3ntu** [comment]
Okay now install the rest of the packages.

**Comment by ChristopherBare** [comment]
Alright, I did that.

**Comment by z3ntu** [comment]
Does wifi still work (after reboot)?

**Comment by ChristopherBare** [comment]
It does.

**Comment by z3ntu** [comment]
`¯\_(ツ)_/¯`

**Comment by solofortitude** [comment]
Hi, 
Did the location change?  I have a razer bland 2014 and i have lost the ability to use my wi-fi.

thx!

:/home/raven# apt install razer-kernel-modules-dkms
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package razer-kernel-modules-dkms
