### ISSUE TITLE
Request support for BlackWidow Ultimate Classic (Mac edition)

### ISSUE THREAD

**Issue by ChristopherBare** [openrazer/openrazer#316]
I have the mac version of the BlackWidow Ultimate. Model number: RZ01-0038. 

Thank you!

**Comment by z3ntu** [comment]
What's the USB ID of the device? `lsusb | grep 1532`

**Comment by ChristopherBare** [comment]
Bus 003 Device 004: ID 1532:010d Razer USA, Ltd

**Comment by z3ntu** [comment]
010d is already supported. It's a Razer BlackWidow Ultimate 2012
