### ISSUE TITLE
On-The-Fly Macro recording not working

### ISSUE THREAD

**Issue by ChristopherBare** [openrazer/openrazer#317]
I cannot get the macro function to work. I tried the link to MacroW and that doesn't seem to do what I want either. 

All I want to do is record `ctrl + alt + t` so that I can open a terminal in one button from the f15 button. 

Can someone help me out?

Thanks!

**Comment by terricain** [comment]
@ChristopherBare New macro code is being worked on,id wait for that to be released

**Comment by ChristopherBare** [comment]
Awesome! Thanks, it's a simple thing that I was trying to do. I just wondered why it wasn't working. I'll wait patiently for the release.
