### ISSUE TITLE
Update Wiki for installation

### ISSUE THREAD

**Issue by claell** [openrazer/openrazer#32]
Currently this seems to be outdated: https://github.com/pez2001/razer_chroma_drivers/wiki/Installation

**Comment by terricain** [comment]
Yeah I quickly updated my copy with a sort of "this is deprecated, use PPA" type message, do places still link to the old repo?

**Comment by claell** [comment]
Oh, seems like the readme still points to the old wiki, so I did not read the deprecated message :)

**Comment by terricain** [comment]
This readme points to this wiki ha. The old readme points to the old wiki

**Comment by claell** [comment]
Thought I just checked it. But seems to be true and I just mixed up the projects.

**Comment by terricain** [comment]
Yeah I can see this happening for a while :/
