### ISSUE TITLE
Ubuntu 17.04 Zesty

### ISSUE THREAD

**Issue by TreyMooneyham** [openrazer/openrazer#321]
I'm rather novice at Linux and also have Ubuntu 17.04, and could really use some help.

I've used the commands supplied on the website, but have been unable to run any of the other programs
(Razer Commander and polychromatic to be precise). Is there an easy-ish way to install the drivers/ppa for Ubuntu 17.04?

**Comment by z3ntu** [comment]
* Please post the output of `sudo dkms status razer_chroma_driver/1.0.0`
* And of `python3 -c "from razer.client import DeviceManager; a = DeviceManager(); print(a.devices)"`

**Comment by TreyMooneyham** [comment]
The first line has no output but the second string sends
`Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named 'razer'`

**Comment by z3ntu** [comment]
Output of `sudo apt install python3-razer razer-kernel-modules-dkms razer-daemon razer-doc` please

**Comment by TreyMooneyham** [comment]
`DKMS: install completed.
-e 
ADD YOUR USER TO THE PLUGDEV GROUP 'sudo gpasswd -a <USERNAME> plugdev'
Setting up python3-evdev (0.6.4-0ubuntu1) ...
Setting up liblapack3 (3.7.0-1) ...
update-alternatives: using /usr/lib/lapack/liblapack.so.3 to provide /usr/lib/liblapack.so.3 (liblapack.so.3) in auto mode
Setting up razer-daemon (1.1.13-0ubuntu1) ...
Setting up python3-numpy (1:1.12.1-1ubuntu1) ...
Setting up python3-razer (1.1.13-0ubuntu1) ...
`

**Comment by z3ntu** [comment]
Now reboot and the output of `python3 -c "from razer.client import DeviceManager; a = DeviceManager(); print(a.devices)"`

**Comment by z3ntu** [comment]
Don't forget to 

> ADD YOUR USER TO THE PLUGDEV GROUP 'sudo gpasswd -a \<USERNAME> plugdev'

**Comment by TreyMooneyham** [comment]
So, for plugdev, I would run `sudo gpasswd -a <myname>'?

**Comment by z3ntu** [comment]
No, `sudo gpasswd -a YOURUSERNAME plugdev`

**Comment by z3ntu** [comment]
Also github doesn't like the smaller-than signs as it tries to interpret them as html. use codeblocks when using them or escape them with a backslash \\

**Comment by TreyMooneyham** [comment]
Output of `python3 -c "from razer.client import DeviceManager; a = DeviceManager(); print(a.devices)"` was `[<RazerKeyboard IO1535122712542>]`

**Comment by z3ntu** [comment]
Should be alright then.

**Comment by TreyMooneyham** [comment]
Thanks for the quick help!
