### ISSUE TITLE
Crash after installation

### ISSUE THREAD

**Issue by claell** [openrazer/openrazer#33]
I just rebooted after installation of the daemon and kernel modules (via PPA) on Ubuntu 16.04. Now I got a crash report from Razer Service "razer-service crashed with ImportError in [...] No module named 'razer.keyboard'"

**Comment by terricain** [comment]
is python3-razer intalled?

**Comment by claell** [comment]
I think not, but I cannot seem to be able to install it via `apt-get install python3-razer` on Ubuntu 16.04.

**Comment by terricain** [comment]
Really? As I installed it on an xenial server (just to test) and it was fine. I'll have a look when I get home, probably LaunchTurd bugging out again. Also what version do you have installed?

**Comment by terricain** [comment]
[pastebin](http://pastebin.com/nRCUdmqS) of installing python3-razer. Should just work on 16.04 unless you have the wrong ppa but I dont see how

**Comment by claell** [comment]
I probably have a wrong PPA. I used the one from Polychromatic. Did not know there are two.

**Comment by GabMus** [comment]
The driver ppa is separated from polychromatic ppa, yeah

**Comment by claell** [comment]
Ok. I will try the other PPA when I am back at my machine (in a week or two).

**Comment by terricain** [comment]
Ahh yeah correct me if im wrong @lah7, originally he had a PPA for it all but now there will be 1 PPA for the core stuff and then a PPA for each client application.

**Comment by lah7** [comment]
The PPA for Polychromatic was **just** for Polychromatic. The README did include a separate Debian package for `amd64` - to save the convenience of needing to compile it, but it was never in the PPA.

**Comment by claell** [comment]
Works with correct PPA.
