### ISSUE TITLE
Nostrom not recognised

### ISSUE THREAD

**Issue by RomainLG** [openrazer/openrazer#331]
(redirected from https://github.com/lah7/polychromatic/issues/102)

I get a Device Not Recognized error under Polychromatic.

I'm on Kali which is a rolling Debian.

```
sessionR@kali:~$  sudo journalctl -b | grep -i razer_mount
Jul 07 19:47:49 kali razer_mount[387]: Driver razerkbd
Jul 07 19:47:49 kali razer_mount[386]: Driver razerkbd
Jul 07 19:47:49 kali razer_mount[398]: Device_ID 0003:1532:0111.0002
Jul 07 19:47:49 kali razer_mount[397]: Device_ID 0003:1532:0111.0003
Jul 07 19:47:49 kali razer_mount[401]: Modprobing razerkbd
Jul 07 19:47:49 kali razer_mount[400]: Modprobing razerkbd
Jul 07 19:47:49 kali systemd-udevd[322]: Process 'razer_mount razerkbd 0003:1532:0111.0003' failed with exit code 1.
Jul 07 19:47:49 kali systemd-udevd[312]: Process 'razer_mount razerkbd 0003:1532:0111.0002' failed with exit code 1.

sessionR@kali:~$ lsusb | grep '1532:'
Bus 004 Device 006: ID 1532:0111 Razer USA, Ltd 

sessionR@kali:~$ sudo modprobe razerkbd
modprobe: FATAL: Module razerkbd not found in directory /lib/modules/4.9.0-kali3-amd64
```

Any help appreciated ! :)

**Comment by terricain** [comment]
What version of the driver are you running? has DKMS build the driver for your kernel verison

**Comment by RomainLG** [comment]
@terrycain 

![screenshot_2017-07-07_21-16-58](https://user-images.githubusercontent.com/13045542/27973290-ca566f2e-6359-11e7-821e-4088462553aa.png)

I installed polychromatic that installed its dependencies. 

I also used 
```
echo 'deb http://download.opensuse.org/repositories/hardware:/razer/Debian_Sid/ /' > /etc/apt/sources.list.d/openrazer-meta.list 
apt-get update
apt-get install openrazer-meta
```
I didn't use dkms (don't know how)

**Comment by z3ntu** [comment]
Please run `sudo apt-get install linux-headers-$(uname -r)` and post the output.

**Comment by RomainLG** [comment]
```
sessionR@kali:~$ sudo apt-get install linux-headers-$(uname -r)
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package linux-headers-4.9.0-kali3-amd64
E: Couldn't find any package by glob 'linux-headers-4.9.0-kali3-amd64'
E: Couldn't find any package by regex 'linux-headers-4.9.0-kali3-amd64'
```

I guess I should update my system? Can't get the nostromo to work if I don't have the latest kernel ?

**Comment by z3ntu** [comment]
Well you need the kernel headers for the installed kernel. Do all upgrades (`sudo apt-get dist-upgrade`) and then run the previous command again.

**Comment by RomainLG** [comment]
I will try that tomorrow morning, I don't have proper Internet right now.

**Comment by RomainLG** [comment]
@z3ntu @terrycain 
OK with the headers it works! I can only control brightness but I guess it already something.

I intend to use the nostromo as an application/shortcut launcher or to control playback during movies. I hope I'll succeed in this endeavor! If you've heard of someone who did this I'm all ears.

```xev``` doesn't seem to receive keystrokes...

Thanks!

Edit: apparently it's expected and macro support is not out yet (?)
https://github.com/terrycain/razer-drivers/issues/259 @prispewnic 
https://github.com/lah7/polychromatic/issues/80
