### ISSUE TITLE
Razer Kraken USB /  1532:0502

### ISSUE THREAD

**Issue by DarkAvengerr** [openrazer/openrazer#334]
I recently moved to Ubuntu and noticed that the sound of my Kraken USB is not clear with the default drivers. Is there any chance that you add support? I can provide some info, if needed.

**Comment by terricain** [comment]
Nope sorry. The driver only deals with the lighting, and I'm not planning on going down the sound route at all.

**Comment by terricain** [comment]
You tried the latest Ubuntu? Or on a different pc or even a different usb port?
