### ISSUE TITLE
Case label value exceeds maximum value for type

### ISSUE THREAD

**Issue by pacmancoder** [openrazer/openrazer#335]
Warning during compilation points on the parameter type error.
unsigned char value is comparing to numbers, bigger than 255.

![2017-07-13 22-41-27](https://user-images.githubusercontent.com/3994505/28184551-7aae5dfc-681c-11e7-8bcc-2b41758a3f07.png)

**Comment by terricain** [comment]
Yeah im sure i've fixed that, hmm

**Comment by terricain** [comment]
I did fix it but it unfixed itself, its fixed now
