### ISSUE TITLE
[Feature Idea] Programming keys / Macros

### ISSUE THREAD

**Issue by pacmancoder** [openrazer/openrazer#341]
I just bought Chroma V2 and I have some thoughts about next possible features of razer-drivers [keyboard driver].
I am new to Linux driver development, so my phrases may sound a little ridiculous 😄 

1) It would be nice, if programming of keys wouldn't be hardcoded in kernel module, instead of  that I propose to add feature to remap specific key. But this way is not too flexible

2) The second way I propose is some kind of callback mechanism for key events from driver. 
This can be implemented something like that:

1. User process registers itself in razer driver and places keyboard device in "programmable mode". 
2. On any key event driver sends to the user-mode process data about key action (real input is not performed in kernel mode at current stage)
3. User-mode process sends input event (using uinput?) accourding to the configuration
4. When user process is exiting,  it disables "programmable mode" and unregisters itself from a driver.

Actually, I love the second, but I don't know how this communication process can affect the performance of input actions handling.

Off-topic: Is there are any place where I can ask my questions about razer-drivers besides github issues? Chat, mail or something?

**Comment by tildearrow** [comment]
The second approach is really good. I doubt it'll introduce input lag, since I tried this approach and input events would process in ~40 microseconds (which is close to no lag).

The razer-drivers guys have a Telegram group, but you need to ask @z3ntu to join.
