### ISSUE TITLE
Razor Death Adder 2013 not recognized

### ISSUE THREAD

**Issue by binarykitchen** [openrazer/openrazer#345]
Guess probably because it's not supported yet.

```
└─( 2 ) ❱❱❱ lsusb | grep '1532:'
Bus 005 Device 002: ID 1532:0037 Razer USA, Ltd 
```

Not listed in https://github.com/terrycain/razer-drivers#mouse

Any chance to add support for it for Ubuntu 17.04?

**Comment by z3ntu** [comment]
Duplicate of #195. You can help by getting pcaps as mentioned in that thread.

**Comment by binarykitchen** [comment]
@z3ntu will do ... but ummm what is pcaps? not mentioned in that thread ...

**Comment by z3ntu** [comment]
Packet captures (it's described in the wiki). But actually we might not need captures. You can subscribe to #195 and get notified of further development. We are quite busy atm so you have to wait a bit.
