### ISSUE TITLE
Razer Blade Stealth 13.3 (0x022d) ripple effect issue

### ISSUE THREAD

**Issue by jonmanes** [openrazer/openrazer#353]
[ripple_issue_pcaps.zip](https://github.com/terrycain/razer-drivers/files/1209348/ripple_issue_pcaps.zip)
The ripple effect does not work. As you suspected it uses the last of the single key setting the board had set. 

The ripple sngl required selecting effect / none twice before it actually went back to no effect so you may see that in the attached pcap.

BTW these pcaps are from the issue as seen on the linux side.

**Comment by jonmanes** [comment]
[RBS_ripple_windows.zip](https://github.com/terrycain/razer-drivers/files/1209402/RBS_ripple_windows.zip)
This pcap is the working feature running from the windows side.

**Comment by alkeryn** [comment]
Other than that is there any other issue with the laptop
(i just bought it but didn't got it yet)

**Comment by jonmanes** [comment]
Working very well for me.

I'm running Ubuntu 17.04 if that helps.

**Comment by alkeryn** [comment]
Thanks, i receive my puppy in few days, i'm gonna put arch on it :P
That will be my first high end linux laptop so kinda hyped xD

**Comment by jonmanes** [comment]
Enjoy it! I love mine

**Comment by alkeryn** [comment]
Well i got my laptop but i can't get openrazer to work polychromatic says that the device is not recognized 
though the id is on the supported list
Running arch

**Comment by alkeryn** [comment]
also modeprobe razerkbd don't find the module

**Comment by z3ntu** [comment]
@Alkeryn Please post the output of `sudo dkms status`.

**Comment by alkeryn** [comment]
I fixed it, forgot to install linux-header
though since then it force my layout into qwerty instead of azerty
even though i have setxkbmap fr in my autostart

**Comment by z3ntu** [comment]
@jonmanes Did you try with the newest version (v2.2.0)?
