### ISSUE TITLE
Razer Blade (late 2016) detected as Razer Blade Stealth (QHD)

### ISSUE THREAD

**Issue by spacepluk** [openrazer/openrazer#355]
Hi there,
I have a Blade (late 2016) with the FHD screen but for some reason the driver detects it as a Stealth (QHD).  It seems to work fine though.

**Comment by terricain** [comment]
Yeah, I think there's 2 issues here, 1 is that the FHD uses the same keyboard as the QHD, and 2 its just a name and most likely wrong, but as its just a name I'm not in a big rush to change it, If I remember next time Im editing the relevant parts I might.
