### ISSUE TITLE
dbus-user-session dependency causes issues with chrome

### ISSUE THREAD

**Issue by MannyC** [openrazer/openrazer#358]
This isn't exactly the driver's fault, but at the moment on Ubuntu 16.04 installing the dbus-user-session package causes gnome-keyring not to unlock on boot, which causes Chrome to take ages to start and not unlock your passwords.  

As dbus-user-session is not a default package it's likely that the driver package will end up installing it.  If it breaks chrome it will probably appear to the user as if it was the driver package that caused the issue.

Uninstalling dbus-user-session "fixes" the issue, but I've yet to test whether razer-drivers will continue to work (currently uninstalled on my system).

This is probably pretty common at the moment, so may be worth documenting on the website, or at least here in this issue.

gnome-keyring issue tracker has more info here: https://bugs.launchpad.net/ubuntu/+source/gnome-keyring/+bug/1689825

**Comment by EricMCarroll** [comment]
I can confirm that removing razer-daemon, polychromatic and dbus-user-session resolves the gnome-keyring and chrome issue in 16.04.3.

Right now removing dbus-user-session forces the removal of its dependencies, namely razer-daemon and polychromatic.

**Comment by z3ntu** [comment]
That's how much I love Ubuntu. Having millions of bug reports that never get any attention from people that fix stuff... Unfortunately we can't really do much if the distro is broken :/

**Comment by aldencolerain** [comment]
@z3ntu I'm in the same boat trying to run Ubuntu and the razor drivers.  Is dbus-user-session a hard dependency are there any alternatives or workarounds anyone has gotten to work?

**Comment by z3ntu** [comment]
It would be nice to have. Another method of autostarting the daemon would be putting the razer-daemon.desktop file in the repository into /etc/xdg/autostart/ and removing the dbus-user-session package. I don't know if this can be achieved with dpkg packages but maybe...

**Comment by terricain** [comment]
> It would be nice to have. Another method of autostarting the daemon would be putting the razer-daemon.desktop file in the repository into /etc/xdg/autostart/ and removing the dbus-user-session package. I don't know if this can be achieved with dpkg packages but maybe...

I thought about this the other day, worse case we could just used xdg for all of ubuntu till we can drop 16.04

**Comment by Zerophase** [comment]
I'll have to figure out how my driver is getting loaded. I removed udev from my startup, and every thing still gets bound correctly every boot.

**Comment by terricain** [comment]
Weird

**Comment by ptrvilya** [comment]
There's a workaround:
`gnome-keyring-daemon &` 
[From [askubuntu](https://askubuntu.com/questions/913342/ubuntu-16-04-some-applications-are-slow-to-start)]

**Comment by z3ntu** [comment]
@EchoCloud and rest here:
Please try the debs and reboot (note: they are only for 16.04!)
[1604debs.tar.gz](https://github.com/openrazer/openrazer/files/1352396/1604debs.tar.gz)

They are based on the contents in the PR #402

**Comment by ghost** [comment]
I installed the daily version from ppa:openrazer/daily on Ubuntu 16.04.3 and dbus-user-session was installed too. Is this expected?

**Comment by ssnl** [comment]
Also interested in the correct way to install these.

**Comment by KazWolfe** [comment]
I found that installing the drivers will install `dbus-user-session`, but you can just uninstall it immediately afterwards without anything complaining:

    sudo apt remove dbus-user-session

Note that this may not work for you depending on your config, but it's worth a shot.

**Comment by z3ntu** [comment]
Found the issue why launchpad is failing my check: `make[1]: lsb_release: Command not found`. Will fix that.

**Comment by z3ntu** [comment]
Should be fixed in 980462d (so in tomorrows build)

**Comment by ghost** [comment]
It works well for me now. Thank you!

**Comment by z3ntu** [comment]
v2.1 is out
