### ISSUE TITLE
Not usable on Razer Blade Stealth 13.3

### ISSUE THREAD

**Issue by royalbaecker** [openrazer/openrazer#359]
Hi,

i installed all drivers and everything as mentioned.

Polychromatic says it finds a Razer Device, but the service cant find it.

i checked through all Issues, and followed the steps given to people with similiar problems, but nothing is working.

if anybody could help me, that would be super nice.

if logs or anything is needed, let me know.

Thank you so much!!

**Comment by z3ntu** [comment]
Can you post the output of lsusb?

**Comment by royalbaecker** [comment]
of course! thank you so much for the help.

here it is:

db@BladeStealth:~$ lsusb
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 006: ID 04f3:2379 Elan Microelectronics Corp. 
Bus 001 Device 005: ID 1532:022d Razer USA, Ltd 
Bus 001 Device 004: ID 1bcf:2c9a Sunplus Innovation Technology Inc. 
Bus 001 Device 003: ID 0cf3:e300 Atheros Communications, Inc. 
Bus 001 Device 002: ID 046d:c52b Logitech, Inc. Unifying Receiver
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub

**Comment by z3ntu** [comment]
Please post the output of `dkms status` and of 
`python3 -c "from razer.client import DeviceManager; a = DeviceManager(); print(a.devices)"`

**Comment by royalbaecker** [comment]
here is the output:

[]

**Comment by z3ntu** [comment]
The first command didn't output anything either?

**Comment by terricain** [comment]
022d isnt released yet

**Comment by terricain** [comment]
it'll will be out in next package

**Comment by royalbaecker** [comment]
well, it outputs these 2 symbols, nothing more.


ahh okay, so that means all i need to do is wait and with the next update all should work fine.
i can live with that.

if you need any help, logs or anything, im available to help!

**Comment by royalbaecker** [comment]
Update, i found and installed your files here:
https://github.com/terrycain/razer-drivers/issues/340

Now it works fine!!! 

Thank you very much!!!

**Comment by terricain** [comment]
1.1.16 is being built, will be out soon
