### ISSUE TITLE
Razer Chroma HDK (Hardware Development Kit) - 4x16 LED strip driver

### ISSUE THREAD

**Issue by CalcProgrammer1** [openrazer/openrazer#361]
Razer now makes an LED strip box similar to the NZXT Hue+.  I'm integrating it into my keyboard visualizer program on Windows with the latest version of the Chroma SDK.  I will try to capture some packets soon.  So far I know it is a USB device, has 4 LED strip ports capable of 16 LEDs per strip, can detect which strips are connected, and looks like it probably can detect how many LEDs are in a strip (if you cut the strip).  It has the standard Chroma patterns (wave, spectrum cycle, static, breathing, etc) and should support custom effects as well.

**Comment by z3ntu** [comment]
Lol this came out a few days ago and you already have it 😁

**Comment by terricain** [comment]
I was gonna get one but its properly overpriced. Yeah I would guess it follows the standard protocol so should be an easy add once I've got captures.

**Comment by Dublerq** [comment]
Once an open source driver is made for that device, making a DIY Chroma HDK with arduino and cheaper led stripes should be easily doable. That would be awesome. In most countries of the world HDK is not available even 6m after the device came out...

**Comment by pnomolos** [comment]
How can I help to get this working?  I have an HDK and am running Ubuntu 19.04.

**Edit** Just read the reverse engineering docs.  I'll try and do that sometime over the next couple of weeks.  Also, here's the `ls -lah /dev/input/by-id/` output:

```
lrwxrwxrwx 1 root root  10 Aug 31 00:17 usb-Razer_Razer_Chroma_HDK-event-if01 -> ../event26
lrwxrwxrwx 1 root root   9 Aug 31 00:17 usb-Razer_Razer_Chroma_HDK-event-kbd -> ../event9
lrwxrwxrwx 1 root root  10 Aug 31 00:17 usb-Razer_Razer_Chroma_HDK-if01-event-kbd -> ../event10
lrwxrwxrwx 1 root root  10 Aug 31 00:17 usb-Razer_Razer_Chroma_HDK-if02-event-mouse -> ../event27
lrwxrwxrwx 1 root root   9 Aug 31 00:17 usb-Razer_Razer_Chroma_HDK-if02-mouse -> ../mouse1
```

**Comment by z3ntu** [comment]
@pnomolos There's a pull request open at #904 which you can test

**Comment by pnomolos** [comment]
@z3ntu The basics appear to be working for me - I only have two strips installed but was able to use `matrix_effect_breath` so far.  Will play around with it more.

**NOTE:** I tried setting `matrix_custom_frame` and managed to hard lock my machine.  I wasn't setting a full row, though, so maybe that was the problem?

**Comment by z3ntu** [comment]
Yes, partial rows are really buggy, so always send full rows^^
