### ISSUE TITLE
Razer Kraken 7.1 Chromas not being detected by Polychromatic.

### ISSUE THREAD

**Issue by benjaminblackbookish** [openrazer/openrazer#367]
I have already asked about this issue on Ask Ubuntu so I am just going to copy and paste my initial question.

> 

Long story short, I am trying to install the non native Razer Drivers for my headset so I can mess around more with my headset setting (like bass boost for example) I am using Ubuntu 16.04 LTS and would really love it if someone helped, thanks.

On the installation document on the git-hub page of Polychromatic it tells you the exact USB VID:PID's of which products are supported, so I typed in 'lsusb | grep '1532:'' into the command line like it says and it comes up with;

Bus 004 Device 004: ID 1532:0504 Razer USA, Ltd

Which is great because it says the product with this USB VID:PID (Kraken 7.1 Chroma's) are supported so I am not really sure why It is not getting recognized when I launch the Polychromatic Controller. There is no the daemon could be broken surely because Its a super fresh install.

Update: I just found the troubleshooting guide and went through it all but nothing changed, the only semi hopefully response I got from putting a certain command into the command was the command sudo gpasswd -a benjamin plugdev which gave me the message adding benjamin to group plugdev. Not sure if thats normal or it does it every time I enter that command.

**Comment by z3ntu** [comment]
Did you reboot since running the command with the plugdev stuff? If no, do so and try again.

**Comment by benjaminblackbookish** [comment]
Yep. One thing I just realized is that when I do 'sudo apt install python3-razer razer-kernel-modules-dkms razer-daemon razer-doc' in the terminal it says process not found. I assume that means my daemon is not running, how would I go about starting it up again?

**Comment by z3ntu** [comment]
Can you make a screenshot of that error and upload it here?

**Comment by benjaminblackbookish** [comment]
Yup, sure. Here you go. http://i.imgur.com/ciaKfOn.png

**Comment by z3ntu** [comment]
The daemon is called `razer-daemon` instead of `razer-service` for a few releases now. Please use that name

**Comment by z3ntu** [comment]
And where did you get the "razer-service" name from?

**Comment by benjaminblackbookish** [comment]
Oh, I was browsing the YouTube comment section of this video hoping to maybe find a fix or something I had forgot to do. https://www.youtube.com/watch?v=3JrqJA8d5BE
Want me to try the same again but razer-daemon instead of razer-service?

**Comment by z3ntu** [comment]
Ah ^^ Yeah run `razer-daemon -Fv` and tell me if there's a success message (that says "Serving DBus") at the end

**Comment by benjaminblackbookish** [comment]
So I kinda dun-goofed, I copy and pasted the original command and then changed the things but it auot ran it without the -Fv tag and I closed the terminal but from what I saw it was a list of Razer Products and I did see something DBus in there but it was not Serving DBus I am pretty sure. I opened up another Terminal and ran it again and it came up with process not found again. Here is a screenshot of it and its the last line which I add the -Fv tag. http://i.imgur.com/14oM0wX.png

**Comment by terricain** [comment]
Change && to ;

**Comment by benjaminblackbookish** [comment]
Okie doke, I will post the results one moment.

**Comment by benjaminblackbookish** [comment]
http://i.imgur.com/PCeAiYe.png and Yes the line right below the last one says...

2017-08-24 17:00:50 | razer                          | INFO     | Serving DBus

**Comment by z3ntu** [comment]
Does polychromatic show the device?

**Comment by terricain** [comment]
also run

```
ls -l /sys/bus/hid/drivers/razer*/0*/
```

**Comment by benjaminblackbookish** [comment]
What do you mean z3ntu? If you mean when I open Polychromatic then no it says no devices detected but considering it shows my headset in the sound setting on Ubuntu.
I will run that command now terrycain and post the results.

**Comment by benjaminblackbookish** [comment]
http://i.imgur.com/PKpa33H.png No such directory? o.O Wut.

**Comment by terricain** [comment]
ok try
```
sudo modprobe razerkraken
lsmod | grep razer
```

**Comment by benjaminblackbookish** [comment]
Here is the outcome of both commands, I have an inkling that my drivers are not installed properly?

http://i.imgur.com/y0SeTJm.png

**Comment by z3ntu** [comment]
Look for info in the wiki for uefi secure boot, you have to turn that off, you can google something with "dkms secure boot"

**Comment by benjaminblackbookish** [comment]
Ok, do you disable UEFI secure boot via the BIOS? From googling it thats the only way I see of turning it off.

**Comment by terricain** [comment]
yeah its a bios setting somewhere

**Comment by benjaminblackbookish** [comment]
Ok, I will be right back with UEFI secure boot turned off and see if it changed anything while launching the program.

**Comment by benjaminblackbookish** [comment]
So I am typing on my phone now. I have deleted the PK key and changed the OS type to 'other OS' and not Windows and I have come up with a window before even booting into Ubuntu with the options. Ubuntu, advanced options for Ubuntu and systme setup. I will provide screenshots one second.

**Comment by benjaminblackbookish** [comment]
http://i.imgur.com/YPgrZfl.jpg
This is what comes up before I get to the Ubuntu login screen.

**Comment by benjaminblackbookish** [comment]
And thus is what it looks like on the part of my BIOS were I turn off Secure Boot. Should I change switching OS type to Windows UEFI mode and not other OS?

**Comment by benjaminblackbookish** [comment]
http://i.imgur.com/p4uxMcD.jpg

**Comment by benjaminblackbookish** [comment]
So I tried switching to Windows UEFI mode in my BIOS instead other OS but it is giving me the same thing. Its bringing me to a screen with three options and I pick Ubuntu but it brings me to a black purple screen.

**Comment by benjaminblackbookish** [comment]
I am stuck on a purple screen after disabling Secure Boot, any ideas?

**Comment by z3ntu** [comment]
Sorry, but I have zero experience with mainboards and secure boot as I've never used it. :/

**Comment by terricain** [comment]
what happens if you re-enable secure boot?

**Comment by benjaminblackbookish** [comment]
OK. So. With secure boot off I go straight to a page saying please unlock the disk but I am not able to enter a password and if I enable secure boot then I come to the page which says Ubuntu, Advanced options or system setup.

**Comment by terricain** [comment]
did you have windows on there with bitlocker?

**Comment by benjaminblackbookish** [comment]
And if I pick Ubuntu it brings to the unlock disk screen but all the text I type does not show up in the password box. It shows in the top left. Sort of like I am in a command line or  something.

**Comment by terricain** [comment]
odd, ive never come across anything like this

**Comment by benjaminblackbookish** [comment]
No, this drive was wiped before installing Ubuntu. There is another option on the area which I disabled secure boot, it is the OS type. Should I try switching it to other OS instead of Windows UEFI

**Comment by benjaminblackbookish** [comment]
If I pick Other OS I just get a purple screen...

**Comment by terricain** [comment]
it shouldnt matter, on mine i literally just turned secure boot off and it booted like nothing had changed

**Comment by terricain** [comment]
how fresh is the installation, as the only think im pretty sure would work is an install once secure boot is off, but your seeing grub so it cant be too bad

**Comment by benjaminblackbookish** [comment]
Of course something weird had happen the first time I timed of Secure Boot so I went the super awkward way and reinstalled Ubuntu with secure boot off. Now I am going to reinstall the Razer drivers and Polychromatic and come back with some results and the steps I went through exactly.

**Comment by benjaminblackbookish** [comment]
Ok so, I have reinstalled Polychromatic and the drivers and these are all the commands I used.

sudo add-apt-repository ppa:terrz/razerutils
sudo apt update
sudo apt install python3-razer razer-kernel-modules-dkms razer-daemon razer-doc
sudo gpasswd -a benjamin plugdev
sudo add-apt-repository ppa:lah7/polychromatic
sudo apt update
sudo apt install polychromatic

I am sure these are correct so I hope it works -_-

**Comment by terricain** [comment]
yeah looks about right

**Comment by benjaminblackbookish** [comment]
Well, it didn't. I see on the 'Device not recognized' page it says. Use 'modprobe' to bind a driver to a device. How would I do that? o.O

**Comment by terricain** [comment]
```
sudo modprobe razerkraken
lsmod | grep razer
```

**Comment by benjaminblackbookish** [comment]
Right. sudo modprobe razerkraken came back with nothing and lsmod | grep razer came back with;

razerkraken            20480  0
hid                   118784  3 hid_generic,usbhid,razerkraken

**Comment by terricain** [comment]
yeah if modprobe is successful it returns nothing.
ok so now
```
ls -l /sys/bus/hid/drivers/razer*/0*/
```

**Comment by benjaminblackbookish** [comment]
ls -l /sys/bus/hid/drivers/razer*/0*/ came back with;

ls: cannot access '/sys/bus/hid/drivers/razer*/0*/': No such file or directory

**Comment by benjaminblackbookish** [comment]
I remember during the install it said it downloaded somewhere else...

**Comment by terricain** [comment]
odd.

ls -l /sys/bus/hid/drivers/

**Comment by benjaminblackbookish** [comment]
Perfect! Came back with;

total 0
drwxr-xr-x 2 root root 0 Aug 24 20:02 hid-generic
drwxr-xr-x 2 root root 0 Aug 24 20:53 razerkraken

**Comment by terricain** [comment]
ls -l /sys/bus/hid/drivers/razerkraken/

**Comment by benjaminblackbookish** [comment]
Comes back with;

total 0
--w------- 1 root root 4096 Aug 24 20:59 bind
lrwxrwxrwx 1 root root    0 Aug 24 20:59 module -> ../../../../module/razerkraken
--w------- 1 root root 4096 Aug 24 20:59 new_id
--w------- 1 root root 4096 Aug 24 20:53 uevent
--w------- 1 root root 4096 Aug 24 20:59 unbind

**Comment by terricain** [comment]
ok so the headphones havent been bound to the driver. Did you reboot since you installed it?
Otherwise unplug them, plug them back in then re-run `ls -l /sys/bus/hid/drivers/razerkraken/` that "should" fix it

**Comment by benjaminblackbookish** [comment]
Oh drat, yeh I forgot to reboot. After rebooting should I run ls -l /sys/bus/hid/drivers/razerkraken/ again?

**Comment by terricain** [comment]
yeah

**Comment by benjaminblackbookish** [comment]
After restarting it comes back with this; 

total 0
lrwxrwxrwx 1 root root    0 Aug 24 21:04 0003:1532:0504.0006 -> ../../../../devices/pci0000:00/0000:00:12.0/usb4/4-5/4-5:1.3/0003:1532:0504.0006
--w------- 1 root root 4096 Aug 24 21:04 bind
lrwxrwxrwx 1 root root    0 Aug 24 21:09 module -> ../../../../module/razerkraken
--w------- 1 root root 4096 Aug 24 21:09 new_id
--w------- 1 root root 4096 Aug 24 21:04 uevent
--w------- 1 root root 4096 Aug 24 21:09 unbind

**Comment by terricain** [comment]
"Should" work now

**Comment by benjaminblackbookish** [comment]
Awesome, lemme test real quick.

**Comment by benjaminblackbookish** [comment]
Worked! Thank you man! You are beyond helpful. Just one last thing, for my birthday next month I am getting a Blackwidow X Chroma and a Deathadder Chroma. If I wear to do it for them it would be these commands right? What would I put instead of razerkraken for both of them?

sudo modprobe razerblackwidow _and_ razerdeathadder _(I think)_
lsmod | grep razer
ls -l /sys/bus/hid/drivers/
ls -l /sys/bus/hid/drivers/razerblackwidow _and_razerdeathadder/

**Comment by terricain** [comment]
nah, those command were just for me to diagnose things. You should just be able to plug them in and they'll magically work.

**Comment by benjaminblackbookish** [comment]
Oh gotcha ;) Thank you again!

**Comment by terricain** [comment]
Np :smile:
