### ISSUE TITLE
Razer Naga Classic Support

### ISSUE THREAD

**Issue by systmrrr** [openrazer/openrazer#369]
![razer-naga-classic-gallery-3__store_gallery](https://user-images.githubusercontent.com/24730797/29837918-44aaabce-8d02-11e7-8573-833e046ece53.png)

Razer Naga Classic Support Please :D
Thanks

**Comment by z3ntu** [comment]
The output of `lsusb | grep 1532` please

**Comment by systmrrr** [comment]
Bus 002 Device 003: ID 1532:0040 Razer USA, Ltd

**Comment by systmrrr** [comment]
;)

**Comment by systmrrr** [comment]
i will send screenshot

**Comment by z3ntu** [comment]
@z3ntu
> Secondly, is this mouse really called "Razer Naga Classic" because according to my spreadsheet it's called the Razer Naga 2014. Because the 0040 mouse is already supported by the driver.

@systmrrr 
> But can not assign tasks to keys

(just that the conversation is complete)

**Comment by systmrrr** [comment]
![secim_004](https://user-images.githubusercontent.com/24730797/29870673-6f219040-8d91-11e7-851b-47430f9523c3.jpg)
No key commands

**Comment by terricain** [comment]
Yeah key bindings are a work in progress and long overdue, when I get time to finish the new macro functionality this will work.

**Comment by systmrrr** [comment]
thank you. good work

**Comment by Adi118** [comment]
@terrycain is there option to remap keys in razer mices yet ?

**Comment by terricain** [comment]
@Adi118 Nope not yet
