### ISSUE TITLE
Razer Naga Classic Support

### ISSUE THREAD

**Issue by z3ntu** [openrazer/openrazer#370]
GitHub kinda died so I recreated this issue:

GitHub, [29.08.17 21:38]
🐛 New issue razer-drivers#369 Razer Naga Classic Support (https://github.com/terrycain/razer-drivers/issues/369)
by @systmrrr (https://github.com/systmrrr)

![razer-naga-classic-gallery-3__store_gallery](https://user-images.githubusercontent.com/24730797/29837918-44aaabce-8d02-11e7-8573-833e046ece53.png) 
 
Razer Naga Classic Support Please :D

Reply to this message to post a comment on GitHub.

GitHub, [29.08.17 21:39]
💬 New comment on razer-drivers#369 Razer Naga Classic Support (https://github.com/terrycain/razer-drivers/issues/369#issuecomment-325756371)
by @z3ntu (https://github.com/z3ntu)

The output of `lsusb | grep 1532' please

Reply to this message to post a comment on GitHub.

GitHub, [29.08.17 21:41]
💬 New comment on razer-drivers#369 Razer Naga Classic Support (https://github.com/terrycain/razer-drivers/issues/369#issuecomment-325756917)
by @systmrrr (https://github.com/systmrrr)

Bus 002 Device 003: ID 1532:0040 Razer USA, Ltd 

Reply to this message to post a comment on GitHub.

**Comment by z3ntu** [comment]
@systmrrr First of all, GitHub let your issue disappear 😄 
Secondly, is this mouse really called "Razer Naga Classic" because according to my spreadsheet it's called the Razer Naga 2014. Because the 0040 mouse is already supported by the driver.

**Comment by systmrrr** [comment]
But can not assign tasks to keys

**Comment by z3ntu** [comment]
Okay #369 is back 😃 Let's talk more there
