### ISSUE TITLE
razer-daemon trouble

### ISSUE THREAD

**Issue by 0xspade** [openrazer/openrazer#379]
![screenshot at 2017-09-08 15-36-10](https://user-images.githubusercontent.com/18681023/30201022-d56d7582-94ab-11e7-81a6-3b643c4cf697.png)

i tried to upload this amd64 and i386 of razer-daemon but it always failed. which i dont know why :(

**Comment by z3ntu** [comment]
please use the repository and do not invoke dpkg manually but use apt.

**Comment by 0xspade** [comment]
i cant add repository thou parrot sec restrict adding a repository..
>`do not invoke dpkg manually but use apt.`

What do u mean by that?

**Comment by z3ntu** [comment]
I meant that you should install it via the repository=apt. Anyways then you should download every single Deb manually and install them with dpkg. Then run the apt install -f command to get the rest of the dependencies

**Comment by z3ntu** [comment]
You can find all files at http://download.opensuse.org/repositories/hardware:/razer/ (use the correct Debian version please)
