### ISSUE TITLE
Razer Naga and Tartarus

### ISSUE THREAD

**Issue by ArtoriasEdgeworth** [openrazer/openrazer#38]
The Razer products Naga and Tartarus aren't listed under the supported group.
Hate to be the guy to ask for everything, but if these were made compatible, it would be very greatly appreciated!!

**Comment by ArtoriasEdgeworth** [comment]
My mistake, Orbweaver, not Tartarus. And I just noticed that there is a thread dedicated to both.
Very sorry!

**Comment by terricain** [comment]
No problem. It happens.

**Comment by terricain** [comment]
There isn't an issue for Naga. You willing to help add support for it?

**Comment by ArtoriasEdgeworth** [comment]
I'm a complete inept when it comes to programming, save for basic RobotC.
I'd love to, but I don't think I'd be of much use.

-Nathan A. Johnson

**Comment by claell** [comment]
You don't need to write a single line of code. You just need to capture some packages with Wireshark. There is also a tutorial. Probably you can do that.

**Comment by ArtoriasEdgeworth** [comment]
I can indeed.

-Nathan A. Johnson
