### ISSUE TITLE
wont install Ubuntu 17.10

### ISSUE THREAD

**Issue by William-Talkington** [openrazer/openrazer#384]
Just a heads up.  seems like Artful is using a version of python .1 off from the dependancy of the deb file in launchpad I know its still in beta but it would be helpful to me to correct this.  thank you

**Comment by lah7** [comment]
I just tried on Ubuntu MATE 17.10 (Daily Build) -- installs and works with no problems. The packaging isn't explicitly depending on any Python version either.

Try the daily PPA:

```
sudo add-apt-repository ppa:openrazer/daily
sudo apt update
sudo apt install openrazer-meta
```

Note that the daily packages are going through a package rename, so front-end apps may temporarily break. (If you happen to be using [Polychromatic](https://github.com/lah7/polychromatic), use its daily PPA `lah7/polychromatic-daily` for now).
