### ISSUE TITLE
Installed from site.... nothing?

### ISSUE THREAD

**Issue by jjgrady12** [openrazer/openrazer#392]
New to Linux Ubuntu - 16.04 - Installed the stable release according to directions - reboot - no change - mouse still out of control.. Am I supposed to see an APP or be able to command line settings?

Thanks!

**Comment by z3ntu** [comment]
This project only makes a dbus endpoint for a applications (+the python library) to use. You will want to install a graphical front end which are listed both on the website and also in the readme.
