### ISSUE TITLE
The following packages have been kept back: polychromatic

### ISSUE THREAD

**Issue by binarykitchen** [openrazer/openrazer#396]
Always seeing the above warning when trying to upgrade with apt-get on latest Ubuntu.

Even `apt-get dist-upgrade` doesn't make a difference. Any advice?

**Comment by z3ntu** [comment]
Full log from apt please
And have you read https://github.com/openrazer/openrazer/releases/tag/v2.0.0 ?

**Comment by binarykitchen** [comment]
ah, that link helped - all good now, thanks dude
