### ISSUE TITLE
No dependency loop with yaourt any more

### ISSUE THREAD

**Issue by simonszu** [openrazer/openrazer#397]
Hi,

the website informs me that i should rather use pacaur instead of yaourt on Arch Linux to install `openrazer-meta`, due to an dependency loop.

I tried with a fresh Arch install and up-to-date package, and the installation with yaourt went without any problems. So, maybe i am able to tell you that this problem doesn't occur any more and that the installation with yaourt is possible again.

**Comment by z3ntu** [comment]
Was there a yaourt update since [May](https://github.com/openrazer/openrazer/issues/244#issuecomment-299528213)?

**Comment by simonszu** [comment]
Yes, yaourt 1.9 was released on July 19th, and the last yaourt buildfile update in the Arch User Repository is from September 19th.

**Comment by z3ntu** [comment]
Yaourt is still generally a bad AUR helper but we'll remove it soon from the website. But if there's one more report about yaourt not working, I'll put it back up 😉
