### ISSUE TITLE
2016 Blade keyboard has 16 columns, not 15

### ISSUE THREAD

**Issue by calder** [openrazer/openrazer#398]
On the 2016 Blade keyboard, the right arrow key is row 5 col 15, but the openrazer Python library thinks the keyboard's dimensions are 6x15. This prevents setting the right arrow key's color with
```python
device.fx.advanced.matrix[5,15] = ...
```
and means its color isn't cleared by
```python
device.fx.advanced.matrix.reset()
```

After executing
```python
device.fx.advanced.matrix = openrazer.client.fx.Frame((6,16))
```
both manual color setting and `reset()` work as expected.

**Comment by terricain** [comment]
@calder Thanks, what usb vid:pid you got?

**Comment by calder** [comment]
Is that device.serial?

**Comment by terricain** [comment]
@calder Nah the line in lsusb that corrosponds to your device

**Comment by calder** [comment]
Ah, this?
```
Bus 001 Device 004: ID 1532:0224 Razer USA, Ltd
```

**Comment by terricain** [comment]
@calder Yeah, will fix on weekend

**Comment by calder** [comment]
Thanks @terrycain!

**Comment by z3ntu** [comment]
@calder Can you please test https://github.com/openrazer/openrazer/tree/fix_bladematrix ?
