### ISSUE TITLE
Layout changing since install

### ISSUE THREAD

**Issue by alkeryn** [openrazer/openrazer#411]
Before install it was in azerty
but now it is always set in qwerty after i use setxkbamp in my autostart script
and i have to use setxkbap again
also sometime it fail shutdown and i have to force shutdown
and quiting X make it crash

**Comment by alkeryn** [comment]
Though sometime it boots in azerty and other times in qwerty so wtf

**Comment by z3ntu** [comment]
I am pretty sure that our kernel driver doesn't interfere with keyboard layout... Do you have any logs you could show us?

**Comment by alkeryn** [comment]
Well i couldn't really fixed it so i wrote a small bash script to set to fr if it isn't at boot time
though it occur randomly so i don't really know why ^^

**Comment by z3ntu** [comment]
🤷‍♂️ 

(if anybody else experiences the same issue, please write a comment here 🙂)
