### ISSUE TITLE
Cannot control Logo LED on new Razer laptops

### ISSUE THREAD

**Issue by KazWolfe** [openrazer/openrazer#413]
The logo LED on the Blade Pro 2017 seems to act a bit oddly.

Writing `0` to `/sys/bus/hid/drivers/razerkbd/[...]/logo_led_state` will set the LED to on. 

Writing `1` will result the following log entry in dmesg, and will set the LED state to on similar to `0`:

    razerkbd: Command not supported. Start Marker: 05 id: ff Num Params: 03 Reserved: 03 Command: 02 Params: 01040100000000000000000000000000 .

Writing `2` will result in the LED pulsating similar to a sleep mode.

**Comment by KazWolfe** [comment]
Looks like we can't turn off the LED right now for whatever reason. It also looks like the Blade Pro isn't on the inverted LED state.

Adding it there breaks the pulse though. Interesting...

**Comment by KazWolfe** [comment]
Packet capture results from Synapse:

From Synapse

| Start | ID | Reserved | Num Params | Class | Command | Sub Cmd |  Params  | Note |
|---|---|---|---|---|---|---|---|---|
| `00` | `3f` | `00 00 00` | `03` | `03` | `00` | `01` | `04 00 00` | Logo Light Off (synapse) |
| `00` | `3f` | `00 00 00` | `03` | `03` |   `00` | `01` | `04 01 00` | Logo Light On (synapse) |

From razerkbd (with #414's patch)

| Start | ID | Reserved | Num Params | Class | Command | Sub Cmd |  Params  | Note |
|---|---|---|---|---|---|---|---|---|
| `00` | `ff` | `00 00 00` | `03` | `03` | `02` | `01` | `04 01 00` | Logo Light Off (razerkbd) |
| `00` | `ff` | `00 00 00` | `03` | `03` | `02` | `01` | `04 00 00` | Logo Light On (razerkbd) |
| `00` | `ff` | `00 00 00` | `03` | `03` | `02` | `01` | `04 02 00` | Logo Light Pulse (razerkbd) |

Does this mean 414 is unnecessary/bad? It looks like different commands are being used now, even...

**Comment by terricain** [comment]
Hmm, Ok well I believe pulse is an artifact of copying and pasting firmware, if it works, I dont see a reason not to allow it ;-) as then we can claim #BetterThanSynapse.

Do you have the actual pcaps, for those 2 captures? I have a script that will grab all that with the updated headers

**Comment by marvin-roesch** [comment]
I'm currently having issues with this as well. I'd simply like to turn off the logo LED completely. Is there some option to get the raw (correct) packet to the device?

**Comment by KazWolfe** [comment]
As of now, @PaleoCrafter, you're stuck using Synapse. If you're feeling a bit more adventurous, you may be able to use `hidraw` but I would have no idea how to do that effectively.

I know a couple people are investigating this bug, so we will hopefully have a fix pushed out soon.

**Comment by marvin-roesch** [comment]
Great to know that. I've looked into using `hidraw` but it appears a little too risky to me. In my eternal wiseness, I of course completely dumped Windows before installing Arch. I guess it's time to whip up a VM, assuming I can manipulate the settings from there.

**Comment by KazWolfe** [comment]
You can, of course, use Virtualbox to send commands to your system. That's how we get packet captures. :)

I would advise you grab another keyboard though. When you bind the Razer device to your VM, the VM *will* take exclusive control over the keyboard.

**Comment by KazWolfe** [comment]
Confirmed with Razer Blade Stealth (Late 2017) as well. See above linked issue.
