### ISSUE TITLE
Heatmap feature seems missing.

### ISSUE THREAD

**Issue by songandsilence** [openrazer/openrazer#416]
First used keyboard driver when it was from pez2011. Heatmap was my favorite effect. Seems to be missing. Ubuntu 17.10, Blackwidow Chroma.

Hope I'm not being stupid.

**Comment by z3ntu** [comment]
I am not aware of any heatmap but I have joined the project after it was split from the pez2001 repo. Could you explain what you mean?

**Comment by lah7** [comment]
Two things come to mind, I think it's the former:

* The original custom effect where pressing keys caused the colours to move to that area... sort of like a heatmap.
* **Or...** a heatmap feature to see how much a key is used, but I don't remember either projects actually implementing this.

**Comment by z3ntu** [comment]
@songandsilence bump

**Comment by songandsilence** [comment]
I'm talking about the effect, from the pez2001 repo.

**Comment by terricain** [comment]
@songandsilence There's a reimplementation of that effect in a test branch though it's not ready

**Comment by songandsilence** [comment]
How can i try it out?
