### ISSUE TITLE
Uninstallable on Ubuntu 17.10

### ISSUE THREAD

**Issue by flexiondotorg** [openrazer/openrazer#418]
It is not possible to install `openrazer-meta` on Ubuntu 17.10 system using your PPA. This is due to `python3-evdev` is not installable in 17.10 because it's `debian/control` file claims it works on Python 3.5 only but Python 3.6 is the only Python3 version available for 17.10.

**Comment by z3ntu** [comment]
Please follow the instructions [here](https://github.com/openrazer/openrazer/releases/tag/v2.0.0) if you haven't already. It seems you're still using the old PPA.

**Comment by flexiondotorg** [comment]
Yeah, this issue was due to a conflicting PPA on the system.
