### ISSUE TITLE
Group membership ID error

### ISSUE THREAD

**Issue by r3pek** [openrazer/openrazer#430]
Right now openrazer-daemon checks for group membership for the user running the daemon by parsing the file /etc/group. This is wrong and should not be done since there are other ways to specify group membership for a user (ldap, sssd, etc), in which case, the group membership isn't correctly identified.
(I personally use pam_sssd for group membership and I was already in the plugdev group, but the daemon kept saying that I wasn't member)

**Comment by terricain** [comment]
Calm down, it uses the built in module to check that. Wether that is right or wrong is here nor there. You could of just asked can the group membership lookup be expanded, rather than typing a whole paragraph

**Comment by r3pek** [comment]
I normally tend to explain the issue and the usecase, not just the problem itself. :)

**Comment by z3ntu** [comment]
@r3pek 
1. I don't find any mention of `/etc/group` in our repo.
2. I am not at all familiar with LDAP, SSSD etc
3. If you can provide us with another way / better way of checking group membership than what we currently have, feel free.

**Comment by r3pek** [comment]
Hi @z3ntu 
1. True. gr_mem just returns members from the file /etc/group (nothing else)
2. No need to ;)
3. change https://github.com/openrazer/openrazer/blob/master/daemon/openrazer_daemon/daemon.py#L183-L184 to
`return grp.getgrnam('plugdev').gr_gid in os.getgroups()`

That should do it ("totally" untested):
```
[r3pek@trinity ~]$ id
uid=803800001(r3pek) gid=803800000(admins) groups=803800000(admins),10(wheel),50(games),78(kvm),150(wireshark),616(cdemu),619(plugdev),803800003(users),803800011(email)
[r3pek@trinity ~]$ grep plugdev /etc/group
plugdev:x:619:
[r3pek@trinity ~]$ python
Python 3.6.3 (default, Oct 24 2017, 14:48:20) 
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import os
>>> import grp
>>> grp.getgrnam('plugdev').gr_gid in os.getgroups()
True
>>> 
```

**Comment by z3ntu** [comment]
Please try https://github.com/z3ntu/openrazer/commit/c708d285630e16c1e77dcb61ea8075569d307987

**Comment by r3pek** [comment]
@z3ntu works.
