### ISSUE TITLE
Razer Basilisk support request

### ISSUE THREAD

**Issue by ShneekeyTheLost** [openrazer/openrazer#433]
The Basilisk is the mouse pitched at the FPS crowd, having a DPI clutch on the thumb for sniping. Currently not supported. I'm not really familiar with VMs and not really comfortable running a VM windows for some of what you are looking for, but here's what I have so far:
```
Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        2
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      0 No Subclass
      bInterfaceProtocol      2 Mouse
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength      94
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x83  EP 3 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0008  1x 8 bytes
        bInterval               8
```
```
lrwxrwxrwx 1 root root   9 Nov  6 10:55 usb-Razer_Razer_Basilisk-event-mouse -> ../event7
lrwxrwxrwx 1 root root   9 Nov  6 10:55 usb-Razer_Razer_Basilisk-if01-event-kbd -> ../event8
lrwxrwxrwx 1 root root  10 Nov  6 10:55 usb-Razer_Razer_Basilisk-if02-event-kbd -> ../event20
lrwxrwxrwx 1 root root   9 Nov  6 10:55 usb-Razer_Razer_Basilisk-mouse -> ../mouse2
```

**Comment by z3ntu** [comment]
Please send us the product & model number of the device for documentation reasons.
And it would be incredibly helpful if you could set up a [Windows VM (eg with VirtualBox)](https://github.com/openrazer/openrazer/wiki/Reverse-Engineering-USB-Protocol#prerequisites) as it could be very tedious otherwise

**Comment by ShneekeyTheLost** [comment]
Model No: RZ01-0233
                Gaming Mouse
Product No: RZ201-02330100

**Comment by terricain** [comment]
Yeah not much else we can do unless you get vbox runnign with windows and synapse recognising the mouse

**Comment by r3pek** [comment]
PCAP captured while doing all sorts of stuff (except save profiles to the onboard memory).

[basilisk_usb.pcap.pcapng.txt](https://github.com/openrazer/openrazer/files/1526668/basilisk_usb.pcap.pcapng.txt)

**Comment by z3ntu** [comment]
usb vid:pid 1532:0064 based on information by @r3pek

**Comment by enthusiasmus** [comment]
I bought a razer basilisk and want to use it on linux! As a developer I want to contribute to openrazer to support the basilisk. How can I help?

Although there are already all needed informations above from other users, here are some logs anyways:

**dmesg output** 
```
[21967.985952] usb 3-2: new full-speed USB device number 5 using xhci_hcd
[21968.126978] usb 3-2: New USB device found, idVendor=1532, idProduct=0064
[21968.126979] usb 3-2: New USB device strings: Mfr=1, Product=2, SerialNumber=0
[21968.126980] usb 3-2: Product: Razer Basilisk
[21968.126980] usb 3-2: Manufacturer: Razer
[21968.127804] input: Razer Razer Basilisk as /devices/pci0000:00/0000:00:14.0/usb3/3-2/3-2:1.0/0003:1532:0064.0008/input/input28
[21968.127886] hid-generic 0003:1532:0064.0008: input,hidraw2: USB HID v1.11 Mouse [Razer Razer Basilisk] on usb-0000:00:14.0-2/input0
[21968.129001] input: Razer Razer Basilisk as /devices/pci0000:00/0000:00:14.0/usb3/3-2/3-2:1.1/0003:1532:0064.0009/input/input29
[21968.186201] hid-generic 0003:1532:0064.0009: input,hidraw3: USB HID v1.11 Keyboard [Razer Razer Basilisk] on usb-0000:00:14.0-2/input1
[21968.186733] input: Razer Razer Basilisk as /devices/pci0000:00/0000:00:14.0/usb3/3-2/3-2:1.2/0003:1532:0064.000A/input/input30
[21968.246274] hid-generic 0003:1532:0064.000A: input,hidraw4: USB HID v1.11 Keyboard [Razer Razer Basilisk] on usb-0000:00:14.0-2/input2
```

**journalctl -b | grep -i Razer**
```
Jan 14 18:20:21 Stand-PC kernel: usb 3-2: Product: Razer Basilisk
Jan 14 18:20:21 Stand-PC kernel: usb 3-2: Manufacturer: Razer
Jan 14 18:20:21 Stand-PC kernel: input: Razer Razer Basilisk as /devices/pci0000:00/0000:00:14.0/usb3/3-2/3-2:1.0/0003:1532:0064.0008/input/input28
Jan 14 18:20:21 Stand-PC kernel: hid-generic 0003:1532:0064.0008: input,hidraw2: USB HID v1.11 Mouse [Razer Razer Basilisk] on usb-0000:00:14.0-2/input0
Jan 14 18:20:21 Stand-PC kernel: input: Razer Razer Basilisk as /devices/pci0000:00/0000:00:14.0/usb3/3-2/3-2:1.1/0003:1532:0064.0009/input/input29
Jan 14 18:20:21 Stand-PC kernel: hid-generic 0003:1532:0064.0009: input,hidraw3: USB HID v1.11 Keyboard [Razer Razer Basilisk] on usb-0000:00:14.0-2/input1
Jan 14 18:20:21 Stand-PC kernel: input: Razer Razer Basilisk as /devices/pci0000:00/0000:00:14.0/usb3/3-2/3-2:1.2/0003:1532:0064.000A/input/input30
Jan 14 18:20:21 Stand-PC kernel: hid-generic 0003:1532:0064.000A: input,hidraw4: USB HID v1.11 Keyboard [Razer Razer Basilisk] on usb-0000:00:14.0-2/input2
Jan 14 18:20:21 Stand-PC openrazer-daemon[15123]: 2018-01-14 18:20:21 | razer                          | DEBUG    | Device event [add]: /devices/pci0000:00/0000:00:14.0/usb3/3-2/3-2:1.1/0003:1532:0064.0009
etc.
```

**tail ~/.local/share/openrazer/logs/razer.log**
```
2018-01-14 18:20:21 | razer                          | DEBUG    | Device event [add]: /devices/pci0000:00/0000:00:14.0/usb3/3-2/3-2:1.1/0003:1532:0064.0009
2018-01-14 18:20:21 | razer                          | DEBUG    | Device event [add]: /devices/pci0000:00/0000:00:14.0/usb3/3-2/3-2:1.2/0003:1532:0064.000A
2018-01-14 18:20:21 | razer                          | DEBUG    | Device event [add]: /devices/pci0000:00/0000:00:14.0/usb3/3-2/3-2:1.0/0003:1532:0064.0008
```

**dkms install openrazer-driver/1.0.0**
`Module openrazer-driver/1.0.0 already installed on kernel 4.9.0-3-amd64/x86_64`

**openrazer-daemon -Fv**
```
Starting daemon.
2018-01-14 18:33:08 | razer                          | INFO     | Initialising Daemon (v2.2.0). Pid: 19498
2018-01-14 18:33:08 | razer.screensaver              | INFO     | Initialising DBus Screensaver Monitor
2018-01-14 18:33:08 | razer                          | DEBUG    | Loaded device specification: RazerAbyssus ---------------------------- (1532:0042)
2018-01-14 18:33:08 | razer                          | DEBUG    | Loaded device specification: RazerAbyssus1800 ------------------------ (1532:0020)
etc.
```

**Comment by ndom91** [comment]
Do you guys need any further info? I have a Razer Basilisk I'd like to have supported here as well. Willing to help in any way possible. 

Do we know whats holding basilisk support back?

**Comment by z3ntu** [comment]
The daemon does not have support for the functionality that the new devices (see the milestone `sw-based lighting`) require. Contributions welcome.

**Comment by enthusiasmus** [comment]
@ndom91 I started to work on a pull request, but there where issues creating the daemon support. Lets meet in telegram and discuss further steps together with z3ntu?

**Comment by z3ntu** [comment]
You can join our community chat, either via Telegram (https://t.me/joinchat/A1E4RT9TxhnxyetdQCSj7Q) or via Matrix (https://matrix.to/#/#openrazer:matrix.org)

**Comment by amalic** [comment]
+1 
would love to turn off the color on the mouse or change it to something permanent

Let me know if i can help. I have installed Win10 on a seperate SSD and can boot it up any time.

**Comment by ndom91** [comment]
Sorry didn't see any of the new posts here until now.

Still need any help? Basilisk owner and daily ubuntu user here :smile:

**Comment by NyleCohen** [comment]
I just bought a razer basilisk and am a daily Linux user. I have a windows machine aswell with synapse installed and is happy to help!

**Comment by Severus157** [comment]
I would also be happy to help if anyone would add support for the Basilisk Mouse. Just got it under the impression it would be already supported.
I am on Arch Linux on my main System. But I can get a Windows Machine with Synapse ready if needed.

**Comment by openhoat** [comment]
+1

**Comment by hokkaidosuneku** [comment]
+1 Would love to see support. May I know what exactly is the issue with the daemon and if there's something that I can provide to help out? @z3ntu

**Comment by NyleCohen** [comment]
I also would love to help with support. I mainly use Ubuntu but have a Windows PC also. I have synapse installed and working on that PC as well.

**Comment by ovalent** [comment]
HI guys, Basilisk owner and Linux Mint user. If you need support let me know. I would be happy to help.

**Comment by ghost** [comment]
So it seems a lot of people would like to help, but it's not clear how. Kind of a shame...

**Comment by m0ellemeister** [comment]
I just got my Basilisk. So +1 for support for this Device. Is there any documentation available how to gather the needed informations for the Devs?

**Comment by ghost** [comment]
@m0ellemeister: I found some info in the [repo wiki](https://github.com/openrazer/openrazer/wiki/Reverse-Engineering-USB-Protocol). Not sure why it's not directly mentioned in the readme though. There are also some [scrips](https://github.com/openrazer/openrazer/tree/master/scripts/wireshark) that might help.
I won't be able to help with this anytime soon unfortunately, I cannot get virtualbox to work without constant system freezes.

edit: Maybe there is a mouse with a similar implementation that can be reused for the Basilisk.

**Comment by m0ellemeister** [comment]
@ceLoFaN Thanks for the heads-up. Maybe I'll find some time to spend on this.

**Comment by 0pLuS0** [comment]
I just bought a Basilisk, I'd like to see support for it too in Linux...

**Comment by florealcab** [comment]
I buy a basilisk mouse too and I would be happy to have support for it on linux :)

**Comment by razumzhir0** [comment]
+1 Basilisk user. Weird exemption...

**Comment by Ninjamannn** [comment]
+1 Basilisk user
give support for a good mouse on a good ubuntu!

**Comment by z3ntu** [comment]
@tempelgogo Please stop "reacting" on every comment here...

**Comment by b-jazz** [comment]
And while we're on the subject, can all people that want openrazer for basilisk please stop adding new comments saying that you want your mouse to be supported? I'm watching this issue so that I can get a notification if/when support is ever implemented. The "me too" comments are just noise. If you want support, you can indicate so by giving a thumbs up to the original issue report. That won't trigger an email notification and everyone will be happier. Thanks!
