### ISSUE TITLE
Packages unavailable on yakkety (Ubuntu 16.10)

### ISSUE THREAD

**Issue by oliverseal** [openrazer/openrazer#434]
The sites say that 16.04 and newer are supported, but the Packages on the ppa for 16.10 are empty. They're available in zesty and and xenial, but no love for 16.10. Is this intentional?

**Comment by z3ntu** [comment]
Ubuntu 16.10 is EOL already.

**Comment by terricain** [comment]
@lah7 is yakkety still on laumchpad? No harm turning it on if it's there

**Comment by z3ntu** [comment]
Am not Luke^^, but not that I see 
![image](https://user-images.githubusercontent.com/3768500/32461123-29502ba6-c335-11e7-86fd-6d624f06b080.png)

**Comment by terricain** [comment]
Ahh yeah am on phone otherwise I'd look. Yeah main reason is laumchpad isn't offering us 16.10.

**Comment by oliverseal** [comment]
k. Well, at least maybe I'll help someone searching on google.

**Comment by lah7** [comment]
16.10 Yakkety is indeed EOL, and Launchpad won't be building for it anymore.

However, you could edit the relevant source file in your `/etc/apt/sources.list.d/` directory and change "yakkety" to "zesty" or "artful".. You can also do this from the **Software & Updates** program. Either way, you'll be able to install the packages from another (supported) release.
