### ISSUE TITLE
failed launch RazerGenie

### ISSUE THREAD

**Issue by bcmmbc122333** [openrazer/openrazer#438]
everytime I try to launch razer commander or razergenie they dont work. This is the error given from razergenie. I am currently using manjaro so that could be causing the error, but I thought I would check here first.

```
● openrazer-daemon.service - Daemon to manage razer devices in userspace
   Loaded: loaded (/usr/lib/systemd/user/openrazer-daemon.service; disabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Wed 2017-11-08 18:18:14 CST; 182ms ago
     Docs: man:openrazer-daemon(8)
  Process: 1039 ExecStart=/usr/bin/openrazer-daemon -Fv (code=exited, status=1/FAILURE)
 Main PID: 1039 (code=exited, status=1/FAILURE)

Nov 08 18:18:13 Brennen-PC systemd[760]: Starting Daemon to manage razer devices in userspace...
Nov 08 18:18:14 Brennen-PC systemd[760]: Started Daemon to manage razer devices in userspace.
Nov 08 18:18:14 Brennen-PC openrazer-daemon[1039]: 2017-11-08 18:18:14 | razer                          | INFO     | Initialising Daemon (v2.0.0). Pid: 1039
Nov 08 18:18:14 Brennen-PC openrazer-daemon[1039]: 2017-11-08 18:18:14 | razer                          | CRITICAL | User is not a member of the plugdev group
Nov 08 18:18:14 Brennen-PC systemd[760]: openrazer-daemon.service: Main process exited, code=exited, status=1/FAILURE
Nov 08 18:18:14 Brennen-PC systemd[760]: openrazer-daemon.service: Failed with result 'exit-code'.
```

**Comment by z3ntu** [comment]
Your user is not a member of the plugdev group. To fix it, please run `sudo gpasswd -a <YOUR-USER> plugdev`.

**Comment by bcmmbc122333** [comment]
now its launching but no devices are being detected by daemon. I am using manjaro with a deathadder chroma.

**Comment by z3ntu** [comment]
Can you please run `sudo dkms install razer_chroma_driver/1.0.0` and post the output?

**Comment by bcmmbc122333** [comment]
Creating symlink /var/lib/dkms/razer_chroma_driver/1.0.0/source ->
                 /usr/src/razer_chroma_driver-1.0.0

DKMS: add completed.
Error! echo
Your kernel headers for kernel 4.9.60-1-MANJARO cannot be found at
/usr/lib/modules/4.9.60-1-MANJARO/build or /usr/lib/modules/4.9.60-1-MANJARO/source.

**Comment by z3ntu** [comment]
That means you have to install the kernel headers for your running kernel. (which seems to be `linux49-headers` on manjaro)

**Comment by bcmmbc122333** [comment]
works perfect! Thanks!

**Comment by z3ntu** [comment]
Great! And next time please take a look at our [troubleshooting page](https://github.com/openrazer/openrazer/wiki/Troubleshooting) 😉
