### ISSUE TITLE
Daemon support for Abyssus 2014

### ISSUE THREAD

**Issue by claell** [openrazer/openrazer#44]
Currently there seems to be only driver support for it.

**Comment by terricain** [comment]
Working on fixing some FN issues in keyboard, but someones already alerted me to this, also need to add my mamba wired and the mamba te so will do them in one go. Should be done once i've got this latest bit of code tested and pushed.

**Comment by terricain** [comment]
Should be in daemon now, just adding some more stuff then will push out some more packages

**Comment by claell** [comment]
Thanks, will test when I am at my device with Abyssus again.

**Comment by terricain** [comment]
No problem, of course up date to the latest packages, not sure if the python library supports everything fully but that can be a seperate issue.

**Comment by claell** [comment]
Device is displayed now in Polychromatic. So I assume the support is successfully implemented.
