### ISSUE TITLE
Please Support CentOS (Version 7)

### ISSUE THREAD

**Issue by RisingPhorce** [openrazer/openrazer#444]
Please consider supporting the distro CentOS 7.
Thanks!

**Comment by z3ntu** [comment]
CentOS doesn't contain Python3 so we can't run our daemon on it. Duplicate of #248, #363 and #408

**Comment by philippeback** [comment]
With software collections python3 is fully supported on CentOS7

**Comment by moozhub** [comment]
I built packages for CentOS 7 forever ago... just enable the EPEL repository and install openrazer-meta from https://github.com/moozhub/yum-repo-mooz ... I haven't had a single issue with it. I haven't really found a reason to build the latest version yet, but if someone wishes me to do so I don't have a problem doing it..

**Comment by philippeback** [comment]
I forked that repo since I wasn't able to get the src rpm from it. Added the needed stuff as a local repo to be able to do a build from the sources.

There is still an issue which is that keys are not registering on my CentOS7.3.

Investigating.

**Comment by moozhub** [comment]
As per the issue you opened, I built the repodata so you can pull the SRPMs down if you so desire.

**Comment by philippeback** [comment]
Cool. Thx.
