### ISSUE TITLE
ConsoleKit support

### ISSUE THREAD

**Issue by ivazqueznet** [openrazer/openrazer#456]
Attached is a script that generates a udev rules file that gives the logged-in user access to Razer devices without needing to belong to plugdev. It should work on any modern distro that uses udev and ConsoleKit. Pass it the directory containing the driver headers and it outputs the rules file to stdout.

    bash genrazerudev.sh openrazer/driver > 60-razer-daemon.rules
    sudo cp 60-razer-daemon.rules /etc/udev/rules.d

[genrazerudev.sh.txt](https://github.com/openrazer/openrazer/files/1499953/genrazerudev.sh.txt)

**Comment by z3ntu** [comment]
You tested it and it works?

**Comment by ivazqueznet** [comment]
Sure did.

```
$ getfacl /dev/input/mouse2 
getfacl: Removing leading '/' from absolute path names
# file: dev/input/mouse2
# owner: root
# group: plugdev
user::rw-
user:ignacio:rw-
group::rw-
mask::rw-
other::---
```

**Comment by z3ntu** [comment]
Are you sure this is also applying on the sysfs files the driver is creating (so e.g. in `/sys/bus/hid/drivers/razerkbd/0*/`)?
If have read something recently, that the uaccess stuff doesn't work in sysfs.

**Comment by ivazqueznet** [comment]
It doesn't appear to be affecting sysfs. Let me do a bit more work on it...

**Comment by ivazqueznet** [comment]
sysfs doesn't support ACLs, so this can't affect that. Never mind...

**Comment by z3ntu** [comment]
Yes, that's what my own research resulted in :(

**Comment by z3ntu** [comment]
Thanks for trying though 😃

**Comment by ivazqueznet** [comment]
It could work if the driver created /dev entries instead, but more work.
