### ISSUE TITLE
Razer blackwidow ultimate 2014 macro keys not working

### ISSUE THREAD

**Issue by jancoow** [openrazer/openrazer#458]
Hi there.

I'm facing an issue with my razer blackwidow ultimate 2014. I can't enter the macro recording on the keyboard. The macro key doesn't blink when I press fn + f9. Also, gaming mode and brightness control doesn't work when pressing fn + f10/f11/f12. I can however edit the brightness through the client application. 

When monitoring the key events generated I get this:
**fn + f9:** xf86launch9
**fn + f10:** Don't know
**fn + f11:** Rec
**fn + f12**: Don't know

**Comment by philippeback** [comment]
Is the keyboard in driver mode?

Check https://github.com/openrazer/openrazer/wiki/Using-the-keyboard-driver#device_mode---set-device-mode

Once I turned the driver mode on, macros worked.
