### ISSUE TITLE
BlackWidow TE Chroma v2 - No backlight until password entered.

### ISSUE THREAD

**Issue by etrigan63** [openrazer/openrazer#476]
Running on Ubuntu 17.10 Gnome. Openrazer latest version and Polychromatic to manage. When I first installed the keyboard, it had a breathing mode that ran even when the screensaver kicked in. Now with Openrazer, I get all of the functions but the keyboard is dark until I enter my password. The log shows it suspending and waking up normally but the wakeup event should happen before the password is entered, not after. Kind of the point of an illuminated keyboard.

**Comment by terricain** [comment]
@etrigan63 Yeah That's an issue of whenever the screensaver daemon sends out dbus events, not much we can do

**Comment by lah7** [comment]
There is a way to turn off this functionality altogether - edit this file: `~/.config/openrazer/razer.conf`

```
# Turn off the devices when the systems screensaver kicks in
devices_off_on_screensaver = False
```

**Comment by etrigan63** [comment]
That will work just fine.
