### ISSUE TITLE
Razer Tartarus V2

### ISSUE THREAD

**Issue by dflament** [openrazer/openrazer#483]
Hello,

i'm really new at this so please, if i sound like a noob, don't laugh :-) Asking kindly support for the pretty new Tartarus V2, only difference to the previous model is the addition of a scroll wheel and Chroma. Many thanks already for any effort made...

**lsusb -d 1532: -v**

> Bus 003 Device 008: ID 1532:022b Razer USA, Ltd 
Device Descriptor:
  bLength                18
  bDescriptorType         1
  bcdUSB               2.00
  bDeviceClass            0 (Defined at Interface level)
  bDeviceSubClass         0 
  bDeviceProtocol         0 
  bMaxPacketSize0        64
  idVendor           0x1532 Razer USA, Ltd
  idProduct          0x022b 
  bcdDevice            2.00
  iManufacturer           1 Razer
  iProduct                2 Razer Tartarus V2
  iSerial                 0 
  bNumConfigurations      1
  Configuration Descriptor:
    bLength                 9
    bDescriptorType         2
    wTotalLength           84
    bNumInterfaces          3
    bConfigurationValue     1
    iConfiguration          0 
    bmAttributes         0xa0
      (Bus Powered)
      Remote Wakeup
    MaxPower              500mA
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        0
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      1 Boot Interface Subclass
      bInterfaceProtocol      1 Keyboard
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength      61
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x81  EP 1 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0008  1x 8 bytes
        bInterval               1
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        1
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      0 No Subclass
      bInterfaceProtocol      1 Keyboard
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength     159
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x82  EP 2 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0010  1x 16 bytes
        bInterval               1
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        2
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      0 No Subclass
      bInterfaceProtocol      2 Mouse
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength      94
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x83  EP 3 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0008  1x 8 bytes
        bInterval               1
Device Status:     0x0000
  (Bus Powered)

**ls -lah /dev/input/by-id/**

> lrwxrwxrwx 1 root root   9 Dec 21 21:39 usb-Razer_Razer_Tartarus_V2-event-kbd -> ../event4
lrwxrwxrwx 1 root root   9 Dec 21 21:39 usb-Razer_Razer_Tartarus_V2-if01-event-kbd -> ../event5
lrwxrwxrwx 1 root root   9 Dec 21 21:39 usb-Razer_Razer_Tartarus_V2-if02-event-mouse -> ../event6
lrwxrwxrwx 1 root root   9 Dec 21 21:39 usb-Razer_Razer_Tartarus_V2-if02-mouse -> ../mouse0

**Model name, number & Product code**

> Model name & number : RZ07-0227, Gaming Keypad
Product code : RZ07-02270100

JPGs to follow tomorrow as i need my wife's windowz computer

**Comment by dflament** [comment]
Screenshots from Synapse v3 Beta, hope this is good enough?

![razer_00](https://user-images.githubusercontent.com/34754152/34310682-352cba5a-e759-11e7-95a7-fb6c6ca15e7d.jpg)
![razer_01](https://user-images.githubusercontent.com/34754152/34310683-3543450e-e759-11e7-8239-6d7a01b38043.jpg)
![razer_02](https://user-images.githubusercontent.com/34754152/34310684-35598152-e759-11e7-93d1-9dabf5b4b083.jpg)
![razer_03](https://user-images.githubusercontent.com/34754152/34310685-3577d1a2-e759-11e7-8d01-df1d342a27b5.jpg)
![razer_04](https://user-images.githubusercontent.com/34754152/34310686-358f6a4c-e759-11e7-9097-988053b2041b.jpg)

**Comment by dflament** [comment]
do you also need a record packet captures of the USB traffic or is the above information more then enough?

**Comment by WaddlePatches** [comment]
Also volunteering to help get this device supported. Functionally almost identical to Orbweaver Chroma, with the addition of a scrollwheel in the place of button 20, and button 20 on the thumbrest. I'm hoping that it uses the same protocol :)

**Comment by WaddlePatches** [comment]
Digging around in the Synapse 3 files on Windows, there's a reference to "NostromoV2"

**Comment by manisjp** [comment]
What do you need for the pcap?

**Comment by z3ntu** [comment]
@manisjp basically the same as in the other issue. At least for the beginning :)

**Comment by monsieuraa** [comment]
I buy a tartarus V2 to, how I can help ?

**Comment by z3ntu** [comment]
@monsieuraa We need packet captures (see https://github.com/openrazer/openrazer/wiki/Reverse-Engineering-USB-Protocol) of the functions that the device can do (like switching lighting effect, changing brightness)

**Comment by dflament** [comment]
ok, after many months i finally got the time to mess around a bit with reverse engineering. Can someone please look at this and tell me if its ok? i did the brightness and the quick effects in a seperate pcap.

Please tell me if i did something wrong or not and if you need more...

[tartarusv2_brightness.pcapng.gz](https://github.com/openrazer/openrazer/files/1998752/tartarusv2_brightness.pcapng.gz)
[tartarusv2_quickeffects.pcapng.gz](https://github.com/openrazer/openrazer/files/1998754/tartarusv2_quickeffects.pcapng.gz)

**Comment by z3ntu** [comment]
pcaps look good, thanks.

**Comment by twiddletec** [comment]
Just wanted to note, that we now also own the V2. 
Drop me note if you need someone testing...

**Comment by ly0** [comment]
Really need for this. Waiting for more detail.

**Comment by nelyafinwe** [comment]
do you need help with this? i have this device as well (0x022b)

**Comment by 0mnipotent** [comment]
I've got a Tartarus V2 1532:022b, 
I can follow instructions and provide data, or i can test what is designed for this.
looking forward to anything :)

**Comment by Altoholic** [comment]
I have a Tartarus Chroma v2 too, if i can help.

**Comment by bboyles303** [comment]
Did this ever happen in a testing/beta release? I have a Tartarus Chroma V2 as well and would love to use it.

**Comment by triggerhappytog** [comment]
Would like to buy the Tartarus V2 for programming purposes, has it been tested?

**Comment by danielrobbins** [comment]
@WhitePatches  I've tried adding the Tartarus V2 and treating it as the equivalent of an OrbWeaver, and at least in polychromatic setting various color stuffs doesn't work. So it may use a different protocol. My commit is here in case anyone else would like to play with it: https://github.com/funtoo/openrazer

If I get more time I may play with USB packet captures to see what's needed to get it working.

**Comment by SunnyOd** [comment]
Hey. I've got the tartarus v2 also. Happy to help out? Was anyone able to work out how it works?

**Comment by 0mnipotent** [comment]
Hi there,

Nah I never heard anything back :/
Which is a shame.
Let me know if you have any luck!

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by ghost** [comment]
I have this device too. Can we expect support in the near future?

**Comment by SunnyOd** [comment]
I'm with you, praying!

**Comment by dimas-cyriaco** [comment]
I have one v2, too. If you guys need anything i`ll be pleased to help.

**Comment by SunnyBTC** [comment]
I'm with you, praying!

**Comment by laaameche** [comment]
I have no coding abilities but like to help to have this device (that I own) working on linux.
Moving from Windows to Linux is not easy with that type of problem :/ but thank you for the other devices that the project support.

**Comment by rporter220** [comment]
I also have a Tartarus V2 and would like to provide any assistance that is needed.

**Comment by ghost** [comment]
This is the most popular keypad in my country and there's barely any other type in the stores. It'd be great if linux would support such a popular device.

**Comment by Darkslide77** [comment]
I also have a Razer Tartarus V2 and am willing to help with any development.

**Comment by lannet2000** [comment]
I also got one tartarus V2 , I'm a programmer if I can help drop me a message.
Have Ubuntu and Fedora.
Thanks

**Comment by erancihan** [comment]
I think the problem right now is to find some one who is familiar with the code base, and have time to deal with the development process

**Comment by ghost** [comment]
I tried to make this work with https://github.com/funtoo/openrazer by merging 2.6.0, updating the `install_files/appstream/io.github.openrazer.openrazer.metainfo.xml` file and creating a new `pylib/openrazer/_fake_driver/razertartarusv2.cfg` file(based on razerorbweaver/tartarus). Here is the diff: https://pastebin.com/tyyyKfSw

Polychromatic threw this:

Device Not Recognised
A Razer product is connected to your computer, but the daemon didn't detect it.
It is possible your Razer product is not bound to the driver properly or it is not yet supported.

@z3ntu can you help me?

Repo with the changes: https://github.com/trialism/openrazer

**Comment by z3ntu** [comment]
@trialism Are you sure the dkms kernel module is built with the new code? And the udev rule installed and the daemon running from the patched source? From looking at the code, I don't see anything obviously wrong.

**Comment by ghost** [comment]
@z3ntu I purged openrazer and then reinstalled it with this repo: https://github.com/trialism/openrazer-meta-aur and these commands:

```sh
sudo pacman -U openrazer-driver-dkms-2.6.0-1-any.pkg.tar.xz
sudo pacman -U openrazer-daemon-2.6.0-1-any.pkg.tar.xz
sudo pacman -U openrazer-meta-2.6.0-1-any.pkg.tar.xz
sudo pacman -U python-openrazer-2.6.0-1-any.pkg.tar.xz
```

It can detect the device now I just can't do anything with it. Neither the spectrum nor the breath nor the static effects nor the brightness settings work.

**Comment by z3ntu** [comment]
@trialism You have to me the `case` statements you added in the driver to different locations then (or add case statements).

At least for brightness (`razer_attr_write_set_brightness`) I can tell you, that you need a case with `report = razer_chroma_extended_matrix_brightness(VARSTORE, ZERO_LED, brightness);` according to the pcaps. If that doesn't work you can try adding `report.transaction_id.id = 0x1F;` as well. That should hopefully work then.

**Comment by ghost** [comment]
@z3ntu I didn't really understand the first part so I just added a few cases: https://github.com/trialism/openrazer/commit/2edb30c61e2406fc3a6623b0e251e47c67d8aa34 - it didn't work.

The brightness works sometimes(probably a GUI issue:) but the slider always shows the zero value.

**Comment by lannet2000** [comment]
Thanks @trialism  and @z3ntu for youe effort, see you are making a Aur package , nice :)
Please let me/us know if and how we can help you.

**Comment by z3ntu** [comment]
> The brightness works sometimes

What do you mean by that?

**Comment by ghost** [comment]
I meant that it doesn't always react to the slider's changes and when it does the slider will go back to the starting position no matter what I do. Even if the slider is at 0 I can pull it from right to left to turn down the brightness(can't turn off) and if I want to increase I can pull from left to right but at both cases the slider will show zero brightness while the actual brightness will change.

**Comment by z3ntu** [comment]
Try adding into `razer_attr_read_set_brightness` the code `report = razer_chroma_extended_matrix_get_brightness(VARSTORE, ZERO_LED);` (and the transaction_id thing if it's needed)

**Comment by ghost** [comment]
Many thanks, the brightness works now: https://github.com/trialism/openrazer/commit/bb33887bb98c8cda33da8e1c771dd300bd199934

What do you think, can we solve the static-effects issue? Is that a special case usually or is the tartarus_v2 doing something differently?

@lannet2000 someone else already provided the relevant pcap files - I'm not familiar with those but if you want to, you could help us tweak the branch.

**Comment by z3ntu** [comment]
Unfortunately the packet captures don't contain any useful information for the effects unfortunately because Synapse 3 just controls everything software-side but in OpenRazer we're using the "hardware" effects (which the firmware on the device can do), so it will be a case of trial and error I think.

**Comment by ghost** [comment]
So good old brute-force. Would it be possible to change the color of specific keys?

**Comment by ghost** [comment]
And is it the driver which decides which effects are available or do we get feedback from the firmware?

**Comment by z3ntu** [comment]
> Would it be possible to change the color of specific keys?

That's achieved with the custom frame effect.

> And is it the driver which decides which effects are available or do we get feedback from the firmware?

Sometimes the device says "no I can't do that", sometimes it just quietly does nothing so no, we don't really get any usable responses from the firmware.

**Comment by z3ntu** [comment]
One more thing I can tell you from the pcaps is, that you need to use `razer_chroma_extended_matrix_effect_custom_frame` with rows 0 to 3 and columns 0 to 5 for custom frame (the first thing you put into the driver, and the dimensions are put into the daemon, so it will be `MATRIX_DIMS = [4, 6]` I think)

**Comment by ghost** [comment]
Thanks for the quick reply and the info!

**Comment by ghost** [comment]
I added a few effects but only the "none" effect works. The frontends don't show the keys and the keypad. https://github.com/trialism/openrazer/commit/9f07174a92e8653842ccc6da28e1f6010b6afe93

**Comment by z3ntu** [comment]
You need to tell the daemon that `'set_custom_effect', 'set_key_row',` are available, otherwise the frontends don't know anything about that. About the other effects, again it will have to be a game of brute force. Likely the `report.transaction_id.id = 0x1F;` statement will be needed for the effects as well.

**Comment by ghost** [comment]
Good news, the following effects work: none, wave, reactive, breath(all types), static.

Gaming mode appeared in the gui but I don't know how should I use it.

I tried to add macro support but the keyboard is still not visible and I can't change the color of individual keys either.

**Comment by ghost** [comment]
I will also try to make the spectrum, starlight and ripple effects work.

**Comment by ghost** [comment]
Starlight and spectrum also work. I removed game-mode because it crashed the tray applet. The ripple effect is supported according to the "master guide" but it doesn't work(probably an issue with the matrix support?). And there is a fire effect too but there is no such helper function - I think it is going to be the 0x06 effect code but I will concentrate on the macro support for now.

**Comment by z3ntu** [comment]
Ripple and Fire effects are done in software.

For the custom frame matrix thing, I don't see anything obviously wrong in your changes. I'm not sure what logic polychromatic uses to display a button there or not, so you can try to compile RazerGenie (see https://github.com/z3ntu/RazerGenie#how-to-compile) and use `meson -Dinclude_matrix_discovery=true builddir` instead of the meson command listed in the readme.

**Comment by ghost** [comment]
I tried that but it didn't display the keypad or the keys either.

**Comment by ghost** [comment]
Is it possible that we need `razer_chroma_extended_ [g,s]et_led_state` functions instead of `razer_chroma_standard_[g,s]et_led_state` functions to make macros and the keypad display work? So far, all the lighting effects needed the `extended` helpers and didn't work with the `standard` ones.

**Comment by tonyperiod** [comment]
i got the V2 as well, moved to linux for better modeling but without a working keypad can't do much... programmers pls do your magic, we love you

**Comment by tonyperiod** [comment]
i have the V2 as well.. i have 0 experience with programming and i just installed linux. but if there is anything i can do to help tell me. i have subscribed to this discussion, i need the tartarus for 3d modeling

**Comment by tonyperiod** [comment]
i have the V2 as well.. i have 0 experience with programming and i just installed linux. but if there is anything i can do to help tell me. i have subscribed to this discussion, i need the tartarus for 3d modeling

**Comment by erlendbirketvedt** [comment]
Any updates on progress here? Anything we can do to help out?

**Comment by jerebare** [comment]
seconded, I switched to linux and can't use my tartarus v2 how I want now. It seems like it's the only razer device not supported by openrazer.

**Comment by ghost** [comment]
I sold mine so I won't work on it anymore.  Make sure to grab the changes from my profile before I delete them. Most of the lighting options worked when I tried them.

**Comment by jerebare** [comment]
> I sold mine so I won't work on it anymore. Make sure to grab the changes from my profile before I delete them. Most of the lighting options worked when I tried them.

I can't figure out how to even get my tartarus v2 device recognized in polychromatic with the files in your github. I download it, do make, or sudo make install etc. and always saying Device Not Recognised in polychromatic.

**Comment by ghost** [comment]
@jere-leppanen it's an Arch/AUR package.

**Comment by jerebare** [comment]
> @jere-leppanen it's an Arch/AUR package.

well, i'm using zorin os 15-ubuntu 18.04, So there is no way for me to test it?

**Comment by ghost** [comment]
@jere-leppanen create a debian package for yourself.

**Comment by ghost** [comment]
@z3ntu should we merge the changes? Most of the core functionalities work, except the fire/ripple lighting and macros(which doesn't work with my BW TE Chroma v2 either, but it's theoretically supported).

**Comment by jere-leppanen** [comment]
> @jere-leppanen create a debian package for yourself.

can't figure it out reading any documentation how to make a debian package.

**Comment by poirierdag** [comment]
> @z3ntu should we merge the changes? Most of the core functionalities work, except the fire/ripple lighting and macros(which doesn't work with my BW TE Chroma v2 either, but it's theoretically supported).

I'd love if you can merge, I've been waiting for this for a month.

**Comment by erancihan** [comment]
i did not see a pull request regarding this, so maybe if @trialism opens up a PR, they can take it into consideration.
it can be considered WIP otherwise, as "... core functionalities work, except the fire/ripple lighting and macros ..."

**Comment by jerebare** [comment]
> i did not see a pull request regarding this, so maybe if @trialism opens up a PR, they can take it into consideration.
> it can be considered WIP otherwise, as "... core functionalities work, except the fire/ripple lighting and macros ..."

Using it myself, essentially only lighting works. Core functionality to me is the rebinding of keys, which it doesn't have. So it has basic lighting changes, no macros, no re-binding of keys and no fire/ripple lighting effects as of yet.

**Comment by ghost** [comment]
@jere-leppanen you can rebind keys with other linux tools. The macro modules doesn't work with this device but there are tools to replace this feature for linux. The fire effect is sw-based. The ripple module also doesn't work with this device.

@freedrone I won't create a PR until @z3ntu agrees with it. The compatibility could improve with openrazer later but @z3ntu will be the one giving support for people.

**Comment by z3ntu** [comment]
@trialism If you have code that works, please open a PR.

**Comment by Nomad-Megz** [comment]
Has there been any progress on this? If there is anything i could possibly do to help, I'll definitely try my best!
