### ISSUE TITLE
Open Razer on ElementaryOS 0.4.1

### ISSUE THREAD

**Issue by meraklimaymun** [openrazer/openrazer#485]
Followed the Ubuntu/Linux Mint method but I can't see any razer apps anywhere.

Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages were automatically installed and are no longer required:
  gir1.2-javascriptcoregtk-4.0 gir1.2-json-1.0 gir1.2-soup-2.4 gir1.2-webkit2-4.0 libido3-0.1-0 libvala-0.34-0
Use 'sudo apt autoremove' to remove them.
The following NEW packages will be installed:
  openrazer-meta
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 6.454 B of archives.
After this operation, 13,3 kB of additional disk space will be used.
Get:1 http://ppa.launchpad.net/openrazer/stable/ubuntu xenial/main amd64 openrazer-meta all 2.2.0~ubuntu16.04.1 [6.454 B]
Fetched 6.454 B in 0s (34,9 kB/s)         
Selecting previously unselected package openrazer-meta.
(Reading database ... 195077 files and directories currently installed.)
Preparing to unpack .../openrazer-meta_2.2.0~ubuntu16.04.1_all.deb ...
Unpacking openrazer-meta (2.2.0~ubuntu16.04.1) ...
Setting up openrazer-meta (2.2.0~ubuntu16.04.1) ...

**Comment by z3ntu** [comment]
You need to install a frontend for the drivers like Polychromatic, RazerGenie or razerCommander, as linked in the readme.
