### ISSUE TITLE
Razer Ornata Chroma blinking/flashing M 

### ISSUE THREAD

**Issue by ghost** [openrazer/openrazer#489]
The Macro indicator located above the numeric keypad keeps flasing in red and I cannot seem to be able to stop it. FN + F9 doesn't have any effect.

Any ideas?

Daemon log:

> 2018-01-01 23:32:05 | razer                          | INFO     | Initialising Daemon (v2.2.0). Pid: 4747
> 2018-01-01 23:32:05 | razer.screensaver              | INFO     | Initialising DBus Screensaver Monitor
> 2018-01-01 23:32:05 | razer                          | DEBUG    | Loaded device specification: RazerAbyssus ---------------------------- (1532:0042)
> 2018-01-01 23:32:05 | razer                          | DEBUG    | Loaded device specification: RazerAbyssus1800 ------------------------ (1532:0020)
> 2018-01-01 23:32:05 | razer                          | DEBUG    | Loaded device specification: RazerAbyssusV2 -------------------------- (1532:005B)
> 2018-01-01 23:32:05 | razer                          | DEBUG    | Loaded device specification: RazerAnansi ----------------------------- (1532:010F)
> 2018-01-01 23:32:05 | razer                          | DEBUG    | Loaded device specification: RazerBlackWidowChroma ------------------- (1532:0203)
> 2018-01-01 23:32:05 | razer                          | DEBUG    | Loaded device specification: RazerBlackWidowChromaOverwatch ---------- (1532:0211)
> 2018-01-01 23:32:05 | razer                          | DEBUG    | Loaded device specification: RazerBlackWidowChromaTournamentEdition -- (1532:0209)
> 2018-01-01 23:32:05 | razer                          | DEBUG    | Loaded device specification: RazerBlackWidowChromaV2 ----------------- (1532:0221)
> 2018-01-01 23:32:05 | razer                          | DEBUG    | Loaded device specification: RazerBlackWidowClassic ------------------ (1532:011B)
> 2018-01-01 23:32:05 | razer                          | DEBUG    | Loaded device specification: RazerBlackWidowClassicAlternate --------- (1532:010E)
> 2018-01-01 23:32:05 | razer                          | DEBUG    | Loaded device specification: RazerBlackWidowUltimate2012 ------------- (1532:010D)
> 2018-01-01 23:32:05 | razer                          | DEBUG    | Loaded device specification: RazerBlackWidowUltimate2013 ------------- (1532:011A)
> 2018-01-01 23:32:05 | razer                          | DEBUG    | Loaded device specification: RazerBlackWidowUltimate2016 ------------- (1532:0214)
> 2018-01-01 23:32:05 | razer                          | DEBUG    | Loaded device specification: RazerBlackWidowXChroma ------------------ (1532:0216)
> 2018-01-01 23:32:05 | razer                          | DEBUG    | Loaded device specification: RazerBlackWidowXTournamentEditionChroma - (1532:021A)
> 2018-01-01 23:32:05 | razer                          | DEBUG    | Loaded device specification: RazerBlackWidowXUltimate ---------------- (1532:0217)
> 2018-01-01 23:32:05 | razer                          | DEBUG    | Loaded device specification: RazerBladeLate2016 ---------------------- (1532:0224)
> 2018-01-01 23:32:05 | razer                          | DEBUG    | Loaded device specification: RazerBladePro2017 ----------------------- (1532:0225)
> 2018-01-01 23:32:05 | razer                          | DEBUG    | Loaded device specification: RazerBladePro2017FullHD ----------------- (1532:022F)
> 2018-01-01 23:32:05 | razer                          | DEBUG    | Loaded device specification: RazerBladeProLate2016 ------------------- (1532:0210)
> 2018-01-01 23:32:05 | razer                          | DEBUG    | Loaded device specification: RazerBladeQHD --------------------------- (1532:020F)
> 2018-01-01 23:32:05 | razer                          | DEBUG    | Loaded device specification: RazerBladeStealth ----------------------- (1532:0205)
> 2018-01-01 23:32:05 | razer                          | DEBUG    | Loaded device specification: RazerBladeStealthLate2016 --------------- (1532:0220)
> 2018-01-01 23:32:05 | razer                          | DEBUG    | Loaded device specification: RazerBladeStealthLate2017 --------------- (1532:0232)
> 2018-01-01 23:32:05 | razer                          | DEBUG    | Loaded device specification: RazerBladeStealthMid2017 ---------------- (1532:022D)
> 2018-01-01 23:32:05 | razer                          | DEBUG    | Loaded device specification: RazerChromaMugHolder -------------------- (1532:0F07)
> 2018-01-01 23:32:05 | razer                          | DEBUG    | Loaded device specification: RazerCore ------------------------------- (1532:0215)
> 2018-01-01 23:32:05 | razer                          | DEBUG    | Loaded device specification: RazerDeathAdderChroma ------------------- (1532:0043)
> 2018-01-01 23:32:05 | razer                          | DEBUG    | Loaded device specification: RazerDeathAdderElite -------------------- (1532:005C)
> 2018-01-01 23:32:05 | razer                          | DEBUG    | Loaded device specification: RazerDeathStalkerChroma ----------------- (1532:0204)
> 2018-01-01 23:32:05 | razer                          | DEBUG    | Loaded device specification: RazerDeathStalkerExpert ----------------- (1532:0202)
> 2018-01-01 23:32:05 | razer                          | DEBUG    | Loaded device specification: RazerDiamondbackChroma ------------------ (1532:004C)
> 2018-01-01 23:32:05 | razer                          | DEBUG    | Loaded device specification: RazerFirefly ---------------------------- (1532:0C00)
> 2018-01-01 23:32:05 | razer                          | DEBUG    | Loaded device specification: RazerImperator -------------------------- (1532:002F)
> 2018-01-01 23:32:05 | razer                          | DEBUG    | Loaded device specification: RazerKraken ----------------------------- (1532:0504)
> 2018-01-01 23:32:05 | razer                          | DEBUG    | Loaded device specification: RazerKrakenClassic ---------------------- (1532:0501)
> 2018-01-01 23:32:05 | razer                          | DEBUG    | Loaded device specification: RazerKrakenV2 --------------------------- (1532:0510)
> 2018-01-01 23:32:05 | razer                          | DEBUG    | Loaded device specification: RazerMamba2012Wired --------------------- (1532:0024)
> 2018-01-01 23:32:05 | razer                          | DEBUG    | Loaded device specification: RazerMamba2012Wireless ------------------ (1532:0025)
> 2018-01-01 23:32:05 | razer                          | DEBUG    | Loaded device specification: RazerMambaChromaWired ------------------- (1532:0044)
> 2018-01-01 23:32:05 | razer                          | DEBUG    | Loaded device specification: RazerMambaChromaWireless ---------------- (1532:0045)
> 2018-01-01 23:32:05 | razer                          | DEBUG    | Loaded device specification: RazerMambaTE ---------------------------- (1532:0046)
> 2018-01-01 23:32:05 | razer                          | DEBUG    | Loaded device specification: RazerNaga2014 --------------------------- (1532:0040)
> 2018-01-01 23:32:05 | razer                          | DEBUG    | Loaded device specification: RazerNagaChroma ------------------------- (1532:0053)
> 2018-01-01 23:32:05 | razer                          | DEBUG    | Loaded device specification: RazerNagaHex ---------------------------- (1532:0041)
> 2018-01-01 23:32:05 | razer                          | DEBUG    | Loaded device specification: RazerNagaHexRed ------------------------- (1532:0036)
> 2018-01-01 23:32:05 | razer                          | DEBUG    | Loaded device specification: RazerNagaHexV2 -------------------------- (1532:0050)
> 2018-01-01 23:32:05 | razer                          | DEBUG    | Loaded device specification: RazerNostromo --------------------------- (1532:0111)
> 2018-01-01 23:32:05 | razer                          | DEBUG    | Loaded device specification: RazerOrbweaver -------------------------- (1532:0113)
> 2018-01-01 23:32:05 | razer                          | DEBUG    | Loaded device specification: RazerOrbweaverChroma -------------------- (1532:0207)
> 2018-01-01 23:32:05 | razer                          | DEBUG    | Loaded device specification: RazerOrnata ----------------------------- (1532:021F)
> 2018-01-01 23:32:05 | razer                          | DEBUG    | Loaded device specification: RazerOrnataChroma ----------------------- (1532:021E)
> 2018-01-01 23:32:05 | razer                          | DEBUG    | Loaded device specification: RazerOrochi2011 ------------------------- (1532:0013)
> 2018-01-01 23:32:05 | razer                          | DEBUG    | Loaded device specification: RazerOrochi2013 ------------------------- (1532:0039)
> 2018-01-01 23:32:05 | razer                          | DEBUG    | Loaded device specification: RazerOrochiWired ------------------------ (1532:0048)
> 2018-01-01 23:32:05 | razer                          | DEBUG    | Loaded device specification: RazerOuroboros -------------------------- (1532:0032)
> 2018-01-01 23:32:05 | razer                          | DEBUG    | Loaded device specification: RazerTaipan ----------------------------- (1532:0034)
> 2018-01-01 23:32:05 | razer                          | DEBUG    | Loaded device specification: RazerTartarus --------------------------- (1532:0201)
> 2018-01-01 23:32:05 | razer                          | DEBUG    | Loaded device specification: RazerTartarusChroma --------------------- (1532:0208)
> 2018-01-01 23:32:05 | razer                          | INFO     | Found device.0: 0003:1532:0034.0001
> 2018-01-01 23:32:05 | razer.device0                  | INFO     | Initialising device.0 RazerTaipan
> 2018-01-01 23:32:05 | razer.device0                  | DEBUG    | Adding razer.device.misc.hasDedicatedMacroKeys method to DBus
> 2018-01-01 23:32:05 | razer.device0                  | DEBUG    | Adding razer.device.misc.getSerial method to DBus
> 2018-01-01 23:32:05 | razer.device0                  | DEBUG    | Adding razer.device.misc.getRazerUrls method to DBus
> 2018-01-01 23:32:05 | razer.device0                  | DEBUG    | Adding razer.device.misc.getDriverVersion method to DBus
> 2018-01-01 23:32:05 | razer.device0                  | DEBUG    | Adding razer.device.misc.suspendDevice method to DBus
> 2018-01-01 23:32:05 | razer.device0                  | DEBUG    | Adding razer.device.misc.resumeDevice method to DBus
> 2018-01-01 23:32:05 | razer.device0                  | DEBUG    | Adding razer.device.misc.getDeviceMode method to DBus
> 2018-01-01 23:32:05 | razer.device0                  | DEBUG    | Adding razer.device.misc.getVidPid method to DBus
> 2018-01-01 23:32:05 | razer.device0                  | DEBUG    | Adding razer.device.misc.setDeviceMode method to DBus
> 2018-01-01 23:32:05 | razer.device0                  | DEBUG    | Adding razer.device.misc.getFirmware method to DBus
> 2018-01-01 23:32:05 | razer.device0                  | DEBUG    | Adding razer.device.misc.getMatrixDimensions method to DBus
> 2018-01-01 23:32:05 | razer.device0                  | DEBUG    | Adding razer.device.misc.hasMatrix method to DBus
> 2018-01-01 23:32:05 | razer.device0                  | DEBUG    | Adding razer.device.misc.getDeviceName method to DBus
> 2018-01-01 23:32:05 | razer.device0                  | DEBUG    | Adding razer.device.misc.getDeviceType method to DBus
> 2018-01-01 23:32:05 | razer.device0                  | DEBUG    | Adding razer.device.dpi.maxDPI method to DBus
> 2018-01-01 23:32:05 | razer.device0                  | DEBUG    | Adding razer.device.dpi.getDPI method to DBus
> 2018-01-01 23:32:05 | razer.device0                  | DEBUG    | Adding razer.device.dpi.setDPI method to DBus
> 2018-01-01 23:32:05 | razer.device0                  | DEBUG    | Adding razer.device.misc.getPollRate method to DBus
> 2018-01-01 23:32:05 | razer.device0                  | DEBUG    | Adding razer.device.misc.setPollRate method to DBus
> 2018-01-01 23:32:05 | razer.device0                  | DEBUG    | Adding razer.device.lighting.logo.getLogoActive method to DBus
> 2018-01-01 23:32:05 | razer.device0                  | DEBUG    | Adding razer.device.lighting.logo.setLogoActive method to DBus
> 2018-01-01 23:32:05 | razer.device0                  | DEBUG    | Adding razer.device.lighting.scroll.getScrollActive method to DBus
> 2018-01-01 23:32:05 | razer.device0                  | DEBUG    | Adding razer.device.lighting.scroll.setScrollActive method to DBus
> 2018-01-01 23:32:05 | razer                          | INFO     | Found device.1: 0003:1532:021E.0007
> 2018-01-01 23:32:05 | razer.device1                  | INFO     | Initialising device.1 RazerOrnataChroma
> 2018-01-01 23:32:05 | razer.device1                  | DEBUG    | Adding razer.device.misc.getVidPid method to DBus
> 2018-01-01 23:32:05 | razer.device1                  | DEBUG    | Adding razer.device.misc.getRazerUrls method to DBus
> 2018-01-01 23:32:05 | razer.device1                  | DEBUG    | Adding razer.device.misc.setDeviceMode method to DBus
> 2018-01-01 23:32:05 | razer.device1                  | DEBUG    | Adding razer.device.misc.getDriverVersion method to DBus
> 2018-01-01 23:32:05 | razer.device1                  | DEBUG    | Adding razer.device.misc.getSerial method to DBus
> 2018-01-01 23:32:05 | razer.device1                  | DEBUG    | Adding razer.device.misc.resumeDevice method to DBus
> 2018-01-01 23:32:05 | razer.device1                  | DEBUG    | Adding razer.device.misc.suspendDevice method to DBus
> 2018-01-01 23:32:05 | razer.device1                  | DEBUG    | Adding razer.device.misc.hasDedicatedMacroKeys method to DBus
> 2018-01-01 23:32:05 | razer.device1                  | DEBUG    | Adding razer.device.misc.getDeviceMode method to DBus
> 2018-01-01 23:32:05 | razer.device1                  | DEBUG    | Adding razer.device.misc.getFirmware method to DBus
> 2018-01-01 23:32:05 | razer.device1                  | DEBUG    | Adding razer.device.misc.getMatrixDimensions method to DBus
> 2018-01-01 23:32:05 | razer.device1                  | DEBUG    | Adding razer.device.misc.hasMatrix method to DBus
> 2018-01-01 23:32:05 | razer.device1                  | DEBUG    | Adding razer.device.misc.getDeviceName method to DBus
> 2018-01-01 23:32:05 | razer.device1                  | DEBUG    | Adding razer.device.misc.getDeviceType method to DBus
> 2018-01-01 23:32:05 | razer.device1                  | DEBUG    | Adding razer.device.lighting.brightness.getBrightness method to DBus
> 2018-01-01 23:32:05 | razer.device1                  | DEBUG    | Adding razer.device.lighting.brightness.setBrightness method to DBus
> 2018-01-01 23:32:05 | razer.device1                  | DEBUG    | Adding razer.device.lighting.chroma.setWave method to DBus
> 2018-01-01 23:32:05 | razer.device1                  | DEBUG    | Adding razer.device.lighting.chroma.setStatic method to DBus
> 2018-01-01 23:32:05 | razer.device1                  | DEBUG    | Adding razer.device.lighting.chroma.setSpectrum method to DBus
> 2018-01-01 23:32:05 | razer.device1                  | DEBUG    | Adding razer.device.lighting.chroma.setReactive method to DBus
> 2018-01-01 23:32:05 | razer.device1                  | DEBUG    | Adding razer.device.lighting.chroma.setNone method to DBus
> 2018-01-01 23:32:05 | razer.device1                  | DEBUG    | Adding razer.device.lighting.chroma.setBreathRandom method to DBus
> 2018-01-01 23:32:05 | razer.device1                  | DEBUG    | Adding razer.device.lighting.chroma.setBreathSingle method to DBus
> 2018-01-01 23:32:05 | razer.device1                  | DEBUG    | Adding razer.device.lighting.chroma.setBreathDual method to DBus
> 2018-01-01 23:32:05 | razer.device1                  | DEBUG    | Adding razer.device.lighting.chroma.setCustom method to DBus
> 2018-01-01 23:32:05 | razer.device1                  | DEBUG    | Adding razer.device.lighting.chroma.setKeyRow method to DBus
> 2018-01-01 23:32:05 | razer.device1                  | DEBUG    | Adding razer.device.led.gamemode.getGameMode method to DBus
> 2018-01-01 23:32:05 | razer.device1                  | DEBUG    | Adding razer.device.led.gamemode.setGameMode method to DBus
> 2018-01-01 23:32:05 | razer.device1                  | DEBUG    | Adding razer.device.led.macromode.getMacroMode method to DBus
> 2018-01-01 23:32:05 | razer.device1                  | DEBUG    | Adding razer.device.led.macromode.setMacroMode method to DBus
> 2018-01-01 23:32:05 | razer.device1                  | DEBUG    | Adding razer.device.led.macromode.getMacroEffect method to DBus
> 2018-01-01 23:32:05 | razer.device1                  | DEBUG    | Adding razer.device.led.macromode.setMacroEffect method to DBus
> 2018-01-01 23:32:05 | razer.device1                  | DEBUG    | Adding razer.device.macro.getMacros method to DBus
> 2018-01-01 23:32:05 | razer.device1                  | DEBUG    | Adding razer.device.macro.deleteMacro method to DBus
> 2018-01-01 23:32:05 | razer.device1                  | DEBUG    | Adding razer.device.macro.addMacro method to DBus
> 2018-01-01 23:32:05 | razer.device1                  | DEBUG    | Adding razer.device.lighting.chroma.setStarlightRandom method to DBus
> 2018-01-01 23:32:05 | razer.device1                  | DEBUG    | Adding razer.device.lighting.chroma.setStarlightSingle method to DBus
> 2018-01-01 23:32:05 | razer.device1                  | DEBUG    | Adding razer.device.lighting.chroma.setStarlightDual method to DBus
> 2018-01-01 23:32:05 | razer.device1                  | DEBUG    | Adding razer.device.lighting.custom.setRipple method to DBus
> 2018-01-01 23:32:05 | razer.device1                  | DEBUG    | Adding razer.device.lighting.custom.setRippleRandomColour method to DBus
> 2018-01-01 23:32:05 | razer.device1.keymanager       | DEBUG    | Starting KeyWatcher
> 2018-01-01 23:32:05 | razer.device1                  | INFO     | Putting device into driver mode. Daemon will handle special functionality
> 2018-01-01 23:32:05 | razer                          | DEBUG    | Adding razer.daemon.version method to DBus
> 2018-01-01 23:32:05 | razer                          | DEBUG    | Adding razer.devices.getDevices method to DBus
> 2018-01-01 23:32:05 | razer                          | DEBUG    | Adding razer.devices.getOffOnScreensaver method to DBus
> 2018-01-01 23:32:05 | razer                          | DEBUG    | Adding razer.devices.supportedDevices method to DBus
> 2018-01-01 23:32:05 | razer                          | DEBUG    | Adding razer.devices.enableTurnOffOnScreensaver method to DBus
> 2018-01-01 23:32:05 | razer                          | DEBUG    | Adding razer.devices.syncEffects method to DBus
> 2018-01-01 23:32:05 | razer                          | DEBUG    | Adding razer.daemon.stop method to DBus
> 2018-01-01 23:32:05 | razer                          | DEBUG    | Adding razer.devices.getSyncEffects method to DBus
> 2018-01-01 23:32:05 | razer                          | INFO     | Serving DBus
> 2018-01-01 23:32:06 | razer                          | DEBUG    | DBus called get_serial_list
> 2018-01-01 23:32:06 | razer.device0                  | DEBUG    | DBus call get_device_type
> 2018-01-01 23:32:06 | razer.device0                  | DEBUG    | DBus call get_device_name
> 2018-01-01 23:32:06 | razer.device0                  | DEBUG    | DBus call get_device_type
> 2018-01-01 23:32:06 | razer.device0                  | DEBUG    | DBus call get_firmware
> 2018-01-01 23:32:06 | razer.device0                  | DEBUG    | DBus call version
> 2018-01-01 23:32:06 | razer.device0                  | DEBUG    | DBus call has_matrix
> 2018-01-01 23:32:06 | razer.device0                  | DEBUG    | DBus call has_matrix
> 2018-01-01 23:32:06 | razer.device1                  | DEBUG    | DBus call get_device_type
> 2018-01-01 23:32:06 | razer.device1                  | DEBUG    | DBus call get_device_name
> 2018-01-01 23:32:06 | razer.device1                  | DEBUG    | DBus call get_device_type
> 2018-01-01 23:32:06 | razer.device1                  | DEBUG    | DBus call get_firmware
> 2018-01-01 23:32:06 | razer.device1                  | DEBUG    | DBus call version
> 2018-01-01 23:32:06 | razer.device1                  | DEBUG    | DBus call has_matrix
> 2018-01-01 23:32:06 | razer.device1                  | DEBUG    | DBus call has_matrix
> 2018-01-01 23:32:06 | razer.device0                  | DEBUG    | DBus call get_dpi_both
> 2018-01-01 23:32:06 | razer.device0                  | DEBUG    | DBus call get_dpi_both
> 2018-01-01 23:32:06 | razer.device0                  | DEBUG    | DBus call get_poll_rate
> 2018-01-01 23:32:06 | razer.device0                  | DEBUG    | DBus call get_logo_active
> 2018-01-01 23:32:06 | razer.device0                  | DEBUG    | DBus call get_scroll_active

razer_mount log: 

> Jan 01 23:14:37 arch-Bednar razer_mount[462]: Driver razermouse
> Jan 01 23:14:37 arch-Bednar razer_mount[464]: Driver razermouse
> Jan 01 23:14:37 arch-Bednar razer_mount[465]: Device_ID 0003:1532:0034.0003
> Jan 01 23:14:37 arch-Bednar razer_mount[463]: Driver razermouse
> Jan 01 23:14:37 arch-Bednar razer_mount[460]: Driver razerkbd
> Jan 01 23:14:37 arch-Bednar razer_mount[467]: Unbinding 0003:1532:0034.0003 from hid-generic
> Jan 01 23:14:37 arch-Bednar razer_mount[468]: Device_ID 0003:1532:0034.0002
> Jan 01 23:14:37 arch-Bednar razer_mount[469]: Device_ID 0003:1532:0034.0001
> Jan 01 23:14:37 arch-Bednar razer_mount[470]: Device_ID 0003:1532:021E.0007
> Jan 01 23:14:37 arch-Bednar razer_mount[459]: Driver razerkbd
> Jan 01 23:14:37 arch-Bednar razer_mount[461]: Driver razerkbd
> Jan 01 23:14:37 arch-Bednar razer_mount[473]: Unbinding 0003:1532:021E.0007 from hid-generic
> Jan 01 23:14:37 arch-Bednar razer_mount[474]: Device_ID 0003:1532:021E.0004
> Jan 01 23:14:37 arch-Bednar razer_mount[475]: Device_ID 0003:1532:021E.0006
> Jan 01 23:14:37 arch-Bednar razer_mount[471]: Unbinding 0003:1532:0034.0002 from hid-generic
> Jan 01 23:14:37 arch-Bednar razer_mount[476]: Unbinding 0003:1532:021E.0004 from hid-generic
> Jan 01 23:14:37 arch-Bednar razer_mount[472]: Unbinding 0003:1532:0034.0001 from hid-generic
> Jan 01 23:14:37 arch-Bednar razer_mount[477]: Unbinding 0003:1532:021E.0006 from hid-generic
> Jan 01 23:14:37 arch-Bednar razer_mount[508]: Binding 0003:1532:0034.0003 to razermouse
> Jan 01 23:14:37 arch-Bednar razer_mount[509]: Binding 0003:1532:021E.0007 to razerkbd
> Jan 01 23:14:37 arch-Bednar razer_mount[514]: Binding 0003:1532:0034.0002 to razermouse
> Jan 01 23:14:37 arch-Bednar razer_mount[517]: Binding 0003:1532:0034.0001 to razermouse
> Jan 01 23:14:37 arch-Bednar razer_mount[518]: Binding 0003:1532:021E.0004 to razerkbd
> Jan 01 23:14:37 arch-Bednar razer_mount[551]: Binding 0003:1532:021E.0006 to razerkbd
> Jan 01 23:14:37 arch-Bednar razer_mount[576]: Finished binding 0003:1532:021E.0007
> Jan 01 23:14:37 arch-Bednar razer_mount[577]: Finished binding 0003:1532:0034.0003
> Jan 01 23:14:37 arch-Bednar razer_mount[578]: Changing group /sys/bus/hid/drivers/razerkbd/0003:1532:021E.0007/
> Jan 01 23:14:37 arch-Bednar razer_mount[579]: Changing group /sys/bus/hid/drivers/razermouse/0003:1532:0034.0003/
> Jan 01 23:14:37 arch-Bednar razer_mount[582]: Changed group /sys/bus/hid/drivers/razermouse/0003:1532:0034.0003/
> Jan 01 23:14:37 arch-Bednar razer_mount[583]: Changed group /sys/bus/hid/drivers/razerkbd/0003:1532:021E.0007/
> Jan 01 23:14:37 arch-Bednar razer_mount[585]: Finished binding 0003:1532:0034.0002
> Jan 01 23:14:37 arch-Bednar razer_mount[586]: Finished binding 0003:1532:0034.0001
> Jan 01 23:14:37 arch-Bednar razer_mount[587]: Changing group /sys/bus/hid/drivers/razermouse/0003:1532:0034.0002/
> Jan 01 23:14:37 arch-Bednar razer_mount[588]: Changing group /sys/bus/hid/drivers/razermouse/0003:1532:0034.0001/
> Jan 01 23:14:37 arch-Bednar razer_mount[591]: Changed group /sys/bus/hid/drivers/razermouse/0003:1532:0034.0001/
> Jan 01 23:14:37 arch-Bednar razer_mount[592]: Changed group /sys/bus/hid/drivers/razermouse/0003:1532:0034.0002/
> Jan 01 23:14:37 arch-Bednar razer_mount[594]: Finished binding 0003:1532:021E.0004
> Jan 01 23:14:38 arch-Bednar razer_mount[595]: Changing group /sys/bus/hid/drivers/razerkbd/0003:1532:021E.0004/
> Jan 01 23:14:38 arch-Bednar razer_mount[597]: Changed group /sys/bus/hid/drivers/razerkbd/0003:1532:021E.0004/
> Jan 01 23:14:38 arch-Bednar razer_mount[609]: Finished binding 0003:1532:021E.0006
> Jan 01 23:14:38 arch-Bednar razer_mount[610]: Changing group /sys/bus/hid/drivers/razerkbd/0003:1532:021E.0006/
> Jan 01 23:14:38 arch-Bednar razer_mount[612]: Changed group /sys/bus/hid/drivers/razerkbd/0003:1532:021E.0006/

**Comment by ghost** [comment]
Possibly related to https://github.com/polychromatic/polychromatic/issues/123

yep, applying the "fix" from the second comment resolves the issue

**Comment by z3ntu** [comment]
Is this still an issue in the latest version?

**Comment by Ryoga85** [comment]
It does happen with my Cynosa Chroma on the current version as well and it makes sense because both Ornata Chroma and Cynosa Chroma don't have any M keys (so you need to be able to bind Macros to any regular key in order to use them). Just pressing Fn+F9 again stops recording a Macro but it doesn't stop the M-LED from blinking.

**Comment by dimyme** [comment]
if self._current_macro_bind_key is None:
    -                        # Restrict macro bind keys to M1-M5
    -                        if key_name not in ('M1', 'M2', 'M3', 'M4', 'M5'):
    -                            self._logger.warning("Macros are only for M1-M5 for now.")
    -                            self._recording_macro = False
    -                            self._parent.setMacroMode(False)
    -                        else:
                                self._current_macro_bind_key = key_name
                                self._parent.setMacroEffect(0x00)

will make stuff work on Ornata keyboard model which has no "M..." extra keys.

**Comment by Ryoga85** [comment]
Hi, I had the same problem with my Cynosa Chroma and because neither any of the comments here nor on the linked post could help, I decided to look deeper into this.

Turned out when you start the macro mode by pressing Fn+F9, the M-LED is set to flashing mode with "self._parent.setMacroEffect(0x01)" in line 411 of file /usr/lib/python3/dist-packages/openrazer_daemon/misc/key_event_management.py

However, when you press Fn+F9 again, the macro mode is ended, but someone forgot to turn the LED off again.
So I added "self._parent.setMacroEffect(0x00)" between line 423 and 424, which fixed the issue for me.

The whole thing starting from line 401 now looks like this:

                # Macro FN+F9 logic
                if key_name == 'MACROMODE':
                    self._logger.info("Got macro combo")

                    if not self._recording_macro:
                        # Starting to record macro
                        self._recording_macro = True
                        self._current_macro_bind_key = None
                        self._current_macro_combo = []

                        self._parent.setMacroEffect(0x01)
                        self._parent.setMacroMode(True)

                    else:
                        self._logger.debug("Finished recording macro")
                        # Finish recording macro
                        if self._current_macro_bind_key is not None:
                            if len(self._current_macro_combo) > 0:
                                self.add_kb_macro()
                            else:
                                # Clear macro
                                self.dbus_delete_macro(self._current_macro_bind_key)
                        self._recording_macro = False
                        self._parent.setMacroEffect(0x00)
                        self._parent.setMacroMode(False)

**Comment by z3ntu** [comment]
Please submit a PR if you have a solution, and also avoid necro-bumping old issues
