### ISSUE TITLE
Options missing on Razer Abyssus 2014

### ISSUE THREAD

**Issue by zbagz** [openrazer/openrazer#490]
Hey there, I've upgraded from Debian Jessie to Debian Stretch 9.3 x64 and now my mouse is moving awfully slow. and the same mouse worked just fine on debian jessie without installing anything as far as I can remember. 

I've tried a couple of different things, including using a different usb port, xinput set-prop, Xorg -configure with a couple different of settings I found on google in an attempt to increase the acceleration but nothing seems to work. So, I thought this could be something related to drivers and installed openrazer.

The problem is that the only option that shows up on my panel is the brightness button to turn off/on the logo light. (I've tried with Polychromatic and RazerGenie but the same thing happens, here's a screenshot https://i.imgur.com/mMfrQup.png). 

My mouse is a Razer Abyssus 2014 | 1532:0042, and according to the docs it *should* work, but I'm not sure, maybe this is a known issue or just something expected due to being a rather old mouse.

Thanks.

**Comment by z3ntu** [comment]
Do you have access to a Windows Virtual Machine? It seems that DPI was never implemented for this mouse (see e.g. #204). If yes, it would be great if you could make screenshots of the options in Synapse (you can ignore the logo led toggle and key remapping (if available)).

**Comment by blackbone** [comment]
> It seems that DPI was never implemented for this mouse.

[Here](https://itwriter.ru/wp-content/uploads/2015/07/3-0-new-1.png) they is. In a russian, but there are 2 options you can config:
Polling rate - 125/500/1000
Axis Specific DPI (x, y) - 100–3500

And here's lsusb
$ lsusb | grep Abyssus
Bus 001 Device 002: ID 1532:0042 Razer USA, Ltd Abyssus 2014

$ lsusb -d 1532:0042 -v
Bus 001 Device 002: ID 1532:0042 Razer USA, Ltd Abyssus 2014
Couldn't open device, some information will be missing
Device Descriptor:
  bLength                18
  bDescriptorType         1
  bcdUSB               2.00
  bDeviceClass            0 
  bDeviceSubClass         0 
  bDeviceProtocol         0 
  bMaxPacketSize0        64
  idVendor           0x1532 Razer USA, Ltd
  idProduct          0x0042 Abyssus 2014
  bcdDevice            2.00
  iManufacturer           1 
  iProduct                2 
  iSerial                 0 
  bNumConfigurations      1
  Configuration Descriptor:
    bLength                 9
    bDescriptorType         2
    wTotalLength           34
    bNumInterfaces          1
    bConfigurationValue     1
    iConfiguration          0 
    bmAttributes         0xa0
      (Bus Powered)
      Remote Wakeup
    MaxPower              500mA
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        0
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      1 Boot Interface Subclass
      bInterfaceProtocol      2 Mouse
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength      94
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x81  EP 1 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0008  1x 8 bytes
        bInterval               1

Can i help you somehow to add support for this mice?

**Comment by z3ntu** [comment]
Yes, if you could make packet captures when changing the dpi slider and the polling rate setting, that would make it very easy (see https://github.com/openrazer/openrazer/wiki/Reverse-Engineering-USB-Protocol)

**Comment by tweelix** [comment]
Hopefully reviving this as this is my favourite mouse.
I tried capturing packets however just changing the dpi slider doesn't seem to generate any packets at all. 
Therefore the first file dpi-1500-100.pcapng is me moving the mouse at 1500dpi, changing the dpi to 100 and then moving the mouse again. Packet No 0-94 where at 1500dpi and packets after that at 100.

I did manage to capture the packets for changing the polling rate setting. The second file polling_rate_500-1000-125 changes the polling rate first to 500, then to 1000 and finally to 125.

The files can be found here:
[captures.zip](https://github.com/openrazer/openrazer/files/4481885/captures.zip)

I'm kind of new to this so if there's anything else I can do to help let me know.

**Comment by z3ntu** [comment]
@tweelix Thanks. I also only see polling rate in the captures so it looks like Synapse does DPI in software on Windows (and not in hardware).

You can try adding `CREATE_DEVICE_FILE(&hdev->dev, &dev_attr_poll_rate);` to https://github.com/openrazer/openrazer/blob/master/driver/razermouse_driver.c#L3138 and `device_remove_file(&hdev->dev, &dev_attr_poll_rate);` to https://github.com/openrazer/openrazer/blob/master/driver/razermouse_driver.c#L3552 and `'get_poll_rate', 'set_poll_rate',` to https://github.com/openrazer/openrazer/blob/master/daemon/openrazer_daemon/hardware/mouse.py#L330 , then poll rate should be available in the front ends.
If you need any help with this, just ask. :)

**Comment by tweelix** [comment]
@z3ntu So that works for the polling rate. I can submit a PR if you'd like.

~~However the DPI mystery deepens. Whenever I finish my testing in the virtualbox windows VM the sensitivity of my mouse is really off, specifically it's way too high. It stays this way until I connect it back to my windows desktop PC after which the sensitivity is back to how it normally is. So maybe it is storing something on the mouse? Mind you it might just be a bug with X11 of some sort.~~
 
~~I actually have two Abyssus mice so I tested one that has been connected to the windows VM and one has come straight from being plugged into my windows pc. Both times set the DPI was set to 1500. The one that's been connected to the VM has much higher sensitivity. All their xinput-props are the same however. Wonder if you have any idea what may be going on here.~~

**Comment by tweelix** [comment]
> However the DPI mystery deepens. Whenever I finish my testing in the virtualbox windows VM the sensitivity of my mouse is really off, specifically it's way too high. It stays this way until I connect it back to my windows desktop PC after which the sensitivity is back to how it normally is. So maybe it is storing something on the mouse? Mind you it might just be a bug with X11 of some sort.
>
> I actually have two Abyssus mice so I tested one that has been connected to the windows VM and one has come straight from being plugged into my windows pc. Both times set the DPI was set to 1500. The one that's been connected to the VM has much higher sensitivity. All their xinput-props are the same however. Wonder if you have any idea what may be going on here.

Never mind, if I just unplug the mouse and plug it back in again it fixes the sensitivity. So it seems to just be either a X11 or XFWM issue. I'll just submit a PR for the Polling Rate

**Comment by z3ntu** [comment]
#1105 is merged. Closing.
