### ISSUE TITLE
Device Support for Razer ManO'War

### ISSUE THREAD

**Issue by simongoertzen** [openrazer/openrazer#492]
The headset works for me, but the volume wheel (up/down/mute) does not.

[lsusb.txt](https://github.com/openrazer/openrazer/files/1600860/lsusb.txt)
[by-id.txt](https://github.com/openrazer/openrazer/files/1600859/by-id.txt)
![polychromatic](https://user-images.githubusercontent.com/23029327/34527603-5489eb74-f0a6-11e7-835d-5371608f0aca.png)

**Comment by z3ntu** [comment]
Please search for existing issues before opening new ones. Duplicate of #43
