### ISSUE TITLE
Fedora 27 Fails to Synchronize with Repo

### ISSUE THREAD

**Issue by wcunning** [openrazer/openrazer#504]
I installed the repository as instructed on the website. When I attempted to install the openrazer-meta package, I got the following dnf error on a fresh install of Fedora 27:

Failed to synchronize cache for repo 'hardware_razer', disabling.     --:-- ETA
Last metadata expiration check: 0:05:19 ago on Sun 14 Jan 2018 11:32:16 AM EST.

I then ping'd download.opensuse.org, and then opened the /etc/yum.repos.d/hardware\:razer.repo  file and opened the actual repository page in a browser. All of that indicates that everything is up online and functional, but dnf seems to not want to pull the repository for some reason. Any idea what's going on?

**Comment by z3ntu** [comment]
![image](https://user-images.githubusercontent.com/3768500/34919966-70e1c134-f96b-11e7-840c-d17079c97941.png)
It works for me in a Fedora 27 virtual machine. I am not too overly familiar with Fedora/dnf so maybe you can ask in the Fedora support forum (if that exists) what the reason could be.

**Comment by wcunning** [comment]
I've asked it on their end, and we'll see what response I get. I will update when I have a resolution or if I get pointed back to download.opensuse.org.

https://ask.fedoraproject.org/en/question/116323/dnf-repo-failed-to-sync-cache/

**Comment by jonesie3419** [comment]
I am having the same issue and am unable to find a solution either. I have done the same as above and confirmed that everything seems to be in working order as far as the repo link being a working link. I have also run: `dnf clean all` followed by `dnf update` and still get the same failed to synchronize error.

![screenshot_2018-01-19_15-12-28](https://user-images.githubusercontent.com/9463832/35169622-30923802-fd2b-11e7-941a-926018d6885f.png)

**Comment by wcunning** [comment]
I have not gotten any traction other than trying dnf clean over on ask.fedoraproject.org. The fact that this is happening to someone else sort of inclines me to thinking that it's potentially a location issue and that bad mirrors are messing with us... Is there a good way to check that, maybe manually edit the mirror list that dnf is using? The verbose output I get says that all mirrors have been tried unsuccessfully.

**Comment by z3ntu** [comment]
Does `wget http://download.opensuse.org/repositories/hardware:/razer/Fedora_27/repodata/71e652ba8c7f6d344c48c876ed85fe52fe47d0bb15e3b4480c45d491865f0364-primary.xml.gz` work for you?

**Comment by fleekix** [comment]
Same issue here Fedora 27.

**Comment by jonesie3419** [comment]
@z3ntu Sorry for the delay in response. Yes the wget works, I followed it up with the dnf update so you could see the two commands back to back, and I still get the weird synchronize cache error.

![screenshot_2018-01-24_07-46-47](https://user-images.githubusercontent.com/9463832/35332938-f805d4b8-00da-11e8-861b-dbef2e487b5b.png)

**Comment by z3ntu** [comment]
@jonesie3419 Can you add `-v` to the dnf command? It should output something with `Cannot download` according to the dnf source code.

**Comment by jonesie3419** [comment]
@z3ntu, sure here you go:

> Cannot download 'http://download.opensuse.org/repositories/hardware:/razer/Fedora_27/': Yum repo downloading error: Downloading error(s): repodata/71e652ba8c7f6d344c48c876ed85fe52fe47d0bb15e3b4480c45d491865f0364-primary.xml.gz - Cannot download, all mirrors were already tried without success; repodata/65ddfab8ea49c9a36fdf8bbf20a92ba2da760bef3bcd55719cb4cae1a0c574a5-filelists.xml.gz - Cannot download, all mirrors were already tried without success.

**Comment by z3ntu** [comment]
Found that in a rather old bug report - can you try that?

> It seems like the connection of mirrors is closed because of timeout. Can you try to set `timeout=100` (or more) [1] into dnf.conf, please?
> 
> [1] http://dnf.readthedocs.org/en/latest/conf_ref.html#options-for-both-main-and-repo

**Comment by jonesie3419** [comment]
Updated in both the repo and the /etc/dnf/dnf.conf file and still seeing the same error:

![screenshot_2018-01-24_10-30-34](https://user-images.githubusercontent.com/9463832/35341283-519ebe32-00f3-11e8-8bbd-c27c48308ea1.png)

![screenshot_2018-01-24_10-31-16](https://user-images.githubusercontent.com/9463832/35341292-561ebc3c-00f3-11e8-81e3-5992bfdcd2fc.png)

> Cannot download 'http://download.opensuse.org/repositories/hardware:/razer/Fedora_27/': Yum repo downloading error: Downloading error(s): repodata/71e652ba8c7f6d344c48c876ed85fe52fe47d0bb15e3b4480c45d491865f0364-primary.xml.gz - Cannot download, all mirrors were already tried without success; repodata/65ddfab8ea49c9a36fdf8bbf20a92ba2da760bef3bcd55719cb4cae1a0c574a5-filelists.xml.gz - Cannot download, all mirrors were already tried without success.
repo: using cache for: nodesource

**Comment by caffienetoolbar** [comment]
I just did a brand new install of Fedora 27 and am having the same error.

**Comment by z3ntu** [comment]
I triggered a rebuild on OBS. Maybe that will fix something.

**Comment by hyph3n** [comment]
Are any of you encountering this problem using a VPN?

I ran into a similar situation a few weeks ago and determined that the repo was killing my connection with an RST packet when attempting a dnf update--even though I could view the files/folders in a web browser no problem, and a dnf install worked just fine on a different system. 

I can't remember if I changed to a different VPN address or just temporarily turned it off on the failing machine, but I was eventually able to update normally. Haven't reproduced the issue since. ¯\\\_(ツ)\_/¯

**Comment by z3ntu** [comment]
@hyph3n I activated a openvpn connection to my server on the host but in the guest VM dnf upgrade still works fine.

**Comment by hyph3n** [comment]
In my case, the problem seemed to be related to the repo not liking one of my VPN provider's (PIA) addresses. As I said, switching to a different address cleared things up for me right away. YMMV :)

**Comment by caffienetoolbar** [comment]
I'm not using a VPN.  I just literally installed Fedora 27 and tried to install.  Just a thought.  Maybe its failing the GPG check.  I ended up finding another page of yours with the binaries and think it installed it ok.  I tried to connect to the same repo for RazerGenie and that fails as well.

**Comment by z3ntu** [comment]
I just installed a fresh VM with Fedora 27, ran the two commands listed on the website and it works without any problems. Sorry, but I really can't reproduce this.
Maybe some mirror on OBS makes problem. What's the country you're accessing the repo from? I'm from Austria.

**Comment by jonesie3419** [comment]
I am not using a VPN either, I am in the United States. I will try a few other things to see if I can get it to work, I also have not tried since you did the rebuild of OBS.

**Comment by hyph3n** [comment]
I just did the following:

1) `sudo dnf clean all`

2) `sudo dnf check-update`

`Failed to synchronize cache for repo 'hardware_razer', disabling.                                                           ] ---  B/s |   0  B     --:-- ETA`

3) Connect to VPN using **North American** IP address.

4) `sudo dnf clean all`

5) `sudo dnf check-update`

`Failed to synchronize cache for repo 'hardware_razer', disabling.                                                           ] ---  B/s |   0  B     --:-- ETA`

6) Connect to VPN using **German** IP address.

7) `sudo dnf clean all`

8) `sudo dnf check-update`

`hardware:razer (Fedora_26)                                                                                                     14 kB/s | 9.2 kB     00:00    `


I don't know why the repo would be rejecting certain IP addresses, but that certainly seems to be what's going on here. Sorry if I didn't explain myself better in my earlier comments.

**Comment by z3ntu** [comment]
@hyph3n Thanks for testing. Could you write an email to the OBS mailing list (https://lists.opensuse.org/archive/opensuse-buildservice/) and explain the issue with basically the last comment you wrote? You can put me in CC (email is on my gh profile).

**Comment by z3ntu** [comment]
Or send an email to admin at opensuse.org which opens a support ticket

**Comment by wcunning** [comment]
It would appear that someone has done the communication with OBS, since I just noticed the repository not complaining when I updated packages today. I have successfully installed openrazer on Fedora 27 in Michigan, United States, North America. I'll leave it for the other people on this issue to chime in with their success or failure before closing the issue, but it looks resolved to me.

**Comment by z3ntu** [comment]
@wcunning Yes, @hyph3n sent an email but I don't have access to the ticket made from that email but great, that it works now!

**Comment by ctrl-b** [comment]
Was this officially resolved? Any instructions on how to make it work? Do you have the link of the ticket? I just tried and is not working... Thanks!

**Comment by hyph3n** [comment]
Confirmed that the OBS repo is working correctly when I use a German exit node on my VPN, not working when I use a north american exit node. 

I am wondering if it would make sense to use COPR for Fedora (https://copr.fedorainfracloud.org/) since the OBS repo seems unreliable when accessed outside of Europe. I don't know exactly what would be involved or how big a lift it would be, but it might be worth investigation.

**Comment by ctrl-b** [comment]
I changed my exit node to a German one, and it's working. Before I was in a north american exit node.
