### ISSUE TITLE
Request for Support: Razer Blade 14" 2017 (Kaby Lake)

### ISSUE THREAD

**Issue by PDXsailor** [openrazer/openrazer#511]
Could you please add official support for the Razer Blade 14" 2017 (Kaby Lake)? The Model Number is RZ09-0195, Product Number RZ09-01953E72.

Thanks, Greg

[OpenrazerInfo.txt](https://github.com/openrazer/openrazer/files/1661963/OpenrazerInfo.txt)
<img width="450" alt="capturesynapse1" src="https://user-images.githubusercontent.com/34016900/35361399-1686e040-0116-11e8-81d7-8bcc41439fc0.PNG">
<img width="450" alt="capturesynapse1half" src="https://user-images.githubusercontent.com/34016900/35361400-16bcf338-0116-11e8-9c7d-e9b5f3674ee9.PNG">
<img width="453" alt="capturesynapse2" src="https://user-images.githubusercontent.com/34016900/35361401-16da091e-0116-11e8-8441-798ac2c06fef.PNG">
<img width="449" alt="capturesynapse3" src="https://user-images.githubusercontent.com/34016900/35361402-1701c210-0116-11e8-9c77-1e71dd6b33b0.PNG">
<img width="449" alt="capturesynapse4" src="https://user-images.githubusercontent.com/34016900/35361403-171e3544-0116-11e8-8577-9eced04589cf.PNG">

**Comment by z3ntu** [comment]
Please post the output of
`lsusb -d 1532: -v`
and
`ls -lah /dev/input/by-id/`
Read [this](https://github.com/openrazer/openrazer/wiki/Reverse-Engineering-USB-Protocol) because we need packet captures of the usb traffic.

**Comment by PDXsailor** [comment]
I already did - see OpenRazerInfo.txt above.

**Comment by z3ntu** [comment]
1532:0224 is already supported.

**Comment by PDXsailor** [comment]
Can the device be added to the readme please?

Razer Blade FHD    1532:0195

Thanks

**Comment by z3ntu** [comment]
1532:0195 is not yet supported so no.
