### ISSUE TITLE
Black Widow Ultimate 2016 accidentally hit macro key now it just keeps blinking

### ISSUE THREAD

**Issue by krutoileshii** [openrazer/openrazer#523]
Just need some help. Accidentally hit macro key and now can't disable it. the blinking red light is annoying . How do I turn it off.

**Comment by ghost** [comment]
Navigate to the directory that your device is detected by openrazer in a terminal. The directory is something like /sys/bus/hid/drivers/razerkbd/

There are probably going to be multiple folders in there. Run "ls <folder name>" on each of them until you see a file with the word "macro" in it; cd into the directory with that file. After that, I think you run "echo 0 > macro_file". Obviously substitute macro_file for the actual name in your case.

That should turn off the light.

**Comment by krutoileshii** [comment]
Awesome thank you. Dang thing was driving me nuts.

**Comment by ghost** [comment]
No worries at all.
