### ISSUE TITLE
Doesnt find any razer devices on Manjaro Linux

### ISSUE THREAD

**Issue by ravi0lii** [openrazer/openrazer#528]
Hello,
openrazer doesnt find any devices on Manjaro (Arch) Linux. Im using Polychromatic controller. I installed everything and started the daemon, but it doesnt work too.
Thanks for you help.

**Comment by z3ntu** [comment]
The output of the following commands please:
`sudo dkms install openrazer-driver/1.0.0; sudo modprobe razerkbd`
`python3 -c "from openrazer.client import DeviceManager; a = DeviceManager(); print(a.devices)"`

**Comment by Rasie1** [comment]
This might be the same issue https://github.com/openrazer/openrazer/issues/520

**Comment by ravi0lii** [comment]
sudo dkms install openrazer-driver/1.0.0; sudo modprobe razerkbd
```
Error! echo
Your kernel headers for kernel 4.14.19-1-MANJARO cannot be found at
/usr/lib/modules/4.14.19-1-MANJARO/build or /usr/lib/modules/4.14.19-1-MANJARO/source.
modprobe: FATAL: Module razerkbd not found in directory /lib/modules/4.14.19-1-MANJARO
```
python3 -c "from openrazer.client import DeviceManager; a = DeviceManager(); print(a.devices)"
```
[]
```

**Comment by z3ntu** [comment]
Please read the first message and install your kernel headers.

**Comment by ravi0lii** [comment]
The problem is that I already installed the kernel headers (`sudo pacman -S linux-headers`)

**Comment by z3ntu** [comment]
If the kernel headers aren't at `/usr/lib/modules/$(uname -r)/build` (even after a reboot) then there's something wrong with the installation.
