### ISSUE TITLE
unable to use my naga chroma mouse on Debian

### ISSUE THREAD

**Issue by ti1336** [openrazer/openrazer#531]
Hi,

i'm trying to use my naga chroma on my office computer with an MX Linux distribution, but i'm unable to make it works... 
I've trying some solved issues, but i'm still doing something wrong :/ 
It's important for me, my left arm is paralized and this mouse is very helpfull for me. 

thank you in advance 

PS : sorry for my bad english

**Comment by z3ntu** [comment]
The output of the following commands please:
`sudo dkms install openrazer-driver/1.0.0; sudo modprobe razerkbd`
`python3 -c "from openrazer.client import DeviceManager; a = DeviceManager(); print(a.devices)"`

**Comment by ti1336** [comment]
`Module openrazer-driver/1.0.0 already installed on kernel 4.13.0-1-amd64/x86_64`
`modprobe: FATAL: Module razer not found in directory /lib/modules/4.13.0-1-amd64`
`[<RazerMouse PM1729H00901230>]`

**Comment by z3ntu** [comment]
Except that you copy pasted the first command wrong 😉 , it seems fine.
What isn't working?

**Comment by ti1336** [comment]
When i'm trying to open custom editor he said to me : device type not implemented
![rgnc](https://user-images.githubusercontent.com/36693572/36474595-45ca79f0-16f8-11e8-9da8-e19d54e46681.png)

**Comment by z3ntu** [comment]
This is an issue for the RazerGenie repository, not the openrazer one :slightly_smiling_face: => https://github.com/z3ntu/RazerGenie/

**Comment by ti1336** [comment]
Oh ok sorry ! Thank you for your help :)
