### ISSUE TITLE
Razer Orochi (wired mode)

### ISSUE THREAD

**Issue by MinervaW1993** [openrazer/openrazer#54]
This is another mouse I have. 

lsusb and response data:https://gist.github.com/MinervaW1993/8cdefdb37187f39edadc966d1fc75c6d

Synapse screenshot
![2016-09-21 00_14_19-razer configurator](https://cloud.githubusercontent.com/assets/22280532/18699551/225371fc-7fa0-11e6-9326-5f2854bb91a2.png)
![2016-09-21 00_14_55-razer configurator](https://cloud.githubusercontent.com/assets/22280532/18699553/22550e04-7fa0-11e6-9b43-9cfad4d20b39.png)
![2016-09-21 00_15_07-razer configurator](https://cloud.githubusercontent.com/assets/22280532/18699557/2259d0c4-7fa0-11e6-86d9-8b74d879f511.png)
![2016-09-21 00_15_21-razer configurator](https://cloud.githubusercontent.com/assets/22280532/18699555/2255c2c2-7fa0-11e6-95e2-31087d0222f6.png)
![2016-09-21 00_16_04-razer configurator](https://cloud.githubusercontent.com/assets/22280532/18699552/22551c3c-7fa0-11e6-8943-2c96ac5c6bbc.png)
![2016-09-21 00_16_32-razer configurator](https://cloud.githubusercontent.com/assets/22280532/18699554/22553870-7fa0-11e6-8886-b79bfa3a8796.png)
![2016-09-21 00_16_57-razer configurator](https://cloud.githubusercontent.com/assets/22280532/18699556/2258bf4a-7fa0-11e6-8270-d9d72136541f.png)
![2016-09-21 00_17_21-razer configurator](https://cloud.githubusercontent.com/assets/22280532/18699559/225bd888-7fa0-11e6-88ca-6a04ec24ec9e.png)
![2016-09-21 00_17_46-razer configurator](https://cloud.githubusercontent.com/assets/22280532/18699560/2262263e-7fa0-11e6-9f2e-0078ab11dd99.png)
![2016-09-21 00_17_59-razer configurator](https://cloud.githubusercontent.com/assets/22280532/18699558/225bc7bc-7fa0-11e6-8b05-f2620b48744a.png)

While idling wireshark got an auto response every 30 seconds. Maybe it is checking battery status?

Wireshark packets:
[orochi.tar.gz](https://github.com/terrycain/razer-drivers/files/484240/orochi.tar.gz)

**Comment by MinervaW1993** [comment]
This is only for wired mode. For bluetooth mode... well big challenge.

**Comment by terricain** [comment]
@MinervaW1993 Your in luck as if its anything like my wireless mamba, most of the hard work should be done :wink:. Your conclusions are pretty accurate, if you look in one of the driver files there is a struct that denotes what bytes are what.

Is the mouse bluetooth or does it have a dock like the mamba?

I do love pcapng's I can cat them together and they just act as one file :smile:. Having separate ones is good, and then when I want to through it through my program I can just join up a few.

**Comment by terricain** [comment]
And LOL at synapse, the idle packet you keep seeing isnt supported by the mouse, but synapse keeps sending it ha.

**Comment by terricain** [comment]
Ok look at branch `RazerOrochi_0x0048`. You know the procedure:wink: [this](https://github.com/terrycain/razer-drivers/wiki/Using-the-mouse-driver) should help with various device files, if things arnt in there then tell me as they'll need adding.

**Comment by MinervaW1993** [comment]
ls -l output:
-r--r--r-- 1 root root 4096 Sep 21 09:39 country
-r--r----- 1 root root 4096 Sep 21 09:39 device_type
lrwxrwxrwx 1 root root    0 Sep 21 09:39 driver -> ../../../../../../../../bus/hid/drivers/razermouse
-r--r----- 1 root root 4096 Sep 21 09:39 get_firmware_version
-r--r----- 1 root root 4096 Sep 21 09:39 get_serial
drwxr-xr-x 3 root root    0 Sep 21 09:39 hidraw
drwxr-xr-x 3 root root    0 Sep 21 09:39 input
-r--r--r-- 1 root root 4096 Sep 21 09:39 modalias
--w--w---- 1 root root 4096 Sep 21 09:39 mode_breath
--w--w---- 1 root root 4096 Sep 21 09:39 mode_none
--w--w---- 1 root root 4096 Sep 21 09:39 mode_reactive
-rw-rw---- 1 root root 4096 Sep 21 09:39 mode_scroll
--w--w---- 1 root root 4096 Sep 21 09:39 mode_spectrum
--w--w---- 1 root root 4096 Sep 21 09:39 mode_static
-rw-rw---- 1 root root 4096 Sep 21 09:39 poll_rate
drwxr-xr-x 2 root root    0 Sep 21 09:39 power
-r--r--r-- 1 root root 4096 Sep 21 09:39 report_descriptor
-rw-rw---- 1 root root 4096 Sep 21 09:39 set_brightness
--w--w---- 1 root root 4096 Sep 21 09:39 set_idle_time
--w--w---- 1 root root 4096 Sep 21 09:39 set_low_battery_threshold
--w--w---- 1 root root 4096 Sep 21 09:39 set_mouse_dpi
lrwxrwxrwx 1 root root    0 Sep 21 09:33 subsystem -> ../../../../../../../../bus/hid
-rw-r--r-- 1 root root 4096 Sep 21 09:39 uevent
-r--r----- 1 root root 4096 Sep 21 09:39 version

All settings work.

The mouse is Bluetooth 4.0, but unfortuanely I don't have a Linux device which has any bluetooth interface :(

**Comment by terricain** [comment]
Nice :smile: If you ever get a linux with teh bluetooth then your welcome to add wireless support ;). Will merge this to main codebase

**Comment by z3ntu** [comment]
@MinervaW1993 What's the model / product number of the mouse? There are 3 different Orochi editions afaik (2011, 2013 & 2015).
