### ISSUE TITLE
Linux Mint 18.3 DeathAdder Elite "Device not recognized" on polychromatic

### ISSUE THREAD

**Issue by escobera** [openrazer/openrazer#542]
Hello there,
I've installed this tool and polychromatic from the stable ppas but can't get my mouse to work under it.

`sudo dkms install openrazer-driver/1.0.0; sudo modprobe razerkbd
python3 -c "from openrazer.client import DeviceManager; a = DeviceManager(); print(a.devices)`

 gives

```
Module openrazer-driver/1.0.0 already installed on kernel 4.13.0-36-generic/x86_64
[]
```

**Comment by z3ntu** [comment]
`sudo modprobe razerkbd `?

**Comment by escobera** [comment]
> sudo modprobe razerkbd?

No message shows up, same with `sudo modprobe razermouse`

**Comment by z3ntu** [comment]
Then `lsmod | grep razer` ?
Seems like the components the kernel driver, daemon and python lib work fine...

**Comment by escobera** [comment]
```
$ lsmod | grep razer
razerkbd               57344  0
razermouse             65536  0
hid                   118784  4 razermouse,hid_generic,usbhid,razerkbd
```

**Comment by z3ntu** [comment]
`lsusb | grep 1532` ?

**Comment by escobera** [comment]
```
$ lsusb | grep 1532
Bus 003 Device 003: ID 1532:005c Razer USA, Ltd 
```

**Comment by maxitenerife** [comment]
I'm experiencing he same problem on Ubuntu 16.04. :(

**Comment by escobera** [comment]
Yeah, I forgot to mention I'm on Linux Mint 18.3

**Comment by z3ntu** [comment]
@maxitenerife Also the same device?

@escobera Output of `ls -al /sys/bus/hid/drivers/razermouse/0*/` ?

**Comment by escobera** [comment]
```
$ ls -al /sys/bus/hid/drivers/razermouse/0*/
ls: cannot access '/sys/bus/hid/drivers/razermouse/0*/': No such file or directory
```

Is this the normal behavior?

**Comment by maxitenerife** [comment]
ls -al /sys/bus/hid/drivers/razermouse/0*/
Bus 002 Device 005: ID 1532:004d Razer USA, Ltd 

ls -al /sys/bus/hid/drivers/razermouse/0*/
ls: cannot access '/sys/bus/hid/drivers/razermouse/0*/': No such file or directory

No message shows upwith sudo modprobe razerkbd, same with sudo modprobe razermouse

It seems as the same problem that others are experiencing under Mint.

**Comment by escobera** [comment]
@z3ntu anything else I can do to debug this issue?

**Comment by z3ntu** [comment]
Is there something with `sudo journalctl -b | grep -i razer_mount` ?
If there is no error I guess udev is not getting triggered correctly.

**Comment by escobera** [comment]
@z3ntu 
`sudo journalctl -b | grep -i razer_mount` shows nothing

**Comment by z3ntu** [comment]
Then it really seems like udev is being weird. Can you try installing an older version of the driver to see if the issue was introduced somewhere?

**Comment by escobera** [comment]
I can do that, but I don't know how to. The ppa seems to carry only the latest version.

**Comment by z3ntu** [comment]
Clone the repo, check out an old version (maybe v2.2.0 if that version supports this device), then look at https://github.com/openrazer/openrazer/wiki/Building-a-package#ubuntu--linux-mint how to build and install the package

**Comment by escobera** [comment]
Hmm I installed v2.2.1 and it worked. Upgraded to `master` and it is working as well. 
Maybe there's something wrong with the install script from the ppa?

**Comment by z3ntu** [comment]
Okay so this issue is Linux Mint 18.3 (based on Ubuntu 16.04) and Ubuntu 16.04... I have downloaded the `openrazer-kernel-modules-dkms_2.2.2~ubuntu16.04.1_amd64.deb` file from the ppa and the udev rules file is in there... And master is literally v2.2.2 ...

**Comment by z3ntu** [comment]
No response - closing.
