### ISSUE TITLE
razer blade stealth late 2016 issue with restart and power off

### ISSUE THREAD

**Issue by dominikS007** [openrazer/openrazer#546]
When turning off the system it will never turn off completely it will crash while trying to turn off, the same goes for the restart. The system that I have is:

Razer Blade Stealth late 2016 UHD 
CPU: Intel® Core™ i7-7500U CPU @ 2.70GHz × 4 
GPU: Intel® HD Graphics 620 (Kaby Lake GT2)
Gnome: 3.26.2

**Comment by z3ntu** [comment]
Does the same thing happen without the drivers installed?

**Comment by dominikS007** [comment]
I am a new user of Ubuntu and do not know many commands, which command would I use to uninstall the whole driver ?

**Comment by z3ntu** [comment]
`sudo apt purge openrazer-meta` and maybe then `sudo apt autoremove`

**Comment by dominikS007** [comment]
I have just restarted the system and the system did not turn off but crashed while doing it.

**Comment by z3ntu** [comment]
If it's still happening without driver installed (check with `dpkg -l | grep openrazer`) then it's not the fault of this software.
