### ISSUE TITLE
Can't get it working on OpenSUSE LEAP (no daemon)

### ISSUE THREAD

**Issue by JeromeDesseaux** [openrazer/openrazer#548]
Hi, 

I did everything regarding the installation (adding the repo, installing...) and everything has been installed. 

But when starting razerGenie, I got an error message that says daemon is not running. 

`➜  ~ sudo service openrazer-daemon start
service: no such service openrazer-daemon
`

I don't know what to do then... Everything is installed :(

Thanks for your help

**Comment by z3ntu** [comment]
Do you still need help?
