### ISSUE TITLE
No Menu

### ISSUE THREAD

**Issue by ghost** [openrazer/openrazer#557]
Once installed on Ubuntu 17.10 there is no menu to edit options. Anyone know where to find these setting for the keyboard?

Thanks

**Comment by lah7** [comment]
OpenRazer simply provides the driver and daemon (backend if you like), you'll need to install a front-end application like [Polychromatic](https://github.com/lah7/polychromatic), [RazerGenie](https://github.com/z3ntu/RazerGenie) or [razerCommander](https://github.com/GabMus/razerCommander).

**Comment by ghost** [comment]
@lah7 Thank you!
