### ISSUE TITLE
Can't modprobe razerkbd

### ISSUE THREAD

**Issue by lostallmymoney** [openrazer/openrazer#563]
Yeah so I'm not really experienced with drivers and such. I installed openrazer and polychromatic and poly tells me that the daemon is running and the mouse (naga 2014) is detected. It tells me to use modprobe to bind the mouse. I tried using modprobe razerkbd but the file isn't in the folder /lib/modules/Kali
Thanks for helping me solve this.

**Comment by z3ntu** [comment]
What's the output of `sudo dkms install openrazer-driver/1.0.0` ?

**Comment by lostallmymoney** [comment]
Thanks looks like i didn't had headers installed. Also is there a 'made to' way to make it boot with --as-root flag as default so I don't have to manually do it ?

**Comment by lostallmymoney** [comment]
Oops i just saw the troubleshooting page lol

**Comment by z3ntu** [comment]
Why are you running the daemon as root...?

**Comment by lostallmymoney** [comment]
Most of the things i do needs root so i just login as root no big deal

**Comment by z3ntu** [comment]
Well, your choice. You could edit the systemd unit file and add the parameter there if you really have to. (filename will be printed with `systemctl --user status openrazer-daemon.service`). But your issues seem to be solved, so I'm closing this.
