### ISSUE TITLE
Add device support for Razer Kraken 7.1 Classic. 1532:0506

### ISSUE THREAD

**Issue by MasterUK** [openrazer/openrazer#568]
So for some reason my Razer Kraken 7.1 Classic headset does not show up as the same number as in the list. Maybe this is because I am from the UK... Could you please assist me in getting this to work.

**Comment by z3ntu** [comment]
* Please post the output of
`lsusb -d 1532:0506 -v`
and
`ls -lah /dev/input/by-id/`
* Read [this](https://github.com/openrazer/openrazer/wiki/Reverse-Engineering-USB-Protocol) because we probably need packet captures.
* Screenshots of all available options on Razer Synapse are needed.
* And lastly, the product & model number of the device for documentation reasons please.

**Comment by MasterUK** [comment]
Heading off to bed. Will comment with the info you have requested tomorrow.
Thanks for the fast response.

**Comment by MasterUK** [comment]
Here are the results from the first two commands.
Going to switch to windows for the screenshots and read that links content.
[lsusb.txt](https://github.com/openrazer/openrazer/files/1892655/lsusb.txt)
[by-id.txt](https://github.com/openrazer/openrazer/files/1892657/by-id.txt)

**Comment by MasterUK** [comment]
![1](https://user-images.githubusercontent.com/38225149/38534258-31981e90-3c75-11e8-8478-b752cb337167.PNG)
![2](https://user-images.githubusercontent.com/38225149/38534259-31c91964-3c75-11e8-9416-5c3fa04b80ea.PNG)
![3](https://user-images.githubusercontent.com/38225149/38534260-31df8d66-3c75-11e8-99a3-0c1ecc1d9070.PNG)
![4](https://user-images.githubusercontent.com/38225149/38534261-31f70d4c-3c75-11e8-8d17-5596b38480de.PNG)
![5](https://user-images.githubusercontent.com/38225149/38534263-320ff88e-3c75-11e8-9418-8512ae79281f.PNG)
![6](https://user-images.githubusercontent.com/38225149/38534264-32275dd0-3c75-11e8-924d-5e70c4a65304.PNG)

**Comment by z3ntu** [comment]
Which distro do you use? I have a driver that might work.

**Comment by MasterUK** [comment]
Lubuntu.

**Comment by z3ntu** [comment]
Please follow https://github.com/openrazer/openrazer/wiki/Building-a-package#ubuntu--linux-mint and replace the `TARGET_BRANCH` with `feature_kraken71_2`

**Comment by MasterUK** [comment]
Will try after work tomorrow. Thanks.

**Comment by z3ntu** [comment]
Bump

**Comment by MasterUK** [comment]
Oh S##t, Forgot about this. Will try them this weekend or tomorrow if I get a bit of free time.
