### ISSUE TITLE
Linuxmint 17.3 add repository ppa - PPA does not support trusty

### ISSUE THREAD

**Issue by tapin13** [openrazer/openrazer#570]
sudo add-apt-repository ppa:openrazer/stable
'This PPA does not support trusty'
Cannot add PPA: ''This PPA does not support trusty''.

Any issues?

Linux tapin13-MS-7519 3.19.0-32-generic #37~14.04.1-Ubuntu SMP Thu Oct 22 09:41:40 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

**Comment by z3ntu** [comment]
We do not support Ubuntu 14.04 or derivatives of that version. Please upgrade to a newer supported version.
