### ISSUE TITLE
Can't start openrazer-daemon on Mint 18.3

### ISSUE THREAD

**Issue by DanyGee** [openrazer/openrazer#574]
**razercommander**
Importing device logic, waiting for daemon
ERROR: the daemon is not responding!
Try running `killall razer-daemon && razer-daemon` or rebooting. If this doesn't work, please fill an issue!
Exception: org.freedesktop.DBus.Python.FileNotFoundError: Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/dbus/service.py", line 707, in _message_cb
    retval = candidate_method(self, *args, **keywords)
  File "/usr/lib/python3/dist-packages/openrazer_daemon/dbus_services/dbus_methods/all.py", line 85, in get_keyboard_layout
    with open(driver_path, 'r') as driver_file:
FileNotFoundError: [Errno 2] No such file or directory: '/sys/devices/pci0000:00/0000:00:1c.4/0000:0d:00.0/usb5/5-2/5-2:1.2/0003:1532:021A.0006/kbd_layout'

**lsmod | grep razer**
razerkbd               57344  0
hid                   118784  7 i2c_hid,hid_generic,usbhid,hid_logitech_dj,razerkbd,hid_logitech_hidpp

**sudo journalctl -b | grep -i razer_mount**        
kwi 18 15:49:38 linuxmint razer_mount[810]: Driver razerkbd
kwi 18 15:49:38 linuxmint razer_mount[809]: Driver razerkbd
kwi 18 15:49:38 linuxmint razer_mount[812]: Device_ID 0003:1532:021A.0005
kwi 18 15:49:38 linuxmint razer_mount[814]: Unbinding 0003:1532:021A.0005 from hid-generic
kwi 18 15:49:38 linuxmint razer_mount[813]: Device_ID 0003:1532:021A.0004
kwi 18 15:49:38 linuxmint razer_mount[815]: Unbinding 0003:1532:021A.0004 from hid-generic
kwi 18 15:49:38 linuxmint razer_mount[838]: Driver razerkbd
kwi 18 15:49:38 linuxmint razer_mount[841]: Device_ID 0003:1532:021A.0006
kwi 18 15:49:38 linuxmint razer_mount[846]: Unbinding 0003:1532:021A.0006 from hid-generic
kwi 18 15:49:38 linuxmint razer_mount[1353]: Binding 0003:1532:021A.0005 to razerkbd
kwi 18 15:49:39 linuxmint razer_mount[1372]: Binding 0003:1532:021A.0004 to razerkbd
kwi 18 15:49:39 linuxmint razer_mount[1373]: Binding 0003:1532:021A.0006 to razerkbd
kwi 18 15:49:39 linuxmint razer_mount[1392]: Finished binding 0003:1532:021A.0005
kwi 18 15:49:39 linuxmint razer_mount[1393]: Changing group /sys/bus/hid/drivers/razerkbd/0003:1532:021A.0005/
kwi 18 15:49:39 linuxmint razer_mount[1395]: Changed group /sys/bus/hid/drivers/razerkbd/0003:1532:021A.0005/
kwi 18 15:49:39 linuxmint razer_mount[1413]: Finished binding 0003:1532:021A.0004
kwi 18 15:49:39 linuxmint razer_mount[1414]: Changing group /sys/bus/hid/drivers/razerkbd/0003:1532:021A.0004/
kwi 18 15:49:39 linuxmint razer_mount[1416]: Finished binding 0003:1532:021A.0006
kwi 18 15:49:39 linuxmint razer_mount[1417]: Changing group /sys/bus/hid/drivers/razerkbd/0003:1532:021A.0006/
kwi 18 15:49:39 linuxmint razer_mount[1418]: Changed group /sys/bus/hid/drivers/razerkbd/0003:1532:021A.0004/
kwi 18 15:49:39 linuxmint razer_mount[1420]: Changed group /sys/bus/hid/drivers/razerkbd/0003:1532:021A.0006/

**dmesg | grep razer**
[    1.944866] razerkbd: loading out-of-tree module taints kernel.
[    1.944880] razerkbd: module verification failed: signature and/or required key missing - tainting kernel
[    5.956328] razerkbd 0003:1532:021A.0005: input,hidraw0: USB HID v1.11 Keyboard [Razer Razer BlackWidow X Tournament Edition Chroma] on usb-0000:0d:00.0-2/input1
[    6.016348] razerkbd 0003:1532:021A.0004: input,hidraw1: USB HID v1.11 Keyboard [Razer Razer BlackWidow X Tournament Edition Chroma] on usb-0000:0d:00.0-2/input0
[    6.017913] razerkbd 0003:1532:021A.0006: input,hidraw2: USB HID v1.11 Mouse [Razer Razer BlackWidow X Tournament Edition Chroma] on usb-0000:0d:00.0-2/input2

[razer.log](https://github.com/openrazer/openrazer/files/1924581/razer.log)

**System**
OS: Linux Mint 18.3 Sylvia x86_64 
Kernel: 4.13.0-36-generic 
Uptime: 48 mins 
Packages: 3229 
Shell: bash 4.3.48 
Resolution: 3840x2160 
DE: Cinnamon 3.6.7 
WM: Mutter (Muffin) 
WM Theme: Arc-Dark (Arc-Dark) 
Theme: Arc-Dark [GTK2/3] 
Icons: Papirus-Dark [GTK2/3] 
Terminal: gnome-terminal 
CPU: Intel i7-6700K (8) @ 4.300GHz 
GPU: NVIDIA NVIDIA Corporation Device 1b80
Memory: 2617MiB / 32102MiB 

**If you need more info - ask.**

**Comment by z3ntu** [comment]
Please run `find /usr/lib/modules -name "razer*.ko"`, and send me the output.

If you just want to fix it you can then follow https://github.com/polychromatic/polychromatic/issues/146#issuecomment-379465409 otherwise we could try to figure out why this weird behaviour happens (i.e. kernel module not getting updated or something).

**Comment by DanyGee** [comment]
**find /usr/lib/modules -name "razer*.ko"*
find: `/usr/lib/modules': no such file or directory

**Comment by z3ntu** [comment]
It's `find /lib/modules -name "razer*.ko"` on ubuntu, sry

**Comment by DanyGee** [comment]
**find /lib/modules -name "razer*.ko"*
/lib/modules/4.13.0-36-generic/kernel/drivers/hid/razermouse.ko
/lib/modules/4.13.0-36-generic/kernel/drivers/hid/razercore.ko
/lib/modules/4.13.0-36-generic/kernel/drivers/hid/razermug.ko
/lib/modules/4.13.0-36-generic/kernel/drivers/hid/razerfirefly.ko
/lib/modules/4.13.0-36-generic/kernel/drivers/hid/razerkbd.ko
/lib/modules/4.13.0-36-generic/kernel/drivers/hid/razerkraken.ko

**Comment by z3ntu** [comment]
`sudo dkms remove openrazer-driver/1.0.0 --all` and then the find command again?

**Comment by DanyGee** [comment]
> sudo dkms remove openrazer-driver/1.0.0 --all and then the find command again?

Now the find command finds nothing.

**Comment by z3ntu** [comment]
`sudo dkms install openrazer-driver/1.0.0` and reboot. Does it work then?

**Comment by DanyGee** [comment]
> sudo dkms install openrazer-driver/1.0.0 and reboot. Does it work then?

**sudo dkms install openrazer-driver/1.0.0**

Creating symlink /var/lib/dkms/openrazer-driver/1.0.0/source ->
                 /usr/src/openrazer-driver-1.0.0

DKMS: add completed.

Kernel preparation unnecessary for this kernel.  Skipping...

Building module:
cleaning build area....
KERNELDIR=/lib/modules/4.13.0-36-generic/build make driver....
cleaning build area....

DKMS: build completed.

razerkbd.ko:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/4.13.0-36-generic/kernel/drivers/hid/

razermouse.ko:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/4.13.0-36-generic/kernel/drivers/hid/

razerfirefly.ko:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/4.13.0-36-generic/kernel/drivers/hid/

razerkraken.ko:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/4.13.0-36-generic/kernel/drivers/hid/

razermug.ko:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/4.13.0-36-generic/kernel/drivers/hid/

razercore.ko:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/4.13.0-36-generic/kernel/drivers/hid/

depmod....

DKMS: install completed.

**REBOOT**

**razercommander**
Importing device logic, waiting for daemon
ERROR: the daemon is not responding!
Try running `killall razer-daemon && razer-daemon` or rebooting. If this doesn't work, please fill an issue!
Exception: org.freedesktop.DBus.Python.FileNotFoundError: Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/dbus/service.py", line 707, in _message_cb
    retval = candidate_method(self, *args, **keywords)
  File "/usr/lib/python3/dist-packages/openrazer_daemon/dbus_services/dbus_methods/all.py", line 85, in get_keyboard_layout
    with open(driver_path, 'r') as driver_file:
FileNotFoundError: [Errno 2] No such file or directory: '/sys/devices/pci0000:00/0000:00:1c.4/0000:0d:00.0/usb5/5-2/5-2:1.2/0003:1532:021A.0006/kbd_layout'

**Comment by z3ntu** [comment]
```
dpkg -l
sudo dkms remove openrazer-driver/1.0.0 --all
sudo mv /usr/src/openrazer-driver-1.0.0 /usr/src/openrazer-driver_old-1.0.0
sudo apt install --reinstall openrazer-kernel-modules-dkms
```
And then reboot (and the output of the dpkg command before please)

**Comment by DanyGee** [comment]
Same deal.

**razercommander**
Importing device logic, waiting for daemon
ERROR: the daemon is not responding!
Try running `killall razer-daemon && razer-daemon` or rebooting. If this doesn't work, please fill an issue!
Exception: org.freedesktop.DBus.Python.FileNotFoundError: Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/dbus/service.py", line 707, in _message_cb
    retval = candidate_method(self, *args, **keywords)
  File "/usr/lib/python3/dist-packages/openrazer_daemon/dbus_services/dbus_methods/all.py", line 85, in get_keyboard_layout
    with open(driver_path, 'r') as driver_file:
FileNotFoundError: [Errno 2] No such file or directory: '/sys/devices/pci0000:00/0000:00:1c.4/0000:0d:00.0/usb5/5-2/5-2:1.2/0003:1532:021A.0006/kbd_layout'

[dpkg_and_others.log](https://github.com/openrazer/openrazer/files/1924818/dpkg_and_others.log)

**Comment by z3ntu** [comment]
`grep VERSION /usr/src/openrazer-driver-1.0.0/driver/razercommon.h` should say 2.3.0 then.

Is the openrazer-driver-1.0.0 folder in /usr/src gone after that?
```
sudo apt purge *openrazer*
ls /usr/src/
```

**Comment by DanyGee** [comment]
**grep VERSION /usr/src/openrazer-driver-1.0.0/driver/razercommon.h**
#define VERSION "2.3.0"

> Is the openrazer-driver-1.0.0 folder in /usr/src gone after that?

**ls /usr/src**
bbswitch-0.8
bcmwl-6.30.223.271+bdcom
linux-headers-4.13.0-36
linux-headers-4.13.0-36-generic
linux-headers-4.8.0-58
linux-headers-4.8.0-58-generic
ndiswrapper-1.60
nvidia-384-384.130
openrazer-driver-1.0.0
openrazer-driver_old-1.0.0
virtualbox-5.1.34
xpad-0.4

After the **sudo apt purge *openrazer***
**ls /usr/src/**
bbswitch-0.8
bcmwl-6.30.223.271+bdcom
linux-headers-4.13.0-36
linux-headers-4.13.0-36-generic
linux-headers-4.8.0-58
linux-headers-4.8.0-58-generic
ndiswrapper-1.60
nvidia-384-384.130
openrazer-driver_old-1.0.0
virtualbox-5.1.34
xpad-0.4

**Comment by z3ntu** [comment]
Oh yeah you can remove that `openrazer-driver_old-1.0.0` folder too.

And just follow https://github.com/polychromatic/polychromatic/issues/146#issuecomment-379465409, I have no idea what the actual issue is... Thanks for trying to help though :smiley:

**Comment by DanyGee** [comment]
Thanks for your help!
I finally managed to get it to work again. Looks like the **cause** was the **old polychrmoatic repo present in the system**.

**Steps taken to fix this:**
1. sudo apt purge \*openrazer* \*polychromatic*
2. Restart
3. Disabled old polychromatic ppa (lah7/polychromatic)
4. Added new ppa (sudo add-apt-repository ppa:polychromatic/stable)
5. Installed openrazer and polychromatic
6. Restart
7. Run razercommander, and it worked :smile:
