### ISSUE TITLE
Chroma keys transalation screws Blackwidow Multimedia Keys

### ISSUE THREAD

**Issue by myelsukov** [openrazer/openrazer#577]
Could you please check the keyboard model prior to translation that uses this table? https://github.com/openrazer/openrazer/blob/master/driver/razerkbd_driver.c#L56

On my Blackwidow keyboard multimedia keys layout is different:
F5 - PlayPause
F6 - Stop
F7 - Prev
F8 - Next

**Comment by z3ntu** [comment]
`lsusb | grep 1532` please

**Comment by myelsukov** [comment]
```
>lsusb | grep 1532
Bus 001 Device 006: ID 1532:010e Razer USA, Ltd
```
Keyboard Layout:
F1 - Mute
F2 - Volume Down
F3 - Volume Up
F5 - Play/Pause
F6 - Stop Playback
F7 - Previous Track
F8 - Next Track
F12 - Brightness
Pause/Preak - Sleep
Right Alt - Razer Macro

To make it work properly on my keyboard I had to modify this table: https://github.com/openrazer/openrazer/blob/master/driver/razerkbd_driver.c#L56

```
static const struct razer_key_translation chroma_keys[] = {
    { KEY_F1,    KEY_MUTE },
    { KEY_F2,    KEY_VOLUMEDOWN },
    { KEY_F3,    KEY_VOLUMEUP },

    { KEY_F7,    KEY_PREVIOUSSONG },
    { KEY_F5,    KEY_PLAYPAUSE },
    { KEY_F8,    KEY_NEXTSONG },
    { KEY_RIGHTALT,    RAZER_MACRO_KEY },

    { KEY_PAUSE, KEY_SLEEP },
    { }
};

```

**Comment by terricain** [comment]
@myelsukov Remind me Saturday and I'll have a look, unless @z3ntu fixed it

**Comment by z3ntu** [comment]
Can you please try the commit 0b806965a7c17ff6461eabb8db4d53313178cce2

**Comment by myelsukov** [comment]
This works.
I am sorry, but I forgot to mention two other keys:

F11 - Game Mode
F12 - Brightness. I have just a single brightness button. Never used it :)

**Comment by z3ntu** [comment]
First, does your keyboard have the same (special) keys as https://d1urewwzb2qwii.cloudfront.net/sys-master/images/h7c/h12/8823290396702 ? Second, is this keyboard really called "BlackWidow Classic"? Does the sticker on the bottom say that?
And third, do you know what that brightness button does on Windows with Synapse?

**Comment by myelsukov** [comment]
It looks exactly like my keyboard.
The sticker says: "Blackwidow Stealth Edition"

**Comment by z3ntu** [comment]
Okay I found 

>  as well control backlighting (F12). The backlight has 5 modes and varies the intensity of the blue LED with last function being a pulsating backlight.

on https://www.bjorn3d.com/2011/10/razer-blackwidow-ultimate-stealth-edition/ which seems to be a review of the Ultimate equivalent of your keyboard. Is yours also from about 2011? Apparently everything pre-2013 was banished from the Razer website never to be found ^^

And I found the product page probably for your keyboard on archive.org: https://web.archive.org/web/20110924152039/http://store.razerzone.com:80/store/razerusa/en_US/pd/productID.235228400/categoryId.49136200/parentCategoryId.35156900 
I'll change the name but I think I am leaving that 'backlighting control key' unmapped for now as nothing is implemented on the daemon side to handle that.

**Comment by myelsukov** [comment]
I don't remember exactly when I got this keyboard but it was long enough ago :)
And I couldn't care less about backlight feature (gaming mode too :) ).

**Comment by z3ntu** [comment]
Try again with the latest commit on the branch `010e_translation` :)

**Comment by myelsukov** [comment]
Cool! Thanks! I am not home now. Will test it later.

**Comment by myelsukov** [comment]
Unfortunately it doesn't work. It still uses old mapping. When I run list_devices.py I am getting this:

```
> python list_devices.py 
Found 1 Razer devices

Razer BlackWidow Stealth Edition:
   type: keyboard
   serial: IO1132039101748
   firmware version: v2.3
   driver version: 2.3.0
```
It looks like this statement doesn't work as expected:
```
    switch(usb_dev->descriptor.idProduct) {
    case USB_DEVICE_ID_RAZER_BLACKWIDOW_STEALTH_EDITION:
        translation = find_translation(chroma_keys_2, usage->code);
    default:
        translation = find_translation(chroma_keys, usage->code);
    }
```
If I use keys_2 in both cases it works fine.

**Comment by z3ntu** [comment]
Dann. Add a `break` before the `default` statement. Missed that before.

**Comment by myelsukov** [comment]
This works better. I missed that break too :)

**Comment by z3ntu** [comment]
So this works? I'll commit it to master then.

**Comment by myelsukov** [comment]
Yes. With "break" it works as expected.
