### ISSUE TITLE
FN+F11 mutes microphone on Gnome

### ISSUE THREAD

**Issue by ghost** [openrazer/openrazer#579]
When i want to change the brightness to be darker the FN+F11 key combo mutes microphone. It does not happen without the polychromatic/openrazer installed

**Comment by lah7** [comment]
Which keyboard are you using?

**Comment by ghost** [comment]
Razer Ornata chroma @lah7

**Comment by Qik000** [comment]
@lah7 ?

**Comment by lah7** [comment]
I don't know the inner workings of the driver/daemon, just seeking more details out your issue.

Apparently this happens under KDE  for @z3ntu too but with a BlackWidow Chroma. Seems that the key events they emit are similar. As a workaround, are you able to reconfigure/disable the keybindings in GNOME?

**Comment by ghost** [comment]
@lah7 Gnome doesnt provide an option to disable or rebind FN keys, thats why i wrote about this here

**Comment by Qik000** [comment]
@lah7 ?

**Comment by z3ntu** [comment]
As a workaround you can stop the daemon by running `systemctl --user stop openrazer-daemon.service`.

**Comment by ghost** [comment]
@z3ntu But then i loose control over the keyboard, can you adreess this bug in near future ?

**Comment by muesli** [comment]
Can confirm this happens here on KDE/Plasma with the Ornata Chroma, too.

**Comment by terricain** [comment]
Does it happen on standard Ubuntu?

**Comment by muesli** [comment]
@terrycain I don't think this is distribution specific. Personally I'm running ArchLinux.

Fn+F11 results in keycode 198, XF86AudioMicMute.

**Comment by g00nix** [comment]
I am getting the same behavior on Razer BlackWidow X Chroma Tournament Edition

**Comment by ghost** [comment]
@terrycain Yes, it does. I ve jumped over to Ubuntu 18.04 and before the installation of the driver the brightness control worked nicely, but after the driver install it started muting the mic.

Its clearly a driver issue

**Comment by DanaGoyette** [comment]
Looks like F20 is hardcoded to be mic mute in Gnome:
https://bugs.freedesktop.org/show_bug.cgi?id=54171

Should those two keys be bound to XF86KbdBrightnessDown / XF86KbdBrightnessUp, or would that be undesirable (due to affecting other keyboards as well)?

**Comment by ghost** [comment]
@DanaGoyette it would be nice if openrazer had an option to entirely disable microphone-mute keycombo.

**Comment by z3ntu** [comment]
@DanaGoyette I think that only adds the mapping that XF86AudioMicMute to the actual functionality.
The mapping from F20 to XF86AudioMicMute is done in xkeyboard-config ([link](https://cgit.freedesktop.org/xkeyboard-config/tree/symbols/inet?id=d0e5e63cf59be444bec0e5b11838a9abce45226d#n120))

**Comment by kanarok** [comment]
there is a file at /usr/share/X11/xkb/symbols/inet where you can comment that particular line. That could do the trick (it did for me)

**Comment by g00nix** [comment]
I got the stale message and see I've posted here in May. I am now running i3wm and the keyboard behaves properly with:
```
bindsym XF86AudioRaiseVolume exec --no-startup-id pactl set-sink-volume 0 +5% #increase sound volume
bindsym XF86AudioLowerVolume exec --no-startup-id pactl set-sink-volume 0 -5% #decrease sound volume
bindsym XF86AudioMute exec --no-startup-id pactl set-sink-mute 0 toggle # mute sound
```

I also tried with volumeicon, by grabbing the hotkeys from there, and I also got expected behavior. 

Might there be an issue with Gnome instead of openrazer?

**Comment by muesli** [comment]
No, that's not Gnome specific. Same issue on other DEs, for example Plasma.

**Comment by spacescientist** [comment]
Indeed: the same problem appears when using xfce4 (Xubuntu 18.04).

In my case, it's for the BW Ultimate 2013 (1532:011A). The issue appeared after I installed openrazer-meta and polychromatic today (via the daily ppa for both). For the time being, @kanarok's trick works for me.

**Comment by tuomount** [comment]
This happens also with Ubuntu 16.04 and Razer Blackwidow Ultimate 2013. Without openrazer fn+f11 just dims the led brightness. With openrazer installed it toggles microphone mute.

**Comment by g00nix** [comment]
I can (re)confirm this bug. I switched backed to Gnome from i3wm so now I am experiencing the bug again since my i3wm fix doesn't work for Gnome

**Comment by rvillegasm** [comment]
Same thing happening here. Just got a Blackwidow Elite, and when I lower the brightness of the LEDs usign FN+F11 on Pop!_OS 20.10 (Gnome 3.38.3), the internal mic gets muted.

**Comment by lunananananananana** [comment]
I found that this issue temporarily disappears after reloading the kernel module (until you reboot or replug the keyboard):

```
sudo modprobe -r razerkbd
sudo modprobe razerkbd
```

In case it matters, I have the BlackWidow Elite

**Comment by sunjay140** [comment]
I am experiencing this issue in Fedora 36 with Gnome.
