### ISSUE TITLE
Applying RGB schemes based on currently pressed keys (i.e. keyboard shortcut helpers)

### ISSUE THREAD

**Issue by samuelbryant** [openrazer/openrazer#580]
When you press FN, the multimedia keys light up. Is there a way to implement custom versions of this through open razer? e.g. Suppose I want to have HJKL all light up whenever I press the windows key.

My guess is no, because if openrazer can access which keys are currently pressed, then it would be very easy to create a userspace keylogger. But I just wanted to check

**Comment by z3ntu** [comment]
You should be able to do that by using the pylib i.e. listening to keys and then calling the openrazer pylib to set the effects.
I think we have something that could generate a heatmap of pressed keys but afaik the code is made to only store when a keypress was made with the hour so the store can't be misused as a keylogger.
