### ISSUE TITLE
Kernel 4.15.17 issues on Fedora

### ISSUE THREAD

**Issue by Spikeophant** [openrazer/openrazer#581]
Hello, 

  After building with DKMS and signing my the razer modules, some of them won't load.  Output from the DKMS install:  (my sign script has an error so I'm manually signing after build right now)
# dkms install openrazer-driver/1.0.0

Kernel preparation unnecessary for this kernel.  Skipping...

Building module:
cleaning build area...
KERNELDIR=/lib/modules/4.15.17-300.fc27.x86_64/build make driver....

Running the post_build script:
Signing kernel_object: *ko
/var/lib/dkms/openrazer-driver/1.0.0/build/../../../../../../root/dkms/sign-kernel.sh: line 11: /usr/src/kernel/4.15.17-300.fc27.x86_64/scripts/sign-file: No such file or directory
cleaning build area...

DKMS: build completed.

razerkbd.ko.xz:
Running module version sanity check.
modinfo: ERROR: could not get modinfo from 'razerkbd': Invalid argument
 - Original module
   - Found /lib/modules/4.15.17-300.fc27.x86_64/extra/razerkbd.ko.xz
   - Storing in /var/lib/dkms/openrazer-driver/original_module/4.15.17-300.fc27.x86_64/x86_64/
   - Archiving for uninstallation purposes
 - Installation
   - Installing to /lib/modules/4.15.17-300.fc27.x86_64/extra/

razermouse.ko.xz:
Running module version sanity check.
modinfo: ERROR: could not get modinfo from 'razermouse': Invalid argument
 - Original module
   - Found /lib/modules/4.15.17-300.fc27.x86_64/extra/razermouse.ko.xz
   - Storing in /var/lib/dkms/openrazer-driver/original_module/4.15.17-300.fc27.x86_64/x86_64/
   - Archiving for uninstallation purposes
 - Installation
   - Installing to /lib/modules/4.15.17-300.fc27.x86_64/extra/

razerfirefly.ko.xz:
Running module version sanity check.
modinfo: ERROR: could not get modinfo from 'razerfirefly': Invalid argument
 - Original module
   - Found /lib/modules/4.15.17-300.fc27.x86_64/extra/razerfirefly.ko.xz
   - Storing in /var/lib/dkms/openrazer-driver/original_module/4.15.17-300.fc27.x86_64/x86_64/
   - Archiving for uninstallation purposes
 - Installation
   - Installing to /lib/modules/4.15.17-300.fc27.x86_64/extra/

razerkraken.ko.xz:
Running module version sanity check.
 - Original module
 - Installation
   - Installing to /lib/modules/4.15.17-300.fc27.x86_64/extra/

razermug.ko.xz:
Running module version sanity check.
 - Original module
 - Installation
   - Installing to /lib/modules/4.15.17-300.fc27.x86_64/extra/

razercore.ko.xz:
Running module version sanity check.
modinfo: ERROR: could not get modinfo from 'razercore': Invalid argument
 - Original module
   - Found /lib/modules/4.15.17-300.fc27.x86_64/extra/razercore.ko.xz
   - Storing in /var/lib/dkms/openrazer-driver/original_module/4.15.17-300.fc27.x86_64/x86_64/
   - Archiving for uninstallation purposes
 - Installation
   - Installing to /lib/modules/4.15.17-300.fc27.x86_64/extra/
Adding any weak-modules

depmod....

DKMS: install completed.

Then I try a modprobe:

# modprobe -v razercore
insmod /lib/modules/4.15.17-300.fc27.x86_64/extra/razercore.ko.xz
modprobe: ERROR: could not insert 'razercore': Invalid argument

I've searched around on here and read the troubleshooting guides and came up empty. This all worked on this system on prior kernels.

**Comment by z3ntu** [comment]
Works for me on a fully up-to-date Fedora 27 install (kernel `4.16.3-200.fc27.x86_64`).
![image](https://user-images.githubusercontent.com/3768500/39348444-6fb2529c-49f7-11e8-83c1-b7a0dc659aa7.png)

Is there anything in the dmesg after you run modprobe?

**Comment by Spikeophant** [comment]
I updated to the latest kernel, 4.16.3-200 and still get the same issue, I believe it's related to this error when I run DKMS: modinfo: ERROR: could not get modinfo from 'razerfirefly': Invalid argument (I get this for each piece.)  I do not get anything in DMESG output after I modprobe.  If it's working on your system it's definitely something on my system that's funky, so I'm going to dig around.

**Comment by z3ntu** [comment]
Can you run `bash -x /usr/bin/dkms install openrazer-driver/1.0.0` and check which command exactly fails there?

**Comment by Spikeophant** [comment]
DKMS doesn't fail, it's when I modprobe that it wont load.  DKMS thinks it's successful.  

DKMS 
Kernel preparation unnecessary for this kernel.  Skipping...

Building module:
cleaning build area...
KERNELDIR=/lib/modules/4.16.5-200.fc27.x86_64/build make driver....

Running the post_build script:
Signing kernel_object: razercore.ko.xz
Signing kernel_object: razerfirefly.ko.xz
Signing kernel_object: razerkbd.ko.xz
Signing kernel_object: razerkraken.ko.xz
Signing kernel_object: razermouse.ko.xz
Signing kernel_object: razermug.ko.xz
cleaning build area...

DKMS: build completed.

razerkbd.ko.xz:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/4.16.5-200.fc27.x86_64/extra/

razermouse.ko.xz:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/4.16.5-200.fc27.x86_64/extra/

razerfirefly.ko.xz:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/4.16.5-200.fc27.x86_64/extra/

razerkraken.ko.xz:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/4.16.5-200.fc27.x86_64/extra/

razermug.ko.xz:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/4.16.5-200.fc27.x86_64/extra/

razercore.ko.xz:
Running module version sanity check.
 - Original module
   - Found /lib/modules/4.16.5-200.fc27.x86_64/kernel/drivers/hid/razercore.ko.xz
   - Storing in /var/lib/dkms/openrazer-driver/original_module/4.16.5-200.fc27.x86_64/x86_64/
   - Archiving for uninstallation purposes
 - Installation
   - Installing to /lib/modules/4.16.5-200.fc27.x86_64/extra/
Adding any weak-modules

depmod....

DKMS: install completed.


Modprobe


# modprobe -v razercore
insmod /lib/modules/4.16.5-200.fc27.x86_64/extra/razercore.ko.xz
modprobe: ERROR: could not insert 'razercore': Invalid argument


But there's nothing in dmesg so i have no idea what is actually failing here.  Typically if I see an issue with symbols dmesg output will tell me what symbols are unknown so I can figure out the dependency tree.  I am no longer getting DKMS: modinfo: ERROR: could not get modinfo from 'razerfirefly': Invalid argument  on Kernel 4.16.5-200.  Out of all this I did get all my signing scripts working well for DKMS so that's a bonus.

Thanks for all your help so far.

**Comment by z3ntu** [comment]
What happens when you run `modinfo /lib/modules/4.16.5-200.fc27.x86_64/extra/razercore.ko.xz`?

**Comment by Spikeophant** [comment]
# modinfo /lib/modules/4.16.5-200.fc27.x86_64/extra/razercore.ko.xz
filename:       /lib/modules/4.16.5-200.fc27.x86_64/extra/razercore.ko.xz
modinfo: ERROR: could not get modinfo from 'razercore': Invalid argument

**Comment by z3ntu** [comment]
Can you upload that file?

**Comment by Spikeophant** [comment]
[razercore.ko.xz.zip](https://github.com/openrazer/openrazer/files/1985400/razercore.ko.xz.zip)
attached.

**Comment by z3ntu** [comment]
1. I get the same error with modinfo.
2. When extracting the razercore.ko.xz file, I get the error `xz: razercore.ko.xz: Compressed data is corrupt` there something seems wrong there. Can you try reinstalling the xz package on your machine or something? Also maybe try installing another dkms module and see if that works.

**Comment by Dr4s1l** [comment]
Got the same issue here, how did you fix this ? Running latest fedora 31 with secure boot, signed *razerkbd* ko.xz file and got the same issue with xz.

**Comment by Spikeophant** [comment]
When I was doing signing of the DKMS scripts I was not extracting them, signing, then re archiving.
