### ISSUE TITLE
Layout 12/PT

### ISSUE THREAD

**Issue by StuntsPT** [openrazer/openrazer#582]
The "Razer BlackWidow Chroma Tournament Edition" has a value of "12" under `/sys/bus/hid/drivers/razerkbd/0*/kbd_layout`.
Layout is pt_PT.
![img_20180430_000014959](https://user-images.githubusercontent.com/1201571/39411878-1968eee0-4c0a-11e8-8ca2-cc607094d97b.jpg)
Screenshot of the layout attached.

**Comment by z3ntu** [comment]
Thanks!
