### ISSUE TITLE
Deathstalker Ultimate

### ISSUE THREAD

**Issue by DiGwork** [openrazer/openrazer#584]
Hi guys I have just installed Openrazer on my Deathstalker Ultimate.
Has there been any work done to support this device specifically around the assignable buttons and the keyboard screen?

**Comment by terricain** [comment]
@DiGwork Not yet. Ideally I need to grab hold of one first

**Comment by minecrawler** [comment]
Please use the open issue #127

@terrycain I did already provide input and stuff. You can use my information or tell me what you need.
