### ISSUE TITLE
Branch build on Debian 9

### ISSUE THREAD

**Issue by fiercebrake** [openrazer/openrazer#585]
Hey guys,

Has anyone built a branch on Debian 9?

I am trying to build branch "feature_lancehead_te_0x0060" in my Debian 9 box by following "https://github.com/openrazer/openrazer/wiki/Building-a-package" (Ubuntu/Mint).

The logs i get are:

dpkg-checkbuilddeps: error: Unmet build dependencies: linux-headers-generic
dpkg-buildpackage: warning: build dependencies/conflicts unsatisfied; aborting
dpkg-buildpackage: warning: (Use -d flag to override.)

**Comment by z3ntu** [comment]
Yes, you have to remove the linux-headers-generic dependency from the `debian/control` file, see https://github.com/openrazer/OBS-packaging/blob/master/make_debian_tar_xz.sh#L22-L23 when building for Debian.
