### ISSUE TITLE
Build for Fedora 28

### ISSUE THREAD

**Issue by AbsyntheSyne** [openrazer/openrazer#588]
Hi. I recently installed Fedora 28 on my desktop and there's no repository for 28, but there is for 27, 26, and rawhide. Is there anyway you could get binary rpm packages built for 28 as well? Thanks!

**Comment by z3ntu** [comment]
I've just enabled the repository and packages should be built and published over the next couple of hours (hopefully).

**Comment by z3ntu** [comment]
You can view the status at https://build.opensuse.org/project/monitor/hardware:razer?arch_x86_64=1&blocked=1&broken=1&building=1&defaults=0&deleting=1&dispatching=1&failed=1&finished=1&locked=1&repo_Fedora_28=1&scheduled=1&signing=1&succeeded=1&unresolvable=1

**Comment by AbsyntheSyne** [comment]
Oh awesome! Thanks! :D

**Comment by z3ntu** [comment]
Repo should be published. Have fun!

**Comment by kierun** [comment]
Could someone update the documentation? Currently, it appears only 26, 27, and rawhide are supported. [Reference](https://openrazer.github.io/#fedora)

**Comment by z3ntu** [comment]
Fixed in https://github.com/openrazer/openrazer.github.io/commit/e15e74bfad35bc12e9dc3e4f28e33533c75c23dd
