### ISSUE TITLE
Changing Macros on the Naga Hex v2

### ISSUE THREAD

**Issue by MonkeyDStyxx** [openrazer/openrazer#590]
So i just bought a new mouse (finally after 7+ years of my old one) and i have installed all the drivers and programs i need, but i am trying to change my key bindings and macros for the buttons on the mouse and i am unsure how to do that. not sure if i missed something in the programs i have (razer genie/polychromatic controller) or if i am just unable to change them. 

any help is appreciated! TIA

**Comment by lesnake** [comment]
I'm in the exact same situation.
I've found that the code related to naga hex family has been commented out in [razer commander](https://github.com/GabMus/razerCommander/commit/caa86a223e0b176caa29962a14d3b60d6f040eeb) as a consequence of the driver side code beeing removed in [openrazer](https://github.com/openrazer/openrazer/blob/master/daemon/openrazer_daemon/hardware/mouse.py).

Some lines related to opening and closing the naga hex V2 keys have been commented in [this commit](https://github.com/openrazer/openrazer/commit/d1e683ac7cbaf0a70c6be1efc33d142f6c26ac72#diff-01d9a4553da1b05815c0b51d357ed0b0) 

I could rebuild all the driver un-commenting the lines, but I dont really can figure out what to expect...

I'd also appreciate help on this.

**Comment by waytoomuchgaming** [comment]
Any news on that ?
Is the Naga Hex v2 still supported ?

**Comment by fang0654** [comment]
Thank you folks for posting this. After uncommenting the lines in both mouse.py (for openrazer) and devicesMacroKeys.py (for razercommander) I have full macro support on my Naga Hex V2! I don't know why it was disabled, but if you re-enable it, it works well.
