### ISSUE TITLE
Razer Atheris support

### ISSUE THREAD

**Issue by hxss** [openrazer/openrazer#595]
I want to buy this mouse. Is it possible to configure its buttons with openrazer?
Will my macroses work with bluetooth connection(as I know this mouse don't have internal memory)?

**Comment by z3ntu** [comment]
No, this mouse is not yet supported. It seems like a relatively new mouse so support may take a while. And button remapping is not supported on all devices currently.

**Comment by hxss** [comment]
Maybe you know - if this mouse generate mouse button click event by dpi button?
I think if yes, then I can use xbindkeys for remapping and configuring modes.

**Comment by hxss** [comment]
>And button remapping is not supported on all devices currently

Razer Orochi(Do I must create new issue for this question?) have 2 buttons on the right side that toggle dpi by default.
http://dl.razerzone.com/master-guides/Orochi2013/Orochi2013OMG-ENG.pdf

So we can't remap this buttons too?

**Comment by z3ntu** [comment]
> Maybe you know - if this mouse generate mouse button click event by dpi button?

no idea

> So we can't remap this buttons too?

Don't think so. And don't create a new issue for that, there are a bunch of issues open for this thing right now anyways.

**Comment by git-ingham** [comment]
I would like to add my voice for Atheris support.  Just bought it.  It works fine on my OpenSUSE Tumbleweed system without it, but the extra features would be nice.

**Comment by hxss** [comment]
@git-ingham did you try to use this mouse over bluetooth? I have problem with polling rate when use this mouse over bt.
https://www.reddit.com/r/linuxquestions/comments/8qviub/bluetooth_mouse_polling_rate/

**Comment by interisti** [comment]
@git-ingham 
trying to make it work on ubuntu 16.0.4, with no luck so far. System does not recognize it at all. Which package have you installed?

**Comment by git-ingham** [comment]
It arrived today, I paired it, and it worked.  Just like that.  I have more problems with my Orochi than the Atheris.  The Atheris tracked fine.

I am using KDE.  Relevant packages:
bluez-5.49-3.2.x86_64
bluedevil5-5.13.0-1.1.x86_64
bluez-tools-0.1.38+git20161212-1.4.x86_64

**Comment by hxss** [comment]
@git-ingham what rate shows evhz over bt?

**Comment by nbenitez** [comment]
+1 for Razer Atheris, please add "Device Support" label.

**Comment by jrbtaylor** [comment]
I would also like to request support for the Atheris

**Comment by nair-ayush** [comment]
I'm a relatively new user of the Atheris. The only workaround I've found with this if you have a Windows/Mac machine side by side. Whether it works from a different machine or not I do not know. But I have dual-booted Windows and Ubuntu 18.04.

Basically, I created a new profile on the Razer Synapse software and assigned **Ubuntu keyboard shortcuts** to the configurable keys and it works like a charm. 

Key thing is to activate that profile before logging out of windows and then start Ubuntu. I'm in USB mode and not Bluetooth. Don't have Bluetooth on my machine. If anybody finds any workarounds keep updating this thread.

Cheers!

**Comment by cheuksing** [comment]
When I using Atheris in linux (pop os), the tracking is unstable.
I found that the mouse will fail to track for 0.1s if it stops moving and moved again after 5s.
I changed poll rate to 1000hz and check the poll rate in evhz.
This is what I got. Any idea?

Hopefully this project will support this mice and solve this issue.  :/

> Razer Razer Atheris - Mobile Gaming Mouse: Latest    76Hz, Average     0Hz
> Razer Razer Atheris - Mobile Gaming Mouse: Latest   100Hz, Average    38Hz
> Razer Razer Atheris - Mobile Gaming Mouse: Latest   111Hz, Average    58Hz
> Razer Razer Atheris - Mobile Gaming Mouse: Latest  1000Hz, Average    71Hz
> Razer Razer Atheris - Mobile Gaming Mouse: Latest    35Hz, Average   257Hz
> Razer Razer Atheris - Mobile Gaming Mouse: Latest    30Hz, Average   220Hz
> Razer Razer Atheris - Mobile Gaming Mouse: Latest    26Hz, Average   193Hz
> Razer Razer Atheris - Mobile Gaming Mouse: Latest     1Hz, Average   172Hz
> Razer Razer Atheris - Mobile Gaming Mouse: Latest  1000Hz, Average   153Hz
> Razer Razer Atheris - Mobile Gaming Mouse: Latest   500Hz, Average   237Hz

**Comment by archerallstars** [comment]
I am about to buy this mouse to use with Ubuntu 19.04. I hope this model will be support soon.

**Comment by z3ntu** [comment]
Can somebody give me the output of `lsusb | grep 1532` ?

**Comment by mustafirus** [comment]
lsusb | grep 1532 
Bus 001 Device 005: ID 1532:0062 Razer USA, Ltd

**Comment by nbenitez** [comment]
Mine is:
`Bus 001 Device 061: ID 1532:0227 Razer USA, Ltd Razer Huntsman`

**Comment by git-ingham** [comment]
Here is mine:

Bus 001 Device 002: ID 1532:0048 Razer USA, Ltd Orochi (Wired)

Kenneth

--
Kenneth L. Ingham, Ph.D.
Kenneth Ingham Consulting, LLC
1601 Rita Dr NE
Albuquerque NM 87106-1127
+1-505-480-7621

A people that values its privileges above its principles soon loses both.
---Dwight D. Eisenhower, First Inaugural Address, January 20, 1953

**Comment by fabiocarneiro** [comment]
```
Bus 001 Device 005: ID 1532:0232 Razer USA, Ltd Razer Blade Stealth
Bus 001 Device 007: ID 1532:0062 Razer USA, Ltd Razer Atheris - Mobile Gaming Mouse
```

**Comment by Scarletvye** [comment]
Bus 001 Device 004: ID 1532:0062 Razer USA, Ltd

I have 2 of these devices, please let me know how I can help. I am running Linux Mint 20. I really want to get this mouse up to its 1000 polling rate.

**Comment by fabiocarneiro** [comment]
@Scarletvye The Atheris works fine without any OpenRazer support, so the main thing for me would be to be able to visualize the DPI settings. I have some jumping sometimes, but I suspect it's not related to the mouse itself.

**Comment by nightsky30** [comment]
@Scarletvye @crian has an Atheris [branch](https://github.com/crian/openrazer/tree/feature_atheris). Not sure what state that branch is in, but you could try that.

**Comment by Belthil** [comment]
I guess this might be an ignorant question, but how can I use the atheris branch? I have installed openrazer from terminal on Pop_OS and RazerGenie, but no idea how to implement the Atheris branch to my installation...

**Comment by nightsky30** [comment]
You'd have to clone and build it. I think Pop_OS should be able to follow the Ubuntu/Mint [instructions](https://github.com/openrazer/openrazer/wiki/Building-a-package). Just insert crains fork/branch in the clone command and follow the rest.

```git clone git@github.com:crian/openrazer.git -b feature_atheris```

**Comment by Belthil** [comment]
Thanks for the reply and instructions!

**Comment by crian** [comment]
This branch is old and not working as expected.

**Comment by nightsky30** [comment]
@Belthil @crian @Scarletvye Feel free to try my PR branch. I think I ironed out the issues. It is currently working well for me :smiley:

**Comment by nightsky30** [comment]
@fabiocarneiro I'm also seeing some jumping/stuttering sometimes. Not sure if it is openrazer related or not. Seems I can recreate by viewing a web page and scroll wheeling a bit, then stopping the scroll wheel and moving the mouse about. Or maybe just letting the mouse sit a bit before moving it? Is this what you're seeing without openrazer?

**Comment by Belthil** [comment]
@nightsky30 I saw the same jumping, or rather, lazy response. In all honesty, the atheris works fine without the openrazer drivers. My hope was to remap it's buttons or create macros on it. I managed to do that by using xbindkeys, but it was only partial success.

**Comment by nightsky30** [comment]
> @nightsky30 I saw the same jumping, or rather, lazy response. In all honesty, the atheris works fine without the openrazer drivers. My hope was to remap it's buttons or create macros on it. I managed to do that by using xbindkeys, but it was only partial success.

It seems the issue is referenced on Razer's support page. There is also a firmware update available for Windows. If I can get my VM up and running again, I may try to update the FW through the USB pass-through and report back. My Atheris is currently running v1.3.

**EDIT:** Looks like the firmware was v1.3...so if that was meant to fix the issue, they didn't do a great job.
