### ISSUE TITLE
problem for installing RazerGenie on kali linux

### ISSUE THREAD

**Issue by ghost** [openrazer/openrazer#596]
● openrazer-daemon.service - Daemon to manage razer devices in userspace
   Loaded: loaded (/usr/lib/systemd/user/openrazer-daemon.service; disabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Tue 2018-05-22 14:28:21 IST; 24s ago
     Docs: man:openrazer-daemon(8)
  Process: 7881 ExecStart=/usr/bin/openrazer-daemon -Fv (code=exited, status=1/FAILURE)
 Main PID: 7881 (code=exited, status=1/FAILURE)

please help me for this.......

**Comment by z3ntu** [comment]
Please run `openrazer-daemon -Fv` in your terminal and look at it. It'll most likely tell you what's wrong. If you have no idea, post the output here.
