### ISSUE TITLE
Bricks my CentOS BlackWidow Chroma

### ISSUE THREAD

**Issue by mschifter** [openrazer/openrazer#597]
Followed directions for yum install, repo setup, driver config.

repo installed properly. Downloaded and installed the configured package and my keyboard stopped working altogether. After following the driver config page and validating my hardware was visible on the usb bus, I had no further success. I noticed razerkbd.ko never installed. yum erase removes some aspects of the driver, but my keyboard is still bricked and I'm writing this on a second keyboard that I plugged in. Recommend YOU DO NOT INSTALL this for CentOS 7 until the package is certified and is even in the official makefile on GitHub.

**Comment by z3ntu** [comment]
Sorry, we do not support OpenRazer on CentOS. Please ask the repo maintainer about that.
