### ISSUE TITLE
[Question] Mac Support

### ISSUE THREAD

**Issue by tyrocca** [openrazer/openrazer#60]
The things you have done here are really cool. I was wondering if you all have ever tried to support macs? I was very disappointed to find out that Razer only made the sdk available to windows. Thanks! - Ty

**Comment by terricain** [comment]
I thought about it and decided for now it would be far too much effort, on top of that I don't have the hardware to test things reliably. I have some big changes planned and after that it would be more feasible but I'm not planning on mac support currently. If I miraculously got given a mac I'd look into it more.
