### ISSUE TITLE
Razer Blade 15 support?

### ISSUE THREAD

**Issue by professor-rage** [openrazer/openrazer#600]
Running Ubuntu 18.04, the windows precision trackpad doesn't work at all. Strangely, a clean install of windows 10 using the Media tool iso also renders the trackpad defunct. Would be great to get basic trackpad support on Linux. TIA

**Comment by z3ntu** [comment]
Sorry, we only do kernel driver support for the lighting, DPI, etc functionality and not basic hardware bringup. I think you should report that upstream at kernel.org .
