### ISSUE TITLE
razer blade stealth late 2017 doesn't detect keyboard

### ISSUE THREAD

**Issue by edvorg** [openrazer/openrazer#602]
Hi. Came across openrazer, but couldn't make it work even though my device is in the list of supported devices
```
[edvorg@edvorg-manjaro ~]$ lsusb | grep 1532
Bus 001 Device 005: ID 1532:0232 Razer USA, Ltd 
[edvorg@edvorg-manjaro ~]$ uname -a
Linux edvorg-manjaro 4.14.40-1-MANJARO #1 SMP PREEMPT Wed May 9 20:10:25 UTC 2018 x86_64 GNU/Linux
```
tried razer commander and polychromatic, both tell me they can connect to openrazer but there are no connected razer devices in the system

**Comment by z3ntu** [comment]
Please post the output of both `sudo dkms install openrazer-driver/1.0.0` and `openrazer-daemon -Fv`

**Comment by edvorg** [comment]
Hello again. I apologize for posting the issue. It got fixed after reboot.
FYI `sudo dkms install openrazer-driver/1.0.0` successfully installs module
probably something related to my local setup was preventing functionality to detect the device
