### ISSUE TITLE
Install stuck on Building initial module for 4.15.0-22-generic

### ISSUE THREAD

**Issue by BinaryJava** [openrazer/openrazer#603]
I tried installing initially and it got stuck at 74%, second time I was told to use the dpkg command and it got stuck at Building initial module for 4.15.0-22-generic.

**Comment by z3ntu** [comment]
What's the output of `sudo dkms install openrazer-driver/1.0.0` ?

**Comment by BinaryJava** [comment]
It was to do with my secure boot, I think it is working now. I don't have an option for universe drivers in my software and updates, but I got no dependency errors either.
