### ISSUE TITLE
Razer BlackWidow Alternate Media Keys

### ISSUE THREAD

**Issue by emerham** [openrazer/openrazer#607]
On my Razer Blackwidow Alternate using the Openrazer daemon my media keys do not work right, Play/Pause (fn+f5) is skip next. Skip Previous (fn+f7) doesn't do anything.

Removing the Daemon the keys come back

**Comment by z3ntu** [comment]
I believe this is a duplicate of #577 . Can you try the latest git master?

**Comment by emerham** [comment]
Ok I'll try the latest master, just ran the RPM build and it build the latest TAG release.

**Comment by emerham** [comment]
Ok Build from latest tag release and it did fix my media keys. Closing as already fixed.

**Comment by z3ntu** [comment]
Great, thanks for testing!
