### ISSUE TITLE
Basilisk mouse on linux

### ISSUE THREAD

**Issue by tl-jakecross** [openrazer/openrazer#608]
I see (after buying) that one of the features of the Basilisk is to be able to bind things to the scroll wheel. That's great on Windows I'm sure. I just want the scroll wheel to act as a wheel and third button on the mouse when I am on Linux. At the moment, the scroll does nothing, and clicking it, seems to be bound to the character "o". 

Is there any way I can get this to behave as a normal mouse on Linux? I have downloaded the openrazer drivers and restarted, hoping it would resolve it but no dice.

**Comment by z3ntu** [comment]
The Razer Basilisk is not supported, see #433 - so our driver doesn't do anything for your mouse currently.
