### ISSUE TITLE
The Debian install procedure shows the OpenSUSE instructions

### ISSUE THREAD

**Issue by bmiro** [openrazer/openrazer#611]
The Debian install procedure on: 

https://openrazer.github.io/#debian

Shows the openSUSE instructions instead of the Debian ones:

![a](https://user-images.githubusercontent.com/398519/41807061-19dcc43e-76c9-11e8-9fa0-d3a18e3d5496.png)

**Comment by lah7** [comment]
Debian packages are built by openSUSE Build System, but I can see the confusion. I'll reword the text.
