### ISSUE TITLE
[UNKNOWN] Razer Nostromo on Ubuntu Desktop 16.04 Only Controls Brightness

### ISSUE THREAD

**Issue by gatewksbury** [openrazer/openrazer#614]
I want to verify that only the brightness control is changeable for a Razer Nostromo on Ubuntu Desktop 16.04 or is this another issues (maybe related to #610).

_OP NOTE: PLEASE CLOSE AND COMMENT IF NOT A BUG FOR FURTHER INFO!_

![screenshot from 2018-07-02 18-55-17](https://user-images.githubusercontent.com/9088546/42190182-b0fb1b4c-7e29-11e8-9528-f1db6887fef8.png)

![screenshot from 2018-07-02 18-55-04](https://user-images.githubusercontent.com/9088546/42190195-c222433c-7e29-11e8-9888-ed88f8003b65.png)

**Comment by z3ntu** [comment]
Is there something else that can be configured on that device (except key remapping - that is not (yet) supported)?

**Comment by alasta4204** [comment]
Good morning , I think I am having a similar issue . I have instailed open razer and polycromatic on Ubuntu 16.04 LTS the tray app works and loads polychromatic loads ok and looks like the pic above however the keys are not click  able . Are you supposed to be able to edit key configurations etc ?

Many thanks in advance

**Comment by lah7** [comment]
Unfortunately, OpenRazer doesn't support key remapping for gamepads yet. The closest is macro support for the M1-M5 keys on the BlackWidow Chroma.

As mentioned in  https://github.com/openrazer/openrazer/issues/259#issuecomment-296959620, it's still true that changing the lighting is _still_ the only possible option. The daemon needs more work to support this functionality. (Any coders -- pull requests welcome - [some useful info here](https://github.com/openrazer/openrazer/issues/167#issuecomment-274497165))

In Polychromatic, that Nostromo image is just the background which isn't supposed to be interactive.

A fellow user mentioned in https://github.com/polychromatic/polychromatic/issues/80 that they use [Keyboard Master](https://bitbucket.org/conzar/keyboarding-master/src) to reconfigure buttons. I haven't tried it, but it might be the only option in the meantime?

**Comment by alasta4204** [comment]
Many thanks for your  prompt reply lah7 . Is there any value in me adding the PPA for the BETAs to get  possible earlier support for the Nostromo?

Warmest regards

**Comment by lah7** [comment]
You can if you like, it'll help with testing (once this feature sees progress, but I believe it's stale). Bear in mind that if you wish to use a front-end, it could be a little while before they update to make use of the new features.

**Comment by alasta4204** [comment]
Thanks again. I am having some success with Keyboard Master after initially struggling with the sparse documentation . I will keep an eye on this thread.

Warmest regards
