### ISSUE TITLE
Possibility to add layer effect on top of custom colorscheme (reopening #477 for update)

### ISSUE THREAD

**Issue by 0011001011** [openrazer/openrazer#615]
Thanks for this amazing software, that's so much fun to use.

To have more fun, and following the previously closed issue (stale), is it possible to activate some effects layers on top of a custom colorscheme ? Ex: Reactive effect on some keys and custom colors on others.

[https://github.com/openrazer/openrazer/issues/477](url)

**Comment by 0011001011** [comment]
If there is no deep hardware driver-related issue for this I may be able to implement it myself if someone can provide me some insights

**Comment by z3ntu** [comment]
See #477
