### ISSUE TITLE
Blackwidow Alternate has kbd_layout of 81

### ISSUE THREAD

**Issue by blipvert** [openrazer/openrazer#616]
I'm trying to get an older BlackWidow keyboard working with openrazer and I am running into problems which I think are due to it returning an unrecognized kbd_layout of 81.  My guess (assuming it is hexadecimal), is that the value should be 01 (this is a US layout keyboard), and the 80 probably means that it is a Macintosh variant (it has the Mac-style ⌘ symbol and no Windows key).

![razer-blackwidow](https://user-images.githubusercontent.com/107617/42232336-15195ef8-7ebc-11e8-9fdc-08a7b6fd979c.png)

As a result, none of the apps can do anything with keyboard mapping, although they can do other tasks like adjust the lighting.

**Comment by z3ntu** [comment]
I've added the layout id as it is to the list for now. As we only know what's documented on the wiki page (https://github.com/openrazer/openrazer/wiki/Keyboard-layouts) it's hard to know if the 8 is really a 'mac layout modifier' or something. Thanks!
