### ISSUE TITLE
Unknow layout

### ISSUE THREAD

**Issue by yodatak** [openrazer/openrazer#618]
When using Razergenie with custom editor it say to me that

`You are using a keyboard with a layout which is not known to the daemon. Please help us by visiting https://github.com/openrazer/openrazer/wiki/Keyboard-layouts. Using a fallback layout for now.`

But cat /sys/bus/hid/drivers/razerkbd/0*/kbd_layout
04

04 | fr_FR

So i don't understand why it failed

**Comment by z3ntu** [comment]
That layout is not yet in a release - so you don't have these changes yet. I'll likely do a 2.3.1 release soon as there are some other changes that warrant a release.
