### ISSUE TITLE
keyboard input being recognized as a mouse

### ISSUE THREAD

**Issue by moozhub** [openrazer/openrazer#620]
Hello,

I noticed that there was some verbiage in the razerkbd driver source that mentions initializing a device as a [mouse](https://github.com/openrazer/openrazer/blob/master/driver/razerkbd_driver.c#L1694). Would you be able to tell me what this may be doing in relation to [Issue #1](https://github.com/moozhub/yum-repo-mooz/issues/1)? Not sure if the device being recognized as a mouse is what's causing the issue, but the only thing I have going with it at the moment in effort to correct their issues...

`[    3.810552] razerkbd 0003:1532:0221.0003: input,hidraw2: USB HID v1.11 Keyboard [Razer Razer BlackWidow Chroma V2] on usb-0000:00:1d.0-1.6/input0`
**`[    3.810689] razerkbd 0003:1532:0221.0005: input,hidraw3: USB HID v1.11 Mouse [Razer Razer BlackWidow Chroma V2] on usb-0000:00:1d.0-1.6/input2`**

Thanks!

**Comment by terricain** [comment]
The keyboard presents itself as 3 usb interfaces, 2 keyboards, and 1 mouse,
the mouse interface is the interface that controls the lighting.

**Comment by moozhub** [comment]
Thanks, I figured that was probably the case. I'll close this for now until I have any other questions
