### ISSUE TITLE
macOS Support

### ISSUE THREAD

**Issue by alexargo** [openrazer/openrazer#623]
Razer has announced that Synapse 3 will not support macOS. Would it be possible to add Mac support? I'd be willing to work on this if I had a bit of direction. I have a hackintosh that I dual boot between Windows and macOS and would love to be able to use some of my Synapse 3 only devices and Synapse on macOS is pretty crappy to begin with.

**Comment by z3ntu** [comment]
Currently the project uses a mixture of kernel drivers and a user-space component. I don't know how the situation is with kernel drivers but I don't think they are easily adapted to macOS.
In the future our plan is to switch to hidraw, a Linux-only feature, to replace (most of) the kernel drivers. I'd say macOS support would require a complete rewrite of OpenRazer to use hidapi or equivalent which probably won't happen in the near future.
But thanks for telling us with Synapse 3, we'll keep it in mind in case we get a ton of freetime :smile:

**Comment by spacenono** [comment]
@alexargo : Did you find a way to use synapse feature on your hackintosh ? (I try to change RGB color of my razer blade 15 2018 on hackintosh mode).

**Comment by sturze** [comment]
+1 i also would love to see this on MacOS. 
any news so far?
@spacenono there is a project on GitHub handling Razer RGB stuff on MAC 
https://github.com/1kc/razer-macos

my priority would be DPI on my Deathadder... I don't see any chance to configure this on MacOS. anybody out there with a workaround without synapse 3?
