### ISSUE TITLE
Erro Pop!_OS 18.04 PT.BR

### ISSUE THREAD

**Issue by ghost** [openrazer/openrazer#625]
● openrazer-daemon.service - Daemon to manage razer devices in userspace
   Loaded: loaded (/usr/lib/systemd/user/openrazer-daemon.service; disabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Sat 2018-07-14 18:02:32 -03; 25s ago
     Docs: man:openrazer-daemon(8)
  Process: 3632 ExecStart=/usr/bin/openrazer-daemon -Fv (code=exited, status=1/FAILURE)
 Main PID: 3632 (code=exited, status=1/FAILURE)

jul 14 18:02:32 pop-os systemd[1686]: Starting Daemon to manage razer devices in userspace...
jul 14 18:02:32 pop-os openrazer-daemon[3632]: Starting daemon.
jul 14 18:02:32 pop-os openrazer-daemon[3632]: 2018-07-14 18:02:32 | razer                          | CRITICAL | User is not a member of the plugdev group
jul 14 18:02:32 pop-os openrazer-daemon[3632]: Stopping daemon.
jul 14 18:02:32 pop-os systemd[1686]: openrazer-daemon.service: Main process exited, code=exited, status=1/FAILURE
jul 14 18:02:32 pop-os systemd[1686]: openrazer-daemon.service: Failed with result 'exit-code'.
jul 14 18:02:32 pop-os systemd[1686]: Failed to start Daemon to manage razer devices in userspace.

**Comment by z3ntu** [comment]
https://github.com/openrazer/openrazer/wiki/Troubleshooting#plugdev
