### ISSUE TITLE
Device type not implemented

### ISSUE THREAD

**Issue by lesnake** [openrazer/openrazer#626]
Hello,
I'm trying to get my NagaHex V2 running. RazerGenie starts, but when I clic on "Open custom Editor", I get a dialog box with "Device type not implemented" in the title bar, and "Pease open an issue in the RazerGenie repository. Device type : mouse"

Which is what I am doing right now.

More info : 
Platform is ubuntu 18.04, razergenie is 2.3.1 (installed using ppa), mouse firmware is v1.0

> $ sudo lsmod |grep razer
> razermouse             65536  0
> hid                   118784  3 razermouse,hid_generic,usbhid

> $ openrazer-daemon -rFv
> Module psutil is missing, not checking for process name
> Process 1131 stopped
> Starting daemon.
> 2018-07-16 22:33:16 | razer                          | INFO     | Initialising Daemon (v2.3.1). Pid: 6358
> 2018-07-16 22:33:16 | razer.screensaver              | INFO     | Initialising DBus Screensaver Monitor
> 
> 2018-07-16 22:33:16 | razer                          | DEBUG    | Loaded device specification: RazerNagaHexV2 -------------------------- (1532:0050)

All the buttons are recognized using xev command

Also, I fetched the source, but I can not build it with this message (either in master or 2.3.1 tag)

> meson.build:8:0: ERROR: Qt5 native dependency not found (checked pkgconfig, qmake-qt5 and qmake)

I can not find which package to add :(

Thanks for support

**Comment by z3ntu** [comment]
Wrong repository. You're looking for https://github.com/z3ntu/RazerGenie/

Your problem ("Device type not implemented") is also already covered by https://github.com/z3ntu/RazerGenie/issues/10

And if you want to build RazerGenie yourself, you have to install the dependencies first as written on https://github.com/z3ntu/RazerGenie/wiki/Dependencies#ubuntu
