### ISSUE TITLE
Razer Abyssus 2014 - Cannot change DPI

### ISSUE THREAD

**Issue by mikerapt** [openrazer/openrazer#628]
Although having razergenie installed, it does not allow me to change DPI. 

https://scontent.fath3-3.fna.fbcdn.net/v/t1.15752-9/37397521_10214644817987207_2743360190807015424_n.png?_nc_cat=0&oh=8f5b77c9da23ecd4390a7c3901b23c6e&oe=5BC5F64E

https://scontent.fath3-3.fna.fbcdn.net/v/t1.15752-9/37412622_10214644825187387_5149333112622153728_n.png?_nc_cat=0&oh=eaeca7ef2ada387af6b12473ca287da9&oe=5BCE2654

**Comment by z3ntu** [comment]
Duplicate of #490 , please read the last comment there.
