### ISSUE TITLE
Blacklight doesn't work on Razer Blade Pro 2016 4k

### ISSUE THREAD

**Issue by rygo6** [openrazer/openrazer#633]
So I can't get backlight controls to work on my blade pro. The shortcut keys work but they have no effect on brightness.

 I added acpi_backlight=none to my /etc/default/grub and that made the brightness go 100% but now I can't control the brightness through shortcut keys and the slider is removed from the settings menu!

I also tried acpi_backlight=vender and acpi_osi=Linux to no success.

Anyone have any ideas?

**Comment by z3ntu** [comment]
USB ID is `1532:0210` (output of lsusb)?
