### ISSUE TITLE
Import issue in openrazer-daemon

### ISSUE THREAD

**Issue by muesli** [openrazer/openrazer#637]
Running Arch, having `openrazer-daemon` 2.3.1-2 from AUR installed, I get this error when trying to start it:

```
Traceback (most recent call last):
  File "/usr/bin/openrazer-daemon", line 11, in <module>
    from openrazer_daemon.daemon import RazerDaemon, __version__
ModuleNotFoundError: No module named 'openrazer_daemon'
```

**Comment by z3ntu** [comment]
Did you rebuild the openrazer packages after the latest python update (3.6.something -> 3.7.something)? You can get a list what you have to rebuild with `pacman -Qo /usr/lib/python3.6/site-packages/`

**Comment by muesli** [comment]
Thanks, that solved it! I wasn't aware manual interaction is required in such a situation. Maybe that's something for the FAQ until official packages have been adopted widely?

**Comment by z3ntu** [comment]
Well this is one of the reason you should know what you are doing when you are using the AUR. :)

**Comment by muesli** [comment]
Fair enough, but if that means you need to know the ins & outs of all the involved languages, dependencies and components, I pretty much doubt anyone's qualified enough to use the AUR ;-)

Since Razer's official page is linking to the AUR, I'd still appreciate a note / remark there.

**Comment by z3ntu** [comment]
The only thing you need to know for python AUR packages is exactly that path change with all major python versions. Perl packages also need something similar. And for normal C++ stuff you'll notice when some application says that it can't find some .so file, then you gotta rebuild.

What official page from Razer..? Could you link that for me?
