### ISSUE TITLE
Problema de dependencias para instalar no deepin

### ISSUE THREAD

**Issue by faening** [openrazer/openrazer#643]
Estou tentando instalar o openrazer-meta no deepin linux mas estou tendo problemas de dependência.

![deepin screenshot_20180815021313](https://user-images.githubusercontent.com/38919735/44132542-d70b93e2-a030-11e8-8bf2-32df58087dbc.png)

**Comment by z3ntu** [comment]
Please ask your questions in English so they can be understood.
