### ISSUE TITLE
Orbweaver Chroma no key macro change options

### ISSUE THREAD

**Issue by AceGilgamesh** [openrazer/openrazer#648]
I'm suspecting this is a limitation in openrazer, but the only option the polychromatic gives me for the orbweaver is to change the brightness and lighting effects, and very limited lighting effects at that.

Can someone confirm if this is openrazer or polychromatic problem?

**Comment by lah7** [comment]
It's a limitation in OpenRazer for now. At the moment, once the daemon initialises the keypad, it continues to behave like a Chroma keyboard (default device behaviour).

**Comment by AceGilgamesh** [comment]
Anything I can do to help getting it working? My knowledge in code is limited, I could be effective in testing or gathering wireshark data if that would be useful?

**Comment by AceGilgamesh** [comment]
I just tried a usb mointoring program, https://www.eltima.com/products/usb-port-monitor/ demo version. Regardless of even setting to monitor all of my connected usb peripherals, nothing was coming over usb that the program was recognizing. Going to see if I can pester Razer directly in some way shape or form for more information. **Since Openrazer does appear to have the capabilities to remap some keyboard keys (please correct me if I'm wrong)** so this should be well in the range of doing the same thing.

**Comment by z3ntu** [comment]
OpenRazer can't remap keys for now.

**Comment by AceGilgamesh** [comment]
Ok, I didn't understand the full functionality of OpenRazer then. Thank you @z3ntu. Should I keep this issue open, or close it?

**Comment by z3ntu** [comment]
I think there are enough issues open about key rebinding, so I'll close this :)
