### ISSUE TITLE
Keyboard on a Razer Blade Stealth not being picked up

### ISSUE THREAD

**Issue by WhyNotHugo** [openrazer/openrazer#651]
Hi! I just got a RBS, and they keyboard doesn't seem to be picked up by openrazer.

I'm attaching `dmesg`, `lspci`, `lsusb`, daemon logs, `xinput` and the output of `sudo journalctl -b | grep -i razer_mount > razer_mount`.

Let me know if there's anything else I can provide; I'm more than happy to help!

Also, thanks for all the work you guy have been doing on openrazer; I've been using it for other peripherals for quite a while, and it's great stuff!

(had to add `.txt` to the files or github wouldn't let me attach them)

[dmesg.txt](https://github.com/openrazer/openrazer/files/2305053/dmesg.txt)
[lspci.txt](https://github.com/openrazer/openrazer/files/2305054/lspci.txt)
[lsusb.txt](https://github.com/openrazer/openrazer/files/2305055/lsusb.txt)
[razer.log](https://github.com/openrazer/openrazer/files/2305057/razer.log)
[razer_mount.txt](https://github.com/openrazer/openrazer/files/2305058/razer_mount.txt)
[xinput.txt](https://github.com/openrazer/openrazer/files/2305059/xinput.txt)

**Comment by WhyNotHugo** [comment]
I've been looking through the code a bit, and it seems that support is already there (and also documented as such).

I initially thought this was a 2018 model, but it actually seems to be a "late 2017".

For some reason though, the keyboard is not being picked up -- even though the device ids seem to match.

**Comment by rustysec** [comment]
@WhyNotHugo i7-8550u version is working for me just fine (other than the #653 pr i opened).

**Comment by WhyNotHugo** [comment]
@rustysec Can you comment something else? I'm not sure what to make out from your comment.

**Comment by rustysec** [comment]
apologies! i have a late 2017 stealth, and openrazer is working. the only problem i faced was in using [RazerCommander](https://github.com/GabMus/razerCommander) to set individual key colors, but i have opened a pull request to patch that problem (hopefully). if i remember correctly, i needed to reboot for the kernel modules to load the first time.

hopefully that's clearer than my first comment.

**Comment by WhyNotHugo** [comment]
So after some debugging, it turns out my kernel headers were missing on this laptop, so while the dkms module was installed, it wasn't building (I'd copied my settings from my previous machine, but I seemed to have skipped the `linux-headers` package).

So now it's all up and working. Yet again, this was a user error. Sorry for the noise!
