### ISSUE TITLE
daemon will not start

### ISSUE THREAD

**Issue by thranmorrow** [openrazer/openrazer#656]
I am running ubuntu 18.04 and installed using the instructions found here https://openrazer.github.io/
when I try to start the driver daemon it throws an error.

Traceback (most recent call last):
  File "/usr/bin/openrazer-daemon", line 177, in <module>
    run()
  File "/usr/bin/openrazer-daemon", line 172, in run
    logger=logger)
TypeError: __init__() got an unexpected keyword argument 'foreground'

what am I doing wrong?

**Comment by z3ntu** [comment]
Please run `sudo apt update && sudo apt upgrade` and then try again.

**Comment by thranmorrow** [comment]
sudo apt update && sudo apt upgrade executed
by try again do you mean install it again or run openrazer-daemon -Fv again?
I did the later and go the same error

**Comment by z3ntu** [comment]
Did you properly add the openrazer ppa?

**Comment by thranmorrow** [comment]
I added it using sudo add-apt-repository ppa:openrazer/daily

**Comment by z3ntu** [comment]
Okay our daily PPA is missing python3-daemonize currently. But you should be fine installing the version for 17.10 (artful) which you can get at https://launchpad.net/~openrazer/+archive/ubuntu/daily/+files/python3-daemonize_2.4.7-artful_all.deb
(install it with `dpkg -i filename`)

**Comment by thranmorrow** [comment]
I already had python3-daemonize installed

sudo apt list --installed | grep python3-daemonize

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

python3-daemonize/artful,artful,now 2.3.1-1 all [installed]

**Comment by z3ntu** [comment]
Okay nvm, bionic (18.04) has python3-daemonize version 2.4.7-2 in their repos. Are you sure, you're on 18.04?

**Comment by thranmorrow** [comment]
certian

cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04 LTS

**Comment by z3ntu** [comment]
Your apt output from before (`python3-daemonize/artful,artful,now 2.3.1-1 all [installed]`) says `artful` though which is the codename for Ubuntu 17.10 so not all packages were upgraded or something.

**Comment by thranmorrow** [comment]
I uninstalled the python3-daemonize earlier today and reinstalled. artful is what I got. and looking at the repos  2.3.1-1 is the latest stable release

**Comment by z3ntu** [comment]
https://packages.ubuntu.com/bionic/python3-daemonize

**Comment by thranmorrow** [comment]
Bingo bongo. that did it
well had to changed the ownership of the log file first, but elsewise that did it

**Comment by z3ntu** [comment]
Great.

**Comment by thranmorrow** [comment]
thanks
