### ISSUE TITLE
Philips Hue Compatibility(Maybe?)

### ISSUE THREAD

**Issue by MelonCola** [openrazer/openrazer#658]
Hey, I was recently thinking of buying some Philips Hue bulbs, and was wondering if there was any chance compatibility for it was coming to openrazer(since it's available in normal synapse). I really doubt it's going to be added anytime soon, but just wondering.

**Comment by z3ntu** [comment]
Uhm no, sorry :)

**Comment by henryruhs** [comment]
@MelonCola Check out [phue](https://github.com/studioimaginaire/phue) - A Python library for the Philips Hue system
