### ISSUE TITLE
Razer BlackWidow Ultimate 2014

### ISSUE THREAD

**Issue by littletwitcher34** [openrazer/openrazer#661]
Is there a chance that this keyboard could be supported in the near future?
I read some where that i could use the 2013 version of drivers but i don't know how to do that.
Can somebody Please help me.

**Comment by z3ntu** [comment]
What's the output of `lsusb | grep 1532` ?

**Comment by ghost** [comment]
Bus 004 Device 003: ID 1532:0214 Razer USA, Ltd

**Comment by z3ntu** [comment]
`1532:0214` is already supported. Closing.
