### ISSUE TITLE
Keyboard layout

### ISSUE THREAD

**Issue by alh61** [openrazer/openrazer#662]
Hi

My keyboard has layout number 07
This is a Scandinavian keyboard, covering both Danish, Swedish and Norwegian layouts.
I'm using it as Danish  da_DK

 What do you need a screenshot of ?

**Comment by coolapso** [comment]
+1 on this one .. is there anything I can do help this to happen? 

cat /sys/bus/hid/drivers/razerkbd/0*/kbd_layout
07

**Comment by z3ntu** [comment]
Was already fixed in commit 7921f188c6bbf221a105ca83564bc2d0dd2e62e6
