### ISSUE TITLE
Settings not persistent, lost after reboot

### ISSUE THREAD

**Issue by APoniatowski** [openrazer/openrazer#663]
Hi there,

there seems to be a problem with keeping the settings persistent. LED settings are lost and the Turn off on screensaver setting is also lost and defaults to being enabled, which is quite annoying in the dark (black keyboard in the dark). Polling rate is defaulted to 500Hz as well.

Is there a way to make this permanent? like a quick workaround?

I am using Manjaro KDE:
Screenfetch

██████████████████ ████████ OS: Manjaro 17.1.12 Hakoila
██████████████████ ████████ Kernel: x86_64 Linux 4.14.66-1-MANJARO
██████████████████ ████████ Uptime: 3h 29m
████████ ████████ Packages: 1121
████████ ████████ ████████ Shell: bash 4.4.23
████████ ████████ ████████ Resolution: 4480x1440
████████ ████████ ████████ DE: KDE 5.49.0 / Plasma 5.13.4
████████ ████████ ████████ WM: KWin
████████ ████████ ████████ WM Theme: Breeze Dark
████████ ████████ ████████ GTK Theme: Breath [GTK2/3]
████████ ████████ ████████ Icon Theme: maia
████████ ████████ ████████ Font: Noto Sans Regular
████████ ████████ ████████ CPU: Intel Core i7-4770K @ 8x 3.5GHz [37.0°C]
GPU: GeForce GTX 1070
RAM: 2816MiB / 15982MiB

**Comment by z3ntu** [comment]
As I wrote in the RazerGenie repo it's not easily implemented with the current architecture :)

**Comment by lah7** [comment]
A workaround could be to create a start-up Python script that interacts with the OpenRazer Python library directly, like this:

```
#!/usr/bin/python3
import openrazer.client
a = openrazer.client.DeviceManager()
a.turn_off_on_screensaver = False
for device in a.devices:
    device.brightness = 100
    device.fx.static(0, 255, 0)
    if device.type == "mouse":
        device.poll_rate = 500
```

:point_up: May vary depending on your device, you can inspect and test by typing the commands in the `python3` console and pressing tab to see the combinations.

**Comment by APoniatowski** [comment]
Thanks guys :)  I will implement a python script to keep the LED colors persistent :)

About the little script you wrote lah7... don't you mean "#!/bin/python3" ?  ;)

**Comment by lah7** [comment]
Whoops, good spot! I'll amend the comment.

**Comment by APoniatowski** [comment]
I've been playing around the effects for my KB, that's fine. for fx and type of fx, how to I narrow it down for my mouse?  the docs makes sense for for kb, but not a mouse though.

Got a naga hex v2 mouse, I can get the hex numbered buttons to change colors, but how do I specify the wheel and logo?

I tried advanced.matrix with 0,1 and 0,2, but this is for kb's as it does not work on a mouse.

Update:   found it under .misc after bruteforcing my way through all the fx options :)
breath_dual is a bit weird... just using ([x , x , x] , [x , x , x]) doesn't work. and documentation is not entirely clear on that one... I tried  (['blue:255'] , ['red: 255']) and it doesn't work (and without quotes)

**Comment by APoniatowski** [comment]
I got an update on this issue... @lah7 that script does not work, when you use the RazerGenie (not razergenie-git) 

ModuleNotFoundError: No module named 'openrazer.client'

The reason I am not using the *-git version, is because it is older than the non-git version

**Comment by lah7** [comment]
RazerGenie interacts with the daemon directly, so it might not have installed the python libraries which will be needed for that script to work. On Arch, it's packaged under `python-openrazer`, make sure this is installed.

@z3ntu packages for Arch, he'll be able to confirm the versioning for `-git` .

**Comment by APoniatowski** [comment]
funny enough, I have that installed... even tried openrazer lib via pip, still no-go :(

**Comment by lah7** [comment]
Maybe your system installation of Python isn't looking in the right place for the libraries, especially if the version has been updated recently. Try setting the `PYTHONPATH` env variable before running the script:

    env PYTHONPATH=/usr/lib/python3/site-packages /path/to/script.py

:point_up: I'm not an Arch user, so `python3` might need to be changed to `python3.5` or `python3.6` depending where `openrazer`'s libraries are installed.

Also, the [openrazer pip](https://pypi.org/project/openrazer/) isn't the same as the [OpenRazer Python library](https://github.com/openrazer/openrazer/tree/master/pylib).

**Comment by z3ntu** [comment]
@APoniatowski Do you have the `openrazer-meta` package installed?

**Comment by APoniatowski** [comment]
updated openrazer-meta now.

I think I found my problem... you were right @lah7  
$ which python
/home/{username}/anaconda3/bin/python
$ which python3
/home/{username}/anaconda3/bin/python3

**Comment by z3ntu** [comment]
It should work though when you use it with the `#!/usr/bin/python3` shebang. How do you invoke the script?

**Comment by APoniatowski** [comment]
via #!/usr/bin/python3... which is strange.

**Comment by APoniatowski** [comment]
okey dokey... selectively blind me... I've been trying to run it with "python my-script.py" and not give it execution permissions and then running it normally, as it was intended (fun times with dual booting and forgetting what you did in linux lol)

**Comment by z3ntu** [comment]
So it's working now for you?

**Comment by APoniatowski** [comment]
yeah, my script is working now... I was being daft when running my script. OS-hopping sucks, it makes me forget what I was doing in OS I log back into

**Comment by komidawi** [comment]
> A workaround could be to create a start-up Python script that interacts with the OpenRazer Python library directly, like this:
> 
> ```
> #!/usr/bin/python3
> import openrazer.client
> a = openrazer.client.DeviceManager()
> a.turn_off_on_screensaver = False
> for device in a.devices:
>     device.brightness = 100
>     device.fx.static(0, 255, 0)
>     if device.type == "mouse":
>         device.poll_rate = 500
> ```

I managed to set DPI, but how to make my logo lightning in breath mode?
_(Razer Deathadder Essential 6400dpi)_

**Comment by lah7** [comment]
@komidawi Probably:

    device.fx.breath_random()
    device.fx.breath_single(0, 255, 0)
    device.fx.breath_dual(0, 255, 0, 255, 0 0)

Or `fx.misc.logo` instead of just `fx`. I don't have this mouse to confirm the exact function. You can poke about using the `python3` interpreter.

**Comment by komidawi** [comment]
@lah7 thank you very much, `fx.misc.logo.breath_single(0, 255, 0)` worked like a charm :smiley_cat:

**Comment by jfaz1** [comment]
3 years later, is the only way to make polling rate persist between reboots to write a script that does this? Tried a few frontends (Polychromatic, RazerGenie) and the polling rate resets back to 500 after each reboot.

**Comment by lah7** [comment]
@jfaz1 Frontends have no responsibility over persistence. OpenRazer (>=3.0.0) has had a software persistence feature for a while now that's supposed to apply the settings at logon instead of a relying on a script.

Check this file:  `~/.config/openrazer/razer.conf`
```ini
[Startup]
restore_persistence = True
```

Next to that is `persistence.conf` which stores the settings:
```ini
[PMXXXXXXXXXX123]
dpi_x = 1800
dpi_y = 1800
poll_rate = 500
```

If it doesn't work when it's on, try turning it off (`restore_persistence = False` - when off, no command is sent. It would be entirely up to the mouse to retain the poll rate). If there's still problems, please raise an issue for your particular mouse - it could be a bug.
