### ISSUE TITLE
Orbweaver Chroma custom effects

### ISSUE THREAD

**Issue by CalcProgrammer1** [openrazer/openrazer#666]
I modified the driver by adding the custom effect and custom frame entries to the Orbweaver Chroma probe and disconnect functions. The mapping is not 1 to 1 so I did some tests to map it out.  I would say leave the mapping up to the application/daemon but that's up to the project maintainers I guess.

Attached is my mapping.  The number in the box is the Orbweaver key in that row/col.
![20180903_124000](https://user-images.githubusercontent.com/1051772/44997909-4d70b080-af77-11e8-9eda-27f11fce0f80.jpg)

**Comment by sevu** [comment]
Hi @CalcProgrammer1, another Orbweaver Chroma user here.

What is this about? Are in the middle the keys on the keyboard, and the one gap is on German keyboard Layout for the  "<" key? What are the numbers at the borders representing?
What are the "custom effect and custom frame entries" ?

Maybe you would like to make a Pull Request?

**Comment by chrisdonlan** [comment]
Macros for the orb weaver are not yet supported, right?

**Comment by hedmo** [comment]
how about wave for the orbweaver?
