### ISSUE TITLE
OpenRazer is integrated into Light, needs testing

### ISSUE THREAD

**Issue by perkele1989** [openrazer/openrazer#668]
I hope that this is OK, as this is really an issue in the Light project, and not OpenRazer. If not, feel free to close this issue.

Light is an application that can control different lightsources on GNU/Linux systems. It originated as a simple bash-script to control backlights, but now supports all kinds of lights, including leds and keyboard backlights.

I have (hopefully) integrated OpenRazer into the Light project, and would very much appreciate some testing, as I do not have any hardware to test it on myself.  It implements targets for the keyboard backlight and 6 different leds.  I followed the wiki on this repository, but also noticed that it was allegedly outdated.

Regards,

**Comment by perkele1989** [comment]
The sourcefiles for the implementation can be found here:

Header: https://github.com/haikarainen/light/blob/master/src/impl/razer.h

Source: https://github.com/haikarainen/light/blob/master/src/impl/razer.c

**Comment by parkerlreed** [comment]
@haikarainen I know this is a tad late but yes it does work. Thanks

````
light -S 100 -s razer/0003:1532:0220.0007/backlight
light -L
Listing device targets:
        sysfs/backlight/intel_backlight
        sysfs/backlight/auto
        sysfs/leds/input58::kana
        sysfs/leds/input58::compose
        sysfs/leds/input60::scrolllock
        sysfs/leds/input60::capslock
        sysfs/leds/input59::scrolllock
        sysfs/leds/input59::kana
        sysfs/leds/input59::compose
        sysfs/leds/input59::capslock
        sysfs/leds/input60::numlock
        sysfs/leds/input28::numlock
        sysfs/leds/input58::scrolllock
        sysfs/leds/input58::numlock
        sysfs/leds/input28::capslock
        sysfs/leds/input60::compose
        sysfs/leds/input28::scrolllock
        sysfs/leds/input60::kana
        sysfs/leds/input59::numlock
        sysfs/leds/input58::capslock
        util/test/dryrun
        razer/0003:1532:0220.0007/backlight
        razer/0003:1532:0220.0007/logo_led
````

**Comment by perkele1989** [comment]
@parkerlreed Very cool, thank you!
