### ISSUE TITLE
Device not Recognised

### ISSUE THREAD

**Issue by Ultracard** [openrazer/openrazer#670]
Hello, I'm new to Linux and I'm not very experienced with it.
I installed the Openrazer driver, and the daemon seems to work. But i downloaded Polychromatic and it shows me an error message, that my device was not recognised. Even though i have a Blackwidow Chroma V2 which is supported. I also have all the dependencies installed.
Can somebody help me? Because i don't know what the issue is. I attached my Razer log if that helps to find the issue.
[razer.log](https://github.com/openrazer/openrazer/files/2359985/razer.log)
Thank You!

**Comment by z3ntu** [comment]
Please read the first line (labeled `CRITICAL`) and then run `sudo gpasswd -a $USER plugdev` to add your user to the plugdev group.
edit: or did you do that already?

**Comment by z3ntu** [comment]
Also please run `sudo dkms install openrazer-driver/2.3.1`

**Comment by Ultracard** [comment]
Yes i already added myself to the plugdev group.

**Comment by Ultracard** [comment]
When i run sudo dkms install openrazer-driver/2.3.1
i get an Error, that my kernel headers for kernel 4.15.0-kali2-amd cannot be foun.

**Comment by z3ntu** [comment]
Then install the kernel headers for your kernel.

**Comment by Ultracard** [comment]
But that might be because yesterday i already tried fixing the problem and on another issue somebody said that i should run 
**sudo apt purge openrazer-meta polychromatic linux-headers-generic**
did that create a problem on my Computer?

**Comment by Ultracard** [comment]
Yes i tried, but when i run
**sudo apt-get install linux-headers-generic**
i get this message in the Terminal:

Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package linux-headers-generic is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'linux-headers-generic' has no installation candidate

**Comment by z3ntu** [comment]
On Kali Linux the package name is probably different.

**Comment by Ultracard** [comment]
I found these commands on the internet, do you think I should try them?
**sudo apt-get dist-upgrade -y 
sudo apt-get install linux-headers-$(uname -r)
sudo apt-get upgrade linux-headers-$(uname -r)**

**Comment by z3ntu** [comment]
`sudo apt-get install linux-headers-$(uname -r)` should do the job (but run the dist-upgrade command before)

**Comment by Ultracard** [comment]
Ok,it's currently upgrading, it will take a few minutes.

**Comment by Ultracard** [comment]
when i run
**sudo apt-get install linux-headers-$(uname -r)**
i get:

Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package linux-headers-4.15.0-kali2-amd64
E: Couldn't find any package by glob 'linux-headers-4.15.0-kali2-amd64'
E: Couldn't find any package by regex 'linux-headers-4.15.0-kali2-amd64'

**Comment by Ultracard** [comment]
I just reebootet  my pc, after entering my password I only get a blank screen, I guess I will have to install linux again, but thank you so much, I would have never thought that I would get help so quickly ☺️.

**Comment by Ultracard** [comment]
Can I ask you again, when I have reinstalled Linux?

**Comment by z3ntu** [comment]
Sure.
