### ISSUE TITLE
Device not recognised

### ISSUE THREAD

**Issue by Ultracard** [openrazer/openrazer#679]
Hello, i recently opened an issue because i had openrazer and polychromatic installed on kali linux.
However it did not recognize my keyboard even though it is the blackwidow chroma v2 and i had all dependencies installed and was added to the group plugdev.

now i´m running elementary os because it´s much easier to use.
I installed openrazer and polychromatic and the daemon is working fine.
But it still doesn´t recognize my device. 
I am in the group plugdev.
Can someone help me?

**Comment by z3ntu** [comment]
What's the output of `sudo dkms install openrazer-driver/2.3.1` ?

**Comment by Ultracard** [comment]
Module openrazer-driver/2.3.1 already installed on kernel 4.15.0-34-generic/x86_64

**Comment by z3ntu** [comment]
`sudo modprobe razerkbd` ?

**Comment by Ultracard** [comment]
nothing happens

**Comment by z3ntu** [comment]
`ls -al /sys/bus/hid/drivers/razerkbd/0*/` ?

**Comment by Ultracard** [comment]
ls: cannot access '/sys/bus/hid/drivers/razerkbd/0*/': No such file or directory

**Comment by z3ntu** [comment]
What about `sudo journalctl -b | grep -i razer_mount` ?

**Comment by Ultracard** [comment]
me@my-AcerAspireE15:~$ sudo journalctl -b | grep -i razer_mount
me@my-AcerAspireE15:~$
again nothing

**Comment by Ultracard** [comment]
oh sorry, i have to use them seperately, wait

**Comment by Ultracard** [comment]
anton@Anton-AcerAspireE15:~$ sudo journalctl -b 
-- Logs begin at Sat 2018-09-15 17:59:48 CEST, end at Sat 2018-09-15 19:31:21 CEST. --
Sep 15 17:59:48 Anton-AcerAspireE15 systemd-journald[350]: Runtime journal (/run/log/journal/) is 8.0M
Sep 15 17:59:49 Anton-AcerAspireE15 kernel: microcode: microcode updated early to revision 0x8e, date 
Sep 15 17:59:49 Anton-AcerAspireE15 kernel: Linux version 4.15.0-34-generic (buildd@lgw01-amd64-037) (
Sep 15 17:59:49 Anton-AcerAspireE15 kernel: Command line: BOOT_IMAGE=/vmlinuz-4.15.0-34-generic root=U
Sep 15 17:59:49 Anton-AcerAspireE15 kernel: KERNEL supported cpus:
Sep 15 17:59:49 Anton-AcerAspireE15 kernel:   Intel GenuineIntel
Sep 15 17:59:49 Anton-AcerAspireE15 kernel:   AMD AuthenticAMD
Sep 15 17:59:49 Anton-AcerAspireE15 kernel:   Centaur CentaurHauls
Sep 15 17:59:49 Anton-AcerAspireE15 kernel: x86/fpu: Supporting XSAVE feature 0x001: 'x87 floating poi
Sep 15 17:59:49 Anton-AcerAspireE15 kernel: x86/fpu: Supporting XSAVE feature 0x002: 'SSE registers'
Sep 15 17:59:49 Anton-AcerAspireE15 kernel: x86/fpu: Supporting XSAVE feature 0x004: 'AVX registers'
Sep 15 17:59:49 Anton-AcerAspireE15 kernel: x86/fpu: Supporting XSAVE feature 0x008: 'MPX bounds regis
Sep 15 17:59:49 Anton-AcerAspireE15 kernel: x86/fpu: Supporting XSAVE feature 0x010: 'MPX CSR'
Sep 15 17:59:49 Anton-AcerAspireE15 kernel: x86/fpu: xstate_offset[2]:  576, xstate_sizes[2]:  256
Sep 15 17:59:49 Anton-AcerAspireE15 kernel: x86/fpu: xstate_offset[3]:  832, xstate_sizes[3]:   64
Sep 15 17:59:49 Anton-AcerAspireE15 kernel: x86/fpu: xstate_offset[4]:  896, xstate_sizes[4]:   64
Sep 15 17:59:49 Anton-AcerAspireE15 kernel: x86/fpu: Enabled xstate features 0x1f, context size is 960
Sep 15 17:59:49 Anton-AcerAspireE15 kernel: e820: BIOS-provided physical RAM map:
Sep 15 17:59:49 Anton-AcerAspireE15 kernel: BIOS-e820: [mem 0x0000000000000000-0x000000000009e7ff] usa
Sep 15 17:59:49 Anton-AcerAspireE15 kernel: BIOS-e820: [mem 0x000000000009e800-0x000000000009ffff] res
Sep 15 17:59:49 Anton-AcerAspireE15 kernel: BIOS-e820: [mem 0x00000000000e0000-0x00000000000fffff] res
Sep 15 17:59:49 Anton-AcerAspireE15 kernel: BIOS-e820: [mem 0x0000000000100000-0x0000000071109fff] usa
Sep 15 17:59:49 Anton-AcerAspireE15 kernel: BIOS-e820: [mem 0x000000007110a000-0x000000007110afff] ACP
Sep 15 17:59:49 Anton-AcerAspireE15 kernel: BIOS-e820: [mem 0x000000007110b000-0x000000007110bfff] res
Sep 15 17:59:49 Anton-AcerAspireE15 kernel: BIOS-e820: [mem 0x000000007110c000-0x0000000072a87fff] usa
Sep 15 17:59:49 Anton-AcerAspireE15 kernel: BIOS-e820: [mem 0x0000000072a88000-0x0000000073b87fff] res
Sep 15 17:59:49 Anton-AcerAspireE15 kernel: BIOS-e820: [mem 0x0000000073b88000-0x0000000089d9dfff] usa
Sep 15 17:59:49 Anton-AcerAspireE15 kernel: BIOS-e820: [mem 0x0000000089d9e000-0x000000008a78dfff] res
Sep 15 17:59:49 Anton-AcerAspireE15 kernel: BIOS-e820: [mem 0x000000008a78e000-0x000000008ae7dfff] ACP
Sep 15 17:59:49 Anton-AcerAspireE15 kernel: BIOS-e820: [mem 0x000000008ae7e000-0x000000008aefdfff] ACP
Sep 15 17:59:49 Anton-AcerAspireE15 kernel: BIOS-e820: [mem 0x000000008aefe000-0x000000008aefefff] usa
Sep 15 17:59:49 Anton-AcerAspireE15 kernel: BIOS-e820: [mem 0x000000008aeff000-0x000000008fffffff] res
Sep 15 17:59:49 Anton-AcerAspireE15 kernel: BIOS-e820: [mem 0x00000000e0000000-0x00000000efffffff] res
Sep 15 17:59:49 Anton-AcerAspireE15 kernel: BIOS-e820: [mem 0x00000000fd000000-0x00000000fe7fffff] res
Sep 15 17:59:49 Anton-AcerAspireE15 kernel: BIOS-e820: [mem 0x00000000fec00000-0x00000000fec00fff] res
Sep 15 17:59:49 Anton-AcerAspireE15 kernel: BIOS-e820: [mem 0x00000000fed00000-0x00000000fed00fff] res
lines 1-37






































-- Logs begin at Sat 2018-09-15 17:59:48 CEST, end at Sat 2018-09-15 19:31:21 CEST. --
Sep 15 17:59:48 Anton-AcerAspireE15 systemd-journald[350]: Runtime journal (/run/log/journal/) is 8.0M,
Sep 15 17:59:49 Anton-AcerAspireE15 kernel: microcode: microcode updated early to revision 0x8e, date =
Sep 15 17:59:49 Anton-AcerAspireE15 kernel: Linux version 4.15.0-34-generic (buildd@lgw01-amd64-037) (g
Sep 15 17:59:49 Anton-AcerAspireE15 kernel: Command line: BOOT_IMAGE=/vmlinuz-4.15.0-34-generic root=UU
Sep 15 17:59:49 Anton-AcerAspireE15 kernel: KERNEL supported cpus:
Sep 15 17:59:49 Anton-AcerAspireE15 kernel:   Intel GenuineIntel
Sep 15 17:59:49 Anton-AcerAspireE15 kernel:   AMD AuthenticAMD
Sep 15 17:59:49 Anton-AcerAspireE15 kernel:   Centaur CentaurHauls
Sep 15 17:59:49 Anton-AcerAspireE15 kernel: x86/fpu: Supporting XSAVE feature 0x001: 'x87 floating poin
Sep 15 17:59:49 Anton-AcerAspireE15 kernel: x86/fpu: Supporting XSAVE feature 0x002: 'SSE registers'
Sep 15 17:59:49 Anton-AcerAspireE15 kernel: x86/fpu: Supporting XSAVE feature 0x004: 'AVX registers'
Sep 15 17:59:49 Anton-AcerAspireE15 kernel: x86/fpu: Supporting XSAVE feature 0x008: 'MPX bounds regist
Sep 15 17:59:49 Anton-AcerAspireE15 kernel: x86/fpu: Supporting XSAVE feature 0x010: 'MPX CSR'
Sep 15 17:59:49 Anton-AcerAspireE15 kernel: x86/fpu: xstate_offset[2]:  576, xstate_sizes[2]:  256
Sep 15 17:59:49 Anton-AcerAspireE15 kernel: x86/fpu: xstate_offset[3]:  832, xstate_sizes[3]:   64
Sep 15 17:59:49 Anton-AcerAspireE15 kernel: x86/fpu: xstate_offset[4]:  896, xstate_sizes[4]:   64
Sep 15 17:59:49 Anton-AcerAspireE15 kernel: x86/fpu: Enabled xstate features 0x1f, context size is 960 
Sep 15 17:59:49 Anton-AcerAspireE15 kernel: e820: BIOS-provided physical RAM map:
Sep 15 17:59:49 Anton-AcerAspireE15 kernel: BIOS-e820: [mem 0x0000000000000000-0x000000000009e7ff] usab
Sep 15 17:59:49 Anton-AcerAspireE15 kernel: BIOS-e820: [mem 0x000000000009e800-0x000000000009ffff] rese
Sep 15 17:59:49 Anton-AcerAspireE15 kernel: BIOS-e820: [mem 0x00000000000e0000-0x00000000000fffff] rese
Sep 15 17:59:49 Anton-AcerAspireE15 kernel: BIOS-e820: [mem 0x0000000000100000-0x0000000071109fff] usab
Sep 15 17:59:49 Anton-AcerAspireE15 kernel: BIOS-e820: [mem 0x000000007110a000-0x000000007110afff] ACPI
Sep 15 17:59:49 Anton-AcerAspireE15 kernel: BIOS-e820: [mem 0x000000007110b000-0x000000007110bfff] rese
Sep 15 17:59:49 Anton-AcerAspireE15 kernel: BIOS-e820: [mem 0x000000007110c000-0x0000000072a87fff] usab
Sep 15 17:59:49 Anton-AcerAspireE15 kernel: BIOS-e820: [mem 0x0000000072a88000-0x0000000073b87fff] rese
Sep 15 17:59:49 Anton-AcerAspireE15 kernel: BIOS-e820: [mem 0x0000000073b88000-0x0000000089d9dfff] usab
Sep 15 17:59:49 Anton-AcerAspireE15 kernel: BIOS-e820: [mem 0x0000000089d9e000-0x000000008a78dfff] rese
Sep 15 17:59:49 Anton-AcerAspireE15 kernel: BIOS-e820: [mem 0x000000008a78e000-0x000000008ae7dfff] ACPI
Sep 15 17:59:49 Anton-AcerAspireE15 kernel: BIOS-e820: [mem 0x000000008ae7e000-0x000000008aefdfff] ACPI
Sep 15 17:59:49 Anton-AcerAspireE15 kernel: BIOS-e820: [mem 0x000000008aefe000-0x000000008aefefff] usab
Sep 15 17:59:49 Anton-AcerAspireE15 kernel: BIOS-e820: [mem 0x000000008aeff000-0x000000008fffffff] rese
Sep 15 17:59:49 Anton-AcerAspireE15 kernel: BIOS-e820: [mem 0x00000000e0000000-0x00000000efffffff] rese
Sep 15 17:59:49 Anton-AcerAspireE15 kernel: BIOS-e820: [mem 0x00000000fd000000-0x00000000fe7fffff] rese
Sep 15 17:59:49 Anton-AcerAspireE15 kernel: BIOS-e820: [mem 0x00000000fec00000-0x00000000fec00fff] rese
Sep 15 17:59:49 Anton-AcerAspireE15 kernel: BIOS-e820: [mem 0x00000000fed00000-0x00000000fed00fff] rese
lines 1-37...skipping...
-- Logs begin at Sat 2018-09-15 17:59:48 CEST, end at Sat 2018-09-15 19:31:21 CEST. --
Sep 15 17:59:48 Anton-AcerAspireE15 systemd-journald[350]: Runtime journal (/run/log/journal/) is 8.0M, max 
Sep 15 17:59:49 Anton-AcerAspireE15 kernel: microcode: microcode updated early to revision 0x8e, date = 2018
Sep 15 17:59:49 Anton-AcerAspireE15 kernel: Linux version 4.15.0-34-generic (buildd@lgw01-amd64-037) (gcc ve
Sep 15 17:59:49 Anton-AcerAspireE15 kernel: Command line: BOOT_IMAGE=/vmlinuz-4.15.0-34-generic root=UUID=52
Sep 15 17:59:49 Anton-AcerAspireE15 kernel: KERNEL supported cpus:
Sep 15 17:59:49 Anton-AcerAspireE15 kernel:   Intel GenuineIntel
Sep 15 17:59:49 Anton-AcerAspireE15 kernel:   AMD AuthenticAMD
Sep 15 17:59:49 Anton-AcerAspireE15 kernel:   Centaur CentaurHauls
Sep 15 17:59:49 Anton-AcerAspireE15 kernel: x86/fpu: Supporting XSAVE feature 0x001: 'x87 floating point reg
Sep 15 17:59:49 Anton-AcerAspireE15 kernel: x86/fpu: Supporting XSAVE feature 0x002: 'SSE registers'
Sep 15 17:59:49 Anton-AcerAspireE15 kernel: x86/fpu: Supporting XSAVE feature 0x004: 'AVX registers'
Sep 15 17:59:49 Anton-AcerAspireE15 kernel: x86/fpu: Supporting XSAVE feature 0x008: 'MPX bounds registers'
Sep 15 17:59:49 Anton-AcerAspireE15 kernel: x86/fpu: Supporting XSAVE feature 0x010: 'MPX CSR'
Sep 15 17:59:49 Anton-AcerAspireE15 kernel: x86/fpu: xstate_offset[2]:  576, xstate_sizes[2]:  256
Sep 15 17:59:49 Anton-AcerAspireE15 kernel: x86/fpu: xstate_offset[3]:  832, xstate_sizes[3]:   64
Sep 15 17:59:49 Anton-AcerAspireE15 kernel: x86/fpu: xstate_offset[4]:  896, xstate_sizes[4]:   64
Sep 15 17:59:49 Anton-AcerAspireE15 kernel: x86/fpu: Enabled xstate features 0x1f, context size is 960 bytes
Sep 15 17:59:49 Anton-AcerAspireE15 kernel: e820: BIOS-provided physical RAM map:
Sep 15 17:59:49 Anton-AcerAspireE15 kernel: BIOS-e820: [mem 0x0000000000000000-0x000000000009e7ff] usable
Sep 15 17:59:49 Anton-AcerAspireE15 kernel: BIOS-e820: [mem 0x000000000009e800-0x000000000009ffff] reserved
Sep 15 17:59:49 Anton-AcerAspireE15 kernel: BIOS-e820: [mem 0x00000000000e0000-0x00000000000fffff] reserved
Sep 15 17:59:49 Anton-AcerAspireE15 kernel: BIOS-e820: [mem 0x0000000000100000-0x0000000071109fff] usable
Sep 15 17:59:49 Anton-AcerAspireE15 kernel: BIOS-e820: [mem 0x000000007110a000-0x000000007110afff] ACPI NVS
Sep 15 17:59:49 Anton-AcerAspireE15 kernel: BIOS-e820: [mem 0x000000007110b000-0x000000007110bfff] reserved
Sep 15 17:59:49 Anton-AcerAspireE15 kernel: BIOS-e820: [mem 0x000000007110c000-0x0000000072a87fff] usable
Sep 15 17:59:49 Anton-AcerAspireE15 kernel: BIOS-e820: [mem 0x0000000072a88000-0x0000000073b87fff] reserved
Sep 15 17:59:49 Anton-AcerAspireE15 kernel: BIOS-e820: [mem 0x0000000073b88000-0x0000000089d9dfff] usable
Sep 15 17:59:49 Anton-AcerAspireE15 kernel: BIOS-e820: [mem 0x0000000089d9e000-0x000000008a78dfff] reserved
Sep 15 17:59:49 Anton-AcerAspireE15 kernel: BIOS-e820: [mem 0x000000008a78e000-0x000000008ae7dfff] ACPI NVS
Sep 15 17:59:49 Anton-AcerAspireE15 kernel: BIOS-e820: [mem 0x000000008ae7e000-0x000000008aefdfff] ACPI data
Sep 15 17:59:49 Anton-AcerAspireE15 kernel: BIOS-e820: [mem 0x000000008aefe000-0x000000008aefefff] usable
Sep 15 17:59:49 Anton-AcerAspireE15 kernel: BIOS-e820: [mem 0x000000008aeff000-0x000000008fffffff] reserved
Sep 15 17:59:49 Anton-AcerAspireE15 kernel: BIOS-e820: [mem 0x00000000e0000000-0x00000000efffffff] reserved
Sep 15 17:59:49 Anton-AcerAspireE15 kernel: BIOS-e820: [mem 0x00000000fd000000-0x00000000fe7fffff] reserved
Sep 15 17:59:49 Anton-AcerAspireE15 kernel: BIOS-e820: [mem 0x00000000fec00000-0x00000000fec00fff] reserved
Sep 15 17:59:49 Anton-AcerAspireE15 kernel: BIOS-e820: [mem 0x00000000fed00000-0x00000000fed00fff] reserved
Sep 15 17:59:49 Anton-AcerAspireE15 kernel: BIOS-e820: [mem 0x00000000fed10000-0x00000000fed19fff] reserved
lines 1-38...skipping...
-- Logs begin at Sat 2018-09-15 17:59:48 CEST, end at Sat 2018-09-15 19:31:21 CEST. --
Sep 15 17:59:48 Anton-AcerAspireE15 systemd-journald[350]: Runtime journal (/run/log/journal/) is 8.0M, max 78.
Sep 15 17:59:49 Anton-AcerAspireE15 kernel: microcode: microcode updated early to revision 0x8e, date = 2018-03
Sep 15 17:59:49 Anton-AcerAspireE15 kernel: Linux version 4.15.0-34-generic (buildd@lgw01-amd64-037) (gcc versi
Sep 15 17:59:49 Anton-AcerAspireE15 kernel: Command line: BOOT_IMAGE=/vmlinuz-4.15.0-34-generic root=UUID=52b59
Sep 15 17:59:49 Anton-AcerAspireE15 kernel: KERNEL supported cpus:
Sep 15 17:59:49 Anton-AcerAspireE15 kernel:   Intel GenuineIntel
Sep 15 17:59:49 Anton-AcerAspireE15 kernel:   AMD AuthenticAMD
Sep 15 17:59:49 Anton-AcerAspireE15 kernel:   Centaur CentaurHauls
Sep 15 17:59:49 Anton-AcerAspireE15 kernel: x86/fpu: Supporting XSAVE feature 0x001: 'x87 floating point regist
Sep 15 17:59:49 Anton-AcerAspireE15 kernel: x86/fpu: Supporting XSAVE feature 0x002: 'SSE registers'
Sep 15 17:59:49 Anton-AcerAspireE15 kernel: x86/fpu: Supporting XSAVE feature 0x004: 'AVX registers'
Sep 15 17:59:49 Anton-AcerAspireE15 kernel: x86/fpu: Supporting XSAVE feature 0x008: 'MPX bounds registers'
Sep 15 17:59:49 Anton-AcerAspireE15 kernel: x86/fpu: Supporting XSAVE feature 0x010: 'MPX CSR'
Sep 15 17:59:49 Anton-AcerAspireE15 kernel: x86/fpu: xstate_offset[2]:  576, xstate_sizes[2]:  256
Sep 15 17:59:49 Anton-AcerAspireE15 kernel: x86/fpu: xstate_offset[3]:  832, xstate_sizes[3]:   64
Sep 15 17:59:49 Anton-AcerAspireE15 kernel: x86/fpu: xstate_offset[4]:  896, xstate_sizes[4]:   64
Sep 15 17:59:49 Anton-AcerAspireE15 kernel: x86/fpu: Enabled xstate features 0x1f, context size is 960 bytes, u
Sep 15 17:59:49 Anton-AcerAspireE15 kernel: e820: BIOS-provided physical RAM map:
Sep 15 17:59:49 Anton-AcerAspireE15 kernel: BIOS-e820: [mem 0x0000000000000000-0x000000000009e7ff] usable
Sep 15 17:59:49 Anton-AcerAspireE15 kernel: BIOS-e820: [mem 0x000000000009e800-0x000000000009ffff] reserved
Sep 15 17:59:49 Anton-AcerAspireE15 kernel: BIOS-e820: [mem 0x00000000000e0000-0x00000000000fffff] reserved
Sep 15 17:59:49 Anton-AcerAspireE15 kernel: BIOS-e820: [mem 0x0000000000100000-0x0000000071109fff] usable
Sep 15 17:59:49 Anton-AcerAspireE15 kernel: BIOS-e820: [mem 0x000000007110a000-0x000000007110afff] ACPI NVS
Sep 15 17:59:49 Anton-AcerAspireE15 kernel: BIOS-e820: [mem 0x000000007110b000-0x000000007110bfff] reserved
Sep 15 17:59:49 Anton-AcerAspireE15 kernel: BIOS-e820: [mem 0x000000007110c000-0x0000000072a87fff] usable
Sep 15 17:59:49 Anton-AcerAspireE15 kernel: BIOS-e820: [mem 0x0000000072a88000-0x0000000073b87fff] reserved
Sep 15 17:59:49 Anton-AcerAspireE15 kernel: BIOS-e820: [mem 0x0000000073b88000-0x0000000089d9dfff] usable
Sep 15 17:59:49 Anton-AcerAspireE15 kernel: BIOS-e820: [mem 0x0000000089d9e000-0x000000008a78dfff] reserved
Sep 15 17:59:49 Anton-AcerAspireE15 kernel: BIOS-e820: [mem 0x000000008a78e000-0x000000008ae7dfff] ACPI NVS
Sep 15 17:59:49 Anton-AcerAspireE15 kernel: BIOS-e820: [mem 0x000000008ae7e000-0x000000008aefdfff] ACPI data
Sep 15 17:59:49 Anton-AcerAspireE15 kernel: BIOS-e820: [mem 0x000000008aefe000-0x000000008aefefff] usable
Sep 15 17:59:49 Anton-AcerAspireE15 kernel: BIOS-e820: [mem 0x000000008aeff000-0x000000008fffffff] reserved
Sep 15 17:59:49 Anton-AcerAspireE15 kernel: BIOS-e820: [mem 0x00000000e0000000-0x00000000efffffff] reserved
Sep 15 17:59:49 Anton-AcerAspireE15 kernel: BIOS-e820: [mem 0x00000000fd000000-0x00000000fe7fffff] reserved
Sep 15 17:59:49 Anton-AcerAspireE15 kernel: BIOS-e820: [mem 0x00000000fec00000-0x00000000fec00fff] reserved
Sep 15 17:59:49 Anton-AcerAspireE15 kernel: BIOS-e820: [mem 0x00000000fed00000-0x00000000fed00fff] reserved
Sep 15 17:59:49 Anton-AcerAspireE15 kernel: BIOS-e820: [mem 0x00000000fed10000-0x00000000fed19fff] reserved
Sep 15 17:59:49 Anton-AcerAspireE15 kernel: BIOS-e820: [mem 0x00000000fed84000-0x00000000fed84fff] reserved
lines 1-39








































-- Logs begin at Sat 2018-09-15 17:59:48 CEST, end at Sat 2018-09-15 19:31:21 CEST. --
Sep 15 17:59:48 Anton-AcerAspireE15 systemd-journald[350]: Runtime journal (/run/log/journal/) is 8.0M, max 78.4M, 
Sep 15 17:59:49 Anton-AcerAspireE15 kernel: microcode: microcode updated early to revision 0x8e, date = 2018-03-24
Sep 15 17:59:49 Anton-AcerAspireE15 kernel: Linux version 4.15.0-34-generic (buildd@lgw01-amd64-037) (gcc version 5
Sep 15 17:59:49 Anton-AcerAspireE15 kernel: Command line: BOOT_IMAGE=/vmlinuz-4.15.0-34-generic root=UUID=52b595af-
Sep 15 17:59:49 Anton-AcerAspireE15 kernel: KERNEL supported cpus:
Sep 15 17:59:49 Anton-AcerAspireE15 kernel:   Intel GenuineIntel
Sep 15 17:59:49 Anton-AcerAspireE15 kernel:   AMD AuthenticAMD
Sep 15 17:59:49 Anton-AcerAspireE15 kernel:   Centaur CentaurHauls
Sep 15 17:59:49 Anton-AcerAspireE15 kernel: x86/fpu: Supporting XSAVE feature 0x001: 'x87 floating point registers'
Sep 15 17:59:49 Anton-AcerAspireE15 kernel: x86/fpu: Supporting XSAVE feature 0x002: 'SSE registers'
Sep 15 17:59:49 Anton-AcerAspireE15 kernel: x86/fpu: Supporting XSAVE feature 0x004: 'AVX registers'
Sep 15 17:59:49 Anton-AcerAspireE15 kernel: x86/fpu: Supporting XSAVE feature 0x008: 'MPX bounds registers'
Sep 15 17:59:49 Anton-AcerAspireE15 kernel: x86/fpu: Supporting XSAVE feature 0x010: 'MPX CSR'
Sep 15 17:59:49 Anton-AcerAspireE15 kernel: x86/fpu: xstate_offset[2]:  576, xstate_sizes[2]:  256
Sep 15 17:59:49 Anton-AcerAspireE15 kernel: x86/fpu: xstate_offset[3]:  832, xstate_sizes[3]:   64
Sep 15 17:59:49 Anton-AcerAspireE15 kernel: x86/fpu: xstate_offset[4]:  896, xstate_sizes[4]:   64
Sep 15 17:59:49 Anton-AcerAspireE15 kernel: x86/fpu: Enabled xstate features 0x1f, context size is 960 bytes, using
Sep 15 17:59:49 Anton-AcerAspireE15 kernel: e820: BIOS-provided physical RAM map:
Sep 15 17:59:49 Anton-AcerAspireE15 kernel: BIOS-e820: [mem 0x0000000000000000-0x000000000009e7ff] usable
Sep 15 17:59:49 Anton-AcerAspireE15 kernel: BIOS-e820: [mem 0x000000000009e800-0x000000000009ffff] reserved
Sep 15 17:59:49 Anton-AcerAspireE15 kernel: BIOS-e820: [mem 0x00000000000e0000-0x00000000000fffff] reserved
Sep 15 17:59:49 Anton-AcerAspireE15 kernel: BIOS-e820: [mem 0x0000000000100000-0x0000000071109fff] usable
Sep 15 17:59:49 Anton-AcerAspireE15 kernel: BIOS-e820: [mem 0x000000007110a000-0x000000007110afff] ACPI NVS
Sep 15 17:59:49 Anton-AcerAspireE15 kernel: BIOS-e820: [mem 0x000000007110b000-0x000000007110bfff] reserved
Sep 15 17:59:49 Anton-AcerAspireE15 kernel: BIOS-e820: [mem 0x000000007110c000-0x0000000072a87fff] usable
Sep 15 17:59:49 Anton-AcerAspireE15 kernel: BIOS-e820: [mem 0x0000000072a88000-0x0000000073b87fff] reserved
Sep 15 17:59:49 Anton-AcerAspireE15 kernel: BIOS-e820: [mem 0x0000000073b88000-0x0000000089d9dfff] usable
Sep 15 17:59:49 Anton-AcerAspireE15 kernel: BIOS-e820: [mem 0x0000000089d9e000-0x000000008a78dfff] reserved
Sep 15 17:59:49 Anton-AcerAspireE15 kernel: BIOS-e820: [mem 0x000000008a78e000-0x000000008ae7dfff] ACPI NVS
Sep 15 17:59:49 Anton-AcerAspireE15 kernel: BIOS-e820: [mem 0x000000008ae7e000-0x000000008aefdfff] ACPI data
Sep 15 17:59:49 Anton-AcerAspireE15 kernel: BIOS-e820: [mem 0x000000008aefe000-0x000000008aefefff] usable
Sep 15 17:59:49 Anton-AcerAspireE15 kernel: BIOS-e820: [mem 0x000000008aeff000-0x000000008fffffff] reserved
Sep 15 17:59:49 Anton-AcerAspireE15 kernel: BIOS-e820: [mem 0x00000000e0000000-0x00000000efffffff] reserved
Sep 15 17:59:49 Anton-AcerAspireE15 kernel: BIOS-e820: [mem 0x00000000fd000000-0x00000000fe7fffff] reserved
Sep 15 17:59:49 Anton-AcerAspireE15 kernel: BIOS-e820: [mem 0x00000000fec00000-0x00000000fec00fff] reserved
Sep 15 17:59:49 Anton-AcerAspireE15 kernel: BIOS-e820: [mem 0x00000000fed00000-0x00000000fed00fff] reserved
Sep 15 17:59:49 Anton-AcerAspireE15 kernel: BIOS-e820: [mem 0x00000000fed10000-0x00000000fed19fff] reserved
Sep 15 17:59:49 Anton-AcerAspireE15 kernel: BIOS-e820: [mem 0x00000000fed84000-0x00000000fed84fff] reserved
lines 1-39

**Comment by Ultracard** [comment]
when i type
grep -i razer_mount
nothing happens

**Comment by Ultracard** [comment]
do you need the complete output of
sudo journalctl -b 
because it continues like that forever

**Comment by z3ntu** [comment]
It is supposed to be one command, but it's possible that nothing is outputted.
What's the output of `lsusb | grep 1532` ? This command should list all Razer devices connected to your PC.

**Comment by Ultracard** [comment]
the output is Bus 001 Device 008: ID 1532:0221 Razer USA, Ltd

**Comment by Ultracard** [comment]
Now it works, i just rebootet my pc and it worked. thanks for your help. It think i just forgot to reboot my pc. sorry, I should have thought about that before.
