### ISSUE TITLE
Catching keyboard events in Windows

### ISSUE THREAD

**Issue by comandante-fidel** [openrazer/openrazer#688]
Hello! It's not an openrazer issue, but a question for developers and community. Can I use in some way openrazer developments to catch keyboard events in Windows? I need to know which key was pressed (actual physical key ID, not key code which can be easily remapped). I hear it's difficult because Windows does not allow third-party apps to directly read HID data, but if Synapse can, may be I can too? Thank you.

(I know openrazer is not 100% crossplatform, and reading HID data in Windows is not the same like in Linux-based OS)

**Comment by z3ntu** [comment]
I have zero knowledge about driver on Windows and neither does anyone else in the team as far as I know. Sorry.
