### ISSUE TITLE
Debian 9 failed to start daemon

### ISSUE THREAD

**Issue by jimbowarrior** [openrazer/openrazer#691]
Hello,

fresh install from apt, I try to start daemon ang I get this error message 

    openrazer-daemon -Fv

`Traceback (most recent call last):
  File "/usr/bin/openrazer-daemon", line 177, in <module>
    run()
  File "/usr/bin/openrazer-daemon", line 172, in run
    logger=logger)
TypeError: __init__() got an unexpected keyword argument 'chdir'`

**Comment by z3ntu** [comment]
Did you add the proper Debian repository? If yes, an apt upgrade should update the dependency python3-daemonize

**Comment by jimbowarrior** [comment]
I installed from apt : deb http://download.opensuse.org/repositories/hardware:/razer/Debian_9.0/ /
apt update
apt dist upgrade

all is up to date, all dependency seems allready installed ....

**Comment by z3ntu** [comment]
What version of python3-daemonize do you have installed?

**Comment by jimbowarrior** [comment]
aptitude install python3-daemonize=2.4.7-1
after this comment my Debian upgrade this package
Now I can setup my keyboard from Polychromatic but light stay off
