### ISSUE TITLE
No driver support for new razer blade 2018

### ISSUE THREAD

**Issue by herzcthu** [openrazer/openrazer#692]
I just bought new 2018 razer blade. No driver support in polychromatic, razerGenie and razerCommander.
I followed this link https://github.com/openrazer/openrazer/wiki/Troubleshooting
I don't see any error.
I can see my razer keyboard in lsusb
Bus 001 Device 004: ID 1532:0233 Razer USA, Ltd 
How to troubleshoot further or how do I make this works?

**Comment by z3ntu** [comment]
Duplicate of #605
