### ISSUE TITLE
Razer Blackwidow Stealth

### ISSUE THREAD

**Issue by nikospaz** [openrazer/openrazer#694]
It stopped working and the keyboard is recognized as BlackWidow Ultimate

**Comment by z3ntu** [comment]
You have the device 1532:011B ?

**Comment by nikospaz** [comment]
No, I think is the 0214

Στάλθηκε από το iPhone μου

12 Οκτ 2018, 15:07, ο χρήστης «Luca Weiss <notifications@github.com<mailto:notifications@github.com>>» έγραψε:


You have the device 1532:011B ?

**Comment by z3ntu** [comment]
Can you make a photo of the bottom of your keyboard with the label?

**Comment by nikospaz** [comment]
[image1.jpeg]

Στάλθηκε από το iPhone μου

13 Οκτ 2018, 16:13, ο χρήστης «Luca Weiss <notifications@github.com<mailto:notifications@github.com>>» έγραψε:


Can you make a photo of the bottom of your keyboard with the label?

**Comment by z3ntu** [comment]
It literally says `[image1.jpeg]`, I guess GitHub doesn't forward image attachments. You can attach the image directly on GitHub or upload it to some image hoster and paste the URL here.

**Comment by nikospaz** [comment]
https://ibb.co/fqtDtp

Στάλθηκε από το iPhone μου

13 Οκτ 2018, 16:58, ο χρήστης «Luca Weiss <notifications@github.com<mailto:notifications@github.com>>» έγραψε:


It literally says [image1.jpeg], I guess GitHub doesn't forward image attachments. You can attach the image directly on GitHub or upload it to some image hoster and paste the URL here.

**Comment by z3ntu** [comment]
Well it seems that the Ultimate and the Ultimate Stealth are the same internally. I don't see what should be wrong here.

**Comment by nikospaz** [comment]
Thank you very much I will uninstall and reinstall everything and I will tell you!!

Στάλθηκε από το iPhone μου

13 Οκτ 2018, 17:59, ο χρήστης «Luca Weiss <notifications@github.com<mailto:notifications@github.com>>» έγραψε:


Well it seems that the Ultimate and the Ultimate Stealth are the same internally. I don't see what should be wrong here.
