### ISSUE TITLE
Openrazer unable to find Razer Blade Stealth (Early 2017)

### ISSUE THREAD

**Issue by gragundier** [openrazer/openrazer#701]
The daemon works fine.  Even though I'm on arch linux, I didn't seem to have rebuild the packages.
However, when I try `python3 -c "from openrazer.client import DeviceManager; a = DeviceManager(); print(a.devices)"`
I get output: []
So, the problem is laptop isn't being detected.  The part I am new to and need help with is on how to fix this problem or determine if I can fix it at all.

**Comment by z3ntu** [comment]
Does `sudo modprobe razercore` output anything?

**Comment by gragundier** [comment]
`modprobe: FATAL: Module razercore not found in directory /lib/modules/4.18.14-arch1-1-ARCH`
and thank you in advance.

**Comment by z3ntu** [comment]
`sudo dkms install openrazer-driver/2.4.0` ?

**Comment by gragundier** [comment]
`[sudo] password for gragundier: 

Creating symlink /var/lib/dkms/openrazer-driver/2.4.0/source ->
                 /usr/src/openrazer-driver-2.4.0

DKMS: add completed.
Error! echo
Your kernel headers for kernel 4.18.14-arch1-1-ARCH cannot be found at
/usr/lib/modules/4.18.14-arch1-1-ARCH/build or /usr/lib/modules/4.18.14-arch1-1-ARCH/source.
`

**Comment by z3ntu** [comment]
Read the message and install your kernel headers :)

**Comment by gragundier** [comment]
OHhhhhhhhh thx.
