### ISSUE TITLE
BlackWidow TE Chroma V2 support

### ISSUE THREAD

**Issue by nkeor** [openrazer/openrazer#702]
Hi! I don't know if this is the place to ask, but I'm thinking of buying a new keyboard, and as I use Linux, I need it to work well. I've seen that the BlackWidow TE Chroma is supported, but the v2 has a wrist rest, and I didn't see the BlackWidow TE Chrome V2 in the supported devices page. It's because it's almost like the previous, or like the non-TE edition, or it's not working?

Thanks! And great job with OpenRazer!

**Comment by z3ntu** [comment]
Looking through old issues this device should be supported as `Razer BlackWidow Tournament Edition Chroma | 1532:0209`
