### ISSUE TITLE
Device Not Recognised

### ISSUE THREAD

**Issue by tycruickshank** [openrazer/openrazer#703]
Hello, I'm getting a 'device not recognized' error when running polychromatic. I'm running Fedora 28 and I'm fairly new to Linux. 
![image](https://user-images.githubusercontent.com/4993479/47610538-70b25c00-da0c-11e8-9f0f-2bad7ba754d1.png)

I have a Death Adder Elite and a Black Widow Ultimate.

I have installed openrazer and polychromatic by adding the repository `dnf config-manager --add-repo http://download.opensuse.org/repositories/hardware:razer/Fedora_28/hardware:razer.repo` and by installing openrazer `dnf install openrazer-meta kernel-devel`. I ran them both as root using sudo.

I've looked through a lot of open and closed issues relating to this on github, but I haven't found a solution that works.

When I run `sudo dkms install openrazer-driver/2.4.0`
I get the output
`Module openrazer-driver/2.4.0 already installed on kernel 4.18.16-200.fc28.x86_64/x86_64`

When I run `sudo modprobe razerkbd`
I get
`modprobe: ERROR: could not insert 'razerkbd': Operation not permitted`

Running `openrazer-daemon -Fv`
outputs `Unable to lock on the pidfile.`

Can anybody offer any help? I'm not sure what to do next.

**Comment by z3ntu** [comment]
Disable secure boot.

**Comment by tycruickshank** [comment]
I'm currently dual booting this machine with windows 10. Can disabling secure boot potentially hose the windows install? When I go to disable it in the UEFI menu I get a warning that I may need to reinstall the OS.

**Comment by lah7** [comment]
Disabling secure boot won't be a problem, it's only [re-enabling it](https://docs.microsoft.com/en-us/windows-hardware/manufacture/desktop/disabling-secure-boot) which may require re-installation of Windows as it warns. There are _advanced workarounds_ out there to re-enable secure boot without data loss should you choose to do so.

The only alternate is to sign the DKMS modules in Fedora yourself to fix the `Operation not permitted` error, but we have don't have sufficient documentation on the matter.

**Comment by tycruickshank** [comment]
Thanks for getting back to me regarding this. I'll look into disabling secure boot again. I just recently did a fresh install of windows on that separate partition and haven't had a chance to do a full backup. Once I back it up I'll try disabling secure boot. 

Once secure boot is disabled, can I re-enable it once I get open razer running or is it something I would need to leave off?

**Comment by lah7** [comment]
It would need to remain disabled in order to use the OpenRazer driver.

Secure boot simply prevents unsigned code from being loaded into the kernel. Since OpenRazer uses DKMS to compile the driver against your computer's installed kernel, you'd either need to sign it yourself or disable the "secure boot" feature.

**Comment by tycruickshank** [comment]
Thanks so much for the help! For the time being I don't want to disable "secure boot" on this particular machine until I get a new external drive for backups.

**Comment by z3ntu** [comment]
Closing this issue then.
