### ISSUE TITLE
Fedora 29 Repository Unavailable/Unlisted

### ISSUE THREAD

**Issue by Orochikaku** [openrazer/openrazer#707]
On the [project page](https://openrazer.github.io/#download), under Fedora there are only repos for 27 and 28. The current version of Fedora is 29

**Comment by z3ntu** [comment]
Thanks for the report. Even though the openSUSE Build Service currently has some kind of problem and everything is super slow, I have managed to enable builds for Fedora 29. 

Hopefully soon the builds will get published - check at https://download.opensuse.org/repositories/hardware:razer/ if there's a `Fedora_29` folder - and then follow the instructions on the website but adjust the URL for Fedora 29. :)

**Comment by ctrl-alt-d** [comment]
Just upgrade to Fedora 29 using your instructions. All running. Thanks.

**Comment by z3ntu** [comment]
Adjusted the website to list Fedora 29. Fixed!
