### ISSUE TITLE
forum/mailing list and a question: keys-rebinding on Blackwidow

### ISSUE THREAD

**Issue by ag88** [openrazer/openrazer#717]
hi Devs,
thanks for putting together this great work, i just bought a Blackwidow Ultimate 2016 and stumbled into this. I've got some questions
1) forum / mailing list / google group / facebook group etc
other than this issues list is there a forum / mailing list / google group / facebook group where this (openrazer and related issues) is being discussed? I did some google searches but has not found any particular forums / mailing lists for discussions related to this.

2) keys rebinding
i made an attempt to install openrazer on my Opensuse linux system, but there are some missing dependencies as my distribution is too old. that aside, i've browsed the issues list and searched previous issues related to keys rebinding.

the closest i found are macros, there are some really good codes in the daemon that deals with the macros
[macro.py](https://github.com/openrazer/openrazer/blob/master/daemon/openrazer_daemon/misc/macro.py)
[key_event_management.py](https://github.com/openrazer/openrazer/blob/master/daemon/openrazer_daemon/misc/key_event_management.py)

however, am i correct to say that macros basically records the key sequences and are stored on the host / pc? that would be quite similar to keys rebinding/shortcuts say in KDE.

i'm actually hoping to redefine some keys on the keyboard itself, in particular i've had an old keyboard that has a 'power' key, pressing that key surprisingly sends a powerdown keycode in both Linux and Windows environment. this is different from macros as the binding needs to be done within the  keyboard rather than in the OS as the macros would be 'lost' when i reboot into windows.

is keys rebinding (i.e. a key sequence sends a different keycode or keycode sequences) possible on Razer (Blackwidow (Ultimate)) keyboards?

**Comment by z3ntu** [comment]
No, key rebinding isn't supported on any device. Macros should mostly work but no guarantees :wink: 

We don't have a mailing list, GitHub issues or our community chat are the ways of communication. I've actually set up a test mailing list at lists.sr.ht: https://lists.sr.ht/~z3ntu/openrazer ~~(funnily enough, sr.ht currently has an outage so you might have to wait a bit for the site to work again)~~

**Comment by ag88** [comment]
thanks! given that things has evolved till date and that Blackwidow Ultimate (an early edition it seemed)
https://www.flickr.com/photos/mondalaci/5647291879/in/album-72157626562246038/
apparently uses a Freescale/NXP MC9S08JM16 
https://cache.nxp.com/docs/en/data-sheet/MC9S08JM16.pdf
which has only 16k flash and 1k sram, the firmware i'd guess would need all that resources to handle usb and a static keymap
it would seem that the functionality of storing remapped keys may not be available after all given the very limited resources on the mcu, i.e. the keyboards possibly couldn't do on-board key remapping

**Comment by z3ntu** [comment]
Closing for now.
