### ISSUE TITLE
GUI not showing fully

### ISSUE THREAD

**Issue by dackdel** [openrazer/openrazer#718]
![screenshot from 2018-11-24 18-56-45](https://user-images.githubusercontent.com/380951/48968811-f250d600-f01a-11e8-95c6-b21f468a4ef1.png)
My device is supported but the gui doesnt show up fully. I have tried scaling up and down the application and restarting but doesn't work. But polychromatic itself works with the few settings i can choose from.

**Comment by z3ntu** [comment]
This issue belongs into https://github.com/polychromatic/polychromatic . Please report it there.
