### ISSUE TITLE
Does this support mouse macros?

### ISSUE THREAD

**Issue by Bilge** [openrazer/openrazer#720]
Does this support mouse macros, such that it is possible to bind mouse buttons to keyboard inputs, such as `F5` or `CTRL+SHIFT+TAB`, for example?

**Comment by z3ntu** [comment]
No, not that I know of.

**Comment by Bilge** [comment]
Perhaps you'd like to convert this into a feature request instead, then?

**Comment by z3ntu** [comment]
I think that we do have open issues for key rebinding / macro support which I won't implement myself because of 1. Missing knowledge, 2. Lack of motivation (I don't have a personal use case for macros and key rebinding) and 3. Lack of time :)
