### ISSUE TITLE
FreeBSD support

### ISSUE THREAD

**Issue by BryanNoller** [openrazer/openrazer#723]
Is is possible to get this supported for FreeBSD?

**Comment by z3ntu** [comment]
No, OpenRazer uses a kernel module specific to the Linux kernel. Of course you could try porting the code over to the FreeBSD equivalent but I don't think that you will have a good time doing that.

But what you can try to do is get my [razer_test](https://github.com/z3ntu/razer_test) project running on FreeBSD which is using hidapi for communication with the devices. And hidapi does have a libusb backend for FreeBSD, so it could work (it definitely compiles at least: see https://builds.sr.ht/~z3ntu/job/13160).

**Comment by z3ntu** [comment]
Hey again,
I've tested it yesterday and that razer_test project of mine works fine on GhostBSD
![image](https://user-images.githubusercontent.com/3768500/54086995-1d073600-434f-11e9-9e25-3a5a0f1cb243.png)
