### ISSUE TITLE
Rayer Huntsman and rayer mamba elite

### ISSUE THREAD

**Issue by b5i** [openrazer/openrazer#730]

**Comment by z3ntu** [comment]
Yes...?

**Comment by tildearrow** [comment]
He probably means missing support.

**Comment by b5i** [comment]
OK Thanks

**Comment by z3ntu** [comment]
Mamba Elite is #693 and Huntsman is #739

**Comment by b5i** [comment]
Thanks ...


Le mar. 15 janv. 2019 à 18:00, Luca Weiss <notifications@github.com> a
écrit :
