### ISSUE TITLE
How to set dip and led on DeathAdder Chroma that is not being detected?

### ISSUE THREAD

**Issue by pateldhruv1993** [openrazer/openrazer#732]
So I got suckered into buying this Deathadder chroma mouse from ebay. Although the mouse works fine, it is not being detected by Synapse or polychromatic or RazerGenie. So I was wondering if there is a way to set DPI and other settings by manually choosing my device. And what would be the commands for it?

I have a VMware running with Ubuntu and openrazer installed. Also, I'm guessing the changed settings would persist even after I close down VMware? And won't need to redo the process after a restart?

**Comment by z3ntu** [comment]
What's the output of the command `sudo dkms install openrazer-driver/2.4.0` ?

**Comment by pateldhruv1993** [comment]
> Module openrazer-driver/2.4.0 already installed on kernel 4.15.0-29-gen64

**Comment by pateldhruv1993** [comment]
> What's the output of the command `sudo dkms install openrazer-driver/2.4.0` ?

`Module openrazer-driver/2.4.0 already installed on kernel 4.15.0-29-gen64`

**Comment by z3ntu** [comment]
What about `sudo modprobe razerkbd; lsmod | grep razer` ?

**Comment by pateldhruv1993** [comment]
> What about `sudo modprobe razerkbd; lsmod | grep razer` ?
```
razerkbd               57344  0
hid                   118784  3 hid_generic,usbhid,razerkbd

```

**Comment by z3ntu** [comment]
What about `openrazer-daemon -Fv` ?

**Comment by pateldhruv1993** [comment]
Unable to lock on the pidfile.

**Comment by z3ntu** [comment]
`lsusb | grep 1532`

Also, did you try rebooting?

**Comment by pateldhruv1993** [comment]
That command didnt result in any output at all.

I'm on a VM so I've rebooted and shut it down multiple times

**Comment by z3ntu** [comment]
If the lsusb (with the grep) doesn't output anything, then no Razer device is connected to the PC.

**Comment by pateldhruv1993** [comment]
Thats what I'm saying. I have a razer mouse with thrid party components in it. Which makes it "invisible" to synapse. I was wondering if there is a way for one of these third party drivers to change my mouse settings as synapse cannot. I talked to razer support and they said my serial number has been used too many times and that is why synapse cannot detect it. So maybe there is a way?

**Comment by z3ntu** [comment]
If the USB VID/PID is not correct, there's nothing I can do about it.
