### ISSUE TITLE
Razer Taipan not properly supported

### ISSUE THREAD

**Issue by Bilge** [openrazer/openrazer#735]
I am using Ubuntu 18.04 LTS which I believe uses the Gnome shell. With the Razer Taipan I am trying to:

* Remap buttons and
* Bind keyboard macros to buttons

I understand it is not a project goal to provide the ability to remap or bind buttons to macros, but I was hoping the driver would be a key piece to solving this puzzle.

Out of the box, **without installing OpenRazer**, this 9-button mouse has the following characteristics:

* Left, right and middle click (including scroll wheel) work as expected in all applications. :ballot_box_with_check: 
* The top button pair (below the scroll wheel) control the mouse sensitivity, but are not captured by `xev`. That is, they emit  no key press events. :x: 
* The two left-hand and right-hand button pairs move forward and backwards in the browser history. However, only the left-hand pair are supposed to do this. `xev` shows both the left and right pair have identical button codes (8 and 9), therefore it is impossible to bind them to separate functions. :x:

**After installing OpenRazer**, absolutely nothing changes except:

* The top button pair now show key press and release events in `xev`. :ballot_box_with_check: 
* The upper button of the top button pair opens the Gnome settings dialog. :x:
* The lower button appears to be bound to some function (`XF86Launch5`), however this appears to have no effect. :x:
* The top button pair still modify mouse sensitivity. :x:

That is, besides making some changes to the behaviour of the top button pair, the driver appears to have no other effect. The fact that it opens the settings menu when the upper button is pressed, with seemingly no way to reconfigure this, is incredibly inconvenient when that's not a function the user wants.

At the very minimum, I'd hope this driver would emit unique key codes for each button of the mouse, however that is currently not the case.

I am highly motivated in getting this issue resolved, and to that end, if any developer is willing to work with me to resolve this I will provide any and all information needed to help improve the driver.

**Comment by tildearrow** [comment]
See #167 for a probably related issue.

**Comment by Bilge** [comment]
Based on what I've learned from [reading](https://askubuntu.com/a/174416/322589) around on the web, it seems the mouse operates in a dumbed down mode by default where half the buttons do not even generate hardware events like they're supposed to. It continues in this fashion until it receives a secret USB message from the Synapse driver to switch it into "driver mode", whereafter it correctly sends the normal hardware events for each button press. It seems OpenRazer could, and most likely should, send this USB message to switch the mouse mode, whereafter it would be trivial to bind custom macros with standard tools such as xbindkeys. Of course, a developer would need to have access to USB debugging tools and the specific hardware in order to track down the correct bytes that comprise this "secret message" for the Taipan.

**Comment by H4HS-Shadow** [comment]
Check out qrazercfg, which may help address the issue, since it appears that the Taipan mouse support status is "Stable": https://bues.ch/cms/hacking/razercfg.html

**Comment by Bilge** [comment]
>Razercfg does only offer options for features supported by the actual hardware of the mouse. So if the hardware does not support button remapping for example, razercfg will not offer button options, even if the windows driver does. 

They only support some rudimentary profile options which are not remotely relevant to getting Linux to recognize all hardware inputs.

**Comment by z3ntu** [comment]
@Bilge What you described as the "secret message" is documented at https://github.com/openrazer/openrazer/wiki/Using-the-keyboard-driver#device_mode---set-device-mode

**Comment by Bilge** [comment]
@z3ntu That's very interesting, although it comes a little late as I had given up hope.

A few hours ago I ordered a different mouse that saves profiles to the device. It saves the entire key map and emits key presses directly from the hardware instead of relying on the software driver, so it works on any OS, including Linux.

**Comment by z3ntu** [comment]
Yep that's much nicer :) You might be interested in https://github.com/libratbag/libratbag for that mouse

**Comment by Bilge** [comment]
@z3ntu Are you sure that page is even relevant to mice? The page is titled, *Using the keyboard driver*. Are you sure it works for mice too, and specifically the Taipan?

**Comment by z3ntu** [comment]
Doesn't matter. Razer devices are mostly the same (at least firmware-wise) but have the "methods" available that are needed for a device (so e.g. a mouse also has DPI, poll rate stuff, keyboard has the keyboard-layout call etc)

**Comment by Bilge** [comment]
I was able to apply `echo -n -e "\x03\x00" > device_mode` to the Taipan successfully. The consequence of this change is that the right-side button pair no longer mirror the left-hand button pair, which is good. However, the right-side buttons still do not emit button presses, but rather, key code events. Specifically:

* Near right-side button emits: `keycode 193 (keysym 0x1008ff46, XF86Launch6)`
* Far right-side button emits: `keycode 194 (keysym 0x1008ff47, XF86Launch7)`

In addition, the top buttons no longer modify DPI (mouse sensitivity). They also emit key codes, as before:

* Near top-side button emits: `keycode 192 (keysym 0x1008ff45, XF86Launch5)`
* Far top-side button emits: Unknown; still launches Gnome settings dialog (keypress seems to be intercepted by Gnome at a lower level than XInput system.)

All other buttons behave the same way as before. It may now be possible to bind custom actions to keycodes 192-194, although I currently do not know how to do this; hitherto I have been mapping button numbers only. I also need to find a way to stop Gnome intercepting the far top-side button.

**Comment by dia-susca** [comment]
> @z3ntu That's very interesting, although it comes a little late as I had given up hope.
> 
> A few hours ago I ordered a different mouse that saves profiles to the device. It saves the entire key map and emits key presses directly from the hardware instead of relying on the software driver, so it works on any OS, including Linux.

Hi, can you please tell me what mouse you ordered?

Have been trying to map taipan keys for ages, and I've waited patiently for a potential driver, but now I've had enough. I need a mouse with 4 extra keys that I can map to copy/paste/cut/enter in Ubuntu 18.04.

**Comment by Bilge** [comment]
Lancehead. But it's discontinued now so you will have to pay a premium to get a new one. Probably the last good mouse Razer will ever make.
