### ISSUE TITLE
Firefly RGB shuts off after a minute

### ISSUE THREAD

**Issue by rusemd** [openrazer/openrazer#736]
Using Ubuntu 18.04, default DE. The software, with Polychromatic as the front end, correctly detected my Deathadder Elite and Firefly, and there are no issues using the software.

However, after about a minute, the lights on the Firefly shut off completely. Changing any of the settings for it or restarting the daemon will cause it to light up again, but only for another minute before the process needs to be repeated.

This continues across reboots.

**Comment by rusemd** [comment]
I'm not sure if this was seen or not or if an update was pushed out to fix this, but I am no longer having this issue. Thanks for making this software, it's working great now!

Edit: nope, I was wrong. Either the issue was fixed and then some update brought it back, or something else on my machine was changed.

**Comment by nightsky30** [comment]
I'm seeing this randomly with my firefly.  Today my firefly shut off the LEDs after about 5 minutes after I set all 3 devices to static blue.  The keyboard and mouse remained lit.  Selecting an effect caused the firefly to light up again.  Now it's been 10 minutes and the firefly is still lit.

There's nothing in the logs indicating an issue.

There could be something going on here.  Can this issue be reopened?

**Comment by z3ntu** [comment]
Sounds like maybe the kernel shuts down the USB port for power saving.

**Comment by rusemd** [comment]
I've reopened it. I don't think whatever I thought fixed it actually did. I've been away from my pc since I opened this issue and it seems to still be a problem for me. I set everything to a static color as well.

I'll see if it's USB power saving or something else.

**Comment by nightsky30** [comment]
@miqued Thanks! :D

@z3ntu I do have my firefly plugged into a bluish USB port on the back of my desktop.  Maybe it gets special power treatment??

Hmmm, the blue USB port is a separate USB 3.1 Gen2 (10Gbps).  All other USB ports on the back are USB 3.1 Gen1 (5Gbps).  I swapped another device from the gen 1 port to the gen 2 to see if the behavior continues with all three Razer devices on gen 1.

Nope, didn't fix it.  The firefly did it again within 5 minutes of being plugged into the USB 3.1 Gen1 (5Gbps) port.  Did find this though...

> power/control
> 
> This file contains one of two words: on or auto. You can write those words to the file to change the device’s setting.
> 
> on means that the device should be resumed and autosuspend is not allowed. (Of course, system suspends are still allowed.)
> auto is the normal state in which the kernel is allowed to autosuspend and autoresume the device.

Device
```
$ cat /sys/bus/usb/devices/usb1/1-2/idProduct 
0c00
$ cat /sys/bus/usb/devices/usb1/1-2/power/control 
on
$ cat /sys/bus/usb/devices/usb1/1-2/power/autosuspend
2
$ cat /sys/bus/usb/devices/usb1/1-2/power/autosuspend_delay_ms
2000
```
But...the port
```
$ cat /sys/bus/usb/devices/usb1/1-2/port/power/control 
auto
```

**Comment by nightsky30** [comment]
So I'm wondering if all ports are set to auto by default, and the reason the firefly port is powered off is because there isn't constant traffic flowing through it when the effect is set to static.  I would think the firefly isn't sending/receiving anything else after the effect is set.  If the firefly effect were set to spectrum or wave, then the traffic should in theory keep the port active and powered.  The keyboard and mouse produce traffic through movement and key press events besides lighting information.  So those ports get enough throughput to remain powered even with static lighting.

Does this sound crazy?

Could a udev rule or some tweak to the daemon set the firefly ../port/power/control setting to "on" when the device is plugged in?

**Comment by terricain** [comment]
So if the firefly is set to wave it shuts off after minute?

**Comment by nightsky30** [comment]
So far I've only seen it cut out while on static.

Trying wave now, though I'm not seeing constant traffic on that effect like I thought I would.  Does the device produce the effect on its own?

**Comment by terricain** [comment]
Yeah there are hardware effects which don't do much usb communication. From first glance it looks like the device is idling and being put to sleep

**Comment by nightsky30** [comment]
So far if set to spectrum or wave the firefly seems to stay awake.  I've tried static with different colors, and for some strange reason it only seems to sleep when it's in a blue hue.  And that makes no sense.  Maybe there is some other circumstance I'm missing.

@miqued Can you get it to fall asleep with a static color other than a blue hue?

**Comment by rusemd** [comment]
I've only ever had it on with white. I can try other colors tomorrow, about 15-16 hours from now. But yeah, static white had it shutting off for me.

Edit: I must've accidentally closed the issue since I'm using my phone's browser. Apologies for any confusion.
