### ISSUE TITLE
Razer Huntsman 1532:0227

### ISSUE THREAD

**Issue by olajmuvek** [openrazer/openrazer#739]
Hy there.

I want to use my Razer Huntsman keyboard Lighting functions. It's the cheaper version of Razer Huntsman Elite.
My version of keyboard, (lsusb : 1532:0227 Razer USA, Ltd ) isn't have memory for RGB program.
PLease tell me how can i use it with openrazer Debian Linux. The daemon is running correctly, but not recognize my device.
What can i do? Please help me with support.
[openrazer-daemon.log](https://github.com/openrazer/openrazer/files/2695998/openrazer-daemon.log)
 
Thanks

**Comment by olajmuvek** [comment]
lsusb  log
[lsusb.log](https://github.com/openrazer/openrazer/files/2696236/lsusb.log)

**Comment by z3ntu** [comment]
* Please post the output of
`ls -lah /dev/input/by-id/`
* Read [this](https://github.com/openrazer/openrazer/wiki/Reverse-Engineering-USB-Protocol) because we probably need packet captures.
* Screenshots of all available options on Razer Synapse are needed.
* And lastly, the product & model number of the device for documentation reasons please.

**Comment by Spenk009** [comment]
I'd like to second the request. Here's at least some info requested: 
```
jezzer@Home:~$  ls -lah /dev/input/by-id/
total 0
drwxr-xr-x 2 root root 180 Dec 25 08:31 .
drwxr-xr-x 4 root root 440 Dec 25 08:31 ..
lrwxrwxrwx 1 root root   9 Dec 25 08:31 usb-Logitech_Gaming_Mouse_G402_6D74429A5456-event-mouse -> ../event2
lrwxrwxrwx 1 root root   9 Dec 25 08:31 usb-Logitech_Gaming_Mouse_G402_6D74429A5456-if01-event-kbd -> ../event3
lrwxrwxrwx 1 root root   9 Dec 25 08:31 usb-Logitech_Gaming_Mouse_G402_6D74429A5456-mouse -> ../mouse0
lrwxrwxrwx 1 root root   9 Dec 25 08:31 usb-Razer_Razer_Huntsman-event-kbd -> ../event4
lrwxrwxrwx 1 root root   9 Dec 25 08:31 usb-Razer_Razer_Huntsman-if01-event-kbd -> ../event5
lrwxrwxrwx 1 root root   9 Dec 25 08:31 usb-Razer_Razer_Huntsman-if02-event-mouse -> ../event6
lrwxrwxrwx 1 root root   9 Dec 25 08:31 usb-Razer_Razer_Huntsman-if02-mouse -> ../mouse1
```
Product number is 'RZ03-02520400-R3G1' and Model number RZ03-0252. This is a German layout (qwertz with äöü).
I've tried capturing key presses left to right of the ctrl row in wireshark, the result is here: http://gofile.me/28Rsd/n7Q4wr3RN

If there is a routine or specific format you would like to receive these let me know. Merry Christmas!

**Comment by Spenk009** [comment]
Here are screenshots of the software with the keyboard connected:
[https://imgur.com/a/bkLDw5e](https://imgur.com/a/bkLDw5e)

**Comment by bfreetech** [comment]
I'm new to all this but I'd like to add my request for Razer Huntsman support. the ID is 1532:0227. It looks like the Huntsman Elite is already supported, so maybe they share the same drivers. Huntsman Elite is 1532:0226, which I found here: https://github.com/openrazer/openrazer#device-support. I'll try to do a packet capture and post it here shortly.

**Comment by tommyjcarpenter** [comment]
Hi,

Also coming into this thread. I bought this exact keyboard: https://smile.amazon.com/gp/product/B07DHNZ676/ref=ppx_yo_dt_b_asin_title_o00_s00?ie=UTF8&psc=1

Item number is RZ03-02520200-R3U1

However only my Chroma Mouse shows up in polychromatic. Looks like huntsman isn't shown.

Here is the ls I see above:

```
 ~/GoogleDrive  ls -lah /dev/input/by-id/                                                                                                                                                            4327ms  Thu 06 Jun 2019 06:36:44 AM EDT
Permissions Size User Date Modified Name
drwxr-xr-x     - root  6 Jun  6:05  .
drwxr-xr-x     - root  6 Jun  6:05  ..
lrwxrwxrwx    10 root  6 Jun  6:05  usb-Razer_Razer_DeathAdder_Chroma-event-mouse -> ../event23
lrwxrwxrwx     9 root  6 Jun  6:05  usb-Razer_Razer_DeathAdder_Chroma-if01-event-kbd -> ../event4
lrwxrwxrwx     9 root  6 Jun  6:05  usb-Razer_Razer_DeathAdder_Chroma-if02-event-kbd -> ../event5
lrwxrwxrwx     9 root  6 Jun  6:05  usb-Razer_Razer_DeathAdder_Chroma-mouse -> ../mouse1
lrwxrwxrwx    10 root  6 Jun  6:05  usb-Razer_Razer_Huntsman-event-if01 -> ../event11
lrwxrwxrwx     9 root  6 Jun  6:05  usb-Razer_Razer_Huntsman-event-kbd -> ../event9
lrwxrwxrwx    10 root  6 Jun  6:05  usb-Razer_Razer_Huntsman-if01-event-kbd -> ../event10
lrwxrwxrwx    10 root  6 Jun  6:05  usb-Razer_Razer_Huntsman-if02-event-mouse -> ../event14
lrwxrwxrwx     9 root  6 Jun  6:05  usb-Razer_Razer_Huntsman-if02-mouse -> ../mouse0
```
Please let me know how I can be of more help.

**Comment by z3ntu** [comment]
See #792
