### ISSUE TITLE
Release on snapcraft

### ISSUE THREAD

**Issue by henryruhs** [openrazer/openrazer#742]
Sorry to bother you, but I came across [snapcraft.io](https://snapcraft.io) and tough this might be an valid alternative to simplify the installation process? Related to our discussion in #711

> Snaps are containerised software packages that are simple to create and install.

> Snaps can be used on all major Linux distributions, including Ubuntu, Linux Mint, Debian and Fedora.

Distribution support:

-  Arch Linux
-  Debian
-  Deepin
-  Elementary OS
-  Fedora
-  GalliumOS
-  KDE Neon
-  Linux Mint
-  Manjaro Linux
-  openSUSE
-  Parrot Security OS
-  Raspbian
-  Solus
-  Ubuntu
-  Zorin OS

I guess this interface is interesting for us? https://docs.snapcraft.io/the-uhid-interface/7931

**Comment by z3ntu** [comment]
From what I could find, it's not possible to package kernel modules via dkms with snaps.

**Comment by henryruhs** [comment]
kernel-module-control provides the ability to insert, remove and query kernel modules. This interface gives privileged access to the device.

https://docs.snapcraft.io/the-kernel-module-control-interface/7853

**Comment by z3ntu** [comment]
Contributions welcome! :)
