### ISSUE TITLE
Can't configure Orbweaver

### ISSUE THREAD

**Issue by Quax1102** [openrazer/openrazer#744]
Hi all, I installed Openrazer on Ubuntu 16.04, and after that I installed hte RazerGenie. WHen I open RazerGenie, I see my Orbweaver, but all I can do is to set the Lighting options. Apart from that, there are no other options available, just a blank form (see attached screenshot). I already completely unsinstalled and reinstalled anything, with no effect so far.

Glad if anyone can point me towards a solution ..

Thanks
![bildschirmfoto vom 2018-12-22 13-26-12](https://user-images.githubusercontent.com/34371019/50374367-3b318580-05ed-11e9-9e9e-698fdd38bd52.png)

**Comment by z3ntu** [comment]
Yes, OpenRazer only supports lighting effects (and very limited macro support, but not on the Orbweaver). Unfortunately for macro support and key remapping you have to find other software to satisfy your needs.
