### ISSUE TITLE
Help me please.

### ISSUE THREAD

**Issue by Nautruche** [openrazer/openrazer#745]
Hello I introduce my nickname is Nautruche and I come to ask you how to do when you launch the application RazerGenie, because I receive a message every time that tells me that No device has been detected. Thank you in advance for your assistance.

**Comment by z3ntu** [comment]
Please post the output of `sudo dkms install openrazer-driver/2.4.0`

**Comment by z3ntu** [comment]
I'm going to close this issue because there wasn't been a response for over 30 days. Feel free to reply if you are still experiencing this issue.
