### ISSUE TITLE
Support for Razer Goliathus Chroma

### ISSUE THREAD

**Issue by multiflexi** [openrazer/openrazer#751]
### Device Info

* Name: Razer Goliathus Chroma
* Product Number:  RZ02-02500100-R3M1
* Model Number: RZ02-0250

### Device Information

    lsusb -d 1532: -v

[lsusb.txt](https://github.com/openrazer/openrazer/files/2724731/lsusb.txt)

    ls -lah /dev/input/by-id/

[lscap.txt](https://github.com/openrazer/openrazer/files/2724733/lscap.txt)

### Packet Captures

<Please see here as we probably need packet captures>
<https://github.com/openrazer/openrazer/wiki/Reverse-Engineering-USB-Protocol>

### Synapse Screenshots
<img width="960" alt="synapse" src="https://user-images.githubusercontent.com/11663844/52192934-cb015b00-284c-11e9-86e3-4dc0fb308905.png">

**Comment by Zeroneca** [comment]
Is there any update on this? Or anyone already working on it? If no, I could try to do this (no guarantee I will succeed)

**Comment by z3ntu** [comment]
Support was merged in #796
