### ISSUE TITLE
Blackwidow Ultimate 2016 connected, but not detected

### ISSUE THREAD

**Issue by SpringerJack** [openrazer/openrazer#755]
### Support

- [x] Have you tried rebooting?
- [x] Have you looked at the [Troubleshooting](https://github.com/openrazer/openrazer/wiki/Troubleshooting) page?

I am on the latest Manjaro Gnome. Running `ls  -l /sys/bus/hid/drivers/razer*/0*/ is giving me` is giving me

 >   Bus 001 Device 012: ID 1532:0214 Razer USA, Ltd BlackWidow Ultimate 2016

as an result, but still openrazer doesn't detect it.

**Comment by LetsLeppr** [comment]
I am on the latest Manjaro Gnome. Running `ls -l /sys/bus/hid/drivers/razer*/0*/` is giving me 

> ls -l /sys/bus/hid/drivers/razer*/0*/
as an result, but still openrazer doesn't detect it.

**Comment by z3ntu** [comment]
That `ls` command can't output the text that you have pasted there, that's the output of the `lsusb` command. Could you please try that again?

**Comment by StopMotionCuber** [comment]
I wanted to comment that I also had this issue last week. I don't have this problem anymore, I would guess that it got resolved in an update

**Comment by z3ntu** [comment]
@StopMotionCuber There wasn't an openrazer update in the last 10 days, but maybe a reboot or another update of some other software fixed it for you.

**Comment by z3ntu** [comment]
I'm going to close this issue because there wasn't been a response for over 30 days. Feel free to reply if you are still experiencing this issue.
