### ISSUE TITLE
Can not run daemon on Manjaro Linux 18.0.2

### ISSUE THREAD

**Issue by TzeHimSung** [openrazer/openrazer#763]
I have tried rebooting computer after installing openrazer and polychromatic. But it's still not working.

![screenshot_20190128_120221](https://user-images.githubusercontent.com/31332409/51814167-018f2100-22f5-11e9-88c6-0724e67ab654.png)
![screenshot_20190128_115915](https://user-images.githubusercontent.com/31332409/51814170-0522a800-22f5-11e9-897f-849dce279092.png)

what's wrong with it?

**Comment by lah7** [comment]
Your user account needs to be added to the `plugdev` group, like so:

    sudo useradd -G plugdev $(whoami)

Then log out and log back in to take effect.

**Comment by TzeHimSung** [comment]
> Your user account needs to be added to the `plugdev` group, like so:
> 
> ```
> sudo useradd -G plugdev $(whoami)
> ```
> Then log out and log back in to take effect.

thanks, the problem is solved.
