### ISSUE TITLE
Support for Razer Blade Stealth Late 2018

### ISSUE THREAD

**Issue by MartinPaulEve** [openrazer/openrazer#765]
### Device Info

* Name: Razer Blade Stealth (Late 2018)
* Product 0239

I have added support for this in this pull request https://github.com/openrazer/openrazer/pull/764

**Comment by z3ntu** [comment]
Sorry wrong issue referenced.

**Comment by z3ntu** [comment]
Support for `1532:0239` is present in git master. Closing.
