### ISSUE TITLE
Not work in manjaro Razer Mamba Wireless

### ISSUE THREAD

**Issue by chmodmasx** [openrazer/openrazer#766]
modprobe: FATAL: Module 1532:0045 not found in directory /lib/modules/4.19.16-1-MANJARO
Razer Mamba Wireless

**Comment by z3ntu** [comment]
Please take a look at the linked page and section: https://github.com/openrazer/openrazer/wiki/Troubleshooting#kernel-headers

**Comment by chmodmasx** [comment]
sorryy .I had not understood when I read the information of that url (https://github.com/openrazer/openrazer/wiki/Troubleshooting#kernel-headers)
my english is very bad.
Now workk!! thanks. i just do install linux-header in arch and work fine
