### ISSUE TITLE
DeathAdder Chroma support?

### ISSUE THREAD

**Issue by meraklimaymun** [openrazer/openrazer#77]
Can we please have Razer DeathAdder Chroma support?

**Comment by z3ntu** [comment]
Duplicate of #23 (probably)

And please post your `lsusb` output of your mouse (to make sure it's the same product).

And a version which is mostly working (just the kernel driver and not the daemon) is available on the branch [feature_DeathAdder0x0043](https://github.com/terrycain/razer-drivers/tree/feature_DeathAdder0x0043)

**Comment by artemjackson** [comment]
@z3ntu is it planned to get full DeathAdder support? And if so, when approximately?

**Comment by z3ntu** [comment]
Look at #23 where you can see everything I know.

**Comment by terricain** [comment]
> get full DeathAdder support? And if so, when approximately?

Yes and hopefully before christmas ;)
