### ISSUE TITLE
Blade15 Device Not Recogised

### ISSUE THREAD

**Issue by Aloento** [openrazer/openrazer#770]
![image](https://user-images.githubusercontent.com/11802769/52318047-91bc1d00-29fd-11e9-9a5b-7b7556af2c32.png)

╰─○ lsusb | grep '1532:'
Bus 001 Device 005: ID 1532:0233 Razer USA, Ltd 
Razer Blade 15

**Comment by Aloento** [comment]
sudo modprobe razerkbd
modprobe: FATAL: Module razerkbd not found in directory /lib/modules/4.19.16-1-MANJARO

**Comment by z3ntu** [comment]
If you didn't figure this out: Install your kernel headers (probably `linux419-headers` on Manjaro)
