### ISSUE TITLE
issue "daemon not responding"

### ISSUE THREAD

**Issue by ghost** [openrazer/openrazer#78]
When I opened Polychromatic he said:

**# Daemon Not Responding
Polychromatic could not initialise the daemon. This could be caused by a bug with the daemon processs.
Exception: org.freedsktop.DBus.Error.NoReply: Did noy receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.**

I don't not know what to do.
Pd: I do not have much knowledge in programming, then I need if you help me as if I knew nothing of this

Thank you

**Comment by terricain** [comment]
Contents of ~/.razer-service/logs/razer.log

**Comment by ghost** [comment]
I don't understand what do you said.

**Comment by terricain** [comment]
Upload what is in that file.

**Comment by ghost** [comment]
I do not know what happened, but everything was magically solved. Only one thing, when I apply a change from the keyboard icon of the top bar of Ubuntu, when I restart the machine the changes are not saved there. That's fine?
Sorry if you're bothered by so many questions.

**Comment by terricain** [comment]
Did you reboot by any chance? And yeah setting are not saved after a reboot, for now that's down to whatever app your using to deal with that

**Comment by ghost** [comment]
I reboot the machine when I install it, several times, but there was no case. I don't understand how it worked out now. The only thing that when restart does not save the configuration, but the other excellent.

You are great, thank you very much for the effort to have made this application. Sorry if I disturbed you with my inquiries. My respects

**Comment by terricain** [comment]
No worries and thanks. Yeah I know it doesnt save config yet. I do plan on having something like that but its a long way off yet, I have more devices and easier features to add first :wink:
