### ISSUE TITLE
Support for Da-Dk layout

### ISSUE THREAD

**Issue by AnzoDK** [openrazer/openrazer#780]
I would be nice with support for something that is not just "Generic Nordic" as 07

Besides, you can update 07 to "Da-DK // se-SE // nb-NO"

Image of layout:
![image](https://user-images.githubusercontent.com/22836283/53186676-c33e0680-3601-11e9-8472-1210797cdea3.png)
This should be universal for all 3 languages mentioned above

**Comment by z3ntu** [comment]
Razer literally calls this layout "Nordic Layout" on their store, so there's little I can do.
![image](https://user-images.githubusercontent.com/3768500/53186813-09936580-3602-11e9-8a97-0961b0f92798.png)
