### ISSUE TITLE
You are the best

### ISSUE THREAD

**Issue by pallebone** [openrazer/openrazer#787]
Just amazed at how great this software is. I just installed the stable branch after finding out about it and used it with polychromatic. Never knew it even existed before today. I rebooted and it found my Mamba TE mouse, Kraken 7.1 and Deathstalker straight up on Ubuntu Mint 19.04. Absolutely insane, all just worked and even works better than the official windows software. Lets me change all the colours and everything. I am in awe at this because this stuff never just works under Linux usually. Least configuration ever, works with less trouble than the official software from the official company. Just wow. Speechless. Thank you.

Pete

**Comment by z3ntu** [comment]
Thank you! We really appreciate people finding use out of the software we have spent so much time making :)
