### ISSUE TITLE
v1.0.17 tag doesn't exist on master

### ISSUE THREAD

**Issue by z3ntu** [openrazer/openrazer#80]
v1.0.13 exists on master but not v1.0.17 (that only exists on the branch `stable`). Is that intentional?

**Comment by terricain** [comment]
Hmmmm no. I'll have a look later probs forgot a push --tags

**Comment by z3ntu** [comment]
That's the commit that exists on `master`: https://github.com/terrycain/razer-drivers/commit/6e9b59979fe7a6c03db778cb4bcae247fa748830
The commit that was tagged as `v1.0.17` (on `stable`): https://github.com/terrycain/razer-drivers/commit/cf35f1847c01c1095e695c6ecc16336440458a11

**Comment by terricain** [comment]
Fixed?

**Comment by z3ntu** [comment]
Yes, thanks

```
$ git describe
v1.0.17-22-gf4fdf20
```
