### ISSUE TITLE
I want to support you!

### ISSUE THREAD

**Issue by auipga** [openrazer/openrazer#816]
I want to
a) support you ( @lah7 @terrycain @z3ntu )
b) indicate, which issues are important to me (with some beers)

Please register this repository in [bountysource.com](https://www.bountysource.com), [issuehunt.io](https://issuehunt.io/) or similar.

**Comment by z3ntu** [comment]
I don't think throwing small amounts of money at us will help much (although we appreciate it) :wink: 

We don't have unlimited amounts of time but Razer seems to have unlimited devices, so code contributions are what's helping us most.

If you really want to donate, Terry's PayPal email is in the README and for me it's https://www.paypal.me/z3ntu

Thanks!

**Comment by lah7** [comment]
As @z3ntu said, thanks for your support, but we'd love to have more free time! :clock1:  If you really wish to support me, then that would be supporting [Polychromatic](https://polychromatic.app), one of the front-ends complementing this project. Refer to the [bottom of the README](https://github.com/polychromatic/polychromatic#donations) if you'd really want to drop a few pennies. :smile:

**Comment by auipga** [comment]
Off topic:
I bought another device which is supported right now.
Is it true, that [all apps](https://github.com/openrazer/openrazer#applications) support just the leds but no key mapping, profiles and supershift?

**Comment by lah7** [comment]
Yes, that's correct at this time.

If it's a keyboard, the 3 GUIs (Polychromatic, RazerGenie and razerCommander) support setting static colours per key, but each app may refer to that feature by different names, like "custom effect", "key mapping" or "application profile".

**Comment by auipga** [comment]
Thanks for clarification.
I'm not the blink-blink kinda guy. I just need to change the key layout in a comfortable way.
Is there a solution you can recommend?

**Comment by lah7** [comment]
I've heard from users that they've used [Keyboarding Master](https://sites.google.com/site/keyboardingmaster/) for remapping keys, but I haven't personally used it. [Pystromo](https://github.com/openrazer/openrazer/issues/167#issuecomment-452164735) would look promising, but is outdated and doesn't seem to work.

**Comment by madmalkav** [comment]
I can confirm I have used Keyboarding Master in the past. Works mostly OK, being my only "serious" issue I cannot map "º" to any key of my Nostromo. That's the key left of "1" and up the Tab and it is quite frequent key used to play with ISO keyboards I think.

**Comment by chabad360** [comment]
@auipga currently the only solution I've found that (seems to) work well is [tildearrow/input-modifer](https://github.com/tildearrow/input-modifier), the interface is a bit clunky, and it doesn't seem to be maintained any more. On the plus side, there's no scripting required, and it doesn't rely on Xinput (unlike Keyboarding Master) so it even work without XOrg.
