### ISSUE TITLE
Lighting of mouse buttons bind to keyboard

### ISSUE THREAD

**Issue by codeman101** [openrazer/openrazer#818]
I have a blackwindow x keyboard and Nega mouse. I'm trying to use razergenie as the front end but every time I changed the color of the side number buttons on the mouse it changes the color of the keyboard keys to the same color and vice-versa.

**Comment by z3ntu** [comment]
There should be a checkbox at the bottom of RazerGenie with the label "Sync devices" that you can turn off to stop this behavior. Hope that answers your question.
