### ISSUE TITLE
Razer keyboard not recognized anymore

### ISSUE THREAD

**Issue by arty-hlr** [openrazer/openrazer#832]
### Distribution

Parrot 4.19

### Support

- [x] Have you tried rebooting?
- [x] Have you looked at the [Troubleshooting](https://github.com/openrazer/openrazer/wiki/Troubleshooting) page?

So, after trying without success so far to bind the keyboard devices to the razerkbd driver, I ended up with these devices not even binding to `hid-generic` on start-up, so the keyboard doesn't work at start-up (except for the F10 and F11 keys for the keyboard lighting...).

I managed to write a script that binds the devices to `hid-generic` and have it run at start-up, but that behaviour is still really weird...

Was anyone in that position with a Razer keyboard at some point? I'd be glad for even a hint or a way to get things how they were before!

**Comment by z3ntu** [comment]
Do you maybe still have files left over from the openrazer installation? Especially the udev rule and the razer_mount script?

**Comment by z3ntu** [comment]
Let's continue in #830, no need to open a separate issue
