### ISSUE TITLE
CMakeLists.txt needs to updated for mousemat change.

### ISSUE THREAD

**Issue by aTosser** [openrazer/openrazer#847]
Still references:

set(SOURCES
   5   │         driver/razermouse_driver.c
   6   │         **driver/razerfirefly_driver.c**
   7   │         driver/razerkbd_driver.c
   8   │         driver/razercommon.c
   9   │         driver/razerchromacommon.c
  10   │         )
  11   │
  12   │ set(HEADERS
  13   │         driver/razermouse_driver.h
  14   │         **driver/razerfirefly_driver.h**
  15   │         driver/razerkbd_driver.h
  16   │         driver/razercommon.h
  17   │         driver/razerchromacommon.h
  18   │         )

**Comment by z3ntu** [comment]
Pull request welcome!
I'm not using CMake files, so I never pay attention to them; but I'm tempted to just remove them from the project if they aren't used by other people either.
