### ISSUE TITLE
"Gaming Mode" disable alt-tab

### ISSUE THREAD

**Issue by bauer41s4** [openrazer/openrazer#848]
### Support

- [x] Have you tried rebooting?
- [x] Have you looked at the [Troubleshooting](https://github.com/openrazer/openrazer/wiki/Troubleshooting) page?

Hi when I enable gaming mode via polychromatic, my alt-tab functionality stops working. Oddly enough, it only stops working with the left alt key, right alt-tab still works. Any advice here? I really like the gaming mode feature, but don't want to lose left alt-tab functionality.

**Comment by z3ntu** [comment]
I'm pretty sure this behavior is intended, but you can follow https://github.com/openrazer/openrazer/wiki/Using-the-keyboard-driver#key_alt_tab---alt-tab-key-combo-disable-toggle to enable alt-tab again.

**Comment by bauer41s4** [comment]
When I look in the /sys/bus/hid/drivers/razerkbd directory, there are 3 different folders showing device IDs. Two of which contain the key_alt_tab file. Any idea as to which one I should be editing?

**Comment by tildearrow** [comment]
Try the second one. The first one is used for non-game mode.

**Comment by bauer41s4** [comment]
That worked -- thank you!
