### ISSUE TITLE
fedora_install doesn't support Fedora25

### ISSUE THREAD

**Issue by Havilland** [openrazer/openrazer#86]
Hi,
I just tried to install the razer-drivers on my Blade Stealth with Kaby Lake using Fedora 25. But the make fedora_install just quit with not supported yet. Is there a plan when F25 will be supported?

havilland

**Comment by terricain** [comment]
Tbf it shoudln't be too difficult to add it now. Making proper RPMs and hosting them is another story though as would need somewhere to host them as I dont really want to just keep committing binaries to the repo.

**Comment by terricain** [comment]
Checkout branch `feature_fedorafpm`. then run `make fedora_package` it should result in some RPMs, which may or may not work. I have a feeling the DKMS bit will take some more work.

You'll need `fpm` for it to work so go find that.

Install RPMs, reboot and run `sudo modprobe razerkbd` it should just work, if not then we need to work on dkms

**Comment by z3ntu** [comment]
# OUTDATED!!!!

### Build rpms
```
git clone https://github.com/z3ntu/razer-drivers.git # my fork with all fixes neccessary
cd razer-drivers
# Install fpm
sudo dnf install rubygems ruby-devel libffi-devel redhat-rpm-config rpm-build
gem install fpm
# Set PATH for fpm (has to be done every time you open the terminal or stick it in your `.bashrc` file)
export PATH=$HOME/.gem/ruby/gems/fpm-1.7.0/bin:$PATH
# Make package
make fedora_package
```

### Install the rpms
```
# Add yourself to the `plugdev` group
sudo groupadd --system plugdev
# Please replace <USERNAME> with your username!
sudo gpasswd -a <USERNAME> plugdev
# Install dependencies
sudo dnf install kernel-devel
# Install the actual rpms (built in the last step)
sudo dnf install *.rpm
# Install the dkms package
sudo dkms install razer_chroma_driver/1.0.0
# Theoretically everything should be working after a reboot!
```

### How to install **manually** (**NOT RECOMMENDED**)

(install all updates before doing this)
```
git clone https://github.com/terrycain/razer-drivers.git
cd razer-drivers
# Install dependencies
sudo dnf install kernel-devel python3-setproctitle python3-numpy
sudo pip3 install notify2
# Compile
sudo make -s all install
# Add yourself to the `plugdev` group
sudo groupadd --system plugdev
# Please replace <USERNAME> with your username!
sudo gpasswd -a <USERNAME> plugdev
# Reboot and everything should be working as expected. Tested on a fresh Fedora 25 install in QEMU.
```

### Unrelated (but useful for debugging)
```
razer-service --foreground --verbose --run-dir ~/.razer-service/data --log-dir ~/.razer-service/logs --pid-file ~/.razer-service/daemon.pid
```

**Comment by terricain** [comment]
We have proper rpms now. see website - https://terrycain.github.io/razer-drivers/
