### ISSUE TITLE
Support for Deathadder v1

### ISSUE THREAD

**Issue by ghost** [openrazer/openrazer#870]
PLEEEEEEEEEASE!!!

**Comment by z3ntu** [comment]
Please fill out the issue template. It's there for a reason...

**Comment by ghost** [comment]
The issue is there is no support for v1 deathadder...I figured that would be pretty self explanatory given the title of the thread. Sorry

**Comment by z3ntu** [comment]
Then please fill out the template. Otherwise I'll have to close this issue.
