### ISSUE TITLE
Needs more informaition ... a lot more!!!

### ISSUE THREAD

**Issue by Kriknos** [openrazer/openrazer#871]
I have Openrazer installed and I tried installing both Polychromatic and RazorGenie both see my Nostrom, but there is no options to change anything. They both point their troubleshooting to your SEVERELY lacking wiki. I check/tried everything there and it seems good, even the logs don't show any errors.

Whether it is with either Polychromatic or RazorGenie or without them, where do I find sufficient information to use Openrazer. I also see you have an API, but I see no documentation for that API. This seems like a highly promising project, but it is useless without proper documentation.

**Comment by z3ntu** [comment]
There's some documentation for the Python bindings in the `feature_docs` branch, where you can build the docs with `make python_library_docs` in the root of the repo. Other docs don't exist unfortunately.
