### ISSUE TITLE
Device Not Recognised - 1532:006e

### ISSUE THREAD

**Issue by grimseh** [openrazer/openrazer#874]
I am on Solus 4.0, installed RazerGenie and OpenRazer using eopkg commandline. Deathadder Essential.

No errors with modprobe:
`razermouse             73728  0`
`hid                   135168  3 usbhid,hid_generic,razermouse`
`usbcore               258048  8 xhci_hcd,usbhid,usb_storage,uvcvideo,btusb,xhci_pci,uas,razermouse`

Running `openrazer-daemon -Fv>`
outputs `Unable to lock on the pidfile.`

Secure boot is disabled, was disabled prior to installation.

**Comment by z3ntu** [comment]
The DeathAdder Essential support was just merged yesterday and isn't in a release yet, that's why you don't have it working. You just have to wait a bit until it's released or update manually to the latest commit.
