### ISSUE TITLE
Device not recognised (razer taipan)

### ISSUE THREAD

**Issue by kik4444** [openrazer/openrazer#878]
### Distribution

4.19.56-1-MANJARO

### Support

- [x] Have you tried rebooting? - YES
- [x] Have you looked at the [Troubleshooting](https://github.com/openrazer/openrazer/wiki/Troubleshooting) page? - YES

I'm running Manjaro and my razer device is the taipan mouse. I installed openrazer-meta and polychromatic and restarted. I've added myself to the plugdev group but it still says my device is not recognised. 

Here is the razer.log - https://pastebin.com/35eDx62p

The result of `sudo journalctl -b | grep -i razer_mount` is:

`
юли 12 14:30:33 Kiko-LM razer_mount[509]: Driver razermouse
юли 12 14:30:33 Kiko-LM razer_mount[508]: Driver razermouse
юли 12 14:30:33 Kiko-LM razer_mount[512]: Device_ID 0003:1532:0034.0006
юли 12 14:30:33 Kiko-LM razer_mount[511]: Device_ID 0003:1532:0034.0005
юли 12 14:30:33 Kiko-LM razer_mount[514]: Modprobing razermouse
юли 12 14:30:33 Kiko-LM razer_mount[515]: Modprobing razermouse
юли 12 14:30:33 Kiko-LM systemd-udevd[436]: Process 'razer_mount razermouse 0003:1532:0034.0006' failed with exit code 1.
юли 12 14:30:33 Kiko-LM razer_mount[520]: Driver razermouse
юли 12 14:30:33 Kiko-LM systemd-udevd[407]: Process 'razer_mount razermouse 0003:1532:0034.0005' failed with exit code 1.
юли 12 14:30:33 Kiko-LM razer_mount[522]: Device_ID 0003:1532:0034.0004
юли 12 14:30:33 Kiko-LM razer_mount[526]: Modprobing razermouse
юли 12 14:30:33 Kiko-LM systemd-udevd[430]: Process 'razer_mount razermouse 0003:1532:0034.0004' failed with exit code 1.
`

And `sudo dkms install openrazer-driver/1.0.0` returns:

`Error! Could not find module source directory.
Directory: /usr/src/openrazer-driver-1.0.0 does not exist.`

I am aware the beginning of the razer.log says that I'm not a member of the plugdev group, but I am. I've tried adding myself multiple times just in case with `sudo gpasswd -a kiko plugdev` and then rebooting, but it doesn't change anything.

**Comment by z3ntu** [comment]
What's the output from the command `sudo dkms install openrazer-driver/2.5.0` ? Also please try running `sudo modprobe razerkbd`

**Comment by kik4444** [comment]
The first command actually returned

`Creating symlink /var/lib/dkms/openrazer-driver/2.5.0/source ->
                 /usr/src/openrazer-driver-2.5.0

DKMS: add completed.
Error! echo
Your kernel headers for kernel 4.19.56-1-MANJARO cannot be found at
/usr/lib/modules/4.19.56-1-MANJARO/build or /usr/lib/modules/4.19.56-1-MANJARO/source.`

And `sudo modprobe razerkbd` returned:

`modprobe: FATAL: Module razerkbd not found in directory /lib/modules/4.19.56-1-MANJARO`

And also the directory `/lib/modules/4.19.56-1-MANJARO/build` only has the file `vmlinux` in it.

**Comment by z3ntu** [comment]
Please install your kernel headers as written at https://wiki.archlinux.org/index.php/Dynamic_Kernel_Module_Support#Installation .

**Comment by kik4444** [comment]
How should I do it for my case? I don't know what to look for, I'm not familiar with how kernel headers work.

**Comment by z3ntu** [comment]
Depends on what kernel package you have installed and are using. Use that and append `-headers` to the name. It's probably `linux419-headers` or something like that - Manjaro has weird package names for that.

**Comment by kik4444** [comment]
Ah yes it was exactly linux419-headers. Now it works, but it's a bit underwhelming. I don't see where I can remap the extra keys.

**Comment by z3ntu** [comment]
Key remapping isn't supported yet. Closing as the setup issue is solved.
