### ISSUE TITLE
NO DEVICE FOUND with AUR install (using yaourt)

### ISSUE THREAD

**Issue by doesnotcommute** [openrazer/openrazer#88]
Tried modprobe and lsmod, can't find the driver.
Manual install fails during make (in path with no white spaces)
Output of make: http://pastebin.com/UCSdryWX

**Comment by doesnotcommute** [comment]
PS - Device is Razer Blade Stealth 2016

**Comment by terricain** [comment]
run `lsusb` and paste output. And the make you ran was on code not from this repository.

**Comment by doesnotcommute** [comment]
lsusb output: http://pastebin.com/jxmfwfjj
Sorry about that. Must have cloned a different repo (there are a couple of them with similar names). will fix it

**Comment by terricain** [comment]
@GabMus @z3ntu Mind helping troubleshooting the AUR install?

**Comment by doesnotcommute** [comment]
Update : ran sudo make -s all install on the code from this repository
Output:

:: Compiling Razer kernel modules
========================================
make: *** [Makefile:25: driver] Error 2

**Comment by terricain** [comment]
Do you have kernel headers installed for the kernel that is currently running

**Comment by z3ntu** [comment]
@doesnotcommute I would suggest you to uninstall the manual installation (manual is always bad) and then install the AUR package. If you have Telegram you can contact me @z3ntu , helping there is better ;)

About the kernel headers: If you have the package `linux` installed, please check if `linux-headers` is also installed.

**Comment by doesnotcommute** [comment]
Installed the kernel headers. 
Output of lsmod | grep razer* : 
razerkbd               28672  0
hid                       114688  6 i2c_hid,hid_generic,usbhid,hid_rmi,hid_multitouch,razerkbd
usbcore               208896  6 uvcvideo,usbhid,razerkbd,xhci_pci,btusb,xhci_hcd

**Comment by doesnotcommute** [comment]
Everything working perfectly. Thanks for the help @terrycain and @z3ntu

**Comment by doesnotcommute** [comment]
PS- Let me know if you need me to test anything on the Blade Stealth 2016 with Arch (specifically Antergos OS)

**Comment by terricain** [comment]
Will do, if you join the telegram chat thats where most of the testing goes on as I just spam it asking for anyone to test.
