### ISSUE TITLE
Device not popppulating in Razer Genie.

### ISSUE THREAD

**Issue by Shimo** [openrazer/openrazer#889]
Device not popppulating in Razer Genie. Getting No device was detected with Razer Naga mouse.

Bus 003 Device 003: ID 1532:002e Razer USA, Ltd RZ01-0058 Gaming Mouse [Naga]

**Comment by z3ntu** [comment]
Can you please give me the output of `sudo dkms install openrazer-driver/2.6.0` ?

**Comment by Shimo** [comment]
```
sudo dkms install openrazer-driver/2.6.0
Module openrazer-driver/2.6.0 already installed on kernel 4.19.60-1-MANJARO/x86_64
```

Edit: In case you need it too

```
sudo lsusb | grep '1532:'
Bus 003 Device 010: ID 1532:002e Razer USA, Ltd RZ01-0058 Gaming Mouse [Naga]

```

**Comment by z3ntu** [comment]
`1532:002e` is not yet supported, if you look into the readme. Closing this as a duplicate of #377
