### ISSUE TITLE
Fan Control for Razer Blade

### ISSUE THREAD

**Issue by DerMuffin** [openrazer/openrazer#892]
### Distribution

Elementary OS 5.0

### Support

- [x ] Have you tried rebooting?
- [x ] Have you looked at the [Troubleshooting](https://github.com/openrazer/openrazer/wiki/Troubleshooting) page?

Does this driver support the fan Control from synapse on Windows? Any Front end i find and install have "only" the options for makros and the Chroma for the Keyboard

**Comment by z3ntu** [comment]
If you can make [USB packet captures](https://github.com/openrazer/openrazer/wiki/Reverse-Engineering-USB-Protocol) of Synapse doing that, I can look at it.

**Comment by BiatuAutMiahn** [comment]
[RazerUSBCap.zip](https://github.com/openrazer/openrazer/files/11790239/RazerUSBCap.zip)
Compressed with ultra preset on 7-zip. This is my SKU: RZ09-0409CEA3-R3U1

**Comment by BiatuAutMiahn** [comment]
I started the capture with the razer services disabled. Then I enabled them, then went into synapse and set the fan to 0, then back up to 5200rpm. I also had a chroma profile the was applied on launch of synapse.

Edit: here is my display filter: `!(usb.src in {"2.6.0","2.2.0","2.1.0","2.2.2"}) && !(usb.dst in {"2.6.0","2.2.0","2.1.0","2.2.2"})`

**Comment by z3ntu** [comment]
Please continue in #1227 or somewhere.
