### ISSUE TITLE
Working with Razer mouse in Windows OS

### ISSUE THREAD

**Issue by MikitaSaladukha** [openrazer/openrazer#905]
Dear OpenRazer team.
I have a small question: for example, I reprogram mouse buttons in Ubuntu OS and then plug the mouse into a computer with Windows OS. Will the buttons work correctly?
Regards,
Mikita Saladukha

**Comment by lah7** [comment]
No, rebinding keys happens at an OS level, and the changes are not stored on the hardware. Generally, the mouse resets to a "default state" when plugged in until the driver/software instructs the mouse what to do.

Under Windows, Razer Synapse is responsible for the button behaviour (and for newer Razer hardware, also to run lighting effects). Under OpenRazer, rebinding keys isn't completed yet, but there is a work in progress implementation in #880.
