### ISSUE TITLE
Slackware/Slackbuild support?

### ISSUE THREAD

**Issue by brokenshakles** [openrazer/openrazer#906]
### Distribution : Slackware-current

I dont know how to do a generic build with this, make fails with : 

bash-5.0$ make

:: Compiling OpenRazer kernel modules
========================================
make -C /lib/modules/5.2.4/build M=/home/brokenshakles/Projects/Helium/slackbuilds/openrazer/openrazer-openrazer-69f5ab9/driver modules
make[1]: Entering directory '/usr/src/linux-5.2.4'
  CC [M]  /home/brokenshakles/Projects/Helium/slackbuilds/openrazer/openrazer-openrazer-69f5ab9/driver/razerkbd_driver.o
  CC [M]  /home/brokenshakles/Projects/Helium/slackbuilds/openrazer/openrazer-openrazer-69f5ab9/driver/razercommon.o
  CC [M]  /home/brokenshakles/Projects/Helium/slackbuilds/openrazer/openrazer-openrazer-69f5ab9/driver/razerchromacommon.o
  LD [M]  /home/brokenshakles/Projects/Helium/slackbuilds/openrazer/openrazer-openrazer-69f5ab9/driver/razerkbd.o
  CC [M]  /home/brokenshakles/Projects/Helium/slackbuilds/openrazer/openrazer-openrazer-69f5ab9/driver/razermouse_driver.o
  LD [M]  /home/brokenshakles/Projects/Helium/slackbuilds/openrazer/openrazer-openrazer-69f5ab9/driver/razermouse.o
  CC [M]  /home/brokenshakles/Projects/Helium/slackbuilds/openrazer/openrazer-openrazer-69f5ab9/driver/razermousemat_driver.o
  LD [M]  /home/brokenshakles/Projects/Helium/slackbuilds/openrazer/openrazer-openrazer-69f5ab9/driver/razermousemat.o
  CC [M]  /home/brokenshakles/Projects/Helium/slackbuilds/openrazer/openrazer-openrazer-69f5ab9/driver/razerkraken_driver.o
  LD [M]  /home/brokenshakles/Projects/Helium/slackbuilds/openrazer/openrazer-openrazer-69f5ab9/driver/razerkraken.o
  CC [M]  /home/brokenshakles/Projects/Helium/slackbuilds/openrazer/openrazer-openrazer-69f5ab9/driver/razermug_driver.o
  LD [M]  /home/brokenshakles/Projects/Helium/slackbuilds/openrazer/openrazer-openrazer-69f5ab9/driver/razermug.o
  CC [M]  /home/brokenshakles/Projects/Helium/slackbuilds/openrazer/openrazer-openrazer-69f5ab9/driver/razercore_driver.o
  LD [M]  /home/brokenshakles/Projects/Helium/slackbuilds/openrazer/openrazer-openrazer-69f5ab9/driver/razercore.o
  Building modules, stage 2.
  MODPOST 6 modules
ERROR: "hid_open_report" [/home/brokenshakles/Projects/Helium/slackbuilds/openrazer/openrazer-openrazer-69f5ab9/driver/razermug.ko] undefined!
ERROR: "hid_hw_stop" [/home/brokenshakles/Projects/Helium/slackbuilds/openrazer/openrazer-openrazer-69f5ab9/driver/razermug.ko] undefined!
ERROR: "__hid_register_driver" [/home/brokenshakles/Projects/Helium/slackbuilds/openrazer/openrazer-openrazer-69f5ab9/driver/razermug.ko] undefined!
ERROR: "hid_hw_start" [/home/brokenshakles/Projects/Helium/slackbuilds/openrazer/openrazer-openrazer-69f5ab9/driver/razermug.ko] undefined!
ERROR: "hid_unregister_driver" [/home/brokenshakles/Projects/Helium/slackbuilds/openrazer/openrazer-openrazer-69f5ab9/driver/razermug.ko] undefined!
ERROR: "hid_open_report" [/home/brokenshakles/Projects/Helium/slackbuilds/openrazer/openrazer-openrazer-69f5ab9/driver/razermousemat.ko] undefined!
ERROR: "hid_hw_stop" [/home/brokenshakles/Projects/Helium/slackbuilds/openrazer/openrazer-openrazer-69f5ab9/driver/razermousemat.ko] undefined!
ERROR: "__hid_register_driver" [/home/brokenshakles/Projects/Helium/slackbuilds/openrazer/openrazer-openrazer-69f5ab9/driver/razermousemat.ko] undefined!
ERROR: "hid_hw_start" [/home/brokenshakles/Projects/Helium/slackbuilds/openrazer/openrazer-openrazer-69f5ab9/driver/razermousemat.ko] undefined!
ERROR: "hid_unregister_driver" [/home/brokenshakles/Projects/Helium/slackbuilds/openrazer/openrazer-openrazer-69f5ab9/driver/razermousemat.ko] undefined!
ERROR: "hid_open_report" [/home/brokenshakles/Projects/Helium/slackbuilds/openrazer/openrazer-openrazer-69f5ab9/driver/razermouse.ko] undefined!
ERROR: "hid_hw_stop" [/home/brokenshakles/Projects/Helium/slackbuilds/openrazer/openrazer-openrazer-69f5ab9/driver/razermouse.ko] undefined!
ERROR: "__hid_register_driver" [/home/brokenshakles/Projects/Helium/slackbuilds/openrazer/openrazer-openrazer-69f5ab9/driver/razermouse.ko] undefined!
ERROR: "hid_hw_start" [/home/brokenshakles/Projects/Helium/slackbuilds/openrazer/openrazer-openrazer-69f5ab9/driver/razermouse.ko] undefined!
ERROR: "hid_unregister_driver" [/home/brokenshakles/Projects/Helium/slackbuilds/openrazer/openrazer-openrazer-69f5ab9/driver/razermouse.ko] undefined!
ERROR: "hid_open_report" [/home/brokenshakles/Projects/Helium/slackbuilds/openrazer/openrazer-openrazer-69f5ab9/driver/razerkraken.ko] undefined!
ERROR: "hid_hw_stop" [/home/brokenshakles/Projects/Helium/slackbuilds/openrazer/openrazer-openrazer-69f5ab9/driver/razerkraken.ko] undefined!
ERROR: "__hid_register_driver" [/home/brokenshakles/Projects/Helium/slackbuilds/openrazer/openrazer-openrazer-69f5ab9/driver/razerkraken.ko] undefined!
ERROR: "hid_hw_start" [/home/brokenshakles/Projects/Helium/slackbuilds/openrazer/openrazer-openrazer-69f5ab9/driver/razerkraken.ko] undefined!
ERROR: "hid_unregister_driver" [/home/brokenshakles/Projects/Helium/slackbuilds/openrazer/openrazer-openrazer-69f5ab9/driver/razerkraken.ko] undefined!
ERROR: "hid_open_report" [/home/brokenshakles/Projects/Helium/slackbuilds/openrazer/openrazer-openrazer-69f5ab9/driver/razerkbd.ko] undefined!
ERROR: "hid_hw_stop" [/home/brokenshakles/Projects/Helium/slackbuilds/openrazer/openrazer-openrazer-69f5ab9/driver/razerkbd.ko] undefined!
ERROR: "__hid_register_driver" [/home/brokenshakles/Projects/Helium/slackbuilds/openrazer/openrazer-openrazer-69f5ab9/driver/razerkbd.ko] undefined!
ERROR: "hid_hw_start" [/home/brokenshakles/Projects/Helium/slackbuilds/openrazer/openrazer-openrazer-69f5ab9/driver/razerkbd.ko] undefined!
ERROR: "hid_unregister_driver" [/home/brokenshakles/Projects/Helium/slackbuilds/openrazer/openrazer-openrazer-69f5ab9/driver/razerkbd.ko] undefined!
ERROR: "hid_open_report" [/home/brokenshakles/Projects/Helium/slackbuilds/openrazer/openrazer-openrazer-69f5ab9/driver/razercore.ko] undefined!
ERROR: "hid_hw_stop" [/home/brokenshakles/Projects/Helium/slackbuilds/openrazer/openrazer-openrazer-69f5ab9/driver/razercore.ko] undefined!
ERROR: "__hid_register_driver" [/home/brokenshakles/Projects/Helium/slackbuilds/openrazer/openrazer-openrazer-69f5ab9/driver/razercore.ko] undefined!
ERROR: "hid_hw_start" [/home/brokenshakles/Projects/Helium/slackbuilds/openrazer/openrazer-openrazer-69f5ab9/driver/razercore.ko] undefined!
ERROR: "hid_unregister_driver" [/home/brokenshakles/Projects/Helium/slackbuilds/openrazer/openrazer-openrazer-69f5ab9/driver/razercore.ko] undefined!
make[2]: *** [scripts/Makefile.modpost:91: __modpost] Error 1
make[1]: *** [Makefile:1599: modules] Error 2
make[1]: Leaving directory '/usr/src/linux-5.2.4'
make: *** [Makefile:25: driver] Error 2

It would be preferable to have a slackbuild that could take new releases of openrazer and build it for slackware systems. (See www.slackbuilds.org for more details on this).  Anyone know how to resolve this so I can configure my Chroma devices?

**Comment by z3ntu** [comment]
Hi, sorry you're facing issues compiling openrazer on your distro.

The errors you're seeing don't make much sense because these symbols should be provided by the kernel and they should definitely compile with Linux 5.2.4. Are you using some other non-standard software in the build toolchain? Maybe some old compiler?
