### ISSUE TITLE
Cant get it to work on solus

### ISSUE THREAD

**Issue by ghost** [openrazer/openrazer#930]
I tried so many things i tried using polychromatic normal commands razergenie and the troubleshoot page but nothing seems to work can somebody help me please

**Comment by z3ntu** [comment]
Can you please describe your issue in more detail? What error do you see?

**Comment by ghost** [comment]
Razer device not detected by deamon

**Comment by ghost** [comment]
And with polychromatic razer device not recognised

**Comment by parkerlreed** [comment]
Logs from the daemon? This isn't much information to go on

**Comment by z3ntu** [comment]
@ItsLeffdePeff Can you give me the output of 
`sudo dkms install openrazer-driver/2.6.0` and of `sudo modprobe razerkbd` ?

**Comment by ghost** [comment]
sudo: dkms: command not found and modprobe: FATAL: Module razerkbd not found in directory /lib/modules/5.2.20-130.current

**Comment by z3ntu** [comment]
Try installing the latest updates and reboot?

**Comment by ghost** [comment]
all the latest updates were already installed

**Comment by z3ntu** [comment]
Then please ask at Solus for help. The latest version in Solus should provide `/lib/modules/5.2.20-130.current/kernel/drivers/hid/razerkbd.ko` which matches the kernel version from your output above.

Maybe one last shot, do you have the package `openrazer-current` installed?

**Comment by ghost** [comment]
openrazer-current worked!!! thank you so much

**Comment by z3ntu** [comment]
Great!
