### ISSUE TITLE
Fedora 31

### ISSUE THREAD

**Issue by irreleph4nt** [openrazer/openrazer#941]
### Distribution

Fedora 31

### Support

Can you please enable Fedora 31 in OBS?

**Comment by z3ntu** [comment]
Done. Unfortunately something needs to be changed in the polychromatic packaging though for that build to succeed, which I'll do in the coming week.

**Comment by z3ntu** [comment]
Builds for Fedora 31 are successful, polychromatic is blocked by https://bugzilla.redhat.com/show_bug.cgi?id=1767403 - once that's fixed the builds should automatically retry I think. Closing.
