### ISSUE TITLE
cannot start 

### ISSUE THREAD

**Issue by Truskawk** [openrazer/openrazer#944]
kuba-pc openrazer-daemon[5479]: 2019-11-04 21:04:43 | razer                          | CRITICAL | User is not a member of the plugdev group

**Comment by z3ntu** [comment]
This means that you have to add your user to the plugdev group, otherwise it won't work.

**Comment by encodedwitch** [comment]
My user is already part of plugdev group but does not work. Any advice on this?

**Comment by ldimartino** [comment]
same problem here, my user is part of plugdev and does not work.

**Comment by z3ntu** [comment]
Could you please post the output of the `id` and of the `groups` command?
