### ISSUE TITLE
Polychromatic applications not opening (Arch, gnome, Blade 15)

### ISSUE THREAD

**Issue by SVaeth** [openrazer/openrazer#953]
### Distribution
Openrazer 2.6.0
Razer Blade 15 (2019) Mercury 1532:0245

### Support

- [x] Have you tried rebooting?
- [x] Have you looked at the [Troubleshooting](https://github.com/openrazer/openrazer/wiki/Troubleshooting) page?

I used the following commands: 
`pacaur -S openrazer-meta`
restarted the laptop
`pacaur -S polychromatic`

and cannot open the controller application.

Some relevant outputs based on troubleshooting and other tickets I looked at:
```
sudo dkms openrazer-driver/2.6.0
Module openrazer-driver/2.6.0 already installed on kernel 5.3.12-arch1-1/x86_64
```
```
lsusb | grep 1532:
Bus 001 Device 005: ID 1532:0245 Razer USA, Ltd Razer Blade
```

```
razer-service -F
bash: razer-service: command not found
```
According to the site, my device is the 2019 Blade Mercury (could have sworn it was the Advanced but eh) and is listed as being supported. Is there something I missed? If you need any further outputs, logfiles let me know. I would like to get up and running asap, as my backlights have shut off on my keyboard and have not come back on since the laptop fell asleep earlier

**Comment by SVaeth** [comment]
Something to further help with finding the issue, the output of running the polychromatic-controller directly:

```
/usr/bin/polychromatic-controller 
Traceback (most recent call last):
  File "/usr/bin/polychromatic-controller", line 26, in <module>
    import distro
ModuleNotFoundError: No module named 'distro'

```

**Comment by z3ntu** [comment]
Install `python-distro`, I forgot to add that dependency to the AUR package.

**Comment by z3ntu** [comment]
Fixed (or just update the polychromatic package on your system).

**Comment by SVaeth** [comment]
Thanks for that, but wait, it's not working yet. I'm getting this issue now, and the tray-applet won't even open and just hangs if I run the binary from the terminal
 
![Screenshot from 2019-11-24 03-19-03](https://user-images.githubusercontent.com/40723506/69491890-68c02800-0e69-11ea-8ab3-3c6371cea50a.png)
![Screenshot from 2019-11-24 03-20-23](https://user-images.githubusercontent.com/40723506/69491891-6958be80-0e69-11ea-9c99-b4fe818664e8.png)

**Comment by z3ntu** [comment]
Does `sudo modprobe razerkbd` succeed? What does `openrazer-daemon -Fv` output?

**Comment by SVaeth** [comment]
Not sure what it did, but `sudo modprobe razerkbd` seems to have succeeded, at least no output

```
openrazer-daemon -Fv
Unable to lock on the pidfile.
```

So the daemon is running

**Comment by SVaeth** [comment]
I found this in the logs
```
2019-11-24 03:22:49 | razer                          | CRITICAL | Could not access /sys/devices/pci0000:00/0000:00:14.0/usb1/1-8/1-8:1.2/0003:1532:0245.0005/device_type, file is not owned by plugdev
```

adding log file. My user is part of plugdev and I have rebooted since. Ignore that first message
[razer.log](https://github.com/openrazer/openrazer/files/3883346/razer.log)

**Comment by z3ntu** [comment]
That's issue #877 then

**Comment by SVaeth** [comment]
Are you sure it's related to the issue polychromatic is having starting applications/recognizing the drivers?

If it isn't, I don't see how this ticket can be closed since I still can't open and use these applications
