### ISSUE TITLE
Polychromatic Tray Applet not opening in Gnome  3.34.1

### ISSUE THREAD

**Issue by SVaeth** [openrazer/openrazer#955]
### Distribution
Arch

Gnome 3.34.1

### Support

- [x] Have you tried rebooting?
- [x] Have you looked at the [Troubleshooting](https://github.com/openrazer/openrazer/wiki/Troubleshooting) page?

I run `/usr/bin/polychromatic-tray-applet` in command line, but tray-applet runs but does not open. I did some digging and found these issues that may be related:
https://github.com/polychromatic/polychromatic/issues/128
https://github.com/syncthing/syncthing-gtk/issues/534 

If Gnome no longer supports App indicators, does this mean it no longer supports Polychromatic Tray Applet? Is there anything I can do to work around this?

**Comment by lah7** [comment]
My understanding is that AppIndicators moved to a GNOME Shell extension.

Try installing the package `gnome-shell-extension-appindicator` and enable/add it to GNOME.

**Comment by SVaeth** [comment]
So I pulled that from the aur earlier, but I could not find anywhere to enable it in GNOME Tweaks, and my theory is because they removed support for app indicators

**Comment by z3ntu** [comment]
Closing this as it's not an openrazer issue, but a [polychromatic issue](https://github.com/polychromatic/polychromatic/).
