### ISSUE TITLE
Razer Ornata Keyborad - Device Not Recognised

### ISSUE THREAD

**Issue by Zaneriis** [openrazer/openrazer#967]
### Distribution

/var/lib/dkms/openrazer-driver/2.6.0
I'm on Ubuntu18.04.1
I purchased a Razor Ornata keyboard
### Support

- [Yes] Have you tried rebooting?
- [Yes] Have you looked at the [Troubleshooting](https://github.com/openrazer/openrazer/wiki/Troubleshooting) page?

Hello
I just installed drivers for my razer ornata keyboard, and polychromatic displays: "Device Not Recognised"
I went to troubleshooting and i searched on the web, but I can't fix the problem. 
After trying to remove and reinstall openrazer, I saw on some topic, i should use modprobe command, but apparently, I haven't permitions: "modprobe: ERROR: could not insert 'razerkbd': Operation not permitted" 
Any ideas?

**Comment by z3ntu** [comment]
Hi, you will have to either disable Secure Boot in the BIOS/UEFI or sign the kernel modules yourself. You can read https://github.com/openrazer/openrazer/wiki/Troubleshooting#kernel-modules-loading for more details.
