### ISSUE TITLE
Orbweaver Chroma wave

### ISSUE THREAD

**Issue by hedmo** [openrazer/openrazer#970]
### Support

- [x] Have you tried rebooting?
- [x] Have you looked at the [Troubleshooting](https://github.com/openrazer/openrazer/wiki/Troubleshooting) page?

 hi is it possible to add the wave effect to the Orbweaver Chroma? 

regards hedmo

**Comment by nightsky30** [comment]
@hedmo I added wave effect support for the Orbweaver Chroma in a [test](https://github.com/nightsky30/openrazer/tree/feature_orbweaver_chroma_wave) branch. Would you care to test it? If it works I can submit a pull request.

**Comment by hedmo** [comment]
@nightsky30 thanks for the fast reply.it works flawless.

best regards hedmo
