### ISSUE TITLE
Unable to use with Kali

### ISSUE THREAD

**Issue by wingzero-KSEC** [openrazer/openrazer#975]
### Support

- [ Y] Have you tried rebooting?
- [ Y] Have you looked at the [Troubleshooting](https://github.com/openrazer/openrazer/wiki/Troubleshooting) page?

So in entering into the world of Linux i was convinced by the lack of some needed tools on Fedora 31 to switch to Kali to have ready access to some things that I would need. However, setting up my Razer Blackwidow V2 tournament edition keyboard has been...difficult. I dont know if its that the version of Kali that im running doesn't have support or whats up. but any time I run the lines of code for ANY the Debian versions i get output stating something along the lines of "These dependencies cannot be installed, the exact output is: 

Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 openrazer-meta : Depends: openrazer-driver-dkms (= 2.6.0-0) but it is not going to be installed
                  Depends: openrazer-daemon (= 2.6.0-0) but it is not going to be installed
                  Depends: python3-openrazer (= 2.6.0-0) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

Any help would be much appreciated

**Comment by zeltwood** [comment]
Hi there! Try `apt --fix-broken install`. Hopefully this works, but I'm not sure. I'm new to Linux, just trying to help.
