### ISSUE TITLE
Kernel Module not found in directory (Fedora 31)

### ISSUE THREAD

**Issue by Zymion6** [openrazer/openrazer#979]
### Distribution

Fedora 31
(5.3.7-301.fc31.x86_64)

/var/lib/dkms/openrazer-driver/2.6.0
Ornata Chroma; Abyssus V2

### Support

- [Y] Have you tried rebooting?
- [Y] Have you looked at the [Troubleshooting](https://github.com/openrazer/openrazer/wiki/Troubleshooting) page?

I've tried using Polychromatic and Razergenie, but neither seem to work.
I've gone through the troubleshooting guide and the only thing that seems to be at fault is this:

```
[N0pe@localhost-live ~]$ sudo modprobe razerkbd
modprobe: FATAL: Module razerkbd not found in directory /lib/modules/5.3.7-301.fc31.x86_64
```

Pretty sure this is just a Fedora problem.

**Comment by z3ntu** [comment]
What happens when you run `sudo dkms install openrazer-driver/2.6.0` ?

**Comment by Zymion6** [comment]
```
Error! echo
Your kernel headers for kernel 5.3.7-301.fc31.x86_64 cannot be found at
/lib/modules/5.3.7-301.fc31.x86_64/build or /lib/modules/5.3.7-301.fc31.x86_64/source.
```

**Comment by Zymion6** [comment]
However I have already run ```$ dnf install kernel-devel```

**Comment by z3ntu** [comment]
If you have `kernel-devel` version `5.3.7-301.fc31.x86_64` installed, you should have the folder `/usr/src/kernels/5.3.7-301.fc31.x86_64`, is that correct?

**Comment by Zymion6** [comment]
I ran ```dnf update``` yesterday and ended up with ```5.3.16-300.fc31.x86_64``` installed in that folder.
This seems to have fixed the problem as the devices are now being recognized.
Thanks for you help :)

**Comment by z3ntu** [comment]
No problem!
