### ISSUE TITLE
"OpenRazer daemon is not installed"

### ISSUE THREAD

**Issue by johnwilliamsdigital** [openrazer/openrazer#984]
### Support

- [x] Have you tried rebooting? Of course
- [x] Have you looked at the [Troubleshooting](https://github.com/openrazer/openrazer/wiki/Troubleshooting) page? Yes.

I'm getting the attached error. 

Not sure what to do to fix it, I'm not an expert programmer so baby steps would be very helpful. 

Kubuntu 19.10

Deathaddereliete Mouse

![razer mouse 1](https://user-images.githubusercontent.com/57566224/71597782-bfbcbb00-2b01-11ea-842e-ec5971290ff2.png)

**Comment by hedmo** [comment]
@johnwilliamsdigital 

can you post the output of :+1: 

`lsmod | grep razer`
and 
`openrazer-daemon`

regards hedmo

**Comment by johnwilliamsdigital** [comment]
Hey, thanks for replying. 

I got it to run with: 

`openrazer-daemon -Fv
sudo modprobe razerkbd`

However, my purpose was to reassign the thumb buttons, which I realized afterwards this app doesn't do. 

Any reccomendations for reassigning mouse buttons?

Thanks!

**Comment by hedmo** [comment]
For botton mapping: https://bues.ch/cms/hacking/razercfg.html
