### ISSUE TITLE
Razer deathadder 2000 dpi mouse not recognized.

### ISSUE THREAD

**Issue by Andre772** [openrazer/openrazer#986]
Hello. My razer mouse is a Deathadder 2000 dpi. I installed razergenie, and it was not detected. There is something I can do.
Thanks

**Comment by z3ntu** [comment]
Can you please give me the output of `lsusb | grep 1532` and of `sudo modprobe razerkbd`?

**Comment by Andre772** [comment]
Ok my friend!

$ lsusb | grep 1532
   Bus 003 Device 003: ID 1532:004d Razer USA, Ltd Razer DeathAdder

This one returned nothing: sudo modprobe razerkbd

**Comment by z3ntu** [comment]
The device isn't recognized because it isn't supported in OpenRazer yet, see #495 . Closing.
