### ISSUE TITLE
No effects for Blade 15 (2018) laptop

### ISSUE THREAD

**Issue by Deanpham1200** [openrazer/openrazer#998]
![ss](https://user-images.githubusercontent.com/59811472/72229677-aa1dab80-356d-11ea-8415-bed2e528e16f.png)
 Many config options for my razer blade doesn't show up on poly chromatic. I've uninstalled and reinstalled both openrazer and poly chromatic and the problem still occurs. Ive also tried razer commander with no luck. Im new to linux and unsure on how to approach this.

**Comment by lah7** [comment]
The good news is, there's nothing wrong with your installation. :+1:

It's a bug in Polychromatic's logic in this version, which is 2 years old. Please see https://github.com/polychromatic/polychromatic/issues/229 for the fix.
