### ISSUE TITLE
Coil whine using Ubuntu

### ISSUE THREAD

**Issue by eduardosousaufjf** [openrazer/openrazer#999]
### Distribution

Ubuntu 18.04

### Support

- [X] Have you tried rebooting?
- [X] Have you looked at the [Troubleshooting](https://github.com/openrazer/openrazer/wiki/Troubleshooting) page?

Whenever I plug my Razer Ornata or Abyssus I get a coil whine that sometimes go away and sometimes not. Steady high frequency.

**Comment by lah7** [comment]
Some Razer hardware are liable to this, I don't think there's anything you (or this project) can do except keep the brightness to 50% or less.

See also: https://github.com/openrazer/openrazer/issues/777
